- Common/util/aasset_stream.cpp
- Common/util/android_file.cpp
- Common/util/path.cpp
- Common/util/path.h
android asset manager can't find files when they are preceded by `/` or `./` inside it's packaged asset.
fix #1577 
I placed the path stuff in the path utilities but if you think it's better to be in the android file then I can move too. I have a feeling that there must be some other proprietary ROM format that would have some similar need but I don't know any at the time.
I also named the function that simplifies the path as `GetPathInForeignAsset` to illustrate that the asset in question is not an AGS asset but a ROM type of information that another system also calls as "asset".
> Android: fix can't open vox packages in single game launcher

- Editor/AGS.Editor/Panes/ScintillaWrapper.cs
prevents Ctrl+Shift+[A-Z] from inserting Ctrl Keys symbols in the script editor.
> Editor: Scintilla fix to not insert Ctrl+key characters in text buffer

- Common/gui/guimain.cpp
- Common/gui/guiobject.h
- Common/gui/guislider.cpp
- Common/gui/guislider.h
Fixes #1581 + refactors its drawing function. Latter is not necessary, but I wrote this code as a part of previous pr attempt (#1583), and imho this may be useful, as it reduces code duplication and clarifies certain settings.
The idea is that Sliders are currently too complicated to simply clip them to the rectangle defined by their position properties. As AGS historically did not restrict the sizes of slider handle and background images, clipping it would perhaps require to redesign its default looks and settings.
> Exclude Sliders from the GUI clipping rule + refactor slider drawing

- Common/ac/characterinfo.h
- Common/gui/guibutton.h
- Common/gui/guidefines.h
- Editor/AGS.Editor/Resources/agsdefns.sh
- Engine/ac/button.cpp
- Engine/ac/button.h
- Engine/ac/characterinfo_engine.cpp
- Engine/ac/object.cpp
- Engine/ac/object.h
- Engine/ac/roomobject.cpp
- Engine/ac/roomobject.h
- Engine/ac/runtime_defines.h
- Engine/game/savegame_components.cpp
- Engine/game/savegame_v321.cpp
- Engine/gui/animatingguibutton.cpp
- Engine/gui/animatingguibutton.h
- Engine/main/game_run.cpp
- Engine/main/game_run.h
- Engine/script/script_api.h
This was mentioned on forums recently, and made me realize I missed Buttons when expanding Character and Object animation with "starting frame".
Added all parameters available for Character and Object's Animate function:
* blocking;
* direction;
* starting frame
So it looks like
```
import void Button.Animate(int view, int loop, int delay, RepeatStyle=eOnce, BlockingStyle=eBlock, Direction=eForwards, int frame=0);
```
NOTE: same as with Character and Object's starting frame, the reverse animation starts with *frame - 1*, hence passing `frame = 0` will begin reverse animation with the last frame.
Refactored the animation handling (frame, loop increment/decrement) algorithm, use common code among Character, Object and Button.
> Script API: expanded Button.Animate() to feature all common params + some refactor

- Editor/AGS.CScript.Compiler/Preprocessor.cs
- Editor/AGS.Editor.Tests/ScriptCompiler/PreprocessorTests.cs
- Editor/AGS.Editor.Tests/Types/RoomTests.cs
- Editor/AGS.Editor.Tests/Types/UnloadedRoomTests.cs
- Editor/AGS.Editor/AGSEditor.cs
- Editor/AGS.Editor/AGSEditor.csproj
- Editor/AGS.Editor/Components/BaseComponentWithScripts.cs
- Editor/AGS.Editor/Components/RoomsComponent.cs
- Editor/AGS.Editor/EditorEvents.cs
- Editor/AGS.Editor/GUI/Progress.cs
- Editor/AGS.Editor/NativeProxy.cs
- Editor/AGS.Editor/Panes/Room/RoomSettingsEditor.cs
- Editor/AGS.Editor/Panes/ScriptEditor.cs
- Editor/AGS.Editor/Utils/BitmapExtensions.cs
- Editor/AGS.Editor/Utils/DirectoryInfoExtensions.cs
- Editor/AGS.Editor/Utils/FileWatchHelper.cs
- Editor/AGS.Editor/Utils/FileWatcher.cs
- Editor/AGS.Native/NativeMethods.cpp
- Editor/AGS.Native/NativeMethods.h
- Editor/AGS.Native/agsnative.cpp
- Editor/AGS.Types/AGS.Types.csproj
- Editor/AGS.Types/Interfaces/IRoom.cs
- Editor/AGS.Types/Interfaces/ISaveable.cs
- Editor/AGS.Types/Room.cs
- Editor/AGS.Types/RoomRegion.cs
- Editor/AGS.Types/Script.cs
- Editor/AGS.Types/SerializeUtils.cs
- Editor/AGS.Types/UnloadedRoom.cs
Reference #469
I still need to cleanup some code and do other improvements, but the most important mechanics are in place so I'm creating a draft PR so people can begin testing.
- When game is loaded into the editor an upgrade process will trigger. The code is handled from the editor but I imagine it'll be replaced with a CLI tool for processing rooms or something similar in the future. The upgrade process will extract room data and images and save them to disk under a directory `Rooms/{room-number}/`
- Room editor is refactored to read data directly from the new assets in the `Rooms/` directory. .crm files are mostly ignored until compile time.
- .crm files will now be generated from the data found in the `Rooms/` directory when rooms are saved/compiled, so with this PR these files …
> Functional open rooms

- Editor/AGS.Editor/Components/RoomsComponent.cs
- Editor/AGS.Editor/Panes/Room/RoomSettingsEditor.cs
Fixes a logic error on background import not resetting masks, and updates the dropdown menu of the available backgrounds when they are removed after a resolution change.
Closes #1431, #1426
> Editor: Fixes for #1138

- CMake/FetchSDL_Sound.cmake
- Windows/README.md
- ci/linux/Dockerfile
- ci/windows/Dockerfile
- debian/README.md
fix #1587
the SDL_sound fixes include:
- 24-bit wav PCM support
- some mp3 sounds were missing a bit of sound at their ends (see https://www.adventuregamestudio.co.uk/forums/index.php?topic=55681.msg636639498#msg636639498)
**Full commit comparison: https://github.com/icculus/SDL_sound/compare/ebcf0fe725448f9dbaa7884114e0b96b9c041570...12983b8acc8f89a4f0b4c320bdcc601a78824822   <<**
> SDL_sound: upgrade to commit icculus/SDL_sound/12983b8acc 

- Common/util/ini_util.cpp
- Common/util/ini_util.h
- Common/util/string_utils.cpp
- Common/util/string_utils.h
- Engine/CMakeLists.txt
- Engine/ac/global_game.cpp
- Engine/ac/global_game.h
- Engine/ac/listbox.cpp
- Engine/debug/debug.cpp
- Engine/gui/guidialog.cpp
- Engine/main/config.cpp
- Engine/main/config.h
- Engine/main/engine.cpp
- Engine/main/main.cpp
- Engine/main/main.h
- Engine/platform/android/acpland.cpp
- Engine/platform/base/mobile_base.cpp
- Engine/platform/base/mobile_base.h
- Engine/platform/ios/acplios.cpp
- Engine/platform/windows/setup/winsetup.cpp
Resolves #104.
* Reorganized config reading and writing functions, added read parameters used by other platforms (such as min/max value range).
* Moved common config management from Android and iOS into a file called "mobile_base.cpp". I noticed that both platforms host and read exactly same options, so there's no reason to have duplicate code. Made sure this code uses common cfg read/write functions.
* Reorganized platform-dependent file lists in CMakeList.txt, to have all non-common code under os condition. I am not well versed in cmake yet, so if this is wrong, i may return things back.
* Not related to config, but i noticed that selectLatestSavegame may be replaced by common functions too. If wanted, this could be done as a separate pr.
Potential todo:
* remove unused options (i …
> Use more common code for config reading and writing among platforms

- Compiler/script2/cs_parser.cpp
- Compiler/test2/cc_parser_test_0.cpp
- Compiler/test2/cc_parser_test_1.cpp
This partially addresses #1590.
Fix bug: AGS doesn't have static variables in `struct`s although there __are__ static functions and static attributes. The new compiler didn't catch this.
Typical code:
```
struct MyStruct {
static bool foo; // ← Compiler should complain at ';': 
//   Only function decls. may start with 'static' and no 'attribute'
}
```
> AGS4: New compiler: Disallow static variables in `struct`s

- Common/ac/spritefile.h
- Editor/AGS.Editor/AGSEditor.cs
- Editor/AGS.Editor/BuildTargets/BuildTargetDebug.cs
- Editor/AGS.Editor/Components/FileCommandsComponent.cs
- Editor/AGS.Editor/Components/HelpCommandsComponent.cs
- Editor/AGS.Editor/Components/RoomsComponent.cs
- Editor/AGS.Editor/Components/TranslationsComponent.cs
- Editor/AGS.Editor/GUI/BusyDialog.cs
- Editor/AGS.Editor/GUI/ExceptionDialog.cs
- Editor/AGS.Editor/GUI/GUIController.cs
- Editor/AGS.Editor/InteractiveTasks.cs
- Editor/AGS.Editor/NativeProxy.cs
- Editor/AGS.Editor/Panes/GeneralSettingsPane.cs
- Editor/AGS.Editor/Panes/SpriteSelector.cs
- Editor/AGS.Editor/Tasks.cs
- Editor/AGS.Editor/Utils/OldGameImporter.cs
- Editor/AGS.Editor/Utils/SpriteTools.cs
- Editor/AGS.Native/NativeDLL.vcxproj
- Editor/AGS.Native/NativeDLL.vcxproj.filters
- Editor/AGS.Native/NativeMethods.cpp
- Editor/AGS.Native/NativeMethods.h
- Editor/AGS.Native/SpriteFileWriter_NET.cpp
- Editor/AGS.Native/SpriteFileWriter_NET.h
- Editor/AGS.Native/agsnative.cpp
Meant to resolve #1404, but currently is a draft; still need to try this out and figure out the best approach to running the recreation tasks.
Implemented managed `SpriteFileWriter`, which is a C++ CLI wrapper around native SpriteFileWriter, also performing necessary conversions between .NET and native data.
Implemented `SpriteTools.WriteSpriteFileFromSources` method that writes a spritefile to the requested destination by reimporting images from sprite sources, or resorting to getting them from the current spritecache, if available.
If image is not available, then simply writes a dummy bitmap of the known size.
This process gets one sprite at a time, and disposes it after writing, thus the memory use supposed to stay low.
This function uses game's sprite compression settings.
Added a …
> Editor: feature recreating full spritefile from sources

- Editor/AGS.Types/Settings.cs
It looks like the `Old-style letterbox mode` doesn't belong in the `(Basic properties)` category anymore, and may be more well suited to the Backward Compatibility category.
This change moves it.
> Editor: letterbox mode moved to compatibility category

- Engine/ac/dynobj/cc_dynamicarray.cpp
This addresses #1604.
When calculating the length of a dynamic array, a value must be read from memory that is two integers in front of that array.  The `C++` code that accessed this memory location was incorrect.
> Fix bug in calculation for the length of a dynamic array

- Common/gfx/gfx_def.h
- Common/gui/guidefines.h
- Common/gui/guimain.cpp
- Common/gui/guimain.h
- Common/gui/guiobject.cpp
- Common/gui/guiobject.h
- Editor/AGS.Editor/Resources/agsdefns.sh
- Editor/AGS.Native/agsnative.cpp
- Engine/ac/draw.cpp
- Engine/ac/draw.h
- Engine/ac/event.cpp
- Engine/ac/guicontrol.cpp
- Engine/game/savegame_components.cpp
- Engine/gfx/ali3dogl.cpp
- Engine/gfx/ali3dogl.h
- Engine/gfx/ali3dsw.cpp
- Engine/gfx/ali3dsw.h
- Engine/gfx/ddb.h
- Engine/gfx/graphicsdriver.h
- Engine/platform/windows/gfx/ali3dd3d.cpp
- Engine/platform/windows/gfx/ali3dd3d.h
As #1393 makes it possible to accelerate gui controls, there's a next step to improve gui perfomance: support GUIControl.Transparency, implemented as a texture's render mode. Before that if one would like to have a translucent button graphic, they would have to either put that button on a standalone GUI, or use raw drawing (DrawImage with transparency arg) which is slower, especially in high-res games.
Adding transparency property itself does not require much changes, as all the logic is there. But since controls are part of the GUI sprite batch, this also means supporting batch's own alpha.
> Script API: implemented GUIControl.Transparency

- Editor/AGS.Editor/Resources/agsdefns.sh
- Engine/ac/draw.cpp
- Engine/ac/overlay.cpp
- Engine/ac/screenoverlay.cpp
- Engine/ac/screenoverlay.h
- Engine/game/savegame_components.cpp
- Engine/main/update.cpp
Resolves #1585.
1. Makes `Overlay.Width` and `Height` settable (previously were read-only). Changing them will scale overlay's image.
2. Added readonly `Overlay.GraphicWidth` and `GraphicHeight`, which return original image's size. This is necessary, because overlays may have autogenerated image, which sizes cannot be found using `Game.SpriteWidth/Height`.
> Script API: allow to scale overlays by setting Width & Height

- Editor/AGS.Editor/Panes/ScintillaWrapper.cs
The error is the following, in the editor, if you have the script editor open, and switch the color theme, it will cause a crash. It's reported in the forums here: https://www.adventuregamestudio.co.uk/forums/index.php?topic=59842.msg636645400#msg636645400
Commit that introduced the error https://github.com/adventuregamestudio/ags/commit/2ee7fc8334f7fd4eb50afdafeb12d2702ee13264
This fix prevents it happen. This is because for the script font change I had to reapply all styles, and for that, I had to reapply all the themed colors after reapplying the styles.
> Editor: fix changing theme when script editor is open causes error

- Editor/AGS.Editor/Components/RoomsComponent.cs
Corrected missing adjustment for mask resolution and handled out of bounds coordinates.
Closes #1625 
Is it fine like this or should the x/y traslation be moved elsewhere?
> Editor: fixed "Select area" tool issues

- Editor/AGS.Editor/Components/RoomsComponent.cs
- Editor/AGS.Native/agsnative.cpp
One problem was that the open format conversion function expects files with extension, while the room template unpacking saves them as "room3asc" and similar. 
The other issue with importing an existing room was that the conversion was not happening.
I tested game template, room templates, adding existing room, and creating a blank room. I hope I covered all the cases with this last fix.
> AGS 4 Editor: Fixes importing room template and existing room

- Common/game/roomstruct.cpp
- Common/game/roomstruct.h
- Editor/AGS.Editor/Components/RoomsComponent.cs
- Editor/AGS.Editor/NativeProxy.cs
- Editor/AGS.Editor/Tasks.cs
- Editor/AGS.Native/NativeDLL.vcxproj
- Editor/AGS.Native/NativeDLL.vcxproj.filters
- Editor/AGS.Native/NativeMethods.cpp
- Editor/AGS.Native/NativeMethods.h
- Editor/AGS.Native/NativeRoom.cpp
- Editor/AGS.Native/NativeRoom.h
- Editor/AGS.Native/agsnative.cpp
- Editor/AGS.Types/Room.cs
NativeRoom class wraps a native RoomStruct object and supports following operations:
* construct from a managed AGS.Types.Room;
* construct by loading from a CRM file (compiled room format);
* convert from native to managed AGS.Types.Room;
* retrieve backgrounds and masks, converting to System.Drawing.Bitmap;
* assign backgrounds and masks, converting from System.Drawing.Bitmap;
* saving native object to CRM file (compiled room format).
Removed `thisroom` global native object, because it's no longer usable anyway. Had to mark couple of places as broken (with FIXME) for the future.
Removed `_roomStructPtr` from the managed Room.
Removed precreating and loading a dummy CRM file when only saving the compiled room.
Removed unnecessary encoding conversion of compiled room files (since they are …
> AGS 4: reimplemented native room operations as NativeRoom class

- Compiler/script/cs_parser.cpp
- Compiler/test/cs_parser_test.cpp
fixes #1642 
Allows for float values to be used and shows errors when trying to use non-zero integers for float, String, or pointer types.
`-` Alan
> Fix compiler float defaults

- Engine/ac/gamesetup.cpp
- Engine/ac/gamesetup.h
- Engine/gfx/gfx_util.cpp
- Engine/main/config.cpp
- Engine/main/engine.cpp
- Engine/main/main.cpp
- Engine/main/main.h
- Engine/media/video/video.cpp
- Engine/platform/android/acpland.cpp
- Engine/platform/base/agsplatformdriver.h
- Engine/platform/base/mobile_base.cpp
- Engine/platform/base/mobile_base.h
- Engine/platform/ios/acplios.cpp
Resolves #106.
* Gathered mobile platform config options into MobileSetup struct.
* Removed all psp_* variables from the core engine code.
* Instead the engine receives port's special config using platform->ReadConfiguration().
* Mobile ports pass respective parts of the MobileSetup into the engine's own config.
* Added "load_latest_save" to the engine config.
More options could be transferred later (i noticed that some may still make sense but are not part of engine's config anymore).
> Tidy up mobile config once more and get rid of psp_* variables

- Editor/AGS.Editor/Components/RoomsComponent.cs
- Editor/AGS.Editor/Utils/BitmapExtensions.cs
Moving this to the general bitmap util class is more convenient because I want to use this method other places (like in the open sprites project)
> Refactored Bitmap loading non locked bitmaps method as util

- Common/gui/guidefines.h
- Editor/AGS.Editor/Resources/agsdefns.sh
- Engine/ac/button.cpp
- Engine/ac/character.cpp
- Engine/ac/character.h
- Engine/ac/characterextras.cpp
- Engine/ac/characterextras.h
- Engine/ac/characterinfo_engine.cpp
- Engine/ac/global_object.cpp
- Engine/ac/global_object.h
- Engine/ac/object.cpp
- Engine/ac/roomobject.cpp
- Engine/ac/roomobject.h
- Engine/ac/viewframe.cpp
- Engine/ac/viewframe.h
- Engine/game/savegame_components.cpp
- Engine/game/savegame_v321.cpp
- Engine/gui/animatingguibutton.cpp
- Engine/gui/animatingguibutton.h
- Engine/script/script_api.h
**Problem**
This has been a user complaint for a while that you cannot alter the volume of sounds linked to the view frames (animation). As these sounds are played automatically, with the current audio system it's not always possible to know which channel they will play on, and even if it were possible, it's not possible to catch that moment when the sound starts playing and adjust it immediately.
**Solution**
The proposed solution seem to be the simpliest available without doing much overhaul of the animation and/or audio system.
Instead of trying to modify the animation frames or the clip properties (which are shared resources and may be played simultaneously from different characters or objects), we view the object as a sound emitter and animation as a process of playing the frames …
> Script API: implement Character.AnimationVolume and volume param for Animate()

- Editor/AGS.Editor/Resources/agsdefns.sh
- Engine/ac/character.cpp
- Engine/ac/display.cpp
- Engine/ac/display.h
- Engine/ac/draw.cpp
- Engine/ac/global_overlay.cpp
- Engine/ac/overlay.cpp
- Engine/ac/overlay.h
- Engine/ac/screenoverlay.cpp
- Engine/ac/screenoverlay.h
- Engine/game/savegame_components.cpp
- Engine/game/savegame_v321.cpp
- Engine/main/update.cpp
Resolves #1044.
Resolves #1209.
Implements room overlays, that is Overlays that are drawn in the room "layer", inside the room viewport and sorted among characters, room objects and walk-behinds. This opens large possibilities, as overlays are created at runtime and are unlimited since 3.6.0. They may be used both as a one time visual effects, or to build a custom room object from ground up.
Technically, not a lot of changes were necessary, we just use same overlays with a flag; depending on the flag they are drawn either as a part of room or part of UI layer. For software renderer room overlays are also processed for walk-behind cropping.
In script, I've been in doubts how to organize this, so ended up with two extra factory functions duplicating two existing ones:
```
/// Creates an …
```
> 3.6.0: Room Overlays

- Editor/AGS.Editor/Resources/agsdefns.sh
- Engine/ac/draw.cpp
- Engine/ac/game.cpp
- Engine/ac/global_overlay.cpp
- Engine/ac/overlay.cpp
- Engine/ac/overlay.h
- Engine/ac/screenoverlay.cpp
- Engine/ac/screenoverlay.h
- Engine/game/savegame_components.cpp
- Engine/game/savegame_v321.cpp
- Engine/main/update.cpp
I think this is the last addition to Overlays, complementing new features added in the last version.
There's a historical issue that Overlays make a full copy of a sprite when created, instead of saving a sprite number like all other objects do. While overlay total number was limited (to 20 afaik) this could be tolerated, but as this restriction is now removed, and overlays may be created in any numbers, this issue becomes quite noteable. It increases the memory usage, often unnecessarily, which becomes silly if a large number of overlays are created using same sprites.
This change adds support for storing a sprite's number in overlays instead of making a bitmap copy, when possible. By default it does so if overlay is assigned a "normal" sprite from the game's resources, as regular …
> Support graphical Overlays not cloning the assigned sprite

- Editor/AGS.Editor/GUI/SpriteExportDialog.Designer.cs
- Editor/AGS.Editor/GUI/SpriteExportDialog.cs
- Editor/AGS.Editor/Panes/SpriteSelector.cs
- Editor/AGS.Editor/Utils/SpriteTools.cs
Possibly resolves #542.
**Expanded sprite export dialog and function.**
I had to redesign the options a bit, changing their logical meaning from "Skip if ..." to "Export only if ...", because it was difficult to combine multiple options otherwise. So old "Skip sprites where source file exists" became "Export if source file is missing".
Added "Export if source file is outside the project folder" option.
The export function exports everything if none of the "export only if" flags is set. Otherwise it exports only those which match one of the conditions.
~**Fixed the update source bug**~
~There has been a bug all this time: when the sprite export updates the source link, it does not add extension to the path, which makes it impossible to re-import from source (editor reports missing file). …
> Expand the sprite export options and add a quick sourceless sprite fixup command

- Common/core/platform.h
- Common/test/stream_test.cpp
- Common/util/bufferedstream.cpp
- Common/util/bufferedstream.h
- Common/util/file.cpp
- Common/util/filestream.h
- Common/util/memorystream.cpp
- Common/util/memorystream.h
BufferedStream has been excluded for writing operations for a while, because there were some problems with it. This PR fixes writing ops within BufferedStream, and adds a number of autotests for streams. Tests are cruicial, as mistakes in writing may lead to greater problems (e.g. damage user files).
Speed tests show that writing with BufferedStream is about 50% faster than with the FileStream (tested by writing long byte-by-byte sequences).
There's an annoying issue of BufferedStream being derived from FileStream rather than let choose what to work on, this is a problem with current streams hierarchy; meanwhile memory-backed FILE functions such as `fmemopen` and `open_memstream`, as these are not in standard C. For simplicity the tests now write and read the file, but just in case I …
> Use BufferedStream for writing files + added stream tests

- Engine/ac/draw.cpp
- Engine/ac/draw.h
- Engine/ac/game.cpp
- Engine/gfx/ali3dogl.cpp
- Engine/gfx/ali3dogl.h
- Engine/gfx/ali3dsw.h
- Engine/gfx/ddb.h
- Engine/gfx/gfxdriverbase.cpp
- Engine/gfx/gfxdriverbase.h
- Engine/gfx/graphicsdriver.h
- Engine/platform/windows/gfx/ali3dd3d.cpp
- Engine/platform/windows/gfx/ali3dd3d.h
Implements a short-term texture (DDB) cache in the graphics renderer(s).
**Has two purposes:**
* shares same texture data among multiple sprites on screen, somewhat reducing amount of texture recreations and memory requirements in case same sprite is used on a number of objects.
* potentially a foundation for implementing a long-term cache similar to the (bitmap) sprite cache in some future (may be seen as a practical experiment).
**Limits:**
* only short-term caching, the texture data is stored only so long as there's at least 1 object using this sprite.
* does not affect GUI and gui objects: since these may contain generated images, they would require additional changes to use this method. So, currently affects: characters, room objects and overlays.
**Implementation:**
* …
> Perfomance: implement short-term texture cache

- CMake/FetchSDL_Sound.cmake
- Windows/README.md
- ci/linux/Dockerfile
- ci/windows/Dockerfile
- debian/README.md
Updates SDL_sound to version in this commit here: https://github.com/icculus/SDL_sound/commit/32ee23e2018378225eba2c2bca8c2264bdbd369f
This should fix MID playback
> SDL_sound: upgrade to newer version

- Editor/AGS.Editor/Resources/agsdefns.sh
- Engine/ac/gamestate.cpp
- Engine/ac/global_api.cpp
- Engine/ac/global_game.cpp
- Engine/ac/global_game.h
- Engine/ac/runtime_defines.h
we are going to support more input types in the near future (Gamepad/Joystick/Touch Screen), at least for Gamepad we are probably going to need to some way of dealing with blocking actions like Speak that can be skipped. Instead of adding new `WaitGamepadMouseKey` functions, it would be interesting to have a more generic Wait function that could take additional parameters for the which inputs should be accepted when skipping this specific function.
I don't know yet how to make an `fInputAny` that would mean any and if when gamepad is added, I need it to include this in the same any or it's alright to then update the value of `fInputAny` on the script API.
> Add WaitInput in the Script API

- Editor/AGS.Editor/Components/DialogsComponent.cs
- Editor/AGS.Editor/Panes/DialogEditor.cs
fixes what was reported by Dave here: https://www.adventuregamestudio.co.uk/forums/index.php?topic=59842.msg636646209#msg636646209
I noticed this was different in Script Editor: https://github.com/adventuregamestudio/ags/blob/874fbbc7a729866dd8fa85c0cf1b0e2c75fce25c/Editor/AGS.Editor/Panes/ScriptEditor.cs#L515-L518
but also, it wasn't respecting what was asked in the `ZoomToFileEventArgs`, since `SelectLine` was true.
> Editor: DialogEditor selects line when required

- Engine/CMakeLists.txt
- Engine/Makefile-objs
- Engine/ac/gamesetup.h
- Engine/ac/room.cpp
- Engine/main/config.cpp
- Engine/main/engine.cpp
- Engine/media/audio/audio.cpp
- Engine/media/audio/audio_core.cpp
- Engine/media/audio/audio_core.h
- Engine/media/audio/sdldecoder.cpp
- Engine/media/audio/sdldecoder.h
- Engine/media/audio/sound.cpp
- Engine/media/audio/sound.h
- Engine/platform/base/mobile_base.cpp
- Engine/util/sdl2_util.cpp
- Engine/util/sdl2_util.h
- OPTIONS.md
- Solutions/Common.Lib/Common.Lib.vcxproj
- Solutions/Common.Lib/Common.Lib.vcxproj.filters
- Solutions/Engine.App/Engine.App.vcxproj
- Solutions/Engine.App/Engine.App.vcxproj.filters
After we changed to SDL2 and the new audio code, every sound clip is loaded into the memory at once now. The old code allowed to stream sound clips under some condition. In addition it had a sound cache for most frequently used sounds. This pr reimplements streaming within the new audio code, which is done if the sound asset is large enough, and a sound cache, this time coded in similarity with sprite cache (i believe in that in the future it might be possible to pick out shared code into a more universal resource cache class).
1. Engine decides whether to stream sound data from file, or load all at once, based on an asset size threshold.
2. For streaming, it passes opened ags stream into audio core, where the stream is wrapped into custom rwops for SDL sound. The reason why this is …
> Restore support for sound streaming if file is big enough + sound cache for small sounds

- Editor/AGS.Editor/Panes/WelcomePane.Designer.cs
- Editor/AGS.Editor/Panes/WelcomePane.cs
- Editor/AGS.Editor/Panes/WelcomePane.resx
Adjusts the Welcome pane for AGS 3.6! :)
When I was looking for where the Welcome pane was, I found a version list which I don't know if it should be updated or not, here:
https://github.com/adventuregamestudio/ags/blob/1c51caf1e8ddd33cff2aa2e6dd2eb55abe562786/Editor/AGS.Types/Game.cs#L1176
> Editor: Welcome pane adjust Upgrading To for 3.6 version

- Compiler/script2/cc_symboltable.h
- Compiler/test2/cc_bytecode_test_0.cpp
- Compiler/test2/cc_bytecode_test_1.cpp
- Compiler/test2/cc_bytecode_test_lib.cpp
- Compiler/test2/cc_bytecode_test_lib.h
- Compiler/test2/cc_parser_test_0.cpp
- Compiler/test2/cc_parser_test_1.cpp
- Compiler/test2/cc_scanner_test.cpp
Mostly affecting compiler2 tests.
> AGS 4: new compiler: replaced char* with const char* where necessary

- Engine/ac/gamestate.cpp
- Engine/ac/gamestate.h
- Engine/ac/overlay.cpp
- Engine/ac/speech.cpp
Presumably fixes #1678
This is a purely internal change. Engine currently keeps pointers to some types of script managed objects (which are merely wrappers over real object IDs) for easier internal use, but it is not really safe, as these objects may be forcedly disposed when deleting script data. Therefore this is not correct.
Affected object types are: Viewport, Camera and Overlay.
This change replaces the direct pointers to script objects with managed handles. Whenever engine needs to access these there's one extra step now, which safely retrieves a script object by handle and tests for result. But this operation is fast, and occurances are relatively rare, so should not be a problem.
> 3.6.0: don't store script object pointers in the game objects

- Engine/plugin/global_plugin.cpp
I did not notice there was already an `ags_shell` plugin check, and GH did not let me reopen the pull request after it closed. Turns out the new one is my own - and is just `agsshell`. It would be good though to support stubs for it.
Old Skies Demo shipped with this plugin.
> Engine: also include agsshell in ags_shell stub check

- Editor/AGS.Editor/GUI/TabbedDocumentManager.cs
Just a small suggestion, added "Help" command to the document's tab context menu, in case user does not know about F1, also if there are multiple subpanes with different keywords, this will ensure displaying help for the pane itself:
> Editor: added Help command for pane's tab context menu

- Editor/AGS.Editor/AGSEditor.csproj
- Editor/AGS.Editor/packages.config
do #1701 , but without the error
technically the CVE reported by the bot doesn't matter for us, since AGS isn't being ran in an IIS server, but as far as I can tell there has been no change in Newtonsoft.Json in behavior. We use it for the color theme.
> Bump Newtonsoft.Json from 10.0.3 to 13.0.1 in /Editor/AGS.Editor

- Plugins/agspalrender/agspalrender.h
A simple and hopefully self explanatory change.
The code was obviously copied from the agstouch plugin 😉
> Fix include guard for agspalrender.h

- Engine/platform/windows/gfx/ali3dd3d.cpp
- Engine/plugin/agsplugin.cpp
- Engine/util/library.h
- Engine/util/library_dummy.h
- Engine/util/library_posix.h
- Engine/util/library_windows.h
This is not related to any open issue; but when debugging one problem recently I realized that Library class does not save library's name etc. So I decided to add this information, and tidy the code along.
* No significant functional changes.
* Tidy code and apply the preferred code style.
* Hid class members that should not be public.
* Fixed implementation that did not have safe checks when disposing.
* Save name and path in the Library class.
* Added GetName(), GetFilePath() and IsLoaded() members.
In addition use wide-char winapi function in the WindowsLibrary (because we are supposed to support utf-8 paths now).
TODO: need to be tested on Linux and Android.
> Tidy Library classes

- Compiler/test2/cc_parser_test_0.cpp
- Compiler/test2/cc_scanner_test.cpp
There has been some kind of a mistake in the new compiler's Scanner class that resulted in the incorrect parsing and/or testing of int32 negative limit (see #1674). Unfortunately, the tests were adjusted to comply for this incorrect behavior, which is quite a wrong thing to do, in my opinion. A recent commit (53538101712f81359a4b4162e1142bb4f0c875bb) fixed one problem in practice, but introduced new ones, and some tests no longer work.
In order to introduce some clarity to this, I suggest correcting the tests first. Note that "Scan.LiteralIntOverflow" test does not work correctly after (53538101712f81359a4b4162e1142bb4f0c875bb), while "Scan.LiteralIntLimits" won't work if that commit would be reverted.
In addition this adds hexadecimal test for the scanner.
> AGS 4: new compiler: fixed int32 limit tests

- Android/library/runtime/src/main/java/uk/co/adventuregamestudio/runtime/AGSRuntimeActivity.java
these methods and properties are accessed from the Native parts in acpland, but we extend `AGSRuntimeActivity` as `AGSPlayerRuntimeActivity` for the AGS Player app, so these need to be protected instead of private to be accessible.
For some reason this behavior is only affecting native in old versions of Android (!)
fix #1712
> Android: fix access level for extended classes

- CMakeLists.txt
- Common/CMakeLists.txt
- Common/ac/spritecache.cpp
- Common/core/platform.h
- Engine/CMakeLists.txt
- Engine/ac/dynobj/cc_dynamicobject.cpp
- Engine/ac/dynobj/managedobjectpool.h
- Engine/debug/debug.cpp
We used to set macro DEBUG_SPRITECACHE=1 in Debug builds and DEBUG_SPRITECACHE=0 in Release builds,
and also set DEBUG_MANAGED_OBJECTS=0 or 1 depending on the command line config of AGS_DEBUG_MANAGED_OBJECTS
But in the code, we actually test using `#ifdef` instead of `#if`.
This commit
- only define DEBUG_MANAGED_OBJECTS if AGS_DEBUG_MANAGED_OBJECTS is true
- adds a new command line flag AGS_DEBUG_SPRITECACHE, which will only define DEBUG_SPRITECACHE if true
> CMake: debug defines only set per external config

- Compiler/script2/cc_symboltable.cpp
- Compiler/script2/cc_symboltable.h
- Compiler/script2/cs_compile_time.cpp
- Compiler/script2/cs_parser.cpp
- Compiler/script2/cs_parser.h
- Compiler/script2/cs_scanner.cpp
- Compiler/script2/cs_scanner.h
- Compiler/test2/cc_bytecode_test_0.cpp
- Compiler/test2/cc_bytecode_test_1.cpp
- Compiler/test2/cc_parser_test_0.cpp
- Compiler/test2/cc_parser_test_1.cpp
- Compiler/test2/cc_scanner_test.cpp
This PR addresses #1711 and #1674.
- Accept '2147483648' in the scanner but balk in the parser unless a unary '-' is in front.
- Accept hexadecimals between '0x80000000' and '0xFFFFFFFF' in the scanner, interpret them as negative integers. (In particular, '0x80000000' is '-2147483648'.)
- Reject hexadecimals beyond '0xFFFFFFFF'.
- Compile-time calculation: The negative of '-2147483648' yields an overflow at compile time.
- Treat integers that start with '0' and no following 'x' as decimal instead of octal.
- Add more googletests for scanner + parser. (I've slightly extended existing tests or moved them into the parser googletests but not reduced them AFAICS.)
- If error messages feature exceptionally long numbers, only show the first 20 digits.
> AGS4: New compiler: Accept LONG_MIN in scanner + parser; don't treat leading '0' as octal

- Compiler/test2/cc_bytecode_test_0.cpp
- Compiler/test2/cc_bytecode_test_1.cpp
- Compiler/test2/cc_parser_test_0.cpp
- Compiler/test2/cc_parser_test_1.cpp
Perused the files and found some cases that haven't been fixed yet.
In all googletest files for the compiler:
- Change `char *` and `const const char *` to `const char *`
- Change `char inpl[]` and similar to `const char inpl[]`
> New compiler: Handle C strings as `const char *` or `const char[]` in Googletests

- Editor/AGS.Editor/NativeProxy.cs
- Editor/AGS.Editor/Panes/CharacterEditor.Designer.cs
- Editor/AGS.Editor/Panes/CharacterEditor.cs
- Editor/AGS.Editor/Panes/CharacterEditor.resx
- Editor/AGS.Editor/Panes/InventoryEditor.Designer.cs
- Editor/AGS.Editor/Panes/ViewEditor.Designer.cs
- Editor/AGS.Editor/Panes/ViewEditor.cs
- Editor/AGS.Editor/Panes/ViewPreview.Designer.cs
- Editor/AGS.Editor/Panes/ViewPreview.cs
- Editor/AGS.Editor/Panes/ViewPreview.resx
- Editor/AGS.Editor/Utils/MathExtra.cs
- Editor/AGS.Editor/Utils/Utilities.cs
- Editor/AGS.Native/NativeMethods.cpp
- Editor/AGS.Native/NativeMethods.h
- Editor/AGS.Native/agsnative.cpp
Completes #710.
The View editor's zoom was implemented by #1415, but preview frame was still unscaled.
While working on this I also noticed that the Character preview pane does not have a zoom control, unlike Inventory and Cursor preview panes which recently received a zoom control.
This PR:
1. ViewPreview control now displays a frame inside a panel with automatic scrollbar, which is displayed if the image is larger than the panel. The frame resizes if the (scaled) sprite cannot fit. It keeps the "default" size in memory, and sets it back if the sprite is small enough: this prevents small sprites from being drawn too low at the window bottom.
2. ViewPreview control now has AutoResize property, that tells it to resize itself (whole control) if the image frame is too big or small. …
> Editor: zoom View's preview frame and Character preview

- Engine/CMakeLists.txt
- Engine/Makefile-objs
- Engine/plugin/agsplugin.cpp
- Engine/plugin/agsplugin.h
- OSX/xcode/AGSKit/AGSKit.xcodeproj/project.pbxproj
- Plugins/AGSSpriteFont/AGSSpriteFont/AGSSpriteFont.cpp
- Plugins/AGSSpriteFont/AGSSpriteFont/AGSSpriteFont.h
- Plugins/AGSSpriteFont/AGSSpriteFont/AGSSpriteFont.vcxproj
- Plugins/AGSSpriteFont/AGSSpriteFont/SpriteFontRenderer.cpp
- Plugins/AGSSpriteFont/AGSSpriteFont/SpriteFontRenderer.h
- Plugins/AGSSpriteFont/AGSSpriteFont/SpriteFontRendererClifftopGames.cpp
- Plugins/AGSSpriteFont/AGSSpriteFont/SpriteFontRendererClifftopGames.h
- Plugins/AGSSpriteFont/AGSSpriteFont/VariableWidthFont.cpp
- Plugins/AGSSpriteFont/AGSSpriteFont/VariableWidthFont.h
- Plugins/AGSSpriteFont/AGSSpriteFont/VariableWidthSpriteFont.cpp
- Plugins/AGSSpriteFont/AGSSpriteFont/VariableWidthSpriteFont.h
- Plugins/AGSSpriteFont/AGSSpriteFont/VariableWidthSpriteFontClifftopGames.cpp
- Plugins/AGSSpriteFont/AGSSpriteFont/VariableWidthSpriteFontClifftopGames.h
- Plugins/AGSSpriteFont/Makefile-objs
- iOS/xcode/ags/ags.xcodeproj/project.pbxproj
This pull request does mainly two things:
* Register the AGSSpriteFont plugin (since currently it is not used and stub functions are used instead).
* Implement the variant of the plugin used for Clifftop Games (Kathy Rain and Whispers of a Machine).
It also fixes some issues with the AGSSpriteFont plugin, such as memory leaks.
I am aware of PR #834, but I used a different approach in the implementation here: I added two new font renderer classes that derive from the unmodified ones of the original plugin and implement the modified functions only. The advantage of this approach is that we can either instantiate the base renderers or the modified ones depending on the game. However that is something I did not actually know how to do (see f89a2f5ff14c111efd7ed52a57ad309cf491f7cb) so any …
> Implement AGSSpriteFont plugin for Clifftop Games

- Common/font/agsfontrenderer.h
- Common/font/fonts.cpp
- Common/font/fonts.h
- Common/font/ttffontrenderer.cpp
- Common/font/ttffontrenderer.h
- Common/font/wfnfontrenderer.cpp
- Common/font/wfnfontrenderer.h
- Engine/plugin/agsplugin.cpp
- Engine/plugin/agsplugin.h
- Plugins/AGSSpriteFont/AGSSpriteFont/AGSSpriteFont.cpp
- Plugins/AGSSpriteFont/AGSSpriteFont/SpriteFontRenderer.cpp
- Plugins/AGSSpriteFont/AGSSpriteFont/SpriteFontRenderer.h
- Plugins/AGSSpriteFont/AGSSpriteFont/VariableWidthSpriteFont.cpp
- Plugins/AGSSpriteFont/AGSSpriteFont/VariableWidthSpriteFont.h
- Plugins/AGSSpriteFont/AGSSpriteFont/VariableWidthSpriteFontClifftopGames.cpp
- Plugins/AGSSpriteFont/AGSSpriteFont/VariableWidthSpriteFontClifftopGames.h
Fixes #1742
CC: @criezy 
This is an experimental change and related to plugin API, so opening as a draft for now. But it actually fixes all the "Whispers of the machine" font issues.
**The reasoning for changes:**
The old `IAGSFontRenderer` interface unfortunately did not provide proper means to return neither font height nor custom linespacing. Instead it had GetTextHeight(text), which in my honest opinion was a mistake to add, as fonts normally should have a specific height property even if individual characters (glyphs) have varied height.<br>
But anyway, the "Clifftop Games" abused GetTextHeight to also return linespacing depending on which text is passed as an argument, using "secret knowledge" about which lines engine uses for a font height test. This mechanic was doomed to be …
> Introduced extended FontRenderer plugin API, more fixes for "Clifftop's" SpriteFont

- Engine/ac/draw.cpp
- Engine/gfx/ali3dogl.cpp
- Engine/gfx/ali3dogl.h
- Engine/gfx/ali3dsw.cpp
- Engine/gfx/ali3dsw.h
- Engine/main/engine.cpp
- Engine/platform/windows/gfx/ali3dd3d.cpp
- Engine/platform/windows/gfx/ali3dd3d.h
Experiment to support togglable VSync at runtime.
Currently implemented: D3D, OGL, and SW mode.
Software mode require SDL2 >= 2.0.18 (gracefully degrades depending on available version at compile)
- D3D requires a reset(), while OGL can be switched directly.
- I removed the outdated restriction about windowed modes not supporting VSync.
- I had to force the current mode's Vsync value to `last_opposite_mode.Vsync` and `usetup.Screen.Params.VSync` so it doesn't get lost while switching from windowed<->fullscreen
- SW and D3D mode appears to keel over whenever reapplying the same vsync value at fullscreen, therefore I added a check to avoid doing so
> Engine: VSync toggle support

- Editor/AGS.Editor/AutoComplete.cs
- Editor/AGS.Editor/Panes/ScintillaWrapper.cs
- Editor/AGS.Editor/Panes/ScriptEditor.cs
- Editor/AGS.Types/AGS.Types.csproj
- Editor/AGS.Types/EditorFeatures/AutoComplete/ScriptAutoCompleteData.cs
- Editor/AGS.Types/EditorFeatures/AutoComplete/ScriptDefine.cs
- Editor/AGS.Types/EditorFeatures/AutoComplete/ScriptEnum.cs
- Editor/AGS.Types/EditorFeatures/AutoComplete/ScriptEnumValue.cs
Enabled the "Go to DEFINITION" contextual menu option to work with `#define`s, enum types, and enum values.
Possible improvements:
- ~track enum values to the exact line~ DONE
- throw message for builtin enums, like when trying to go to views/audios script names (unless we plan to show builtin headers in the future)
> Editor: Implement "Go to Definition" for Define and Enum

- Engine/platform/base/sys_main.cpp
Fixes #1692.
CC: @ericoporto 
Following the discussion in #1692, we must use a combination of SDL_setenv(SDL_AUDIODRIVER) and SDL_InitSubSystem here, and *not* use SDL_AudioInit, because SDL_AudioInit does not increment subsystem's reference count. Which in turn may cause problems down the way when initializing any additional SDL-based audio lib or plugin; at the very least - the mojoAl (OpenAL's implementation we're using).
If we specifically requested a driver name, and that failed, we fallback to automatic drivers list by resetting environment variable SDL_AUDIODRIVER and calling SDL_InitSubSystem(SDL_INIT_AUDIO) again. That forces SDL to try every available driver in an order.
**IMPORTANT:** For the second step, the point is to make SDL_getenv to return NULL, so that SDL_AudioInit …
> 3.6.0: Initialize SDL audio using env variables, don't SDL_AudioInit

- .cirrus.yml
minimal change so that the MacOS binaries in the CI are both arm64 and intel compatible. This makes the MacOS build take more time though - it still will finish earlier than the rest of the CI.
> CI: MacOS builds to fat binary

- Plugins/AGSSpriteFont/AGSSpriteFont/AGSSpriteFont.cpp
- Plugins/agsblend/AGSBlend.cpp
- Plugins/agspalrender/ags_palrender.cpp
When I tried to build with built-in plugins on Windows, I was getting compilation errors, I was able to build fine after the following changes.
> Plugins: built-in plugins don't need DLL entrypoint

- Editor/AGS.Editor/ColorThemes/Controls/ComboBoxCustom.cs
Fix #1760 
I get there could be a better solution but I think this is the less disruptive for 3.6.0.
> Editor: properties combobox lost subscribed events when themed

- Script/push_version.py
Just adding a parenthesis. Python 2 will still work with it, but python 3 won't error with the parenthesis.
> Script: push_version compatible with Python 3 too

- Android/library/runtime/src/main/java/org/libsdl/app/SDLActivity.java
fix broken keyboard text input on Android. 
Explained in details here: https://github.com/adventuregamestudio/ags/issues/1756#issuecomment-1242514082 , the right fix would be to implement IME I think, but until SDL figures what to do upstream, I think it's ok to revert to the previous behavior and fix with the other way next time we upgrade SDL2.
> Android: fix android keyboard doesn't print characters

- Editor/AGS.Editor/Components/RoomsComponent.cs
- Editor/AGS.Editor/Panes/Room/RoomEditFilters/BaseAreasEditorFilter.cs
- Editor/AGS.Types/Constants.cs
- Normalizes palettes also handling partial palettes
- Safer handling of invalid masks
- Added PNG to the formats available for mask export/import
- Restored the original red color for mask brushes
> Mask handling improvements

- Compiler/script2/cs_parser.cpp
- Compiler/script2/cs_parser.h
- Compiler/test2/cc_parser_test_1.cpp
This PR addresses #1775.
When a function is called, each parameter must be an expression; it cannot be an assignment. Flag `=` in function call parameters.
Typical code: 
```
{
int foo;
Debug(4, foo = 7); // <-- Compiler should balk here
}
``` 
(Also fix an inconsistency in function `ParseExpression()` that I found when fixing this bug: This function is called with a parameter `src` but had ignored this parameter and used the field `_src` instead, which was wrong.)
> New compiler: Flag `=` in function call parameters

- Android/library/runtime/src/main/java/uk/co/adventuregamestudio/runtime/AGSRuntimeActivity.java
- Android/library/runtime/src/main/res/values/arrays.xml
- Android/library/runtime/src/main/res/values/strings.xml
- Android/library/runtime/src/main/res/xml/preferences.xml
- Common/util/geometry.h
- Engine/ac/gamesetup.cpp
- Engine/ac/gamesetup.h
- Engine/ac/sys_events.cpp
- Engine/device/mousew32.cpp
- Engine/main/config.cpp
- Engine/platform/android/acpland.cpp
- Engine/platform/base/mobile_base.cpp
- Engine/platform/base/mobile_base.h
- Engine/platform/base/sys_main.cpp
This reimplements touch-to-mouse controls inside the engine, similar to the control scheme of 3.5.1 (before moving to SDL2 and new Android port), with minor differences. Touch-to-mouse emulates mouse buttons and motion, letting players to control AGS games with Android port. The 3.6.0 currently uses default SDL2 emulation, which only supports LMB, but that's not enough for games which require RMB too.
Mouse emulation is enabled using a config setting ("[touch]", "emulate_mouse"). This parameter may have several values, acting as a choice between the control schemes. Right now it supports 2 schemes: a default SDL2-like scheme and reimplementation of an old AGS scheme (see below). The touch-to-mouse may also be disabled completely. In theory, it may be disabled also by the game's own …
> Android: reimplement touch-to-mouse controls in the engine

- Android/README.md
- Android/library/runtime/src/main/res/values/strings.xml
- Android/library/runtime/src/main/res/xml/preferences.xml
- Android/misc/android.cfg
- Editor/AGS.Editor/BuildTargets/BuildTargetAndroid.cs
- Engine/platform/android/acpland.cpp
- Engine/platform/base/mobile_base.cpp
- Engine/platform/base/mobile_base.h
This removes following preferences that no longer have implementation in the engine:
* Sound - Use multithreading (cannot be toggled now, depends on compilation flags)
* Sound - samplerate (was not exposed to menu)
* Midi options group
> Android: remove deprecated/unused preferences

- Android/library/runtime/src/main/java/uk/co/adventuregamestudio/runtime/PreferencesActivity.java
- Android/library/runtime/src/main/res/values/strings.xml
- Android/library/runtime/src/main/res/xml/preferences.xml
- Common/util/geometry.h
- Engine/ac/sys_events.cpp
- Engine/platform/android/acpland.cpp
- Engine/platform/base/mobile_base.cpp
- Engine/platform/base/mobile_base.h
Resolves #862.
Use the mouse speed config option when generating emulated touch-to-mouse events.
@ericoporto added your commit with the option in AGS Player's preferences.
> Android: support relative speed factor for touch-to-mouse emulation

- Compiler/preproc/preprocessor.cpp
- Compiler/preproc/preprocessor.h
- Editor/AGS.CScript.Compiler/Entities/ErrorCode.cs
- Editor/AGS.CScript.Compiler/Preprocessor.cs
- Editor/AGS.Editor/Components/TranslationsComponent.cs
- Editor/AGS.Editor/TextProcessing/SpeechLinesNumbering.cs
The main goal of this PR is to prevent data loss and corruption from dealing with unclosed strings,
- Fixed the preprocessor not reporting unterminated literals
- Abort translation update on error
- Abort auto-numbering speech line on error
- Reload translation froms disk before any update operation to prevent loss of user changes
With these commits all causes of corruption and data loss, when dealing with translations and autonumbering speech, should be covered.
When something fails, the operation is aborted without applying changes.
Might be worth backporting to 3.5.1
fixes #1777,  #1022
> Handle unterminated strings to avoid data corruption

- OSX/README.md
adjustments to fix #1684
future things for MacOS would be
- uploading the engine binary to CI artefacts
- some way to [build from editor](https://github.com/adventuregamestudio/ags/issues/1333#issuecomment-1042790885)
- updating the xcode projects
> OSX: minor readme adjustment

- Engine/plugin/global_plugin.cpp
AGS Blend plugin functions are listed in it's source code.
https://github.com/adventuregamestudio/ags/blob/c30138ddcbdb658dde7d513303e57efcc1ee4463/Plugins/agsblend/AGSBlend.cpp#L886-L892
DrawSprite stub was missing, this is why things have always crashed when I forgot to turn built-in plugins on!
[link to my comment about this ages ago](https://github.com/adventuregamestudio/ags/issues/1148#issuecomment-765043268)
> Engine: fix agsblend plugin stub missing DrawSprite

- CMake/FetchSDL2.cmake
I was playing with Ubuntu 16.04, and noticed that the wrong `SDL_config.h` was being used. This change should ensure the CMake genereated one is used when using CMake.
> CMake: make sure generated SDL_config.h is used

- Common/util/multifilelib.cpp
Hi,
This small fix comes from ScummVM testing on a big-endian system. Games using `MFLUtil::ReadV21()` would try to allocate gigantic amounts of memory, because some values were not read properly.
`MFLUtil::ReadEncInt32()` just didn't use the return value of `SwapBytesInt32()`, and so this value was still represented with the wrong endianness.
> Common: fixed ReadEncInt32() on big-endian systems

- Editor/AGS.Editor/Panes/ScintillaWrapper.cs
- Editor/AGS.Editor/Panes/ScriptEditor.cs
I am a bit confused, according to [rongel in the forums](https://www.adventuregamestudio.co.uk/forums/index.php?topic=59842.msg636649791#msg636649791) we had this feature previously. But I just checked and we didn't. I did found some code that is meant to provide some brace highlighting while typing, but it doesn't work for me in the 3.5.1 branch. 
I honestly don't remember this feature, but in case we actually had it, this works and is a small change to merge.
> Editor: scintilla automatically highlights braces in current position

- Engine/gfx/ali3dsw.cpp
fix #1799 
Offset is calculated using `ScalePt`, which already includes the destination rectangle offset in it's calculations, so the additional math later is not needed.
> Engine: fix gfx sw driver presented offset twice

- Editor/AGS.Editor/AGSEditor.csproj
- Editor/AGS.Editor/Entities/EditorPreferences.cs
- Editor/AGS.Editor/GUI/PreferencesEditor.Designer.cs
- Editor/AGS.Editor/GUI/PreferencesEditor.cs
- Editor/AGS.Editor/GUI/frmMain.Designer.cs
- Editor/AGS.Editor/packages.config
This is a WIP for improved theme support.
Features:
- simpler theme format with fallback global values - [DOWNLOAD THEMES](https://www.dropbox.com/s/6hlc00l36a4nz88/Themes_v3.zip?dl=0)
- added a few themeable elements
- VS2015 Blue Theme (other variations and original base theme can be changed in preferences)
- implemented Scintilla's ScrollWidthTracking for auto horizontal scrollbar sizing
- small improvements to default theme
The expanded theme code has simplified some areas, and I made it backward compatible-ish (a few renamed styles won't load without throwing errors).
This is not the perfect solution I'd like to have implemented, but it's a little better than we currently have, both for source code and for theme authoring.
Other areas of improvement:
Abandoned:
- ~VS2015 theme …
> Ags4: Editor UI refresh

- Engine/ac/display.cpp
- Engine/ac/display.h
- Engine/ac/global_overlay.cpp
- Engine/ac/overlay.cpp
- Engine/ac/screenoverlay.cpp
- Engine/ac/screenoverlay.h
- Engine/game/savegame_components.cpp
- Engine/game/savegame_v321.cpp
This addresses a problem which I found while was fixing #1797 (it was not directly related to 1797 though).
**The problem**
Previously `Overlay.SetText()` was passing into `CreateTextOverlay()` -> `Overlay_CreateTextCore()` -> `_display_main()`.
This effectively removed and recreated an internal overlay object with different image but the same ID.
Also, previously, this method could have been only called for custom overlays in practice. For these the script object was not touched, and kept the correct overlay reference.
The situation has changed when we let user script to access some of the internally created overlays, such as Text and Portrait overlays created by a blocking Say command (`Speech.TextOverlay` and `Speech.PortraitOverlay`). When these overlays are recreated, they also must …
> Don't recreate overlay object in call to Overlay.SetText()

- CMake/FetchSDL2.cmake
- ci/linux/Dockerfile
- ci/windows/Dockerfile
to harmonize the builds, make sure Android, Windows, Linux and MacOS are using the same [SDL 2.24.1](https://github.com/libsdl-org/SDL/releases/tag/release-2.24.1), avoiding depending on a specific commit. I tested the Android build to make sure it's alright, Windows too. This SDL is based on [release-2.24.x branch](https://github.com/libsdl-org/SDL/commits/release-2.24.x).
better wait the CI to finish just before merging just in case.
> Upgrade SDL to 2.24.1

- Common/libinclude/ogg/config_types.h.in
- Common/libinclude/ogg/ogg.h
- Common/libinclude/ogg/os_types.h
- Common/libinclude/theora/codec.h
- Common/libinclude/vorbis/codec.h
- Common/libsrc/freetype-2.1.3/src/gzip/ftgzip.c
- Engine/Makefile-defs.osx
- Engine/plugin/plugin_builtin.h
- OSX/README.md
- OSX/xcode/AGSKit/AGSKit.xcodeproj/project.pbxproj
- OSX/xcode/AGSKit/AGSKit.xcodeproj/xcshareddata/xcschemes/AGSKit.xcscheme
- OSX/xcode/AGSKit/AGSKit/Info.plist
- OSX/xcode/ags/ags-Info.plist
- OSX/xcode/ags/ags.entitlements
- OSX/xcode/ags/ags.xcodeproj/project.pbxproj
- OSX/xcode/ags/ags.xcodeproj/xcshareddata/xcschemes/ags.xcscheme
- OSX/xcode/ags/plugin_registration.cpp
This should make the Xcode project be useable again in macOS. This is useful to figure out the iOS port (#1505), as it will require using Xcode.
It requires some manual steps which I detailed in the README.
I can split the contents of this commit in different ones if necessary.
---
When trying to use Xcode to debug AGS, I could not make AGS work for nothing... Turns out Xcode by default adds some parameters to a debugged executable and AGS was picking up these. 
I configured the debug schemes here to not add these parameters, so things are working. But I think maybe we should print the full argv if there's an unused parameter that is preceded by `-`. I will probably open an issue on this later.
> MacOS: update xcode project

- Common/gfx/allegrobitmap.cpp
- Common/gfx/allegrobitmap.h
- Common/gfx/bitmap.cpp
- Common/gfx/bitmap.h
- Engine/ac/global_dynamicsprite.cpp
- Engine/main/engine.cpp
- libsrc/allegro/include/allegro/gfx.h
- libsrc/allegro/include/allegro/internal/aintern.h
Following discussion from #1681
The idea is to create a method to read `.bmp` images from Stream (and store in bitmap objects), and write a `.bmp` image to a Stream (based from a bitmap object).
This is because current allegro methods in use work in either File or PackFile, but not the in use AGS Streams.
- ~~method to convert a bmp color depth to the game color depth~~
- make sure game palette is not overridden by the palette on bmp file. Not sure how to do this?
We can also decide we don't need this right now, since the packfile bmp writing bug has been fixed (#1681), since it's really close for 3.6.0 to be stable.
> Add bitmap streamer

- Engine/ac/dynobj/cc_dynamicarray.cpp
A minor mismatched free picked in `cc_dynamicarray.cpp`, it uses new char[...] but frees it using a delete instead of delete[]. I am trying to learn how to use valgrind and picked this.
I am leaving it as draft because I want to run a simple game that allocates and deallocates a dynamic array to verify this is correct. There isn't many things in AGS code in valgrind, it generates a bunch of false positives when using my intel video card with the opengl driver.
> mismatched free in cc_dynamicarray

- OSX/README.md
- OSX/xcode/AGSKit/AGSKit.xcodeproj/project.pbxproj
- OSX/xcode/ags/ags-Info.plist
- OSX/xcode/ags/ags.xcodeproj/project.pbxproj
Minor fix for macOS port
- README includes CMake main usage link
- Xcode links the app statically to the engine library and doesn't embed the AGSKit framework, reducing 17 MB in `.app` size (an ags macOS app now starts at around 7MB)
- Xcode project correctly shows icon in the app when using the archive build scheme
> Fix macos icon

- Engine/ac/file.cpp
Fixes #1822
This fixes engine failing to properly resolve script paths which contain subdirectories. This results in subdirs never created and files failing to open for writing.
Was likely broken somewhere in the middle of 3.6.0 development. But it will be proper to double check that 3.5.1 still works correctly, and if not also apply a corresponding fix there.
EDIT: Tested 3.5.1 and it works fine, so this is only a 3.6.0 bug.
Things to test:
* File.Open with eFileWrite or FileAppend;
* DynamicSprite.SaveToFile;
* Tokens: `$SAVEGAMEDIR$`, `$APPDATADIR$`, no token should remap to `$APPDATADIR$` automatically (with and without subdirs).
> Fixed ResolveScriptPath not handling subdirs correctly

- Editor/AGS.Editor/Components/BaseComponentWithFolders.cs
- Editor/AGS.Editor/GUI/ProjectTree.cs
The tree view was entirely repopulated in order to sort folders before other entries, but doing so could break focusing on the newly created item due to keys being recreated from scratch.
I added a check to directly insert folders where appropriate, along with an exception for the Audio where the speech icon stays above.
Fixes #1811
> Editor: do not repopulate the tree when adding new folders

- Editor/AGS.Editor/GUI/CallStackPanel.Designer.cs
- Editor/AGS.Editor/GUI/FindResultsPanel.Designer.cs
- Editor/AGS.Editor/GUI/OutputPanel.Designer.cs
- Editor/AGS.Editor/GUI/ProjectPanel.Designer.cs
- Editor/AGS.Editor/GUI/PropertiesPanel.Designer.cs
- Editor/AGS.Editor/GUI/frmMain.Designer.cs
Assigning to the Dock property has side effect. It should only be specified on the components themselves, never from frmMain.
> Editor: restore proper panel dock fill behavior

- Common/game/main_game_file.cpp
By default `std::shared_ptr` uses `delete` to delete its data. When using it to store an array we need to pass a custom deleter that uses `delete []` instead. The easiest way to do this is to use the partial specialisation of `std::default_delete` for arrays.
> Common: Fixed new[]/delete mistmatch

- Engine/gfx/ali3dsw.cpp
- libsrc/allegro/include/allegro/gfx.h
- libsrc/allegro/include/allegro/inline/gfx.inl
- libsrc/allegro/include/allegro/internal/aintern.h
- libsrc/allegro/src/allegro.c
- libsrc/allegro/src/c/cmisc.c
- libsrc/allegro/src/graphics.c
- libsrc/allegro/src/vtable15.c
- libsrc/allegro/src/vtable16.c
- libsrc/allegro/src/vtable24.c
- libsrc/allegro/src/vtable32.c
- libsrc/allegro/src/vtable8.c
the bank switching methods are unused and safe for removal. Maybe just wait the CI build, but I could not find any use for these.
> Allegro: remove bitmap bank stuff

- Engine/gfx/gfxdriverbase.cpp
> Perhaps it should be made a plugin's responsibility to clear if it needs to. Because now engine will still do certain action without knowing whether plugin needs it at all (plugin may be performing a 3D rendering without using raw stage surface).
For the last point, in this case the plugin can simply return false, right?
https://github.com/monkey0506/ags2client/blob/7db4df8baccf955b0ff9fb496d9779a2fb90bf25/main.cpp#L136
The above is used in agsteam plugin, so it currently affects all AGS games on Steam. 
---
I think this is safe to be applied, but perhaps the responsibility change has to be something for a next version change.
TO-DO: figure out if there is any plugin besides SnowRain that uses this call for **drawing** edit: ags_parallax and palrender in this repository also use the …
> Engine: only clear _stageScreen after it's dirty

- Common/gfx/allegrobitmap.h
The initial proposal was to redo this using GetData
> This is definitely a mistake that GetScanLine was still in use; it's a remnant of times when Bitmap class was introduced trying to fully mimic Allegro's BITMAP behavior. Allegro's BITMAP could contain different kind of data, starting from simple linear bitmaps, and following with video textures, planar bitmaps, etc. But the engine was mostly using linear memory bitmaps (except for the final render to screen, afaik), and now when Allegro's source is stripped, there are no other bitmap types supported at all.
> 
> So it's correct to assume that Bitmap's data is simply a linear array of pixels with fixed stride calculated as w*h*bpp, do not use GetScanLine at all, and use GetData instead for getting the beginning of array once. The length …
> Scanline safety check as assert 

- Engine/ac/draw.cpp
https://github.com/adventuregamestudio/ags/blob/b327011f0cd07a2d02f7fcafaee967b024f8c2f7/Engine/ac/draw.cpp#L1620
the `construct_object_gfx` should return `true` if the texture doesn't change, and `false` if it doesn't, but the logic was inverted in the commit https://github.com/adventuregamestudio/ags/commit/cca997fe83ec5f7014677a69095a7c9ec1494cd9 , only for the hardware accelerated renderer.
For some reason this doesn't break any small test game I made, but it does break some animations in a bigger game.
Edit: ok, I think I understand why it doesn't break my test games, the delay has to be 1 frame.
> Engine: draw fix, true means texture don't change

- Common/libsrc/aastr-0.1.1/aarot.c
- Common/libsrc/aastr-0.1.1/aastr.c
- Editor/AGS.Native/cstretch.cpp
- libsrc/allegro/include/allegro/inline/draw.inl
- libsrc/allegro/include/allegro/inline/gfx.inl
- libsrc/allegro/src/blit.c
- libsrc/allegro/src/c/cblit.h
- libsrc/allegro/src/c/cgfx.h
- libsrc/allegro/src/c/cspr.h
- libsrc/allegro/src/c/cstretch.c
- libsrc/allegro/src/flood.c
- libsrc/allegro/src/rotate.c
- remove bmp_unwrite_line, this was related to the removed bank stuff, so we don't need it anymore
- minor adjustments to cblit so it's a bit more lean, but without logic change
> Allegro cleanup bmp related methods

- Common/CMakeLists.txt
- Common/util/matrix.h
- Engine/CMakeLists.txt
- Engine/ac/draw.cpp
- Engine/gfx/ali3dogl.cpp
- Engine/gfx/ali3dogl.h
- Engine/gfx/gfxdriverbase.cpp
- Engine/gfx/gfxdriverbase.h
- Engine/gfx/graphicsdriver.h
- Engine/platform/windows/gfx/ali3dd3d.cpp
- Engine/platform/windows/gfx/ali3dd3d.h
- Solutions/Common.Lib/Common.Lib.vcxproj
- Solutions/Common.Lib/Common.Lib.vcxproj.filters
Resolves #1708, but also useful while resolving #1838 (which was the main reason to do this now).
1. Use glm in Direct3D renderer as well, to ease sharing the matrix code between OpenGL and Direct3D.
2. Global offset and flip are only set once in the parent sprite batch, instead of applying to every batch on screen.
3. For hw renderers - separate Room Viewport and Room Camera into two nested batches.
4. No longer use sprite batch's `Viewport` field as a source of coordinate translation (also removed extra `Offset` field); use strictly `Transform` field for that. This makes setting up a sprite batch more clear and consistent. `Viewport` will only define a clipping rectangle. Nested batch's `Viewport` will be considered relative to the parent batch, and will be transformed using parent …
> Make sprite batch parameters more consistent

- Common/ac/spritefile.cpp
- Engine/gfx/gfxdriverbase.cpp
Loop Unswitching only in functions that are hotspot signaled by running a profiler in a high definition game (1920x1080) with lots of frames. Used both Very Sleepy and AMDuProf as profilers.
I didn't find any other place where this was relevant in the code, since other places aren't ran nearly as often as these functions can be ran.
Here's a small benchmark, it improves 4-5fps in my computer.
[ClearBenchmark.zip](https://github.com/adventuregamestudio/ags/files/10269431/ClearBenchmark.zip)
> unswitch loops in functions that are hotspot in high definition games

- .gitignore
- Editor/AGS.Editor/Debugger/NamedPipesEngineCommunication.cs
- Engine/debug/debug.cpp
- Engine/debug/debugger.h
- Engine/main/game_run.cpp
- Engine/main/game_start.cpp
- Engine/main/quit.cpp
**Note:** since the engine part of that PR that actually adds the logging functionality requires a `--log-debugger=` flag, I think we could actually add the Engine [commit](https://github.com/adventuregamestudio/ags/pull/1518/commits/b58b186b05457787e45aafd415b264b1675b0a96) that adds it.
I am not 100% sure, but I think it may be possible to figure out an Editor plugin if the engine parts are taken care. It would require some different set of changes in the Editor to make this possible though.
---
Just picking up some of the debugger related commits from the Editor Log PR. I added a new one to tidy things a bit.
> Debugger related commits from Editor Log PR

- Common/util/matrix.h
- Engine/ac/draw.cpp
- Engine/ac/draw.h
- Engine/gfx/ali3dogl.cpp
- Engine/gfx/ali3dogl.h
- Engine/gfx/ali3dsw.cpp
- Engine/gfx/ali3dsw.h
- Engine/gfx/gfxdriverbase.cpp
- Engine/gfx/gfxdriverbase.h
- Engine/gfx/graphicsdriver.h
- Engine/main/engine.cpp
- Engine/main/engine_setup.cpp
- Engine/main/graphics_mode.cpp
- Engine/platform/windows/gfx/ali3dd3d.cpp
- Engine/platform/windows/gfx/ali3dd3d.h
Resolves #1838 and will potentially help #1837 after merged/ported to ags4.
After implementing rendering GUI controls as separate textures (see #988 and #1393 for details), it turned out that the implementation has a serious mistake: any additional visual effect applied to a whole GUI, such as Transparency, would apply incorrectly, as controls would blend with GUI background using same effect, producing different visual result.
I guess there may be different approaches for resolving this problem. But we also assume that in the future GUI may be assigned more various properties, such as rotation (already exists in ags4), which makes it more difficult to clip controls to GUI borders on screen, or custom shaders, which would be expected to be applied to GUI & controls in whole, while each …
> Render GUIs on a texture, then render that texture on screen

- CMake/Emscripten/FindSDL2.cmake
- CMakeLists.txt
- Emscripten/install_dependencies.sh
- Emscripten/launcher_index.html
- ci/emscripten/Dockerfile
- SDL2 in Emscripten was 2.0.20, this version of Emscripten comes with 2.24.2
- additional minor fixes in the launcher html (non-related, but felt like a good opportunity to do it, they don't functionally alter anything)
- in the dockerfile, an additional non-related TZ data fix is applied, to prevent possible hanging when the docker image is updating packages 
I had upgraded the SDL2 to 2.24.2 in Emscripten https://github.com/emscripten-core/emscripten/pull/18026, forgot to upgrade here too.
> Emscripten: upgrade to 3.1.28

- .cirrus.yml
- Apple Silicon macOS images have different permissions in usr/local
- Newer ninja binaries are built as Universal macOS apps
> Ci: macOS Intel images are obsoleted from CirrusCi

- .cirrus.yml
- ci/linux/Dockerfile
This restores the previous behaviour for library search paths.
I think the problem is the change in the build environment rather than any change in the engine source code, but build artifacts from this PR need to be tested against everything that is known to be failing to be sure.
When testing, be sure to use the binaries that are packaged to go with the Editor rather than the regular make or cmake builds.
P.S. This just restores the previous behaviour. Whether the previous behaviour and directory layout for game files was a good idea is probably another discussion.
Fixes #1864
> CI: Prefer RPATH over RUNPATH for Linux binaries

- Engine/gui/cscidialog.cpp
- Engine/gui/cscidialog.h
- Engine/gui/guidialog.cpp
- Engine/gui/mylabel.cpp
- Engine/gui/mylabel.h
- Engine/gui/mylistbox.cpp
- Engine/gui/mylistbox.h
- Engine/gui/mypushbutton.cpp
- Engine/gui/mypushbutton.h
- Engine/gui/mytextbox.cpp
- Engine/gui/mytextbox.h
- Engine/gui/newcontrol.h
fix #1875 
It's a good idea to let the CI build on all platforms. I tested and [`<cstdint>`](https://en.cppreference.com/w/cpp/header/cstdint) was not needed for [`intptr_t`](https://en.cppreference.com/w/cpp/types/integer) in any platform locally, apparently the compilers somehow already include.
> Engine: csci gui messages uses intptr_t insted of long

- Engine/main/game_file.cpp
After the Clifftop mod commit (https://github.com/adventuregamestudio/ags/commit/6a238e9cb4acda222898dd4b597cf20581b401f6) in `Engine/main/game_file.cpp`, the error returned from `ReadGameData` is not actioned upon, and it's later rewritten by the error from `UpdateGameData`.
This just adds an error check, where it returns it in case of error.
> Engine: fail when reading game data should return error

- Editor/AGS.Native/ScriptCompiler.cpp
- Editor/AGS.Native/agsicons.cpp
Just access resources to ensure 64-bit/32-bit compatibility
---
This would allow a current editor to use a custom experimental 64-bit build of acwin.exe, for testing purposes, so it can still rewrite the game icon (otherwise it produces an error at this step, so it's not possible to build the game)
> Editor: do not load exe in agsnative

- Common/libsrc/alfont-2.0.9/alfont.c
In Alfont, `s_pointer` holds a copy of the string we are drawing, but in case it's completely clipped, we return. But in this case, we don't free `s_pointer`, which is incorrect. You can see that later on, incase the string is not completely clipped, the `s_pointer` is freed.
Because the templates use wfn fonts, made a small game that draws text with a truetype font that gets clipped. You can run it using the build from master and see the RAM usage grow in realtime! :)
[TestClip.zip](https://github.com/adventuregamestudio/ags/files/10369913/TestClip.zip)
> Alfont: fix leak, release before freeing last reference

- CMAKE.md
fix #1827 
If someone needs parallel building they can look into CMake docs, there's no need to go beyond the minimum necessary in the instructions here. 
Presumably, nowadays most people will use CMake through a front end/IDE that already takes care of these things (CLion/VS/VSCode...).
> CMake: remove --parallel from instructions

- Editor/AGS.Editor/Utils/AndroidUtilities.cs
Make sure AGS Editor finds the sdkmanager when installed using the Command Line tools from Android Studio Dolphin and later.
Also it searches first in the new directories and later in the old directories. Starting in Android Studio Electric Eel, the matching SDK Manager also uses a different Java version, so if you upgrade to Electric Eel and tools and tries to run the SDK Manager from the old directory it will fail because Java version has changed.
> Editor: android build finds sdkmanager in alternative directories

- Compiler/script2/cc_compiledscript.cpp
- Compiler/script2/cc_compiledscript.h
- Compiler/script2/cs_parser.cpp
- Compiler/script2/cs_parser.h
- Compiler/test2/cc_bytecode_test_0.cpp
- Compiler/test2/cc_bytecode_test_1.cpp
- Compiler/test2/cc_parser_test_0.cpp
- Compiler/test2/cc_parser_test_1.cpp
- Compiler/test2/cc_parser_test_lib.cpp
- Compiler/test2/cc_scanner_test.cpp
This addresses #1832 and #1836.
This replaces #1835.
Bug 1: When using compile-time compilations, the compiler emitted some `Linenum` pseudo-directives but cut them out afterwards so that the generated code didn't know about the affected lines any longer. This meant that breakpoints couldn't be set on such lines. (`Linenum` directives link specific points of generated code to specific source lines.)
This bug had been able to creep in because the Bytecode tests of the compiler ran without emitting `Linenum` directives. (The Bytecode tests make the compiler emit actual code for small AGS snippets and check whether the code is as expected.) So in particular, the Bytecode tests did not check whether these directives were correctly set. In my opinion, I had made a bad design decision when I …
> New compiler: Don't omit LINENUM directive with CTC; improved Googletests

- Engine/main/engine.cpp
- Engine/media/audio/audio_core.cpp
This fixes compilation errors with GCC 13 on Fedora rawhide (development branch):
```
media/audio/audio_core.cpp: In function 'void audio_core_init()':
media/audio/audio_core.cpp:244:42: error: 'runtime_error' is not a member of 'std'
244 |     if (!g_acore.alcDevice) { throw std::runtime_error("AudioCore: error opening device"); }
|                                          ^~~~~~~~~~~~~
media/audio/audio_core.cpp:29:1: note: 'std::runtime_error' is defined in header '<stdexcept>'; did you forget to '#include <stdexcept>'?
28 | #include "util/memory_compat.h"
+++ |+#include <stdexcept>
29 |
media/audio/audio_core.cpp:247:43: error: 'runtime_error' is not a member of 'std'
247 |     if (!g_acore.alcContext) { throw std::runtime_error("AudioCore: error creating context"); }
| …
```
> add explicit includes for <stdexcept>

- Common/font/fonts.cpp
> Engine: font width of empty text should be zero

- Android/agsplayer/app/build.gradle
- Android/agsplayer/app/src/main/AndroidManifest.xml
- Android/agsplayer/app/src/main/java/uk/co/adventuregamestudio/agsplayer/AGSPlayerRuntimeActivity.java
- Android/agsplayer/app/src/main/java/uk/co/adventuregamestudio/agsplayer/FileUtil.kt
- Android/agsplayer/app/src/main/java/uk/co/adventuregamestudio/agsplayer/GameListRecyclerViewAdapter.kt
- Android/agsplayer/app/src/main/java/uk/co/adventuregamestudio/agsplayer/MainActivity.kt
- Android/agsplayer/app/src/main/res/layout/recyclerview_row.xml
- Android/agsplayer/app/src/main/res/values/strings.xml
add a button with three dots on each game entry in the ags player to invoke the context menu of the item.
following this [comment](https://github.com/adventuregamestudio/ags/issues/1871#issuecomment-1405353587)
> there's no visual indication that you may open them for a particular game (no button/icon besides the game title).
> Android: AGS Player add per game button options

- Editor/AGS.Editor/GUI/GUIController.cs
- Editor/AGS.Editor/GUI/StartNewGameWizardPage.Designer.cs
- Editor/AGS.Editor/GUI/StartNewGameWizardPage.cs
- Editor/AGS.Editor/GUI/StartNewGameWizardPage.resx
- Editor/AGS.Editor/GUI/WizardDialog.Designer.cs
- Editor/AGS.Editor/GUI/WizardDialog.cs
- Editor/AGS.Editor/GUI/WizardDialog.resx
- Editor/AGS.Native/NativeMethods.cpp
- Editor/AGS.Native/agsnative.cpp
- Editor/AGS.Types/EditorFeatures/BaseTemplate.cs
- Editor/AGS.Types/EditorFeatures/GameTemplate.cs
- Editor/AGS.Types/EditorFeatures/RoomTemplate.cs
Resolves #564.
This adds a description field to the template selection page in the New Game wizard. The template descriptions are now preloaded, along with the icons. This lets user read about the template prior to creating a game.
The pr is made against ags4 branch for now. It's simple enough, thus if wanted, this may be backported to some 3.6.* update later.
Example of looks:
Known issues:
1. There's something strange about how the linebreaks are managed by the text box. Double linebreaks seem to work fine (see the screenshot), but single linebreaks do not cause the line wrap for some reason... This might be a .NET bug, or something that I'm missing in text box setup.
2. I had to make the Wizard dialog to auto-resize based on the "minimal size" property of all the pages. This caused the …
> 4.0: Add description field to the Game Template selection page

- Android/library/runtime/src/main/java/uk/co/adventuregamestudio/runtime/AgsSettingsFragment.java
- Android/library/runtime/src/main/java/uk/co/adventuregamestudio/runtime/PreferencesActivity.java
- Engine/platform/android/acpland.cpp
fix #1871
The fix is what I explained in the issue. I added some comments to clarify what is going on.
- Removed chdir when reading the config, which was confusing. 
- There was also a misleading chdir [here](https://github.com/adventuregamestudio/ags/compare/master...ericoporto:ags:fix-android-ags-player-global-settings#diff-52a453b9246fe11573220e59a7f04e2498bd6cbd37802cf98494faf83dd1d61bL357-L358), because the passed variable was always null it did nothing.
> Fix android ags player global settings

- Editor/AGS.Editor/Panes/ScintillaWrapper.cs
fix #1912 
MarkerNext when reaching the last breakpoint keeps returning the same value, which hangs ags in the loop forever until breakpointLines is big enough to crash for lack of memory.
https://github.com/jacobslusser/ScintillaNET/wiki/Markers-and-Bookmarking-Lines
> Editor: fix breakpoint on last line hangs editor

- Editor/AGS.Editor/GUI/SpriteExportDialog.Designer.cs
- Editor/AGS.Editor/GUI/SpriteExportDialog.cs
- Editor/AGS.Editor/Panes/SpriteSelector.cs
- Editor/AGS.Editor/Utils/SpriteTools.cs
This adds an option to reset the tile settings for a sprite during bulk export, which fixes the case where the exported sprite is later reloaded from the exported source file (i.e. what was imported from a spritesheet is not exported as a spritesheet and so cannot be reloaded as a spritesheet). I did consider defaulting this checked in the GUI but decided against it because the original spritesheet import data (tile offsets) would be deleted. It seems safer to default to keeping data rather than deleting it. It could also be [ab]used to bulk reset all tile settings independently of the souce path rewrite.
I also noticed that pressing the tab key wasn't moving between the GUI controls in an expected order so I've reset the order to run from to to bottom, and from left to right.
> Editor: Add option to reset tile settings on sprite export

- Editor/AGS.Editor/Panes/SpriteSelector.cs
This restores some functionaility that was lost by the removal of "Replace sprite using last sprite" and makes the file tracking more consistent.
Note: There appears to be a separate problem of no error handling when the "previous" files no longer exist, but this was a pre-existing condition which can be looked at separately.
Closes #1911
> Editor: Add sprite selector option "Replace sprite using previous files..."

- Editor/AGS.Editor/Utils/SpriteTools.cs
Catch exceptions on the sprite import filestream.
I couldn't see an obvious place to hook some kind of dynamic check on the "previous" file references (which are the most likely cause of the failure) but this is enough to stop the crash.
Fixes #1915
> Editor: Fix crash for sprite import with bad filestream

- Compiler/script/cs_compiler.cpp
- Compiler/script/cs_compiler.h
- Compiler/script2/cs_compiler.cpp
- Compiler/script2/cs_compiler.h
- Editor/AGS.Editor/AGSEditor.cs
- Editor/AGS.Editor/NativeProxy.cs
- Editor/AGS.Native/NativeMethods.h
- Editor/AGS.Native/ScriptCompiler.cpp
Wanted to do this long ago...
This lets compilers to return a list of extension names (arbitrary string IDs). These extensions are taken by the Editor and turned into preprocessor macros, in a form of `SCRIPT_EXT_<NAME>`.
The primary purpose is being able to write scripts meant for both new and old compilers, where some code may only work with the new compiler. This may be useful for module writers, but also if you make a test game and need to switch compilers during the test.
For starters, the new compiler declares one generic "AGS4" extension. But it's possible to add one extension name per new individual syntax feature, if necessary, later.
Example of script:
```
#ifdef SCRIPT_EXT_AGS4
Display("AGS 4 compiler extensions are ENABLED");
#endif
#ifndef SCRIPT_EXT_AGS4
Display("AGS 4 …
```
> 4.0: declare script compiler extension strings as preprocessor macros

- CMakeLists.txt
- Common/util/filestream.cpp
- Common/util/filestream.h
- Emscripten/launcher_index.html
- Emscripten/post.js
- Engine/CMakeLists.txt
- Engine/ac/timer.cpp
- Engine/platform/emscripten/acpemscripten.cpp
- AGS Script errors and messages use Alert boxes on browsers too
- A new directory is used by the engine, `/home/web_user/saved_games`, files saved there are persisted (config and save slots)
- A new modal ui is added to be able to clear these files
- We leverage this modal ui to add an extra button for toggling fullscreen. Exiting fullscreen is accomplished by using Esc key (in mobile browsers, default exiting of fullscreen using back gesture also works). Alt+Enter still works the same.
I already updated here https://ericoporto.github.io/agsjs
> Add emscripten improvements

- CMakeLists.txt
- Emscripten/README.md
- ci/emscripten/Dockerfile
I didn't notice before, but with the current version of Emscripten we are using, the Freetype source files we have in AGS repository builds without problems!
I still have this bottom of the font being cut off problem with Kathy Rain running in the web port, that I am not sure yet what that would be.
I also updated the build in agsjs to use this version: https://ericoporto.github.io/agsjs/ (just remember to make sure to clear the cache when testing)
> Emscripten: use same Freetype from AGS internal sources

- CMakeLists.txt
- Emscripten/launcher_index.html
- Engine/platform/emscripten/acpemscripten.cpp
- fix reported bug where the cog wheel ⚙️ button disappeared under certain conditions
- fix to make sure focus is set on the canvas when clicking it, even in an iframe (SDL has a prevent default that blocked this defaul behavior on browser)
- lower the font size a bit
- fix bug where iframe size is not set correctly when returning from fullscreen, there are some hacks there but I tried to make them minimal and non-brittle, we can perhaps rollback on a lot of it once this is fixed upstream
pushed these changes:
https://ericoporto.github.io/agsjs/
https://eri0o.itch.io/agsjs-test  (p: agstest)
> Emscripten some fixes

- Editor/AGS.Native/agsnative.cpp
When I was building the Editor for 64-bit, build errors appeared in VS on these lines. Looking into wikipedia I found this
> z | For integer types, causes printf to expect a size_t-sized integer argument.
> -- | --
</body>
</html>
https://en.wikipedia.org/wiki/Printf_format_string
The fix is still compatible with win32.
> Editor: Native use %zd compatible with size_t

- Engine/plugin/global_plugin.cpp
I know it's a bit soon, but the idea of this plugin is to be able to remove it when no external url loading is desired. Unfortunately the way for this is stubs.
My hope is to switch out people from `agsshell` as I hope to reduce surface of problems through this url specific plugin. I know this is a bit soon, but I have got an increased number of asks about agsshell in the last days.
> Engine: add plugin stub for agsappopenurl

- Common/util/geometry.h
- Editor/AGS.Editor/AGSEditor.cs
- Engine/ac/gamesetup.cpp
- Engine/ac/gamesetup.h
- Engine/ac/sys_events.cpp
- Engine/ac/sys_events.h
- Engine/device/mousew32.cpp
- Engine/device/mousew32.h
- Engine/main/config.cpp
- Engine/main/engine_setup.cpp
- Engine/platform/base/mobile_base.cpp
- OPTIONS.md
Resolves #1930.
Support interpreting mouse motion events as absolute or relative, individually per "mouse" device (real or emulated). The inner engine code that assigns a game cursor position no longer relies on config setting, but instead relies on the accumulated mouse position, provided by the event handling unit. Relative motion (movement delta) is currently unused but kept in the code, as it may become useful later for certain purposes.
Event handling assumes that the received mouse position and deltas are generated with all the settings already applied by the sending device (absolute/relative mode, speed, and so forth).
Touch2mouse code is adjusted to have its own absolute/relative option, and calculate new position in the relative mode correspondingly.
Added a separate config …
> 3.6.0: separate absolute/relative switch for Touch-to-mouse emulation

- Engine/platform/util/libc.c
This is a weird issue; there were number of libc function placeholders added to the engine, mainly for Android, as its older versions of NDK were missing these. Some were not real implementations, but emulations; e.g. mbstowcs() and wcstombs() were simply copying the strings char by char without any actual conversion.
For unknown reasons (oversight?),  these functions were also included into Linux build, and later - OSX. This was many years ago (see 67447accbdcfb73af0b2c44c9cb9e6bcace965e0).
Now we do have a limited use of wcstombs() in the engine, and these placeholders prevent from using proper functions from libc.
This PR does two things:
* Fixed the mbstowcs() and wcstombs() placeholders to ensure they properly terminate output string, as per specs.
* Disable them for now. If they …
> Fix incorrectly linked mbstowcs() and wcstombs() placeholders

- Common/core/platform.h
- Engine/gfx/ogl_headers.h
Minor adjustment in OGL headers
- simplify `Engine/gfx/ogl_headers.h`
- mark iOS as OpenGL ES2 platform.
> simplify ogl headers

- Common/font/ttffontrenderer.cpp
- Engine/ac/global_audio.cpp
- libsrc/allegro/src/win/gdi.c
- in `Common/font/ttffontrenderer.cpp`, the params of font renderer are checked for null, but also used without checking for null, I moved this check to the top.
- in `libsrc/allegro/src/win/gdi.c` hdc is used after being released, this is only not a problem because the method that uses it is not used anywhere (I thought about deleting all, but it could be useful for adding an image in Winsetup one day as a decoration)
- in `Engine/ac/global_audio.cpp`, there is a logical mistake
> Small fixes

- Engine/ac/draw.cpp
- Engine/ac/system.cpp
- Engine/ac/system.h
- Engine/gfx/ali3dogl.cpp
- Engine/gfx/ali3dogl.h
- Engine/gfx/ali3dsw.cpp
- Engine/gfx/ali3dsw.h
- Engine/gfx/gfxdriverbase.cpp
- Engine/gfx/gfxdriverbase.h
- Engine/gfx/graphicsdriver.h
- Engine/main/graphics_mode.cpp
- Engine/platform/windows/gfx/ali3dd3d.cpp
- Engine/platform/windows/gfx/ali3dd3d.h
This is a reaction to #1949, but I cannot tell whether this is enough to fix it at the moment.
This does two things:
1. Small refactor that ensures that VSync is not necessarily reset when using a gfxdriver's interface if it's already set to the given value. This is to reduce code duplication and unify behavior a little.
2. Gfx driver will try to detect when vsync is not supported, and also remember when changing vsync at runtime fails. In this case it won't try to set it again, until the display mode changes.
> 3.6.0: improve how vsync is changed at runtime

- Engine/ac/system.cpp
on invalid index, the index is not actually reported because it's missing in the right side of the string format.
> Engine: System_GetAudioChannels missing index in error message

- Engine/platform/windows/win_ex_handling.cpp
- size_t requires %zu in format (see #1934)
- on 64-bit , ExceptionAddress, an intptr_t requires a different format string to be readable
- I looked the PRIxPTR from inttypes.h, but I think this custom format prints nicely as a counterpart of 0x%08X
- we use 16 zeroes as the fixed length, because of 64 bits (from 8 for 32-bit variant) ((inttypes.h has nothing for this)
- I64 is windows for unsigned 64-bit int (I think I could also use `ll` here)
- X is for the hexadecimal, same as the 32-bit variant
> Fix Windows Exception handling in 64-bit builds

- Engine/ac/sys_events.cpp
fix #1954
FingerContainer is probably not a good name, and I guess it could be more efficient, but I don't expect the number of fingers to be more than one digit ever, so I think this should work fast enough.
> Engine: fix touch events not working in iOS Safari

- Engine/ac/dialog.cpp
- Engine/ac/display.cpp
- Engine/ac/draw.cpp
- Engine/ac/invwindow.cpp
- Engine/gui/guidialog.cpp
- Engine/gui/mylistbox.cpp
- Engine/gui/mypushbutton.cpp
- Engine/gui/newcontrol.cpp
- Engine/main/game_run.cpp
- Engine/main/game_run.h
- Engine/plugin/agsplugin.cpp
The problem at hand is that when using touch-to-mouse emulation, the cursor position cannot be tracked (unlike with real mouse) . It's only updated upon a touch. Unfortunately, the gui reaction to cursor in AGS is a bit overcomplicated, where it must remember the last control the mouse was on in order to trigger an interaction correctly upon a mouse down/up event. At the same time this "mouse-over-control" state is updated too late (for unclear reasons), after the mouse button events were already handled. Because of that, following problems may occur:
* it takes 2 touches to press a button (or interact with some other controls): first sets a "focus" on a control, another triggers a push.
* if the cursor has been over a button, a touch on another control or on an empty place over same gui …
> Fix touch controls requiring two touches to activate a gui control

- .cirrus.yml
- Editor/AGS.Native/NativeDLL.vcxproj
- Solutions/Common.Lib/Common.Lib.vcxproj
- Solutions/Compiler.Lib/Compiler.Lib.Test.vcxproj
- Solutions/Compiler.Lib/Compiler.Lib.vcxproj
- Solutions/Engine.App/Engine.App.vcxproj
- Solutions/Engine.sln
- Solutions/Tests.App/Common.Lib.Test.vcxproj
- Solutions/Tests.App/Engine.App.Test.vcxproj
- Solutions/Tools.App/afg2dlgasc.vcxproj
- Solutions/Tools.App/agf2autoash.vcxproj
- Solutions/Tools.App/agf2glvar.vcxproj
- Solutions/Tools.App/agspak.vcxproj
- Solutions/Tools.App/agsunpak.vcxproj
- Solutions/Tools.App/crm2ash.vcxproj
- Solutions/Tools.App/crmpak.vcxproj
- Solutions/Tools.App/trac.vcxproj
- Solutions/libogg.props
- Solutions/libtheora.props
- Solutions/libvorbis.props
- Solutions/sdl2.props
- ci/windows/Dockerfile
**context:** when testing a high definition, demanding, game, it may be the case that the memory usage may grow enough to cause OoM errors in some specific hard to reproduce scenarios, with 32-bit Windows app (limited to <2GB RAM). It may be wise to explore building Windows engine for 64-bit.
**what this pr does:** allows using VS to build Windows engine to 64-bit - currently other desktop ports and mobile ports of the engine are already 64-bit capable.
---
**Warning:** _this changes impact some things in the VS Workflow, please read below_
This change builds a new [**WinDevDependenciesVS.zip**](https://github.com/adventuregamestudio/ags/files/11069235/WinDevDependenciesVS.zip), which include pre-builts of 64-bit of SDL_sound, Xiph libraries and SDL2!
The paths for the new ones in your …
> Allow Windows 64-bit Engine Builds using Visual Studio Solutions

- Engine/ac/system.cpp
- Engine/media/audio/audio.cpp
A user reported to us a crash in the AGS engine in ScummVM, and I have verified that it happens in this standalone ags as well.
In Unavowed, at the Staten Island stage, the game crashes with the following message:
`Error: System.AudioChannels: invalid sound channel index 8, supported 0 - 8`
(the error message is actually incorrect and should read `supported 0 - 7`, and I fixed that as well)
And it is indeed trying to use channel 8, which is `>= game.numGameChannels` (which is also 8). I suspect this is caused by 86564e983572b4ffb3cd12b00c116ae91c6fcbe4. In any case allowing using the crossfade channel  in `System_GetAudioChannels` does fix the issue and the game can continue. I am proposing the fix here first (before committing to scummvm) to hear from AGS experts in case there is a …
> Fix a crash in unavowed when trying to use crossfade channel

- Common/util/alignedstream.cpp
- Common/util/alignedstream.h
- Common/util/datastream.cpp
- Common/util/datastream.h
- Common/util/geometry.h
- Common/util/iagsstream.h
- Engine/ac/character.cpp
- Engine/ac/draw.cpp
- Engine/ac/gamestate.h
- Engine/ac/movelist.cpp
- Engine/ac/movelist.h
- Engine/ac/room.cpp
- Engine/ac/roomobject.cpp
- Engine/ac/route_finder.cpp
- Engine/ac/route_finder.h
- Engine/ac/route_finder_impl.cpp
- Engine/ac/route_finder_impl.h
- Engine/ac/route_finder_impl_legacy.cpp
- Engine/ac/route_finder_impl_legacy.h
- Engine/game/savegame_components.cpp
- Engine/main/update.cpp
- Engine/main/update.h
- Engine/plugin/agsplugin.cpp
I wanted to make this part more readable.
Not sure to what extent I should drag this PR but I really want to rename some stuff because last time I looked at this code I had a bad time.
Also, those `fixed` variables are some legacy from DOS era, aren't they? I could convert them to floats maybe.
Things to note:
- there are `memcpy`s in route_finder_impl.cpp and route_finder_impl_legacy.cpp
- `class Navigation` is still packing shorts into int, will look at it later
- I found a comment about implementing the movelist as a `vector`, could be the next step
> Engine: rewrote MoveList to avoid using packed shorts for coords

- Common/util/file.cpp
- Common/util/file.h
- Common/util/stdio_compat.c
- Common/util/stdio_compat.h
- Engine/ac/game.cpp
Been looking for remaining unnecessary `long` and `malloc` in the base engine code, and decided to make a FileCopy function to replace an explicit data read/write in one case.
The function is added to File namespace and stdio_compat.c in compliance with existing similar utils.
Tested this on Win and Linux, but making this pr primarily to make sure the posix variant compiles everywhere.
> Add File::FileCopy function and replace one instance of manual buffer copying

- Editor/AGS.Editor/Components/AudioComponent.cs
- Editor/AGS.Editor/Panes/AudioEditor.cs
- Editor/AGS.Types/AudioClip.cs
Resolves #566
This lets users to see Length on the clips' property grid.
The Length is taken from the previewer currently, so relies on its work. If previewer failed, will be assigned 0.
This field is not serialized, and is only updated when the preview pane opens (there's no other way to see clip's properties at the moment anyway).
> Editor: added readonly Length property to AudioClip

- Editor/AGS.Editor/Resources/agsdefns.sh
- Editor/AGS.Types/Room.cs
- Engine/ac/event.cpp
- Engine/ac/event.h
- Engine/ac/room.cpp
- Engine/ac/screen.cpp
- Engine/script/script.cpp
Resolves #1971
1. Adds Room event "Leave room after fade-out", with default function name `room_Unload`, for consistency with `room_Load`.
2. Adds new global event (for `on_event`): `eEventLeaveRoomAfterFadeout`.
The names are chosen for consistency with existing ones, but may be adjusted to something more elegant later perhaps.
Tested with the following room script:
```
function room_Load()
{
System.Log(eLogInfo, "room_Load, %d", player.Room);
}
function room_AfterFadeIn()
{
System.Log(eLogInfo, "room_AfterFadeIn, %d", player.Room);
}
function room_Leave()
{
System.Log(eLogInfo, "room_Leave, %d", player.Room);
}
function room_Unload()
{
System.Log(eLogInfo, "room_Unload, %d", player.Room);
}
```
And in global script:
```
function on_event(int evt, int data)
{
System.Log(eLogInfo, …
```
> AGS 4: implemented "Leave room after fade-out" callback, and corresponding global event

- Common/script/cc_internal.h
- Engine/script/cc_instance.cpp
- Engine/script/cc_instance.h
- Engine/script/runtimescriptvalue.cpp
- Engine/script/runtimescriptvalue.h
Resolves #843 and #1987.
Contains a number of adjustments to the script interpreter function (ccInstance::Run), increases potential game fps and reduces CPU load for "script heavy" games.
Adds `DEBUG_CC_EXEC` compilation flag, and hides most error checks within the opcode implementations under this flag.
DEBUG_CC_EXEC is enabled if AGS_PLATFORM_DEBUG is enabled, but we may also make it completely separate later if wanted.
The changes were tested against two games with complex scripts in the "infinite fps" mode (where engine runs game loops as fast as it can):
1. First person space sim prototype: https://github.com/ivan-mogilko/ags-wcproto
2. Car racing arcade game: https://github.com/ivan-mogilko/ags-lastfurious
First has generally very slow script; showed a fps rise from ~64-65 to ~75 in …
> Performance fixes for script interpreter

- Editor/AGS.Editor/app.config
- Editor/AGS.Editor/app.manifest
Turns dpi-aware on, this makes ags not blurred in Windows 10 by default. I couldn't find any side effect, so I ask people to test this. The text becomes sharp and it's much nicer to code like this.
With dpi-aware on
Without dpi-aware on (commented)
> Editor: turn dpi aware on

- Common/font/wfnfont.cpp
- Common/font/wfnfont.h
- Common/font/wfnfontrenderer.cpp
Resolves #2002.
Added support for unicode texts in utf-8 format in WFNRenderer class.
---
In regards to testing...
Current WFN font format does not have a limitation on character indices, but has a limitation on the total size of the glyph data: 64k - (size of header). This is because the TOC has only 2 bytes per glyph offset, so higher address cannot be written.
That still may be enough to write several alphabets in, as the glyphs themselves do not have to be sequential: you can write standard ascii glyphs with codes 1-127 and then, say, Greek letters corresponding to codes 884 - 1023. This will make a large offset table (because it has to have entries from 0 to 1023), but only 128 + 141 = 269 glyphs. If each glyph will have a size of, say 9x14 pixels, with the WFN format that would …
> WFN Renderer supports utf-8 texts

- Common/libsrc/alfont-2.0.9/alfont.c
Fixes #1438
This fixes cases when the wanted glyph is not available in the Font and its index is higher than the max glyph number. Potentially fixes incorrect text render, and in the worst case - random memory corruptions.
Frankly, I have no idea how this was supposed to work, but it was like this in the imported alfont 2.0.9 sources, apparently.
For the reference, it *does not seem* like this problem was affecting #1909, as the game does not trigger the safety checks I've added in this commit.
> AlFont: fix accessing cached glyphs beyond the array range

- Editor/AGS.Editor/Resources/agsdefns.sh
- Engine/ac/audioclip.cpp
- Engine/ac/character.cpp
- Engine/ac/dialog.cpp
- Engine/ac/gui.cpp
- Engine/ac/guicontrol.cpp
- Engine/ac/hotspot.cpp
- Engine/ac/inventoryitem.cpp
- Engine/ac/object.cpp
- Engine/script/script_runtime.cpp
- Engine/script/script_runtime.h
This implements readonly ScriptName property and a static GetByName() method for all the object types that have script names. The method looks up for the object of corresponding type with the given script name, and returns its pointer, or null if such object is not found.
NOTE: passing other type's script name will also return null, for example calling Character.GetByName() with a room object's name.
`scriptName` argument is case-sensitive, obviously.
```
static AudioClip* AudioClip.GetByName(const string scriptName);
static Character* Character.GetByName(const string scriptName);
static Dialog* Dialog.GetByName(const string scriptName);
static GUIControl* GUIControl.GetByName(const string scriptName);
static GUI* GUI.GetByName(const string scriptName);
static Hotspot* …
```
> Script API: implemented ScriptName and Type.GetByName() for all applicable types.

- Editor/AGS.Editor/Resources/agsdefns.sh
- Engine/ac/event.h
- Engine/ac/game.cpp
Resolves #1295
By a user's request, this adds a `eEventSaveGame` event which is run after a game was saved.
Similar to other events, this is scheduled to run after the current script callback is completed.
> Script API: implement eEventGameSaved

- Engine/main/main.cpp
- Engine/plugin/agsplugin.cpp
- Engine/util/library.h
- Engine/util/library_dummy.h
- Engine/util/library_posix.h
- Engine/util/library_windows.h
Fix #1707
Modified Library class to accept an optional list of lookup dirs when loading a shared lib.
This is used to find game plugins when running the engine from outside the game dir, passing game path as an argument.
@ericoporto I removed a piece of code from PosixLibrary meant for Android, that looked up in `<android_app_directory> /lib`. This seem to be a very old code, and I don't know if it's still necessary with the current port? If it is, I will find a different way of passing this path.
> Explicitly search for plugins in a game's data dir 

- Compiler/script2/cs_parser.cpp
- Compiler/test2/cc_parser_test_1.cpp
This addresses #2019.
This PR makes the compiler throw an error message for expressions that use `++` or `--` as binary operators. These operators can only be used as unary-prefix or unary-postfix operators.
Typical code:
```
function game_start() 
{
int a = 10;
int b = 5;
int c = a ++ b;  \\ ← Compiler will balk here
}
```
> New Compiler: Fix bug: '++' and '--' can't be binary op

- Engine/ac/overlay.cpp
Whenever we access an Overlay, we iterate through all overlays until we find the one with the corresponding ID. This has been this way since the origins of AGS, as you can see in [in ac_overlay.cpp in the initial commit](https://github.com/adventuregamestudio/ags/blob/bb1b708965a35da0853878ac4b670234ddeb5b17/Engine/acmain/ac_overlay.cpp).
Overlays touch a lot of things and I am sure there is some smarter way to redo things so we can just access directly what we mean when using the Script Overlays. Still, a minor easy to do optimization is to simply remember the last result and use it, if the result has changed, well then look for it again. This improves FPS in my example game below when running in infinite fps mode (I go from 66fps to 82fps in the Oasis area) and can also reduce hiccups …
> Engine: remember overlay index and try it before looking again

- Editor/AGS.Editor/Panes/SpriteSelector.cs
- Editor/AGS.Editor/Tasks.cs
- Editor/AGS.Editor/Utils/SpriteTools.cs
- Editor/AGS.Types/Interfaces/ISpriteFolder.cs
- Editor/AGS.Types/SpriteFolder.cs
Resolves #2033 
* Export options are passed in a struct ExportSpritesOptions, to save number of function arguments (also in case it will be expanded further)
* Implement a Task ExportSprites which uses BusyDialog for the threaded work.
* ExportSprites uses IWorkProgress interface to report current state.
* Had to add CountSpritesInAllSubFolders method to ISpriteFolder interface, to avoid redundant work with GetAllSpritesFromAllSubFolders.
This helps greatly when exporting all sprites from a big game.
> Editor: export sprites asynchronously with progress count

- Engine/platform/bsd/acplbsd.cpp
Just forgot to update the header there after renaming!
I noticed because I saw it here:
https://cgit.freebsd.org/ports/commit/?id=05203b94b144224c53d048556a9ba255f2fc20d6
> Engine: FreeBSD fix header include

- Engine/ac/character.cpp
- Engine/ac/display.cpp
- Engine/ac/draw.cpp
- Engine/ac/dynobj/scriptoverlay.cpp
- Engine/ac/game.cpp
- Engine/ac/global_character.cpp
- Engine/ac/global_overlay.cpp
- Engine/ac/overlay.cpp
- Engine/ac/overlay.h
- Engine/ac/room.cpp
- Engine/ac/runtime_defines.h
- Engine/ac/screenoverlay.h
- Engine/game/savegame.cpp
- Engine/game/savegame_components.cpp
- Engine/game/savegame_v321.cpp
- Engine/main/update.cpp
Fixes #2045.
Implemented variant 2, mentioned in the issue ticket.
I might also try variant 1 (hashmap) later to see if that makes things faster or more convenient.
In variant 2, we keep ScreenOverlays in std::vector, but do not erase elements in the middle and invalidate them instead. Record free indexes in a helper stack. When creating a new overlay, first check for the recorded free indexes.
Overlay's type now equals storage index, thus no need to search for overlay of certain type anymore.
This speeds up both creation/deletion of overlays, and their access.
Removed the gap between "fixed" overlay types and custom ones, to save space. If we ever need more special overlays, these could be created as custom and their ids saved in a variable (similar to how background speech works). …
> 3.6.1: improve ScreenOverlays storage performance

- Common/ac/game_version.h
- Common/game/main_game_file.cpp
- Common/gui/guibutton.cpp
- Common/gui/guidefines.h
- Common/gui/guilabel.cpp
- Common/gui/guilabel.h
- Common/gui/guimain.h
- Common/gui/guitextbox.cpp
- Common/gui/guitextbox.h
- Editor/AGS.Editor/AGSEditor.cs
- Editor/AGS.Editor/DataFileWriter.cs
- Editor/AGS.Editor/Tasks.cs
- Editor/AGS.Types/GUIControl.cs
- Editor/AGS.Types/GUIListBox.cs
- Editor/Native/acgui_agsnative.cpp
- Engine/ac/drawingsurface.cpp
- Engine/ac/string.cpp
- Engine/ac/string.h
- Engine/gui/gui_engine.cpp
I do not know the reasons, but historically AGS only reverses messages (incl speech), labels and wrapped drawn strings in RTL mode.
The purpose of this PR is to expand RTL render to other controls and text drawing operations:
Also to decide:
> Extend Right-to-left text render for GUI and non-wrapping DrawString

- CMAKE.md
- debian/README.md
additionally, readjust CMake readme, remove version as it's best to use the latest when possible to reduce issues, and default for Release builds in readme, in case people are building as users.
> CMAKE: Linux readme with added info on CMake

- Common/util/string_utils.h
- Editor/AGS.Editor/DataFileWriter.cs
- Editor/AGS.Native/NativeMethods.cpp
- Editor/AGS.Native/NativeUtils.h
- Editor/AGS.Native/agsnative.cpp
Done for #1226, but is a valid change on its own (i suppose this could be also backported to 3.6.1).
(See [this comment](https://github.com/adventuregamestudio/ags/issues/1226#issuecomment-1522025191) for explanation)
This ensures that special sequences like "\n" are converted to characters '\n', and similar, in properties containing human-readable texts. Normally this is only useful for GUI controls, room messages, and perhaps Custom Properties, but I did it for all of them, for a formal consistency (Character "realname", and so forth).
> Editor: unescape text properties when writing game data

- Common/font/fonts.cpp
- Compiler/script/cc_compiledscript.cpp
- Compiler/script2/cs_scanner.cpp
- Compiler/test2/cc_scanner_test.cpp
This PR removes the ability for the `[` character to be used as a newline.
It also means that it won't be possible to add newlines to GUI Labels until another PR to unescape the escaped "\n" in their Text properties from the Editor (when set from script they will work as usual).
> Removes special cases for [ as a newline character

- Common/util/file.cpp
- Editor/AGS.Editor/Resources/agsdefns.sh
- Engine/ac/file.cpp
- Engine/ac/file.h
- Engine/ac/path_helper.h
- Engine/plugin/agsplugin.cpp
- Engine/plugin/agsplugin.h
Resolves #899
File.ResolvePath resolves a script path into the filesystem path, in exact same way as the engine does it when searching for a file.
(like doing a case-insensitive search on case-sensitive filesystems).
As a bonus, added readonly File.Path property, that returns an opened File's path.
> Script API: implemented File.ResolvePath()

- .gitignore
- Emscripten/README.md
- Emscripten/launcher_index.html
- Engine/main/engine.cpp
- Engine/platform/base/agsplatformdriver.h
- Engine/platform/base/sys_main.cpp
- Engine/platform/emscripten/acpemscripten.cpp
opening as a draft to discuss the problem. I can't quite fix the complex layers of abstractions in Emscripten and SDL2 to make it work with Safari, but I can just ignore all that and just do the 4 lines of JS that are needed to make it work...
I added a new method in platform driver where I can tell if changing to fullscreen is supported or not, and if not, I just don't do anything in the engine.
This means that you can only enter fullscreen in Safari by using the "Toggle Fullscreen" button in the HTML launcher, and you can exit by press Esc (or Swiping down in iPhone). Additionally, in iPhone there is no way to remove this gesture so if your game has swipes (like my ManaMatch game), it's basically impossible to keep it fullscreen on iPhone...
(this all really gives me an urge to remove …
> Emscripten: Fix Safari can't Fullscreen

- Common/gui/guiobject.h
- Editor/AGS.Types/Character.cs
- Editor/AGS.Types/InteractionSchema.cs
- Editor/AGS.Types/Interactions.cs
- Editor/AGS.Types/InventoryItem.cs
- Editor/AGS.Types/PropertyGridExtras/InteractionPropertyDescriptor.cs
- Editor/AGS.Types/PropertyGridExtras/PropertyTabInteractions.cs
- Editor/AGS.Types/Room.cs
- Editor/AGS.Types/RoomHotspot.cs
- Editor/AGS.Types/RoomObject.cs
- Editor/AGS.Types/RoomRegion.cs
- Engine/ac/event.cpp
- Engine/ac/event.h
- Engine/ac/global_character.cpp
- Engine/ac/global_hotspot.cpp
- Engine/ac/global_inventoryitem.cpp
- Engine/ac/global_object.cpp
- Engine/ac/global_region.cpp
- Engine/ac/gui.cpp
- Engine/ac/invwindow.cpp
- Engine/ac/room.cpp
- Engine/ac/runtime_defines.h
- Engine/script/script.cpp
- Engine/script/script.h
Resolves #1765
I believe this is decade overdue...
This adds 2 optional parameters to all of the interaction event callbacks in AGS: object's pointer and a verb (aka cursor mode).
The purpose is to be able to distinguish object and interaction type when user links same function to multiple events. This is similar to how GUI events have GUI/Control and mouse button as parameters.
Right now the users have to resort to ugly workarounds, like calling GetAtScreenXY extra time (which is unreliable), or saving the interacted object in a global variable in on_mouse_click.
The event functions will have following prototype for Characters, Objects, Hotspots and InventoryItems:
```
function cEgo_Interact(Character *c, CursorMode mode)
```
Hotspots have 2 special events without CursorMode param, these …
> Scripting: add object pointer and verb parameters to object interaction functions

- Engine/ac/event.cpp
- Engine/ac/event.h
- Engine/ac/gui.cpp
- Engine/main/game_run.cpp
- Engine/script/script.cpp
I think reducing a bit the macros and using enums instead in a few parts may be useful, in this case, just wanted to replace the callback types since adding something for `on_touch` may be something we do in the future.
I made it in ags4 but if master is preferred I can rebase to it.
> Engine: use enum for Text script callback types

- .cirrus.yml
- make all macOS builds in a single machine
- CMake Linux task builds Debug and Release
- Additionally, in CMake Linux task, pass j2 for minimal parallelism
- Windows Engine and Editor tasks builds Debug and Release in the same task
- Make sure a test runs right after one build, so we can fail earlier
- for Linux make task (which doesn't make into release), drop the i386 build - we don't run tests in it
- for the engine and tests, use VS builds with multiprocessor compilation
This is in-line with #2076, with the idea of reducing a bit the usage of Cirrus CI, the idea is we can possibly still stay under it's set limit of compute credits by doing few changes - I know these list above looks like a lot, but the general of the tasks done is the same and it produces the same binaries using the …
> CI: Reduce container and machine usage

- Editor/AGS.Editor/ApplicationController.cs
- Editor/AGS.Editor/Components/AudioComponent.cs
- Editor/AGS.Editor/GUI/GUIController.cs
- Editor/AGS.Editor/GUI/OutputPanel.cs
- Editor/AGS.Editor/Utils/Utilities.cs
- Editor/AGS.Types/AGS.Types.csproj
- Editor/AGS.Types/AudioClip.cs
- Editor/AGS.Types/PropertyGridExtras/AudioClipSourceFileUIEditor.cs
- Editor/AGS.Types/PropertyGridExtras/ReadOnlyConverter .cs
I will start saying that I don't know if this is a good idea, but what this does is it adds a right click option to force reimport of one audio clip or force reimport all audio clips.
The way it works is it uses the clip source file name and copies the file to the clip cache file name, if it exists.
Maybe fix #778 and someone else can write a  better issue for the things that are in that issue that came up later on.
Also fix #2051
> Feature reimport audio clips

- .cirrus.yml
- build in parallel linux make task used in non-release
- skip running ci when changes are in only markdown files
- do faster shallow clone by default
This complements https://github.com/adventuregamestudio/ags/pull/2079 , for issue  #2076
using shallow clone alone reduces around 40 seconds for all tasks!
> CI: diverse CI resource usage improvements

- Editor/AGS.Editor/AGSEditor.csproj
- Editor/AGS.Editor/Panes/DialogEditor.cs
- Editor/AGS.Editor/Panes/ScriptEditor.cs
- Editor/AGS.Editor/Panes/ScriptEditorBase.cs
- Editor/AGS.Editor/TextProcessing/FindAllUsages.cs
Resolves #1480
The problem with DialogEditor is that it's a stripped copy-paste version of the ScriptEditor (when it comes to working with script itself). So many menu commands that work in the ScriptEditor control are not available in DialogEditor.
The solution seem to be to create a parent class that shares a chosen functionality among these two.
In this PR, the parent class ScriptEditorBase is created, which has following functionality picked out from ScriptEditor and DialogEditor and merged:
* Menu commands and their functions;
* Context menu commands for Scintilla control and their functions;
* Various operations on a script: find, replace, goto line, goto definition, etc.
The menu commands appear to work per se, but some of them have exceptions where they don't work. This is not …
> Editor: share base menu functionality between ScriptEditor and DialogEditor

- .cirrus.yml
- this PR has an addition that excludes a few more files for triggering the CI when they are the sole things in the commit.
But the main thing here is CCache is included in macOS builds. I kept a fairly small cache size, a regular macOS builds uses ~110MB, and the cache size at 180MB - the reason for this is downloading and specially uploading is not that fast.
Using CCache, I could cut the macOS build time to around half of it, so this should help lower the Apple Silicon usage significantly, which should help us cut on Compute Credits. In my tests CCache didn't cause any issue and it was fairly stable.
> CI: add ccache in macOS builds

- Compiler/script2/cc_compiledscript.cpp
- Compiler/script2/cs_parser.cpp
- Compiler/script2/cs_parser.h
- Compiler/test2/cc_parser_test_1.cpp
This addresses #2066.
If a function was referenced in code but not defined with body, the compiler didn't point out properly the specific function.
I added a googletest that demonstrates the bug and fixed the bug.
Typical code: 
```
void Test();
{
Test();
}
```
> AGS4 new compiler: Fix bug: Forward-declared, unresolved function not reported correctly

- .cirrus.yml
- ci/windows/Dockerfile
- include x64 irrKlang for WinVSDevDependencies downloads
- additionally add vcredist 64 so we can track it
The idea here is just to have dependencies tracked for a future Editor build as 64-bit, described in #2088. By having the irrKlang dependencies there already, they would be in the `WinDevDependenciesVS` for next releases.
> CI: add irrKlang 64-bit and vcredist 64 in docker

- Compiler/script2/cs_parser.cpp
- Compiler/test2/cc_bytecode_test_0.cpp
- Compiler/test2/cc_bytecode_test_1.cpp
This addresses #2081.
When a dynamic array is accessed by a constant index, an array overrun check must be generated. This check must happen at runtime because the actual size of the dynamic array isn't known at compile time. 
Typical code: 
```
function game_start() {
int arr[] = new arr[1];
Display("%d", arr[1000]); // ← overflow check must be generated here
}
```
This PR doesn't need a dedicated Googletest because existing tests already cover this.
Modify existing Googletests so that they accept the new generated code.
Delete some superfluous Googletests because the remaining tests cover sufficiently what the deleted tests have checked.
> Add array overrun check to constant index access of dynamic array

- Compiler/script2/cs_parser.cpp
- Compiler/test2/cc_bytecode_test_0.cpp
- Compiler/test2/cc_parser_test_1.cpp
This addresses #2068. 
Fix bug: Commas `,`within array indexes within function calls were mis-interpreted as parameter delimiters.
Add googletests
Typical code: 
```
int arr[10, 10, 10];
void Test(int x) {}
{
Test(arr[1, 2, 3]); // ← mis-interpreted as three parameters for call to `Test`
}
```
> Don't confuse param delimiters `,` and array index delimiters `,` in calls to function

- Android/library/runtime/src/main/java/org/libsdl/app/HIDDeviceBLESteamController.java
- Android/library/runtime/src/main/java/org/libsdl/app/HIDDeviceManager.java
- Android/library/runtime/src/main/java/org/libsdl/app/HIDDeviceUSB.java
- Android/library/runtime/src/main/java/org/libsdl/app/SDL.java
- Android/library/runtime/src/main/java/org/libsdl/app/SDLActivity.java
- Android/library/runtime/src/main/java/org/libsdl/app/SDLAudioManager.java
- Android/library/runtime/src/main/java/org/libsdl/app/SDLControllerManager.java
- Android/library/runtime/src/main/java/org/libsdl/app/SDLSurface.java
- CMake/FetchSDL2.cmake
- Editor/AGS.Editor/BuildTargets/BuildTargetAndroid.cs
- ci/linux/Dockerfile
- ci/windows/Dockerfile
- libsrc/download.sh
- libsrc/sha1sums
I think we want to follow SDL 2 releases, from what I monitored, the regressions that were introduced since 2.24.1 are fixed.
I tested on macOS, Windows and Android, but not thoroughly. I haven't tested on Linux yet.
Emscripten is the only one not upgraded here - I haven't upgraded Emscripten upstream yet, I will do that and adjust later, but possibly in a new PR.
Ah, this SDL2 upgrade was a bit painful in my Android Studio and CLion IDEs, I had to delete all cache/intermediate build files to get it to build correctly. In the CI, because things are always built cleanly, this is already taken care.
Also, it's possibly a good idea if someone has an Android device to check if things are still working ok - I only tested in emulator, and it seems alright, but there are lots of android changes …
> Upgrade SDL to 2.28.2

- Engine/ac/dialog.cpp
- Engine/ac/display.cpp
- Engine/ac/invwindow.cpp
- Engine/ac/mouse.cpp
- Engine/ac/room.cpp
- Engine/ac/sys_events.cpp
- Engine/ac/sys_events.h
- Engine/gui/cscidialog.cpp
- Engine/main/game_run.cpp
- Engine/main/game_run.h
- Engine/media/video/video.cpp
- Engine/plugin/agsplugin.cpp
Implement mouse event buffer similar to key buffer, and process it all in check_controls().
Process Mouse.Click() simulation by sending appropriate events.
This theoretically allows to get multiple number of `on_mouse_click` callbacks per game frame, with different buttons too (in case 2 mouse buttons were pressed simultaneously).
NOTE: I was not able to register more than 1 click with 1 button per game frame, no matter the game speed. ~Possibly this is also restricted by SDL2 somehow (might need to investigate).~ Looks like i'm not clicking fast enough, or my mouse is unable to send clicks fast enough.
It's possible to receive all 3 `on_mouse_click` events with 3 different buttons in a row though.
Also possible to simulate unlimited number of clicks using Mouse.Click() script command. …
> Support multiple mouse clicks per game frame

- Editor/AGS.Editor/Panes/LipSyncEditor.Designer.cs
- Editor/AGS.Editor/Panes/LipSyncEditor.cs
- Editor/AGS.Editor/Panes/LipSyncEditor.resx
This PR adjusts the LipSync pane to use a table layout instead of hardcoded control positions. This makes it work in both 100% and 200% scaling. 
In Windows 10, I need to use the following compatibility setting in the application properties so it's scaling can be tested.
I opened #2087 to list all the various pane that have issues.
> Editor: LipSync pane with scalable table layout

- Editor/AGS.Editor/Entities/AutoCompleteParserState.cs
fix #2101
I couldn't find any unintended side effect on this change in the autocomplete!
> fix the no static arrays in autocomplete issue

- Engine/gfx/gfx_util.cpp
- Plugins/agspalrender/raycast.cpp
These issues were originally reported on the scummvm repo (see PR https://github.com/scummvm/scummvm/pull/5220)
Also fixed a couple occurrences where mapWidth/mapHeight is not used
> Fixes for possibile indexes out of bounds

- Editor/AGS.Editor/AGSEditor.cs
- Editor/AGS.Editor/Components/RoomsComponent.cs
- Editor/AGS.Editor/Components/TranslationsComponent.cs
- Editor/AGS.Types/Translation.cs
- Editor/AGS.Types/Utilities.cs
AGS.Types had been used as a Editor's "API" for a long while now, it's commonly linked to Editor plugins and third-party tools (such as FontEditor app). Therefore we cannot make any assumptions about filesystem around AGS.Types library, and should not implicitly delete or move project files.
Besides that, implicitly loading from legacy format and deleting files in random time is inconsistent with how Editor normally works.
With this change I move migration from old TRS format to the new PO format into the TranslationComponent class, where it runs it triggered by GamePostLoad event.
In addition, rise format index, and add a constant that tells the first version the PO became new translation source format.
Made a PR because I still have concerns that I could miss something.
> 4.0 Editor: move translation src migration process to TranslationComponent

- Editor/AGS.Editor/Resources/agsdefns.sh
- Engine/CMakeLists.txt
- Engine/ac/display.cpp
- Engine/ac/dynobj/cc_serializer.cpp
- Engine/ac/dynobj/scriptjoystick.cpp
- Engine/ac/dynobj/scriptjoystick.h
- Engine/ac/game.cpp
- Engine/ac/game.h
- Engine/ac/joystick.cpp
- Engine/ac/joystick.h
- Engine/ac/runtime_defines.h
- Engine/ac/speech.cpp
- Engine/ac/sys_events.cpp
- Engine/ac/sys_events.h
- Engine/main/engine.cpp
- Engine/main/game_run.cpp
- Engine/main/game_run.h
- Engine/media/video/video.cpp
- Engine/script/exports.cpp
- Engine/script/script_api.h
- Solutions/Engine.App/Engine.App.vcxproj
- Solutions/Engine.App/Engine.App.vcxproj.filters
fix #1364  | [Forum thread](https://www.adventuregamestudio.co.uk/forums/index.php?topic=59945.0)
Adds a Joystick API with support to SDL Game Controller too (named Gamepad in Script API here).
- Joysticks are managed internally in the engine: you can't open or close connection to joysticks from the script api.
- Missing a better integration with the engine and a way to set the buttons for things like skipping text dialogs with the joystick. 
- Haptics (Rumble) is not added here.
- Navigating default AGS menus with joystick/gamepad is not intended to be supported because it would require a new concept of selection.
- Also I have no idea what to do regarding save files.
**`Joystick.JoystickCount`**
```AGS Script
static readonly int Joystick.JoystickCount
```
Get the number of connected …
> Feature joystick

- .cirrus.yml
- .github/workflows/build.yml
- CMakeLists.txt
this is #2076 issue, which included the improvements in #2079, #2083, #2085 and #2091 PRs, adapted for 3.6.0 branch.
> Sync CI speed-ups to release 3.6.0 branch

- Common/ac/spritecache.cpp
- Common/ac/spritecache.h
- Engine/ac/draw.cpp
- Engine/ac/draw.h
- Engine/ac/dynamicsprite.cpp
- Engine/ac/game.cpp
- Engine/ac/game.h
- Engine/ac/gamestate.h
- Engine/ac/room.cpp
- Engine/gui/gui_engine.cpp
Fixes #2104 . Please read the ticket and comments for detailed explanation of the problem.
There are following changes done here.
1. SpriteCache now has a "placeholder" field initialized to a 1x1 transparent bitmap by default. operator `[]` is ensured to always return this placeholder if an invalid sprite was requested. This is a safeguard against program exceptions. Note that it's still possible to test for sprite's existence explicitly by calling DoesSpriteExist.
I think it may be feasible to add a method for setting custom placeholder. Possibly a copy of sprite 0 may be assigned as a placeholder. I may add this behavior if someone thinks that's a good idea. At first I thought to just use sprite 0 implicitly, but it's a real possibility that sprite 0 does not exist in game. So I went …
> Change the rules of how game objects are updated after sprite's update/deletion

- Editor/AGS.Editor/Panes/CharacterEditor.Designer.cs
- Editor/AGS.Editor/Panes/CursorEditor.Designer.cs
- Editor/AGS.Editor/Panes/InventoryEditor.Designer.cs
- Editor/AGS.Editor/Panes/ViewEditor.Designer.cs
- Editor/AGS.Editor/Panes/ViewEditor.cs
- Editor/AGS.Editor/Panes/ViewPreview.Designer.cs
- Editor/AGS.Editor/Panes/ViewPreview.cs
- Editor/AGS.Editor/Panes/ZoomTrackbar.Designer.cs
Resolves #2020, and suggestion in comments by @ericoporto :
> In the view, originally I meant the left pane to have no relationship to the zoom slider at right, and instead just fill the panel as well as possible. I still think this works best for the animation preview, as it's more a quick preview of an animation that will be only properly viewed in-game, later, in a context. I think the slider should only affect the right pane there.
1. Adjust zoom sliders to allow downscale down to min value of 20%, changed step to 10% mostly to let more precise downscale than with 25% step. Made zoom control wider on existing panels, for convenience (idk why MSVS did so many changes to Designer code everywhere, apparently this happens when regenerating the control looks).
2. Added AutoFrameFill mode …
> Editor: allow downscale Character preview & make frame preview in View pane fill whole size

- Common/util/ini_util.h
- Editor/AGS.Editor/AGSEditor.cs
- Editor/AGS.Editor/BuildTargets/BuildTargetAndroid.cs
- Editor/AGS.Editor/NativeProxy.cs
- Editor/AGS.Editor/Utils/Utilities.cs
- Editor/AGS.Native/NativeMethods.cpp
- Editor/AGS.Native/NativeMethods.h
Resolves #2137
Because I also wish to patch this in release-3.6.0 branch, I chose the most straightforward method, and used IniUtils from C++ part of the Editor to merge new options with the config file.
Gather up dictionary of sections in C# code, and then pass to NativeProxy, where it converts to the native strings using TextHelper, and writes to ini using IniUtils.
I tested this and confirmed that the resulting file contains "titletext" setting in UTF-8, and that winsetup can successfully display this text in its caption.
Same is done for android.cfg.
I do not think that there are any other options that may contain utf-8 text (?), but will leave to others to comment on this.
> Editor: write INI files using IniUtils from AGS.Native

- Editor/AGS.Editor/AutoComplete.cs
- Editor/AGS.Editor/ComponentController.cs
- Editor/AGS.Editor/Components/AudioComponent.cs
- Editor/AGS.Editor/Components/BaseComponent.cs
- Editor/AGS.Editor/Components/CharactersComponent.cs
- Editor/AGS.Editor/Components/CursorsComponent.cs
- Editor/AGS.Editor/Components/DialogsComponent.cs
- Editor/AGS.Editor/Components/FontsComponent.cs
- Editor/AGS.Editor/Components/GuiComponent.cs
- Editor/AGS.Editor/Components/InventoryComponent.cs
- Editor/AGS.Editor/Panes/ScriptEditorBase.cs
- Editor/AGS.Types/EditorFeatures/AutoComplete/ScriptEnumValue.cs
Btw, I looked into creating a ScriptElement in EditorFeatures/AutoComplete, which both ScriptVariable and ScriptEnumValue could extend from, but ScriptVariable name is VariableName and ScriptEnumValue name is just Name, so I couldn't easily make both extend from the same thing without breaking AGS Types api.
Ah, `#define` macros don't have the concept of what they belong to, so there isn't an easy way to add VIEW macro support (in ags4, we could have view as enum after #1175).
I also noticed the when launching the help, if it detects that the found thing is an enum, it could use it's type to instead search the help for that, because currently the enum values in the built-in header are not index, only their enum type. I am not doing this here because I am thinking if I can add them to the …
> Editor: support go-to for GUI controls, Cursors, Audio Types and Fonts

- Common/util/geometry.h
- Engine/ac/character.cpp
- Engine/ac/draw.cpp
- Engine/ac/movelist.cpp
- Engine/ac/movelist.h
- Engine/ac/room.cpp
- Engine/ac/roomobject.cpp
- Engine/ac/route_finder_impl.cpp
- Engine/ac/route_finder_impl_legacy.cpp
- Engine/ac/runtime_defines.h
- Engine/main/update.cpp
- Engine/main/update.h
- Engine/plugin/agsplugin.cpp
Fixes #935.
AGS historically has a hidden problem: its pathfinder and walking algorithm uses math with relatively low precision. This may result in rounding mistakes. What this means in practice is that under some circumstances the "movement direction" (vector) is slightly off, e.g. more towards X than Y (or other way). In such case the character may reach the X destination while Y destination is still few pixels away.
How is this issue solved currently in AGS (and for a long time): when AGS finds out that one coordinate is complete, but another is not (for example X done and Y is still not reached), it starts waiting until character reaches Y, but also accepts a certain "mistake", in 2-3 pixels. If character is already within 2-3 pixels from the destination, then it just stops. This …
> Fix "walking on place" bug in 3.6.1

- Common/ac/characterinfo.h
- Engine/ac/character.cpp
- Engine/ac/movelist.cpp
- Engine/ac/movelist.h
- Engine/ac/roomstatus.h
- Engine/ac/route_finder.cpp
- Engine/ac/route_finder.h
- Engine/ac/route_finder_impl.cpp
- Engine/ac/route_finder_impl.h
- Engine/ac/route_finder_impl_legacy.cpp
- Engine/game/savegame_components.cpp
- Engine/main/update.cpp
Done after a conversation in #2125 , not directly related, but I wanted to experiment with recalculating movelists.
Try to support changing Character's movement speed while character is moving. This is done by recalculating movelist's stages and updating current stage's distance (`onpart` variable).
Recalculation is done as a rather trivial math, where we divide on the old speed factor and multiply on the new speed factor. This does not involve any pathfinding at all, as we only need to "replace" a speed factor in x/ypermove arrays, so to speak.
I did this only in case of a "new" pathfinder, because old one is used in old games only, where changing walkspeed during walk was prohibited. But technically this code is applicable to both.
Preliminary tests show a good progress, so I decided to …
> Allow to change walking speed during walking

- Editor/AGS.Editor/AGSEditor.cs
- Editor/AGS.Editor/BuildTargets/BuildTargetAndroid.cs
- Editor/AGS.Editor/BuildTargets/BuildTargetBase.cs
- Editor/AGS.Editor/BuildTargets/BuildTargetDataFile.cs
- Editor/AGS.Editor/BuildTargets/BuildTargetLinux.cs
- Editor/AGS.Editor/BuildTargets/BuildTargetWeb.cs
- Editor/AGS.Editor/BuildTargets/BuildTargetWindows.cs
- Editor/AGS.Editor/Components/BuildCommandsComponent.cs
- Editor/AGS.Editor/GUI/GUIController.cs
Fixes #1976, again.
* Picked out DeleteCommonGameFiles(), to be able to call same from any BuildTarget;
* Added cleanup of split resources.
* Call cleanup for the current filename too, just to be sure everything is deleted beforehand. This fixes split resources not being deleted if this option changes in General Settings.
Also:
* Save user data file (aka WorkspaceState) right after game building, to ensure that any information amended during build is always saved on disk regardless whether user saves or not the project itself.
> Editor: more fixes for compiled files cleanup

- Editor/AGS.Editor/Components/BuildCommandsComponent.cs
minor thing, but it looks much nicer with this separator.
I should have added it when I added these.
> Editor: add separator in build menu before open folder

- .cirrus.yml
Make sure we are getting the templates from the right branch that is now https://github.com/adventuregamestudio/ags-templates/tree/release-3.6.0
> ci: set release-3.6.0 templates branch

- Common/core/assetmanager.h
- Common/util/string.h
- Compiler/script2/cc_compiledscript.cpp
- Editor/scintilla/src/UniConversion.h
Getting the engine and editor to build in windows 10 with vs2022, the IDE wanted to update the SDK to 10 and the platform toolset to 143.
In order for the solutions to build (besides some configuration changes that are probably not retrocompatible), these file changes were required.
If I understand things correctly, they have to do with the fact that some declarations have been moved from `std` to more "specific" headers.
Please, test these out with older toolchains.
> Added #include directives that seem to be required

- Engine/media/audio/audio.cpp
- Engine/platform/base/sys_main.cpp
- Separate the gamepad system so it's failure doesn't fail all ags engine
- Make sure we only quit the SDL audio subsystem if it's ref count was increased
Fixes the issue reported here: https://www.adventuregamestudio.co.uk/forums/engine-development/ags-engine-web-port/msg636658208/#msg636658208
If sys_main was a singleton, it's instance could hold a variable to identify the successfully loaded systems - currently, only the SDL_GameController subsystem would be necessary. While there are some considerations into account about usage of singletons, they would help us reduce global variables - and have a better track of things the engine has in memory.
> Engine: use SDL_InitSubSystem for required systems

- Engine/media/audio/audio.cpp
- Engine/platform/base/sys_main.cpp
This is done after comments in #2166. Unfortunately I realized the problem too late, after merging the pr.
Keep record of the SDL subsystems we init in a static variable inside sys_main, and use this info when shutting SDL subsystems down. The idea is that this is incapsulated in sys_main, so that external code would not interfere with this.
Somewhere in the future we could remake sys_main into a singleton class, for instance.
EDIT: i have a deja vu, because this looks like something I was trying to add a while ago... but maybe this was in a different program.
@ericoporto could you please also try that this still works as expected?
This should be applied to a 3.6.0 branch too.
> Record inited SDL subsystems and use this info during uninit

- Editor/AGS.Editor/AGSEditor.csproj
- Editor/AGS.Editor/Components/AudioComponent.cs
- Editor/AGS.Editor/Components/BaseComponentWithFolders.cs
- Editor/AGS.Editor/Components/CharactersComponent.cs
- Editor/AGS.Editor/Components/DialogsComponent.cs
- Editor/AGS.Editor/Components/GuiComponent.cs
- Editor/AGS.Editor/Components/InventoryComponent.cs
- Editor/AGS.Editor/Components/RoomsComponent.cs
- Editor/AGS.Editor/Components/ScriptsComponent.cs
- Editor/AGS.Editor/Components/ViewsComponent.cs
- Editor/AGS.Editor/GUI/ProjectTree.cs
- Editor/AGS.Editor/GUI/TreeViewExtensions.cs
Resolves #2105.
Added an ability to keep the expansion state of a project tree inside `RePopulateTreeView()` method.
`RePopulateTreeView` is a part of a IEditorComponent interface, and has 2 variants, where 1st has no args and 2nd accepts a selected item id. I did it so that state-saving is only done in the second variant, because there may be cases where whole tree must be refreshed. This may be reviewed later if necessary.
Also added a pair of BeginUpdate/EndUpdate around tree repopulation, but it does not seem to have much effect (?).
I noticed that there is a number of RePopulateTreeView calls in components, that call the 1st variant without args. I'd check these too and see if some could use the variant with node id in order to keep tree expanded.
> Editor: keep ProjectTree's expanded state while doing simple actions

- Common/ac/game_version.h
- Editor/AGS.Editor/AGSEditor.cs
- Editor/AGS.Editor/AGSEditor.csproj
- Editor/AGS.Editor/Components/RoomsComponent.cs
- Editor/AGS.Editor/Components/ScriptsComponent.cs
- Editor/AGS.Editor/GUI/GUIController.cs
- Editor/AGS.Editor/Utils/ScriptGeneration.cs
- Editor/AGS.Types/Script.cs
- Engine/main/game_start.cpp
Resolve #1306.
The purpose of this change is to remove a hardcoded call to SetRestartPoint at the start of the game, which may be unwanted if the game uses its own save rules or custom saves.
Users should be advised to call SetRestartPoint manually at the end of `game_start()` instead: that will have equivalent result.
This change needs to be added to every template, and also noted in the manual.
1. Disables hardcoded SetRestartPoint at the game start in the engine.
**NOTE:** pre-3.6.1 games still have it run, for backwards compatibility.
2. On project upgrade, insert a SetRestartPoint() call to the game_start() found in GlobalScript.asc. This is for user's convenience. Ironically this is 99% of the changes in this PR. But I may disable or remove this if it's found to be not a good …
> 3.6.1: disable hardcoded SetRestartPoint

- Editor/AGS.Editor/Resources/agsdefns.sh
- Engine/ac/character.cpp
- Engine/ac/drawingsurface.cpp
- Engine/ac/global_api.cpp
Users complain regularly about not being able to print variables directly in SayBackground(). I looked around the API, and found there are several functions that display text on screen, but don't support formatting, while their counterparts do. So I turned these functions into variadic with text formatting support.
This refers to:
* DisplayAtY();
* DrawingSurface.DrawStringWrapped();
* Character.SayAt();
* Character.SayBackground();
**Backwards compatibility:**
Old games will always call these functions without extra args. The only problem will occur if the text contains format placeholders. In such case engine's `ScriptSprintf` function prints these placeholders verbatim.
> ScriptAPI: added formatting support to a few text displaying functions

- Compiler/preproc/preprocessor.cpp
- Compiler/preproc/preprocessor.h
- Compiler/test/preprocessor_test.cpp
- Editor/AGS.CScript.Compiler/Entities/ErrorCode.cs
- Editor/AGS.CScript.Compiler/Preprocessor.cs
- Editor/AGS.Editor/AutoComplete.cs
I could not find if there was there a ticket for this, maybe I had a false memory about it.
In any case, I got weary of not being able to have ```#ifdef N #else #endif``` kind of construct, and tried to implement basic support  for "#else".
This is a *most trivial and naive* implementation, because it assumes only ifdef/else/endif combination. This won't work with "else if", but these are not supported by AGS preprocessor at the moment.
Added to:
* Editor's preprocessor (C# one);
* Editor's Autocomplete. Although autocomplete seems to break often when preprocessor definitions are around, but that might be a separate issue. At least it seems to work when the `#if/else/endif` are on top of the script (outside of function).
* C++ preprocessor, to sync with the embedded C# one.
If this proves …
> Basic support for "#else" preprocessor in AGS script

- Common/ac/spritefile.cpp
this is done to squeeze that for to be a little faster when loading something from the spritefile. The change is almost negligible but in the VS Profiler what happens is the fraction of `UnpackIndexedBitmap` is reduced compared to `BitmapToVideoMem` (in gfxdriverbase).
> Common: avoid if in indexed bmp unpack

- Compiler/script2/cs_parser.cpp
- Compiler/test2/cc_parser_test_1.cpp
This is a preliminary fix for #2174.
Accept expressions such as `new S()` where a parameter list follows the type. The parameter list is ignored. A warning is issued.
> New compiler: Accept & skip '()' after 'new'

- Engine/gfx/gfxdriverbase.cpp
- Engine/gfx/gfxdriverbase.h
Hi, tried a bit of moving code around in BitmapToVideoMem. In my tests, this benchmark below that clears fullscreen bitmap and pushes to memory using an Overlay went from 22.6 FPS using what we currently have on master to 26.9 FPS after the modifications from this PR. It's nothing ground breaking, but still somewhat an improvement. Please verify this improvement.
Test Game: [ClearBenchMark.zip](https://github.com/adventuregamestudio/ags/files/13035487/ClearBenchMark.zip)
Project: [ClearBenchmarkProject.zip](https://github.com/adventuregamestudio/ags/files/13035484/ClearBenchmarkProject.zip)
I am not sure about the many commits and how to organize them or if I should merge them in a single one, and also if the code that I got to in the end is acceptable.
Ah, I don't know any 16-bit game, …
> Engine: refactoring BitmapToVideoMem

- Compiler/script2/cs_parser.cpp
- Compiler/test2/cc_parser_test_1.cpp
Fixes #1921
When a local function is forward-declared but not locally defined with body then calls to that function can't be resolved. The compiler catches that but it flagged it with a nonsensical error message (which is a bug)
This same situation can also come up when a programmer forgets the `import` keyword when declaring an external function. 
Change the error message so that both cases are covered.
Typical code: 
```
struct Test
{
static int F(); // might be a local function, might be external but 'import' forgotten
};
{
Test.F();
}
```
The compiler will now flag line 3 and give the error message:
> > The local function 'Test::F' is never defined with body (did you forget 'import'?)
> New compiler: Better error msg. for forward declaration of local functions

- CMake/c_flag_overrides.cmake
- CMake/cxx_flag_overrides.cmake
- Common/core/platform.h
- Engine/main/main.cpp
- Engine/platform/windows/acplwin.cpp
- Engine/platform/windows/setup/winsetup.cpp
- Engine/platform/windows/win_ex_handling.cpp
- Engine/platform/windows/win_ex_handling.h
- Engine/util/library_windows.h
- Plugins/agsblend/AGSBlend.cpp
- libsrc/allegro/CMakeLists.txt
- libsrc/allegro/include/allegro/internal/alconfig.h
- libsrc/allegro/include/allegro/platform/almsvc.h
This is to be able to build on Windows by using MinGW instead of MSVC. Of course, we will forever use MSVC because of the Editor (and C++/CLR), but still, wanted to investigate possibilities - just to safeguard.
Here is a 64-bit build through MinGW: [ags.zip](https://github.com/adventuregamestudio/ags/files/13062121/ags.zip)
_Known issue:_ SDL2 is statically linked and SDL2 statically linked has some issue with fullscreen on Windows I couldn't yet figure it out (this happens in MSVC too, so it's not mingw specific)
There is no rush here, so this can be reviewed with calm.
> Add mingw basic support

- Common/ac/gamesetupstruct.cpp
- Common/ac/gamesetupstruct.h
- Common/ac/gamesetupstructbase.cpp
- Common/ac/gamesetupstructbase.h
- Common/ac/gamestructdefines.h
- Common/game/main_game_file.cpp
- Common/game/main_game_file.h
- Common/gui/guidefines.h
- Common/gui/guilabel.cpp
- Common/gui/guilistbox.cpp
- Common/gui/guimain.cpp
- Editor/AGS.Editor/DataFileWriter.cs
- Editor/AGS.Editor/Resources/agsdefns.sh
- Editor/AGS.Editor/Tasks.cs
- Editor/AGS.Editor/Utils/DialogScriptConverter.cs
- Editor/AGS.Native/agsnative.cpp
- Editor/AGS.Types/Settings.cs
- Engine/ac/dynobj/scriptgame.cpp
- Engine/ac/event.h
- Engine/ac/gamestate.cpp
- Engine/ac/gamestate.h
- Engine/ac/global_api.cpp
- Engine/ac/global_game.cpp
- Engine/ac/global_game.h
- Engine/ac/gui.cpp
- Engine/ac/runtime_defines.h
- Engine/game/game_init.cpp
- Engine/game/savegame.cpp
- Engine/main/engine.cpp
This is a suggestion, but I think that it goes in line with the general idea of cutting built-in functionality that is
* may be easily implemented in game script;
* has narrow use in contemporary games.
This PR completely removes Score functionality, which includes:
- Total score / current score variables;
- GiveScore script command, and associated sound setting;
- "give-score" command in dialog script;
- `@SCORE@` and related label macros.
> AGS 4: Remove built-in Score functionality

- Editor/AGS.Editor/GUI/LogPanel.Designer.cs
- Editor/AGS.Editor/GUI/LogPanel.cs
- Editor/AGS.Editor/Hacks.cs
This PR adds theme support to the log panel and fixes a couple things:
- added default margins to the RichTextBox
- resized log panel buttons to match icon size
Was there anything new that was missing theming?
> Theme support for Log Panel

- .gitignore
- Common/util/file.cpp
fixes Android error reported here https://www.adventuregamestudio.co.uk/forums/advanced-technical-forum/ogg-audio-makes-the-game-freeze-android/msg636658856/#msg636658856
> In other news, I seem to have trouble building for Android on this new version. I get the following error every time I try to launch the .apk on my phone :
> "AGSNative
> Loading game failed with error:
> Main game file not found or could not be opened.
> Filename: ac2game.dta..
> 
> The game files may be incomplete, corrupt or from unsupported version of AGS."
> 
> Until I manage to fix that, I won't be able to verify that the issue is fixed in the 3.6.1....
The issue is the previously used methods can't test for file existence inside the Android asset file.
> Common: use Android asset compatible methods

- Android/agsplayer/build.gradle
- Android/library/runtime/build.gradle
- Android/mygame/app/build.gradle
- Android/mygame/build.gradle
- Common/CMakeLists.txt
- Common/util/android_file.cpp
This is made on top of #2214 to make it easy to test. What it does is it specifically disable the additional compression Android does, only for `.ags` and `.vox` packages.
Added some extra things
- Added also fix #2219
- Defined Case Sensitive Filesystem macro in Android build
- Upgraded gradle Android plugin just to keep it updated.
To-do: check if unpacking an .ags and .vox package in the asset dir makes it run faster - these will still be compressed, but seeking to the file should be faster without the package indirection.
> Fix: don't compress `.ags` and `.vox` in android assets

- Editor/AGS.Editor/AGSEditor.cs
- Editor/AGS.Editor/Panes/ScintillaWrapper.cs
- Editor/AGS.Native/NativeDLL.vcxproj
- Solutions/Common.Lib/Common.Lib.vcxproj
- Solutions/Compiler.Lib/Compiler.Lib.vcxproj
- Solutions/Compiler2.Lib/Compiler2.Lib.vcxproj
As discussed on discord, I cleared a few of the compilation warnings from the Editor.Full solution
> Fix warnings

- Editor/AGS.Editor/ApplicationController.cs
- Editor/AGS.Editor/Components/DefaultSetupComponent.cs
- Editor/AGS.Editor/Components/ScriptsComponent.cs
- Editor/AGS.Editor/Components/SettingsComponent.cs
- Editor/AGS.Editor/EditorEvents.cs
- Editor/AGS.Editor/Tasks.cs
Fix #1005
This makes GeneralSettings and DefaultSetup behave consistently with the other unique persistent panels (such as GlobalVariables, LipSync, etc), and get recreated when the new game is opened. This fixes them in case CurrentGame reference has changed in the editor.
In practice this fixes editor not acting properly after importing a pre-3.* game.
> Editor: recreate GeneralSettings and DefaultSetup documents when a new game is opened

- Editor/AGS.Editor/Panes/Room/RoomEditFilters/BaseAreasEditorFilter.cs
- Editor/AGS.Editor/Panes/Room/RoomEditFilters/CharactersEditorFilter.cs
- Editor/AGS.Editor/Panes/Room/RoomEditFilters/EdgesEditorFilter.cs
- Editor/AGS.Editor/Panes/Room/RoomEditFilters/EmptyEditorFilter.cs
- Editor/AGS.Editor/Panes/Room/RoomEditFilters/IRoomEditorFilter.cs
- Editor/AGS.Editor/Panes/Room/RoomEditFilters/ObjectsEditorFilter.cs
- Editor/AGS.Editor/Panes/Room/RoomSettingsEditor.cs
Fix #984, addresses a minor problem mentioned in #614.
* Display coordinates hint when Characters or Objects are moved with keys too.
* Fixed hint's position was only constrained by top-left border; made sure it is always visible even if a moved object is out of visible bounds (e.g. if user zoomed into a different part of room).
* Allow to move Objects outside of room bg, similar to Characters.
* Brought Characters and Objects moving code to more consistency (although imo they should get a base class, but that's for separate task).
On a side note, the coordinates may be difficult to see sometimes, depending on background.
For a moment I've been thinking about letting user choose a color in Editor prefs, but even a custom color will still be fixed and have same problem. So this is an open …
> Editor: enhance coordinates hint when moving Objects and Characters around the room

- Editor/AGS.Editor.Tests/ScriptCompiler/PreprocessorTests.cs
Because #2178 happened before editor tests were backported in #2180, the `#else` clause test added in the cpp preprocessor was not added for the C# one. This just ports that test over to the editor tests.
> Editor: add Test for Preprocessor else macro

- Editor/AGS.CScript.Compiler/Entities/FastString.cs
I noticed the StartsWith comparison is using the default `CurrentCulture`, in the `FastString` implementation, which from the [docs here](https://learn.microsoft.com/en-us/dotnet/api/system.string.compare?view=netframework-4.6.2) I think is more meant for regular text, but for variables and other elements in AGS Script, I think we expect binary matches. `FastString` is used only in a context of processing AGS Script language, so I think it's safe to change it's behavior to such.
The motivation is I noticed this makes StartsWith to run a little faster. To profile I used the description of #1926, and just loaded my ImGi script module and typed a lot of things in it's script module to make the ConstructCache run a lot.
I am not super sure of how much this improves because for some reason I …
> Editor: slightly perf improve in FastString StartsWith

- Editor/AGS.Editor/Panes/DialogEditor.cs
- Editor/AGS.Editor/Panes/ScriptEditorBase.cs
additional for #2231 
There are still small details there, but in this way, using an action in the edit menu won't affect the scintilla editor if a textbox has focus.
Checking for focus in scintilla instead won't work, so this is why it's done in such way.
> Editor: if textbox is focused, edit menu affects it

- Editor/AGS.Editor/AGSEditor.csproj
- Editor/AGS.Editor/Components/BuildCommandsComponent.cs
- Editor/AGS.Editor/GUI/GUIController.cs
- Editor/AGS.Editor/GUI/frmMain.cs
- Editor/AGS.Editor/Program.cs
- Editor/AGS.Editor/Utils/CommandLineOptions.cs
- Editor/AGS.Editor/Utils/StdConsoleWriter.cs
- Editor/AGS.Types/Exceptions/CompileMessage.cs
fix #666
The goal here is so that using `/compile` flag the Editor won't show a pop-up or require human input in some way it could hang a continuous integration pipeline - because no one would be there to click the button.
- `/compile` will make the Editor alert messages get logged to the terminal
- Additionally, messages that goes to the output panel also gets logged to the terminal
- The software exit code will be non-zero if the compilation failed when using `/compile`
- This can be used to fail a pipeline in case we have a build error in a game
> Editor: compile flag turns alert in log messages

- Common/ac/spritecache.cpp
- Common/ac/spritecache.h
- Common/util/resourcecache.h
- Editor/AGS.Editor/Resources/agsdefns.sh
- Engine/ac/draw.cpp
- Engine/ac/draw.h
- Engine/ac/game.cpp
- Engine/ac/game.h
- Engine/ac/mouse.cpp
- Engine/ac/mouse.h
- Engine/ac/route_finder_impl_legacy.cpp
- Engine/ac/timer.h
- Engine/ac/viewframe.cpp
- Engine/ac/viewframe.h
- Engine/device/mousew32.cpp
- Engine/device/mousew32.h
- Engine/game/savegame.cpp
- Engine/main/engine.cpp
- Engine/media/audio/sound.cpp
- Engine/media/audio/sound.h
This is the last thing i wanted to try adding in 3.6.1.
It's been always a problem in AGS that game developers have little control over the resource management. That is a big topic, and has to be thought through well before writing a good API, but I wanted to add couple of simple temporary methods, acting as a  replacement for existing hacks that let precache a number of sprites and fix performance in certain scenes.
* Game.PrecacheSprite(int sprnum) precaches a single sprite;
* Game.PrecacheView(int view, int first_loop, int last_loop) precaches sprites and *linked sounds* for all frames in the given range of loops for the view.
Precaching a sprite in both of these methods does not load only a raw sprite, but also prepares a texture for it, since we have a texture cache now too, and …
> Script API: add Game.PrecacheSprite() and PrecacheView()

- Common/core/assetmanager.cpp
- Common/core/assetmanager.h
- Common/util/string_types.h
Fix #2247
std::unary_function and std::binary_function have been deprecated in C++11, and removed completely in C++17.
The std algorithms are supposed to accept any functor that defines correct operator.
Additionally, in AssetManager replaced struct LibsByPriority with a function pointer and 2 sorting functions. This is to avoid making redundant checks for a priority type during sort operations.
> Remove deprecated inheritance from std::x_function

- Engine/gfx/ali3dogl.cpp
- Engine/gfx/ali3dogl.h
- SDL iOS OpenGL view ([SDL_uikitopenglview.m](https://github.com/libsdl-org/SDL/blob/SDL2/src/video/uikit/SDL_uikitopenglview.m)) generates its own framebuffer, use it instead of 0
- Ensure that iOS is initialized with a 0 depth size to avoid generated depth framebuffers
- Add missing GL_FRAMEBUFFER_COMPLETE_EXT definition
@edmundito is working on the iOS port I left unfinished. Most of the changes are in the `iOS` directory. I want to pick the ones that aren't in small bits to make it easier to review, as there isn't a lot of stuff.
> Engine: ali3dogl iOS fix for SDL renderbuffer

- libsrc/sha1sums
broken by 1d6acae994a1bff8fec8b7401f78926ed64d4502
(I broke it by mistake in #2200)
> libsrc: fix shasum for SDL_sound

- Engine/script/cc_instance.cpp
- Engine/script/cc_instance.h
For the cc_instance where the script runner is, just general tidying it up
- adding const as needed
- using static_cast instead of c style cast where possible
- remove unused variables
> Engine: tidying up of script instance

- Engine/platform/android/acpland.cpp
- Engine/platform/ios/acplios.cpp
- Use FindFile class when searching for translations;
- Uniform DisplayAlert code.
- Use our Path functions when getting parent path.
- Add `const` to `char*` where makes sense.
Cannot test this on iOS myself.
On a side note, these likely could benefit from a MobilePlatform base class.
> Small fixes for Android and iOS

- CMake/FetchSDL_Sound.cmake
- Windows/README.md
- ci/linux/Dockerfile
- ci/windows/Dockerfile
- debian/README.md
- libsrc/download.sh
- libsrc/sha1sums
updates to https://github.com/icculus/SDL_sound/commit/c5639414c1bb24fb4eef5861c13adb42a4aab950
the added commits are mostly safety https://github.com/icculus/SDL_sound/compare/1507be95c3605e4fd6a48ea4c527e4aa711a1566...c5639414c1bb24fb4eef5861c13adb42a4aab950
> SDL_Sound: update version

- .gitignore
- iOS/README.md
- just put `iOS/Resource` dir on gitignore, in case additional files are added (like lipsync) to avoid commiting by accident.
- added a reminder on the Readme that the project doesn't come with neither Team (your development team or account) set or the bundle identifier set. 
I can't confirm in documentation, but I believe that the bundle identifier must be unique per Team. When trying to build the project along with @edmundito, I was having errors `"Failed to register bundle identifier"` and `"no profiles for uk.co.adventuregamestudio.iosgame"`, and after a few failures we concluded this - after using different bundle identifiers worked!
> iOS minor readme and gitignore additions

- Engine/gfx/gfxdriverbase.cpp
Noticed when SetVsync fails we log an uninitialized value, instead of the current Vsync.
> Engine: fix log of uninitialized value in gfx driver base

- Common/core/assetmanager.cpp
- Common/gfx/bitmap.cpp
- Common/test/stream_test.cpp
- Common/util/aasset_stream.cpp
- Common/util/aasset_stream.h
- Common/util/bufferedstream.cpp
- Common/util/bufferedstream.h
- Common/util/file.cpp
- Common/util/file.h
- Common/util/filestream.cpp
- Common/util/filestream.h
- Common/util/memorystream.cpp
- Common/util/memorystream.h
- Common/util/stream.h
- Engine/ac/dynobj/scriptfile.cpp
- Engine/ac/dynobj/scriptfile.h
- Engine/ac/file.cpp
- Engine/ac/file.h
- Engine/ac/global_dynamicsprite.cpp
- Engine/ac/global_file.cpp
- Engine/ac/global_file.h
- Engine/ac/global_game.cpp
- Engine/ac/path_helper.h
- Engine/debug/logfile.cpp
- Engine/platform/emscripten/acpemscripten.cpp
- Engine/plugin/agsplugin.cpp
- Engine/plugin/agsplugin.h
- Engine/script/cc_instance.cpp
This PR is following concerns stated in my comment to the previous IAGSStream pr here:
https://github.com/adventuregamestudio/ags/pull/2227#issuecomment-1850532997
summarized in a cleaner way in this PR draft:
https://github.com/adventuregamestudio/ags/pull/2256#issuecomment-1858997247
To put it simply, the primary goal is to make our IStream interface match IAGSStream (or other way around), and make our internal base Stream class work as a direct implementation of IAGSStream, and be able to pass Stream object to plugins, without an additional wrapper class. The purpose of this is to avoid extra wrappers over objects passed to plugins (and stream may be the first new object we expose, but there may be others in the future, such as sound player and decoder, etc). The wrappers like that …
> Update IAGSStream api, and use base Stream class as its direct implementation

- Engine/ac/dialog.cpp
- Engine/ac/display.cpp
- Engine/ac/display.h
- Engine/ac/drawingsurface.cpp
- Engine/ac/global_drawingsurface.cpp
- Engine/ac/global_gui.cpp
- Engine/ac/overlay.cpp
- Engine/ac/string.cpp
- Engine/ac/string.h
- Engine/gui/gui_engine.cpp
- Engine/gui/mylabel.cpp
- Engine/plugin/agsplugin.cpp
Fixes #2264.
The root of the problem was that parsing the voice token had been inside a utility function called `break_up_text_into_lines()`.
Having it called implicitly in such function makes it prone to mistakes. In couple of cases the parsing is already done much earlier.
As a side issue, remade the ugly GET_OPTIONS_HEIGHT macro into a DialogOptions::CalcOptionsHeight() method.
> Fix engine trying to parse voice-over token for the second time

- Editor/AGS.Editor/ColorThemes/Controls/ComboBoxCustom.cs
for #1919
Not the proper fix but it should at least prevent things from crashing.
> Editor: ensure themed combobox item index is valid

- Common/util/aasset_stream.cpp
- Common/util/aasset_stream.h
I've been doing adjustments in Stream classes lately, and while reading AAssetStream code noticed that OwnHandle and WrapHandle methods do not actually work, because the associated constructor does not assign a member pointer (and does not init few other members). I guess this was never used nor tested. So I refactored the class a little: picked out a method for opening AAsset pointer by name, and have Open/OpenSection methods take this pointer and "own" parameter. Then they may be called from that non-working constructor too.
Other than that, fixed couple of minor mistakes (minor in the sense that they would rarely be an issue in practice, but still):
* in Seek method "current offset" has to be remembered only after successful asset seek, and old pos kept if there was an error. At least …
> More fixes for AAssetStream

- Common/test/stream_test.cpp
- Common/util/datastream.cpp
- Common/util/datastream.h
- Engine/game/savegame.cpp
- Engine/game/savegame_components.cpp
- Engine/game/savegame_internal.h
- Engine/game/savegame_v321.cpp
- Engine/plugin/agsplugin.cpp
- Engine/plugin/plugin_engine.h
Because after #2227 plugins may get a seekable stream from the handle that engine passes to them for reading and writing saves,  there has to be some method for safeguarding their serialization by restricting to certain range of offsets. Technically this may be achieved by several means, one is to load their data in memory and give them a memory stream, another is to give them a proxy stream that serves as a "window" over the portion of the base stream. There won't be any difference from the save format's perspective, it's just an implementation choice.
In this PR I chose the latter method (a stream "window"), but it may be easily replaced with the former (reading and writing a memory buffer).
I also wish i did this in the new save format from the beginning, as this seems most logical …
> 3.6.1: safeguard plugin save reading and writing

- .cirrus.yml
this adds engine builds for Windows 64-bit using MSVC in the pipeline, and stores the built binaries in the CI (but don't release it), so someone can download from Cirrus and test it.
> CI: added acwin 64-bit builds

- Common/game/main_game_file.cpp
Hey, I think this is a typo, `LEGACY_MAX_CHAR_NAME_LEN` should really be `LEGACY_MAX_SCRIPT_NAME_LEN` here (they have different max sizes)
> Common: fix typo leads out of range memcpy

- Editor/AGS.Editor/DataFileWriter.cs
- Editor/AGS.Native/NativeMethods.cpp
Fix #2288
The '[' is still supported as a linebreak in 3.* branch, for backwards compatibility. If user wants to have literal '[' they have to escape it like '\\['. But recent change 432ae84 have introduced Unescape call for properties (in order to support '\n' etc). Unescape call removes backslashes in unrecognized sequences. So now we have to add this hack, escaping a backslash with another backslash, this will keep it intact.
> Editor: fix '\[' sequences lost in textual properties

- Editor/AGS.Native/NativeMethods.cpp
- Editor/AGS.Native/agsnative.cpp
Fix #2290.
When the "Crop sprite edges" operation is performed, Editor will update the respective sprites' import settings, such as OffsetX,Y, and ImportWidth,Height. This allows to correctly restore the cropped sprites from their source files.
**How to test**
Create a game using one of the standard templates. Go to character sprites, select multiple frames, do "Crop sprite edges". Notice how sprites became thinner. Save the project, then do either "replace sprites from sources" or "restore all sprites from sources". The cropped sprites must remain cropped.
You may compare this behavior with existing one, where the sprites will get restored to the previous size.
> Editor: save "Crop sprite edges" operation in sprite's import settings

- Common/ac/characterinfo.cpp
- Common/ac/characterinfo.h
- Common/ac/gamesetupstruct.cpp
- Common/ac/gamesetupstructbase.h
- Common/game/main_game_file.cpp
- Editor/AGS.Native/agsnative.cpp
- Engine/ac/character.cpp
- Engine/ac/characterinfo_engine.cpp
- Engine/ac/dynobj/cc_staticarray.h
- Engine/ac/global_audio.cpp
- Engine/ac/global_character.cpp
- Engine/ac/global_game.cpp
- Engine/ac/string.cpp
- Engine/game/game_init.cpp
- Engine/game/savegame_components.cpp
- Engine/main/game_run.cpp
Fix #2296
This fixes a mistake introduced in commit 4be1556, which in turn followed b02814b8bb3bb7a2cd00110466e2bd3047e772d1
The problem is, that CCStaticArray does not work as intended, and seems won't (at least not without some extra workarounds).
When the script compiler is told to get an Nth element of a global struct array, such as character[n], it calculates the memory address as
Character* ptr = (array address + sizeof(Character) * n).
If this address is used for the read/write operations, these ops can be intercepted by interpreter and remapped into the real fields (see IScriptObject::ReadN, WriteN interface). But if this address is used IN POINTER COMPARISON BY VALUE, then we cannot do anything. And if our real struct in the engine is stored on a different relative memory offset …
> Engine: fixed CharacterInfo breaking script compatibility again

- Engine/main/main.cpp
- Engine/platform/android/acpland.cpp
- Engine/platform/base/agsplatform_xdg_unix.cpp
- Engine/platform/base/agsplatform_xdg_unix.h
- Engine/platform/base/agsplatformdriver.cpp
- Engine/platform/base/agsplatformdriver.h
- Engine/platform/emscripten/acpemscripten.cpp
- Engine/platform/ios/acplios.cpp
- Engine/platform/osx/acplmac.cpp
- Engine/platform/windows/acplwin.cpp
- OPTIONS.md
Fix #2279
1. Implement general DisplayAlert logic in the base AGSPlatformDriver class. This method does 3 things: print to log, write to stdout and display message box, depending on current settings.
2. Add new method called DisplayMessageBox which purpose is strictly to display a message box if platform can do that. Platforms that cannot or should not may override this method, or override _guiMode variable.
3. Added a "dirty" fix for duplicate alert in stdout, which may appear because of passing the message to the log system. The platform class will store a pointer to a function that has to be called when printing a message. This pointer is assigned according to "_logToStdErr" setting. When printing, use this pointer instead of checking for the setting. This also lets setting this …
> Unify DisplayAlert in all platform classes

- CMake/FetchSDL_Sound.cmake
- OSX/README.md
- Script/push_sdlsound.py
- Windows/README.md
- version.json
I noticed that SDL_Sound's revision is changed by hand all the time, and some files already have different revisions mentioned (even multiple different ones in a single readme).
Added another python script for updating the revision number. This requires a new values group in version.json:
```
"sdlsound": {
"revision": "c5639414c1bb24fb4eef5861c13adb42a4aab950",
"urlHash": "d1037daa0e444efa8a09defaa1a6321f"
}
```
Affected files are hardcoded in the script, and may be amended as necessary. Currently they are:
* CMake/FetchSDL_Sound.cmake
* debian/README.md
* OSX/README.md
* Windows/README.md
---
The full script's work may be tested by inserting random values into json, and running "push_sdlsound.py".
> Add a script for updating SDL_Sound revision in readmes and cmake files

- Editor/AGS.Editor/Resources/agsdefns.sh
- Engine/ac/character.cpp
- Engine/ac/drawingsurface.cpp
- Engine/ac/game.cpp
- Engine/ac/game.h
- Engine/ac/gamestate.cpp
- Engine/ac/gamestate.h
- Engine/ac/global_api.cpp
- Engine/ac/global_game.cpp
- Engine/ac/global_game.h
- Engine/ac/listbox.cpp
- Engine/ac/listbox.h
- Engine/ac/runtime_defines.h
- Engine/gui/guidialog.cpp
- Engine/gui/guidialog.h
- Engine/main/game_run.cpp
- Engine/script/exports.cpp
- Engine/script/script.cpp
Historically FillSaveGameList has a hardcoded range of 0 to 99 slots, and for some reason also additionally limits total shown slots to 50 items, which normally means that it's limited to slots 0-50. This change lets user to tell which range of slots to fill, and removes item count limit, because it makes no sense anymore.
Same change is done to function RestoreGameDialog and SaveGameDialog. These are old, but may still be used sometimes, so I decided to still do this.
The new functions are declared as
```
/// Fills the list box with the current user's saved games in the given range of slots.
import int  FillSaveGameList(int min_slot = 0, int max_slot = 50);
import void RestoreGameDialog(int min_slot = 0, int max_slot = 50);
import void SaveGameDialog(int min_slot = 0, int max_slot = 50); …
```
> AGS 4: Script API: in FillSaveGameList() accept a range of slots

- Solutions/Tools.App/afg2dlgasc.vcxproj
- Solutions/Tools.App/agf2autoash.vcxproj
- Solutions/Tools.App/agf2glvar.vcxproj
- Solutions/Tools.App/agspak.vcxproj
- Solutions/Tools.App/agsunpak.vcxproj
- Solutions/Tools.App/crm2ash.vcxproj
- Solutions/Tools.App/crmpak.vcxproj
- Solutions/Tools.App/trac.vcxproj
The x64 build of the Tools using the vcxproj files were not working, this makes them build the same as the x86 builds - except they are x64 builds.
> Tools: fix vcxproj for x64 builds

- .gitignore
I am remaking the Editor x64 branch locally and going a bit crazy (switching branches cause it to forget my gitignore changes...) because I need to place the x64 irrKlang and stuff in `Editor/References` and I think all dll files there could just be ignored.
> gitignore: ignore dll files placed in References

- Common/ac/common.cpp
- Common/gui/guimain.cpp
- Common/gui/guimain.h
- Editor/Native/acfonts_agsnative.cpp
- Engine/ac/character.cpp
- Engine/ac/draw.cpp
- Engine/ac/game.cpp
- Engine/ac/room.cpp
- Engine/ac/sprite.cpp
- Engine/font/fonts_engine.cpp
- Engine/main/engine.cpp
- Engine/main/game_run.cpp
- Engine/main/game_start.cpp
- Engine/main/main.cpp
- Engine/main/quit.cpp
- Engine/main/update.cpp
- Engine/platform/windows/win_ex_handling.cpp
- Engine/script/script.cpp
Hey, just to make it easier to search our codebase when someone reports a `PP=X` in a crash / exception. There was a mix of SET_EIP, `our_eip=X` and `our_eip = X` (varying blank spaces). If all eip changes are guarded in a macro, it's much easier to find using the code search feature of an IDE or `git grep` in the command line.
I am letting it be a draft because the `SET_EIP` macro is in `"gui/guimain.h"` and perhaps it should be in somewhere else, but not sure where.
> Refactor `our_eip=X` to use `set_our_eip(X)` function

- Editor/AGS.Editor/Resources/agsdefns.sh
- Engine/CMakeLists.txt
- Engine/ac/dynobj/all_dynamicclasses.h
- Engine/ac/dynobj/cc_walkablearea.cpp
- Engine/ac/dynobj/cc_walkablearea.h
- Engine/ac/dynobj/cc_walkbehind.cpp
- Engine/ac/dynobj/cc_walkbehind.h
- Engine/ac/dynobj/scriptobjects.h
- Engine/ac/game.cpp
- Engine/ac/room.cpp
- Engine/ac/walkablearea.cpp
- Engine/ac/walkbehind.cpp
- Engine/game/game_init.cpp
- Engine/script/exports.cpp
- Solutions/Engine.App/Engine.App.vcxproj
- Solutions/Engine.App/Engine.App.vcxproj.filters
Converting walkable areas and walk-behinds script api to OO-style, in compliance with existing Hotspot, Regions etc api.
This adds two managed structs, and array properties in the Room struct for getting these.
```
builtin managed struct WalkableArea {
/// Gets the walkable area at the specified position on the screen.
import static WalkableArea* GetAtScreenXY(int x, int y);
/// Returns the walkable area at the specified position within this room.
import static WalkableArea* GetAtRoomXY(int x, int y);
/// Gets the drawing surface for the 8-bit walkable mask
import static DrawingSurface* GetDrawingSurface();
/// Changes this walkable area's scaling level.
import void SetScaling(int min, int max);
/// Gets the ID number for this area.
import readonly attribute int ID;
/// Gets/sets whether …
```
> AGS 4: Script API: convert Walk-areas and Walkbehinds API to OO-style

- Engine/gfx/ali3dogl.cpp
- Engine/gfx/gfxfilter_aaogl.cpp
- Engine/gfx/gfxfilter_ogl.cpp
- Engine/gfx/ogl_headers.h
This supposedly fixes occasional edge lines around sprites, occurring in "render in screen resolution" mode with Linear filter, and certain scaling factors.
A quote from Khronos specs, about a difference between GL_CLAMP and GL_CLAMP_TO_EDGE :
> GL normally clamps such that the texture coordinates are limited to exactly the range [0;1]. When a texture coordinate is clamped using this algorithm, the texture sampling filter straddles the edge of the texture image, taking half its sample values from within the texture image, and the other half from the texture border. It is sometimes desirable to clamp a texture without requiring a border, and without using the constant border color.
> <...> CLAMP_TO_EDGE, clamps texture coordinates at all mipmap levels such that the texture filter never …
> OpenGL: use GL_CLAMP_TO_EDGE with Linear filter

- .cirrus.yml
- Solutions/Compiler.App.sln
- Solutions/Compiler.App/Compiler.App.vcxproj
- Solutions/Compiler.Lib.sln
- Solutions/Compiler.Lib/Compiler.Lib.Test.vcxproj
- Solutions/Compiler.Lib/Compiler.Lib.vcxproj
- Solutions/Tests.App/Common.Lib.Test.vcxproj
- Solutions/Tests.App/Engine.App.Test.vcxproj
x64 builds of the Tests in Solutions weren't building, added missing macros and includes.
additionally, run the tests in the CI for x64 too.
> Solutions: fix Tests for x64 builds

- Engine/ac/draw.cpp
- Engine/gfx/ali3dogl.cpp
- Engine/gfx/ali3dogl.h
- Engine/gfx/ali3dsw.h
- Engine/gfx/graphicsdriver.h
- Engine/main/graphics_mode.cpp
- Engine/platform/windows/gfx/ali3dd3d.cpp
- Engine/platform/windows/gfx/ali3dd3d.h
Print available adapter info for Direct3D and OpenGL (this basically means GPU / system driver description).
Print approximate available video memory to the log.
For OpenGL: use ATI / Nvidia extensions if available to get their gpu memory info.
> Print graphics adapter info + OpenGL video memory detection

- Engine/CMakeLists.txt
- Engine/gfx/ali3dogl.cpp
- Engine/gfx/gfxdriverbase.h
- Engine/platform/windows/gfx/ali3dd3d.cpp
- Engine/script/cc_instance.cpp
- Engine/script/runtimescriptvalue.cpp
- Engine/script/runtimescriptvalue.h
- Engine/script/script_runtime.cpp
- Engine/script/script_runtime.h
- Solutions/Engine.App/Engine.App.vcxproj
I've been looking into a Dave Gilbert's problem with "out of mem" errors, and it turned out that the texture cache functionality is not behaving as I expected it to. The problem is that engine allocates system memory proportional to video memory allocation when caching textures. It feels as if there were a duplicate of each texture's surface in RAM. It might be that this is normal and I simply don't have enough theoretical knowledge about how textures are stored to judge; but it might also mean that we have something done wrong.
In any case, as an effect the total usage of system memory becomes approximately equal to the sum of sprite cache and texture cache.
Strictly speaking, if we have a large texture cache allocated, then we don't need spritecache at all. But that does not change the …
> Windows: enable /LARGEADDRESSAWARE for 32-bit builds

- .github/workflows/build.yml
I am separating ags3 and ags4 specific builds of the auto-test game, since the last release of the ags-test-games repository
https://github.com/adventuregamestudio/ags-test-games/releases
This is because ags4 and ags3 aren't binary compatible, so we would need to rebuild the test game with ags4 for ags4. I think it's easier to have two separate games, since ags4 has features that ags3 doesn't have, and ags3 has worries with backwards compatibility that ags4 doesn't have, so it's better to have room for the specific tests necessary for each.
This change should also make into 3.6.1 branch (better wait until this builds ok in the ci below).
> ci: use ags3 specific auto-test game

- .github/workflows/build.yml
ags4 specific variant of  #2335
It would be nice to get a new release of ags4 because I think the specifics of the global arrays (inventory, character, ...) changed.
> ci: use ags4 specific auto-test game

- Common/ac/gamesetupstruct.h
- Common/game/main_game_file.cpp
- Common/game/room_file.cpp
- Common/game/roomstruct.cpp
- Common/game/roomstruct.h
- Editor/AGS.Editor/AGSEditor.cs
- Editor/AGS.Editor/DataFileWriter.cs
- Editor/AGS.Editor/Resources/agsdefns.sh
- Editor/AGS.Native/agsnative.cpp
- Editor/AGS.Types/Room.cs
- Editor/AGS.Types/RoomWalkableArea.cs
- Editor/AGS.Types/Settings.cs
- Engine/ac/character.cpp
- Engine/ac/characterextras.cpp
- Engine/ac/characterextras.h
- Engine/ac/game.cpp
- Engine/ac/gamestate.cpp
- Engine/ac/gamestate.h
- Engine/ac/room.cpp
- Engine/ac/roomstatus.cpp
- Engine/ac/roomstatus.h
- Engine/ac/walkablearea.cpp
- Engine/game/savegame_components.cpp
- Engine/main/engine.cpp
- Engine/script/script_api.h
Resolves #2243
This implements new property called FaceDirectionRatio for Game, Room, WalkableArea and Character. This property affects selection of directional loop while Character moves and turns.
```
/// Gets/sets the default y/x ratio of character's facing directions, determining directional loop selection for all Characters in game.
static attribute float Game.FaceDirectionRatio;
/// Gets/sets the optional y/x ratio of character's facing directions, determining directional loop selection for each Character in the current room.
static attribute float Room.FaceDirectionRatio;
/// Gets/sets the optional y/x ratio of character's facing directions, determining directional loop selection for each Character while on this area.
static attribute float FaceDirectionRatio;
/// Gets/sets the …
```
> AGS 4: Script API: implement FaceDirectionRatio

- Emscripten/install_dependencies.sh
- ci/emscripten/Dockerfile
- This upgrades the Emscripten SDL2 port to 2.28.4
- We also need to upgrade node version because emscripten updated it
- Adjusted docker file for bug in `--lto` handing in embuilder in 3.1.55
> Emscripten: upgrade to 3.1.55

- Engine/CMakeLists.txt
- Engine/media/audio/audio_core.cpp
- Engine/media/audio/audio_core.h
- Engine/media/audio/audioplayer.cpp
- Engine/media/audio/audioplayer.h
- Engine/media/audio/sound.cpp
- Engine/media/audio/soundclip.cpp
- Engine/media/audio/soundclip.h
- Solutions/Engine.App/Engine.App.vcxproj
- Solutions/Engine.App/Engine.App.vcxproj.filters
The "audio core" system was implemented in 3.6.0, as a part of moving from Allegro 4 towards SDL-based utilities and a more convenient audio thread.
Although the original idea of "audio core" interface was to have everything behind the set of functions, in practice it proved to be rather annoying, as we had to have a duplicate function per each "audio player" action. This creates a mostly redundant layer of complexity.
But besides that, there's a technical issue: each "audio core" function's call locks the mutex, and sometimes we need to do several things at once. This means either call several functions with a lock/unlock pair in a succession, or write more cumbersome helper functions that do a number of things under one lock/unlock pair. If calling several functions, the state of the …
> Redesign audio core to return a locked AudioPlayer object instead of having a multitude of helper functions

- Engine/CMakeLists.txt
- Engine/ac/asset_helper.h
- Engine/ac/file.cpp
- Engine/ac/game.cpp
- Engine/ac/game.h
- Engine/ac/gamestate.h
- Engine/ac/global_game.cpp
- Engine/ac/global_video.cpp
- Engine/main/engine_setup.cpp
- Engine/main/game_run.cpp
- Engine/media/video/flic_player.cpp
- Engine/media/video/flic_player.h
- Engine/media/video/theora_player.cpp
- Engine/media/video/theora_player.h
- Engine/media/video/video.cpp
- Engine/media/video/video.h
- Engine/media/video/videoplayer.cpp
- Engine/media/video/videoplayer.h
- Solutions/Engine.App/Engine.App.vcxproj
- Solutions/Engine.App/Engine.App.vcxproj.filters
- libsrc/allegro/include/allegro/fli.h
- libsrc/allegro/src/fli.c
This is a limited backport from #2338, containing only improved VideoPlayer class, but no changes to script API, and no global working thread for non-blocking videos. Its main purpose is to keep code in branches at least somewhat consistent, but also make it easier to do improvements to video playback.
* Separated VideoPlayer and BlockingVideoPlayer classes, where VideoPlayer is a generic player, while BlockingVideoPlayer defines a game state which runs VideoPlayer in particular way.
* Turned BlockingVideoPlayer as another GameState implementation (complementary to the recent #2332).
* VideoPlayer now has buffer queue for video frames, supports both autoplay and manual frame-by-frame work modes.
* No actual working thread is implemented in this PR, but it may be done later, to improve …
> Separate VideoPlayer and BlockingVideoPlayer game state classes

- Android/README.md
- Android/library/runtime/src/main/res/values/strings.xml
- Android/library/runtime/src/main/res/xml/preferences.xml
- Android/misc/android.cfg
- Android/mygame/app/src/main/assets/android.cfg
- Editor/AGS.Editor/BuildTargets/BuildTargetAndroid.cs
- Engine/ac/draw.cpp
- Engine/ac/gamesetup.cpp
- Engine/ac/gamesetup.h
- Engine/gfx/ali3dogl.cpp
- Engine/gfx/ali3dogl.h
- Engine/gfx/ali3dsw.h
- Engine/gfx/graphicsdriver.h
- Engine/main/config.cpp
- Engine/platform/android/acpland.cpp
- Engine/platform/base/mobile_base.cpp
- Engine/platform/base/mobile_base.h
- Engine/platform/ios/acplios.cpp
- Engine/platform/windows/gfx/ali3dd3d.h
- OPTIONS.md
- iOS/README.md
- iOS/misc/ios.cfg
This "supersampling" setting comes from the original mobile port of AGS, but it's not clear whether it was useful. My understanding is that it increases resolution in which game sprites are drawn to a fixed multiplier of 2, but there's already is a "Render in screen resolution" setting that does the similar thing.
More importantly, there are issues with this:
1. It was never implemented in another hardware accelerated driver (Direct3D), being exclusive to OpenGL.
2. It was never added to standard setup, so not very visible.
3. It's not clear whether it was working properly all this time. There have been multiple changes to graphic renderers, and some of them may assume that rendering at "native resolution" is done at exactly, well, native resolution.
UPDATE:
Also removed unused "video" …
> 3.6.1: remove "supersampling" setting from OpenGL renderer

- Common/CMakeLists.txt
- Common/util/smart_ptr.h
- Engine/platform/windows/gfx/ali3dd3d.cpp
- Engine/platform/windows/gfx/ali3dd3d.h
- Solutions/Common.Lib/Common.Lib.vcxproj
- Solutions/Common.Lib/Common.Lib.vcxproj.filters
Resolves #2343.
An automatically releasing pointer for IDirect3D objects.
> Implemented a RAII wrapper over IUnknown, for Direct3D

- Editor/AGS.Editor/Resources/agsdefns.sh
- Engine/CMakeLists.txt
- Engine/ac/dynobj/scriptvideoplayer.cpp
- Engine/ac/dynobj/scriptvideoplayer.h
- Engine/ac/global_video.cpp
- Engine/ac/timer.cpp
- Engine/ac/video_script.cpp
- Engine/main/engine_setup.cpp
- Engine/main/game_run.cpp
- Engine/media/audio/audio.cpp
- Engine/media/audio/audio_core.cpp
- Engine/media/audio/audio_core.h
- Engine/media/audio/soundclip.cpp
- Engine/media/audio/soundclip.h
- Engine/media/video/theora_player.h
- Engine/media/video/video.cpp
- Engine/media/video/video.h
- Engine/media/video/video_core.cpp
- Engine/media/video/video_core.h
- Engine/media/video/videoplayer.cpp
- Engine/media/video/videoplayer.h
- Engine/script/exports.cpp
- Engine/script/script_api.h
- Engine/util/threading.h
- Solutions/Engine.App/Engine.App.vcxproj
- Solutions/Engine.App/Engine.App.vcxproj.filters
For #2155.
This is not a complete functionality, but a draft, meant to test out the idea. Random mistakes are to be expected.
1. Rewrote VideoPlayer class, so that it buffers video frames and prepares a "ready frame" when the time is right, but does not draw anything itself. The plan for the VideoPlayer is that it can work in 2 modes: autoplay and frame-by-frame mode. In the first mode it calculates timing when the next frame should be presented, and switches the "ready frame". In the frame-by-frame mode it will be in paused state but advance to next frame by a call to NextFrame(). Audio is not played in the frame-by-frame mode.
2. Picked out BlockingVideoPlayer class which is basically a "game state" singleton that runs VideoPlayer, blocking the rest of the game. This is used for the old …
> AGS 4: non-blocking video playback

- Editor/AGS.Editor/Components/RoomsComponent.cs
- Editor/AGS.Editor/Panes/Room/RoomEditFilters/CharactersEditorFilter.cs
- Editor/AGS.Editor/Panes/Room/RoomEditFilters/ObjectsEditorFilter.cs
- Editor/AGS.Editor/Utils/Utilities.cs
- Editor/AGS.Native/NativeRoom.cpp
- Preserve bit depth from crm to new room format
- Preserve bit depth for imported room background
- Fixes error in displaying object/characters in the room editor
Related to #2349 and #2218
This PR is missing the palette remapping for 8bit mode, I see there's a TODO comment that the feature was meant to be reimplemented but it was not done yet. Perhaps I'll look into it next.
> AGS4: 8bit fixes

- Common/ac/gamesetupstructbase.cpp
- Common/ac/gamestructdefines.h
- Editor/AGS.Editor/Resources/agsdefns.sh
- Editor/AGS.Types/Enums/ScriptAPIVersion.cs
- Engine/ac/system.cpp
- Engine/ac/system.h
This implements two script functions: System.GetEngineInteger() and System.GetEngineString(), which return some runtime engine parameter by its ID (and an optional index).
The idea of this is to be able to get a number of predefined types of parameters from the engine in script, meant mainly for diagnostic purposes (logging, debugging, performance testing, etc). Because this purpose is not related to a game's logic, I believe that it does not make sense to litter script API with properties, but instead have just a couple of functions that return a value by id.
This is sort of inspired by similar cases in some popular APIs, such as OpenGL, OpenAL, and some others.
The reasons why I did not want to use strings as IDs is that the list of value IDs for those functions will likely be …
> Script API: implement System.GetEngineInteger() and GetEngineString()

- Editor/AGS.Editor/Components/BaseComponentWithScripts.cs
- Editor/AGS.Editor/Components/RoomsComponent.cs
- Editor/AGS.Editor/Entities/EditorPreferences.cs
- Editor/AGS.Editor/GUI/GUIController.cs
- Editor/AGS.Editor/GUI/PreferencesEditor.cs
- Editor/AGS.Editor/GUI/frmMain.cs
- Editor/AGS.Editor/Panes/ScriptEditor.cs
fix #1066 
~~I didn't add the icon as requested, it would be good to disambiguate between room and script, but I didn't want to deal with ALL possible tabs.~~ Welp, turns out someone already did that in the past, added a way to turn it on.
It also looked interesting to have some method to deal with the tab name, that could perhaps be overriden in some way, but I didn't figure a common place to them.
Please evaluate.
> Editor: add room description in tab name

- Editor/AGS.Editor/AGSEditor.csproj
- Editor/AGS.Editor/Components/ScriptsComponent.cs
- Editor/AGS.Editor/Entities/ExistingFileToAdd.cs
- Editor/AGS.Editor/Entities/ExistingScriptHeaderToAdd.cs
- Editor/AGS.Editor/Entities/ScriptModuleDef.cs
- Editor/AGS.Editor/GUI/GUIController.cs
- Editor/AGS.Editor/ImportExport.cs
- Editor/AGS.Editor/Utils/ScriptFileUtilities.cs
- Editor/AGS.Editor/Utils/Utilities.cs
fix #589
This took way more lines of code than I thought it would. I broke things down in multiple steps and when I went to implement there was a lot that I thought would be written that just wasn't.
<details><summary>Hidden completed checklist because it's not as relevant now!</summary>
- I think I can't figure the encoding from the file itself, so I am using the one set in the project.
- ~Are special characters in file names allowed? (Specifically basename)~ I think the filesystem already took care of this
~~Leaving as a draft until I can test a bit more.~~ 
</details>
Tested and it appears to work alright!
> Editor: add feature add existing ash/asc files

- Editor/AGS.Editor/AGSEditor.csproj
- Editor/AGS.Editor/Components/BaseComponentWithFolders.cs
- Editor/AGS.Editor/GUI/LineInBetween.cs
- Editor/AGS.Editor/GUI/ProjectTree.cs
- Editor/AGS.Editor/GUI/ProjectTreeItem.cs
- Editor/AGS.Types/AGS.Types.csproj
- Editor/AGS.Types/Enums/TargetDropZone.cs
Edit: I copied the things I haven't checked yet to the bottom of this.
fix #1526 
Please test this, also any tips on the things that are problematic let me know.
**NOTE:** This won't fix moving _items_ BETWEEN _folders_. This would require much bigger changes. TBH, I don't even think this is a good idea.
I think the commits would be better if they all got squashed in a single commit, but leaving as is currently. In the PR the files changed tab can show the changes squashed.
https://github.com/adventuregamestudio/ags/assets/2244442/9ac7f6fe-ab3c-4ae8-a768-3dba963114c4
- My own feeling is that this makes dragging and dropping a bit finnicky, because the nodes are very small, the tree nodes could be made slightly bigger in height, I think it would work better for this interaction.
- There is …
> Editor: move folders between folders and move item downwards in Project Explorer

- Editor/AGS.Editor/AGSEditor.csproj
- Editor/AGS.Editor/Panes/Room/RoomEditFilters/BaseThingEditorFilter.cs
- Editor/AGS.Editor/Panes/Room/RoomEditFilters/CharactersEditorFilter.cs
- Editor/AGS.Editor/Panes/Room/RoomEditFilters/HotspotsEditorFilter.cs
- Editor/AGS.Editor/Panes/Room/RoomEditFilters/IRoomEditorFilter.cs
- Editor/AGS.Editor/Panes/Room/RoomEditFilters/ObjectsEditorFilter.cs
Resolves #2230
Introduces BaseThingEditorFilter<TThing>, a generic parent class for room filters which handle "things": objects which have precise coordinates and are drawn individually.
Picks out much of the shared code out from ObjectsEditorFilter and CharactersEditorFilter classes.
Although BaseThingEditorFilter is generic, it cannot access actual object properties, because, unfortunately, Character and RoomObject do not have a base class which would share common properties... This is why when there's a need to get something out of them, such as position or a script name, it has to call a virtual method to let child class handle this.
This does not have to be seen as a "final" implementation; as interfaces are not modified, and all classes are internal to the editor, these classes may …
> Editor: create a parent class for Object and Character room filters

- Editor/AGS.Editor/Panes/ScintillaWrapper.cs
fix #2323
The issue here is if foldExplicitStart is empty it is defined as `"//{"`  and foldExplicitEnd it is defined as `"//}"`.
This causes the confusing behavior that if foldCommentExplicit  is true, the scintilla cpp lexxer can fold in comments following the previously defined start and terminator string. We are setting it to false to disable this unexpected behavior.
> Editor: fix script editor fold in comment in scintilla lexxer

- Editor/AGS.Editor/Panes/WelcomePane.Designer.cs
- Editor/AGS.Editor/Panes/WelcomePane.cs
Allow scaling of the Welcome Pane, this is step 1/7, partial of #2087
I plan to work on each pane slowly when I find time, in separate PRs, also because these panes have lots of specific details, I think it's better to work them one by one.
<details>
<summary>Editor at 125% scaling</summary>
</details>
<details>
<summary>Editor at 200% scaling</summary>
</details>
To test this PR I recommend editing the `Editor/AGS.Editor/app.manifest` and uncommenting the dpi aware setting (lines 52 to 58).
> Editor: fix welcome pane scaling under dpiaware

- Common/ac/gamestructdefines.h
- Engine/ac/draw.cpp
- Engine/ac/dynamicsprite.cpp
- Engine/ac/gamestate.h
The previous attempt, using a boolean `spritemodified` array, proved to be having logical loopholes. In simple words, because `spritemodified` flag was resetting each draw pass, it won't affect objects that are temporarily not visible, and they failed to reupdate when becoming visible again. This affected Software renderer.
Texture-based renderers have a different problem, where they fail to recognize when an old sprite was deleted and a completely new dynamic sprite created accidentally with the same ID. The cause was simply that the check for this is done inside sync_object_texture(), but sync_object_texture itself is not called unless draw() function thought that object had changed. So there has to be a check outside too...
Here I decided to reimplement notification mechanism, and use …
> 3.6.1: rewrote dynamic sprite to texture notification mechanism

- Common/game/main_game_file.cpp
Zak McKraken 2 is game version 2.55 and uses the ags flashlight plugin. using this patch it successfully parses the plugin data.
https://www.maniac-mansion-mania.com/index.php/en/resources-mainmenu-76/downloads/episoden/fanadventures/95-the-new-adventures-of-zak-mckracken/file.html
> call ReadPlugin already with version 2.55

- Common/libinclude/ogg/config_types.h
u_int_32t is not a standard type, it's from legacy sys/types.h and mixed in here with stdint.h types. fix it by also using stdint.h type instead.
> fix build error with musl libc

- Common/gui/guimain.cpp
- Common/gui/guimain.h
- Editor/AGS.Editor/NativeProxy.cs
- Editor/AGS.Editor/Panes/GUIEditor.Designer.cs
- Editor/AGS.Editor/Panes/GUIEditor.cs
- Editor/AGS.Native/NativeMethods.cpp
- Editor/AGS.Native/NativeMethods.h
- Editor/AGS.Native/agsnative.cpp
Resolves #2379.
Adds a "Controls transparency" slider to the GUI Editor, lets draw controls in semi-transparent way or hide them completely.
> Editor: implement "Controls transparency" slider in GUI Editor

- Common/font/agsfontrenderer.h
- Common/font/fonts.cpp
- Common/font/fonts.h
- Common/font/ttffontrenderer.cpp
- Common/font/ttffontrenderer.h
- Common/font/wfnfontrenderer.cpp
- Common/font/wfnfontrenderer.h
- Common/gui/guimain.cpp
- Common/libsrc/alfont-2.0.9/alfont.c
- Common/libsrc/alfont-2.0.9/alfont.h
- Editor/AGS.Native/NativeMethods.cpp
- Engine/ac/display.cpp
- Engine/ac/draw.cpp
This is an attempt to fix certain fonts getting "cut off" from the top when being drawn on a limited size texture or bitmap, such as Labels (when run with texture-based renderer - Direct3D / OpenGL).
The reason for such behavior is that fonts may include glyphs which topmost extent is higher than the reported "ascender". In this case the engine simply does not know that glyphs may be drawn higher, and the prepared texture is not accommodated for that.
**Example font(s)**
[Pixel-Noir Skinny Short.zip](https://github.com/adventuregamestudio/ags/files/15044400/Pixel-Noir.Skinny.Short.zip)
**How we fix this:**
1. Following a caller's instruction (a new flag ALFONT_FLG_PRECALC_MAX_CBOX), alfont preloads all glyphs one by one and records the maximal extents of their "control boxes". These …
> Calculate real TTF glyphs extent, fix fonts cut from the top

- Editor/AGS.Editor/ColorThemes/ColorThemes.cs
- Editor/AGS.Editor/Panes/SpriteSelector.cs
- Editor/AGS.Editor/Tasks.cs
I think everywhere we start a new process from the Editor the process doesn't need a shell, as we aren't using commands from those, so it should be alright to set `UseShellExecute` to false in all of them.
I have a guess that this would not cause the Defender to trigger in this specific case reported in the forums : https://www.adventuregamestudio.co.uk/forums/beginners-technical-questions/ags-3-6-0-crashing-when-i-hit-f5-to-launch-the-game/msg636662661/#msg636662661
> Editor: no need to use shell in our started process

- Common/util/wgt2allg.cpp
- Common/util/wgt2allg.h
- Editor/AGS.Editor/AGSEditor.csproj
- Editor/AGS.Editor/Components/RoomsComponent.cs
- Editor/AGS.Editor/NativeProxy.cs
- Editor/AGS.Editor/Panes/PaletteEditor.cs
- Editor/AGS.Editor/Panes/Room/RoomSettingsEditor.cs
- Editor/AGS.Editor/Utils/BitmapExtensions.cs
- Editor/AGS.Editor/Utils/PaletteUtilities.cs
- Editor/AGS.Native/NativeMethods.cpp
- Editor/AGS.Native/NativeMethods.h
- Editor/AGS.Native/NativeRoom.cpp
- Editor/AGS.Native/NativeRoom.h
- Editor/AGS.Native/agsnative.cpp
- Editor/AGS.Types/Enums/PaletteColourType.cs
Fixes #2218
Reimplemented palette remap on the managed side, where it is applied to the Bitmaps as they are imported to the room.
Confirmed that backgrounds now look in the Editor as they should after remap (compared with ags3 branch), and look the same in the Engine.
Introduced a separate Palette in RoomComponent, which merges default palette from Game, and palette from the last imported primary background (index 0). This prevents Game's palette from being modified by room bgs.
Make sure the native palette is also synchronized when a primary room background is imported or reloaded. Native-side palette is still used when importing 8-bit sprites.
NOTES:
* couple of first commits in AGS.Native is a small code cleanup, to help myself understand the meaning of function arguments.
> AGS 4.0: Fix room background import in 8-bit games

- Engine/ac/string.cpp
- libsrc/allegro/include/allegro/unicode.h
- libsrc/allegro/src/unicode.c
Somehow this problem was ignored after all these years (even though the String API was updated with Unicode support).
The implementation of script function String.Replace was limiting resulting string to 2048 bytes, and furthermore used that buffer without any size checks. This may potentially lead to a buffer overflow and memory corruption.
NOTE: buffer limit has been 3000 originally, but reduced to 2048 in the latest master branch.
Example test case:
```
function TestLongReplace()
{
String source = "REPLACE THIS BIT"; // test replace in the beginning
while (source.Length < 4096)
{
source = source.Append("xxxxxxxxxxxxxxxx REPLACE THIS BIT xxxxxxxxxxxxxxxx");
}
source = source.Append("REPLACE THIS BIT"); // test replace in the end
String dest1 = source.Replace("REPLACE THIS BIT", "THIS IS …
```
> 3.6.1: fix unsafe buffer use in String.Replace and removed result limit of 2048 bytes

- Common/util/utf8.h
- Editor/AGS.Editor/Resources/agsdefns.sh
- Engine/ac/string.cpp
There is always a time where I need to use this when reading from a custom file, I have it done in AGS Script, but it really should be right there in the String itself, as it exists in Javascript, C# and all other languages I use.
An example of place where I would like to use this would be in something like [dicttoini](https://github.com/ericoporto/dont-give-up-the-cat/blob/main/dont-give-up-the-cat/dicttoini.asc).
Edit: had to push force minor [utf-8 proper fix](https://github.com/adventuregamestudio/ags/compare/67557870484852e26e7367f04aceb6b098eee0e6..3549ae856845ad58395519e6b1960cb5066476b5).
> ags4: add string trim (remove trailing and leading whitespace in string)

- Common/util/string_compat.h
- Engine/ac/string.cpp
Various implementations of libc may have non-standard overloads of `strstr`, making it impossible to use static_cast or reinterpret_cast with them directly (either would work with one libc, but may fail with another).
Experiment to see which approach may work here.
> Hotfix function pointer assignment in String_Replace independent of libc

- Common/util/string_compat.c
- Common/util/string_compat.h
- Engine/ac/string.cpp
Another attempt on this...
Trying to make it work across different implementations of libc, including ones with non-standard overloads.
Declare a C standard compatible variant of strstr in our string_compat file, and assign that to a pointer instead.
> (2) Hotfix function pointer assignment in String_Replace independent of libc 

- Engine/ac/character.cpp
- Engine/ac/display.cpp
- Engine/ac/display.h
- Engine/ac/draw.cpp
- Engine/ac/global_character.cpp
- Engine/ac/overlay.cpp
- Engine/ac/overlay.h
- Engine/ac/runtime_defines.h
- Engine/ac/screenoverlay.cpp
- Engine/ac/screenoverlay.h
- Engine/main/game_run.cpp
- Engine/main/update.cpp
This fixes #1180 for AGS 4. Initially I had a deeper reimplementation in mind for ags4, where not overlays keep links to characters, but characters have a link to their speech overlays, but then decided to step back for a simpler one for a time being.
I also think that this is safe to be backported to ags3, as this is really a bug fix, does not modify a save format; and the only thing different will be returned property values, which may be wrapped in a "script api" check. But I'll look into that separately.
---
The purpose of this change is to have x,y parameters of ScreenOverlay to contain explicit coordinates at all times, and use coordinates strictly depending on the Overlay's layer (screen or room).
Historically, non-blocking character speech overlays stored a magic OVR_AUTOPLACE …
> 4.0: Overlays always store their explicit position, reimplemented autopositioning

- Engine/ac/gamesetup.h
- Engine/game/game_init.cpp
- Engine/main/config.cpp
- Engine/main/main.cpp
- Engine/plugin/agsplugin.cpp
- Engine/plugin/plugin_engine.h
- Engine/plugin/plugin_stubs.cpp
- OPTIONS.md
Add `--no-plugins` command line argument, and related config setting, which tells to **not** load plugins from dynamic libraries.
Built-in plugins and stubs are still going to be used in this case (if they are available).
This may be used to either force engine to use built-in plugins, or as a safety measure to run engine without loading any extra binary.
> Implement `--no-plugins` command arg and config setting

- Compiler/preproc/preprocessor.cpp
- Compiler/preproc/preprocessor.h
- Compiler/test/preprocessor_test.cpp
- Editor/AGS.Editor.Tests/ScriptCompiler/PreprocessorTests.cs
This PR is targeting master branch but it is actually useful in ags4 and part of #2328 as it enables building the preprocessor with both the legacy compiler but also the new ags4 compiler.
- is_digit and is_alphanum are replaced by standard functions
- Fixes preprocessor not properly picking up escaped characters
- the preprocessor also needs the `NEW_SCRIPT_TOKEN_PREFIX` from that header.
With these changes I can build the preprocessor independently of the compiler.
> Compiler: preprocessor can build without compiler

- Common/ac/gamesetupstructbase.h
- Common/script/cc_internal.h
- Common/script/cc_script.cpp
- Common/script/cc_script.h
- Common/util/string_utils.cpp
- Common/util/string_utils.h
- Compiler/script/cc_compiledscript.cpp
- Compiler/script/cc_compiledscript.h
- Compiler/script/cs_compiler.cpp
- Compiler/script/cs_parser.cpp
- Compiler/script/cs_parser_common.h
- Compiler/test/cs_parser_test.cpp
- Editor/AGS.Native/Scripting.h
- Engine/script/cc_instance.cpp
A variant of #2411 for ags3 branch.
This replaces C arrays in ccScript class, and all the related reallocation code, with std containers: std::vectors and std::strings.
A care had to be taken when fixing parsers, as AGS script's bytecode is based on int32 values for historical reasons.
Because of that I had to introduce a helper function codesize_i32() which lets to clearly state the purpose of using "current code size" in assignment to int32 variables.
NOTE: I backported a change (1f38e662fe5aa30a6eda69fd375cc5a359cde23e) that reverted to only doing compiled script writing in C++ code (as opposed to C#), because it's very inconvenient to have two versions of this code. I suppose eventually we will be using standalone compiler(s) instead anyway.
> AGS 3: replace C arrays in ccScript with std containers

- Common/gfx/bitmap.cpp
- Common/gfx/bitmap.h
- Editor/AGS.Editor/Panes/Room/RoomEditFilters/BaseAreasEditorFilter.cs
- Editor/AGS.Native/agsnative.cpp
Fixes #2416
Implemented a conversion from imported 4-bit bitmaps into 8-bit ones supported by the Editor & Engine.
There were 2 potential approaches here, one is to convert on C# side, another in the native C++ side.
I chose to do this in native, and have a helper function in Common lib, to make this potentially usable in the engine. For example, this may be used when loading an image from file.
> Support importing 4-bit bitmaps as 8-bit (for masks and sprites)

- Editor/AGS.Editor/AGSEditor.csproj
- Editor/AGS.Editor/Panes/Room/RoomEditFilters/BaseAreasEditorFilter.cs
- Editor/AGS.Editor/Panes/Room/RoomSettingsEditor.cs
- Editor/AGS.Editor/Utils/BitmapExtensions.cs
- Editor/AGS.Types/Constants.cs
This ports minimal necessary code from AGS 4 to AGS 3, letting users to import indexed PNGs (of any palette size) as 8-bit room backgrounds and masks.
I am not certain why this was never added to ags3 branch, perhaps simply forgotten. I think this was addressed for ags4 in issues #1771 and #1772.
I copied only minimal necessary code from BitmapExtensions class, and it seems that, combined with the recent support for small palette image import, this allows to import any indexed PNGs as room bgs and masks.
> Backport importing indexed PNGs as room backgrounds and masks (AGS 4 -> AGS 3)

- Editor/AGS.Controls/AGS.Controls.csproj
- Editor/AGS.Controls/AdressBarEx/AddressBarExt.cs
- Editor/AGS.Controls/Controls/ToolStripDropDownMenuEx.cs
- Editor/AGS.Editor/Panes/Room/RoomSettingsEditor.cs
Fix #2415
Wrote a ToolStripDropDownMenuEx class which extends ToolStripDropDownMenu and amends or overrides its behavior.
Unfortunately had to use various hacks, including getting internal base methods using reflection.
WHAT IS DONE:
* Scroll dropdown menu with mouse wheel.
* Allow to change arrow buttons height to a bigger value.
* Set dropdown height is at least as big to accommodate 16 items at once, that is current max number of walkable areas, etc.
~* Don't close the open dropdown menu when hovering over other items in the Address Bar.~
EDIT: this fix is temporarily removed, because it turned to be not reliable and causing new problems.
> Improve Room Editor's navigation bar's scrolling

- Engine/debug/debug.cpp
- Engine/platform/base/agsplatform_xdg_unix.cpp
- Engine/platform/base/agsplatform_xdg_unix.h
- Engine/platform/base/agsplatformdriver.h
- Engine/platform/windows/acplwin.cpp
Fix #2437
There are platforms where this behavior is not suitable even for a Debug game build, because writing to current working dir will modify the game bundle, causing reaction from the operating system or app store. Introduce a IsLocalDirRestricted() method to the platform driver class, use it when "warnings.log" is created to know whether we are allowed to write it into cwd, or should be using a safer user dir.
For the time being, do not impose this restriction on Windows and Linux.
NOTE: this is a temporary hotfix. For the proper solution we'd need to revise "warnings.log" feature and possibly use config settings instead.
> Engine: hotfix certain platforms to not save "warnings.log" in current working dir

- Common/gfx/gfx_def.h
- Common/gui/guimain.cpp
- Common/gui/guimain.h
- Editor/AGS.Editor/Resources/agsdefns.sh
- Engine/ac/draw.cpp
- Engine/ac/global_inventoryitem.cpp
- Engine/ac/global_inventoryitem.h
- Engine/ac/gui.cpp
- Engine/ac/gui.h
- Engine/ac/invwindow.cpp
- Engine/main/game_run.cpp
Implements script API for GUI scaling. Set as draft for now, in case API receives any criticism.
Adds:
* GUI.ScaleX,
* GUI.ScaleY,
* GUI.SetScale(x,y),
* GUI.GUIToScreenPoint(int guix, int guiy, bool clipToGUI),
* ScreenToGUIPoint(int screenx, int screeny, bool clipToGUI)
All scale values are set in floats, and used as direct scaling factors, which means that
```
final_width = gui.Width * gui.ScaleX;
final_height = gui.Height * gui.ScaleY;
```
Scaled object's image shifts relative to object's "origin". In case of GUI that's **top-left corner**. If user wants to have scaling relative to GUI's center, they will have to adjust X,Y position as well.
Negative values are *allowed* and result in mirrored image. That's not "intentional", it just works this way... If this seems redundant, it's …
> AGS 4: Add GUI.ScaleX, ScaleY and SetScale(x,y)

- Engine/ac/parser.cpp
Parser should exclusively use is_valid_word_char to check for word boundaries (affects dash and apostrophe containing words).
> Engine: fix check for word boundaries in the parser

- Editor/AGS.Editor/GUI/BusyDialog.Designer.cs
- Editor/AGS.Editor/GUI/BusyDialog.resx
Fixing something that bothered me for the longest time. When the game builds and the BusyDialog appears, the user can hover over the progress indicator, and the background will slightly change color. The reason behind this is that the indicator is a hacked button.
What I did to solve it was tor set the background for click/hover to transparent. Additionally, I removed a tab index and disabled validation since it's not needed.
Before - note that the screenshot does not include the mouse cursor, but it's placed over the progress indicator:
> Editor: Fix properties for properties indicator in BusyDialog

- Editor/AGS.Editor/Panes/ScintillaWrapper.cs
- Editor/AGS.Editor/Panes/ScriptEditor.cs
- Editor/AGS.Editor/Panes/ScriptEditorBase.cs
The change contains several improvements to the context menu and the Edit menu for the script editor:
1. Context menu items display the shortcut keys next to them (e.g., Copy shows Ctrl+C)
2. Added new shortcut keys for Go To Definition, Find All Usages, and Go To Sprite (based on Visual Studio conventions)
3. Added those options to the Edit menu
4. Code cleanup
(My Windows is in Spanish. Mayús. = Shift)
> Editor: Add shortcut keys for context menu items and Go to Definition, Find All Usages, Go to Sprite, and dd items to Edit menu

- Editor/AGS.Editor/Tasks.cs
- Engine/ac/dynobj/cc_character.cpp
- Engine/ac/dynobj/cc_dialog.cpp
- Engine/ac/dynobj/cc_gui.cpp
- Engine/ac/dynobj/cc_guiobject.cpp
- Engine/ac/dynobj/cc_hotspot.cpp
- Engine/ac/dynobj/cc_inventory.cpp
- Engine/ac/dynobj/cc_object.cpp
- Engine/ac/gui.cpp
- Engine/ac/gui.h
- Engine/ac/room.cpp
- Engine/game/game_init.cpp
- Engine/game/savegame.cpp
This change affects GUIs, Inventory Items, Dialogs and Characters
These elements are imported using their direct raw memory references instead of handles but they are used in script as pointers, this change modifies the header generation to actually use pointers and also registers to them their handles.
This change can be visible when using the Watch Variable feature as the handle will show up there. I am leaving this as draft because I am not sure yet of the consequences of  this change.
> Editor,Engine: declare game object imports as pointers

- Editor/AGS.Editor/Tasks.cs
- Engine/game/game_init.cpp
Continuing from https://github.com/adventuregamestudio/ags/pull/2453#issuecomment-2203865445
I am leaving as a draft for now because I am trying to figure if something has to change in `Game.AudioClips[i]` script interface
https://github.com/adventuregamestudio/ags/blob/4d5d29e87e4f00aa800dd18a66e2219cf92f84b8/Engine/ac/game.cpp#L778-L783
and
https://github.com/adventuregamestudio/ags/blob/4d5d29e87e4f00aa800dd18a66e2219cf92f84b8/Editor/AGS.Editor/Resources/agsdefns.sh#L2473
The reason I ask is because I noticed it returns a pointer to `ScriptAudioClip` and wasn't sure if it would be the same.
> [ags4] Adjust Audio Clips imports to use handles

- Common/ac/characterinfo.h
- Common/ac/game_version.h
- Common/ac/gamestructdefines.h
- Common/game/main_game_file.cpp
- Editor/AGS.Editor/AGSEditor.cs
- Editor/AGS.Editor/DataFileWriter.cs
- Editor/AGS.Editor/Resources/agsdefns.sh
- Editor/AGS.Editor/Utils/NativeConstants.cs
- Editor/AGS.Native/NativeMethods.cpp
- Editor/AGS.Native/agsnative.cpp
- Editor/AGS.Types/Character.cs
- Engine/ac/character.cpp
Following user's request, this adds a individual Character.TurnWhenFacing, complementing Character.TurnBeforeWalking and a global "Characters turn to face direction" (called internally "TurnBeforeFacing" by oversight, it seems) property from General Settings.
For consistency with "turn before walking", character only turns on spot when *both* global and this character's TurnWhenFacing setting is enabled.
> Add TurnWhenFacing character property (design-time and in script)

- Common/ac/spritecache.cpp
- Common/ac/spritefile.cpp
- Common/ac/spritefile.h
- Common/gfx/gfx_def.h
- Editor/AGS.Editor.Tests/Types/SpriteTests.cs
- Editor/AGS.Editor/AGSEditor.cs
- Editor/AGS.Editor/AGSEditorController.cs
- Editor/AGS.Editor/NativeProxy.cs
- Editor/AGS.Editor/Panes/SpriteImportWindow.Designer.cs
- Editor/AGS.Editor/Panes/SpriteImportWindow.cs
- Editor/AGS.Editor/Panes/SpriteSelector.cs
- Editor/AGS.Editor/Utils/BitmapExtensions.cs
- Editor/AGS.Editor/Utils/SpriteTools.cs
- Editor/AGS.Native/NativeMethods.cpp
- Editor/AGS.Native/NativeMethods.h
- Editor/AGS.Native/agsnative.cpp
- Editor/AGS.Types/AGS.Types.csproj
- Editor/AGS.Types/Enums/SpriteImportColorDepth.cs
- Editor/AGS.Types/Sprite.cs
- Engine/gfx/ddb.h
- Engine/gfx/gfxdefines.h
- Engine/main/graphics_mode.h
This complements #2455.
Adds a combobox to the "Import Sprite" window that lets select whether to import the sprite, converting to game's default color depth (default choice), or import as a 8-bit image. This list may potentially be expanded, if necessary.
The choices are currently named:
* "In Game Color Depth"
* "As 8-bit image"
At first I wanted the second option to be displayed only if the imported image is of indexed pixel format, but this may be complicated to do, as multiple different files may be selected at once.
Removed "Import alpha channel" option, as redundant.
Other things...
Sprite index file now stores additional array of bytes, defining sprite's color depth. This is to let know the sprite's color depth without loading it up.
---
**NOTE:** for testing 8-bit sprites as …
> AGS 4: allow to import sprites as 8-bit image regardless of game color depth

- Editor/AGS.Editor/Components/FileCommandsComponent.cs
- Editor/AGS.Editor/GUI/GUIController.cs
- Editor/AGS.Editor/GUI/MainMenuManager.cs
- Editor/AGS.Types/EditorFeatures/MenuCommand.cs
This is the minimal amount of code I could think that give support to submenus. The other approach would be to make the property read-only and then make so you can only pass such list in Constructor - which would make it more similar to the other properties.
I noticed the following todo:
```
// TODO: I do not see any way to schedule sub-menus in this system!?
// but if it's supported, maybe put these 2 global messages commands int a submenu
```
Decided to try to fix it. Not sure on the name of the group as "Global Messages upgrade".
> Editor: add support for sub items in file menu and move global messages upgrade actions to submenu

- Editor/AGS.Editor/AGSEditor.csproj
- Editor/AGS.Editor/Components/FileCommandsComponent.cs
- Editor/AGS.Editor/Entities/EditorPreferences.cs
- Editor/AGS.Editor/GUI/GUIController.cs
- Editor/AGS.Editor/GUI/MainMenuManager.cs
- Editor/AGS.Editor/InteractiveTasks.cs
- Editor/AGS.Editor/Utils/Debounce.cs
- Editor/AGS.Types/EditorFeatures/MenuCommand.cs
Adds a lot of machinery to allow replacing menu commands enough so that recent games can be updated
This adds the following menu
Please review this carefully as I had to do a lot of bolting between different things for this to work. This is also new surface of bugs, if we decided this is unwanted, it's alright! An alternative could be to have an entry to bring up the initial screen of AGS.
The good: it actually works
The bad: code is a mess (I couldn't figure what should be in GUIController and what should be in main menu manager!)
Still, I thought it was a good things to have in the editor to easily alternate between games in the editor.
Edit: actually I think I can always hide the most recent game as it will always be the one being edited
> Editor: add open recent games to file menu

- Editor/AGS.Editor/Panes/GlobalVariablesEditor.Designer.cs
- Editor/AGS.Editor/Panes/TextParserEditor.Designer.cs
prevents text from being cut vertically, both panes are very similar (a group with a label and a control), so I just used docking at top for label and fill for the main control.
this is a minimal fix part of #2087
> Editor: fix global variables and text parser pane scaling

- .cirrus.yml
Ensure the ags4 templates are used instead of the ones on master branch when building ags4 editor
> [ags4] ci: use ags4 templates

- Editor/AGS.Editor/Utils/StdConsoleWriter.cs
When making the console printer in the editor, I made a function to work around a quirk of the Windows terminal with non console applications.
In the editor, in the part that prints messages to the command line, when an warn/error message is too big AND it's the first line to be print an exception will happen here. This fix will prevent this.
> Editor: fix count negative on too big message

- Engine/ac/character.cpp
- Engine/ac/dialog.cpp
- Engine/ac/event.cpp
- Engine/ac/event.h
- Engine/ac/game.cpp
- Engine/ac/global_game.cpp
- Engine/ac/global_room.cpp
- Engine/ac/gui.cpp
- Engine/ac/room.cpp
- Engine/device/mousew32.cpp
- Engine/device/mousew32.h
- Engine/main/game_run.cpp
- Engine/main/game_run.h
- Engine/script/nonblockingscriptfunction.h
- Engine/script/script.cpp
Resolves #2468
1. Refactored "game events" code inside the engine. This is the first big commit, details may be found in commit's description. Functionality must remain the same, but the event parameters are stored more explicitly now.
2. Added coordinate parameters to "on_mouse_click" callback, now it should be declared as:
```
function on_mouse_click(MouseButton button, int mx, int my)
```
3. Added similar parameters to "dialog_options_mouse_click", now it should be declared as:
```
function dialog_options_mouse_click(DialogOptionsRenderingInfo *info, MouseButton button, int mx, int my)
```
These changes are fully backwards compatible, as the engine was previously taught to skip trailing parameters if the script has declared these functions with less number of arguments.
> Pass mouse position into "on_mouse_click" script callback

- Editor/AGS.Editor/Entities/EditorPreferences.cs
- Editor/AGS.Editor/GUI/PreferencesEditor.cs
- Editor/AGS.Editor/Panes/ScintillaWrapper.cs
- Editor/AGS.Editor/Panes/ScriptEditor.cs
Two modes of comment/uncomment are supported through Editor Preferences (default `addsSpace` is false):
- addsSpace == false: comment is inserted as the first character of the line, uncommenting will not modify space characters
- addsSpace == true: comment is inserted as the first indentation character with and additional space after, uncommenting will remove one space character after if it exists.
I am trying to remake #1575 in a way that is acceptable, as this is a feature I constantly miss. The method I prefer to use for myself when coding is the one that adds a space.
I used `Shift` + `Ctrl` + `Q` for the shortcut, if a different one is preferred please tell me.
> Editor: adds toggle line comments in script editor

- Common/gfx/allegrobitmap.cpp
- Common/gfx/allegrobitmap.h
- Common/gfx/bitmap.cpp
- Common/gfx/bitmap.h
- Common/util/geometry.h
- Engine/ac/character.cpp
- Engine/ac/character.h
- Engine/ac/draw.cpp
- Engine/ac/game.cpp
- Engine/ac/movelist.cpp
- Engine/ac/movelist.h
- Engine/ac/object.cpp
- Engine/ac/room.cpp
- Engine/ac/room.h
- Engine/ac/route_finder.cpp
- Engine/ac/route_finder.h
- Engine/ac/route_finder_impl.cpp
- Engine/ac/route_finder_impl.h
- Engine/ac/route_finder_impl_legacy.cpp
- Engine/ac/route_finder_impl_legacy.h
- Engine/ac/route_finder_jps.inl
- Engine/main/engine.cpp
- Engine/main/quit.cpp
- Engine/main/update.cpp
- Engine/plugin/agsplugin.cpp
- Solutions/Engine.App/Engine.App.vcxproj
- Solutions/Engine.App/Engine.App.vcxproj.filters
This backports code refactor related to IRouteFinder interface from ags4 to ags3 branch (parts of #2441), while keeping existing functionality intact. The purpose is a cleaner code, and keeping ags3 code closer to ags4 in terms of structure (where possible).
Planned tests:
> Backport RouteFinder refactor to ags3 branch

- Editor/AGS.Editor/AGSEditor.csproj
- Editor/AGS.Editor/Components/RoomsComponent.cs
- Editor/AGS.Editor/GUI/AdjustMasksDialog.Designer.cs
- Editor/AGS.Editor/GUI/AdjustMasksDialog.cs
- Editor/AGS.Editor/GUI/AdjustMasksDialog.resx
- Editor/AGS.Editor/Panes/Room/RoomSettingsEditor.cs
- Editor/AGS.Editor/Utils/BitmapExtensions.cs
- Editor/AGS.Types/AGS.Types.csproj
- Editor/AGS.Types/Enums/AdjustMaskOptions.cs
- Editor/AGS.Types/Interfaces/IRoomController.cs
modified:   Editor/AGS.Editor/Panes/Room/RoomSettingsEditor.cs
Make it so that room masks are resized instead of reset when the resolution of the background changes
> Editor: resize room masks when changing the background to a different size instead of just resetting them.

- Common/game/roomstruct.cpp
- Common/gfx/gfx_def.h
- Editor/AGS.Editor/Resources/agsdefns.sh
- Engine/ac/character.cpp
- Engine/ac/draw.cpp
- Engine/ac/dynamicsprite.cpp
- Engine/ac/global_object.cpp
- Engine/ac/global_region.cpp
- Engine/ac/global_room.cpp
- Engine/ac/global_screen.cpp
- Engine/ac/object.cpp
- Engine/ac/overlay.cpp
- Engine/ac/screenoverlay.cpp
- Engine/ac/screenoverlay.h
Support for tinting overlay, for consistency with characters and objects.
Added following to the Overlay struct in script:
```
/// Tints the overlay to the specified colour.
import void     Tint(int red, int green, int blue, int saturation, int luminance);
/// Sets the light level for this overlay.
import void     SetLightLevel(int light_level);
/// Removes an existing colour tint or light level from this overlay.
import void     RemoveTint();
/// Gets whether the overlay has a tint set.
readonly import attribute bool HasTint;
/// Gets whether the overlay has a light level set.
readonly import attribute bool HasLightLevel;
/// Gets the individual light level for this character.
readonly import attribute int  LightLevel;
/// Gets the Blue component of this overlay's colour tint.
readonly …
```
> AGS 4: Script API: add Overlay.Tint and SetLevel, complying to character and object settings

- Editor/AGS.Editor/Resources/agsdefns.sh
- Engine/ac/overlay.cpp
This is my proposal:
```
/// Sets this overlay's position, and optionally its size.
import void SetPosition(int x, int y, int width = 0, int height = 0);
/// Changes the size of the overlay.
import void SetSize(int width, int height);
```
In SetPosition() width and height are optional parameters, if they are not set (or rather <= 0), then the old size is kept.
Having them combined in SetPosition makes 1 function less, and also we might expand existing SetPosition for other objects with optional width and height too.
But if someone thinks that this is not a good idea, i may reduce SetPosition to strictly x,y and make a third function that has 4 parameters.
> Script API: added helper functions Overlay.SetPosition and SetSize

- Editor/AGS.Editor/Resources/agsdefns.sh
- Engine/ac/dialog.cpp
- Engine/ac/event.cpp
- Engine/ac/event.h
- Engine/script/script.cpp
Resolves #1328
This adds following EventTypes for use in "on_event" callback:
```
eEventDialogStart.
eEventDialogStop,
eEventDialogRun,
eEventDialogOptionsOpen,
eEventDialogOptionsClose,
```
* eEventDialogStart - run when the dialog state begins; arg1 = dialog number;
* eEventDialogStop - run when the dialog state ends; arg1 = last dialog number;
* eEventDialogRun - run when any dialog's entry is executed, whether starting entry or one of the options; arg1 = dialog number, arg2 = option number (0 = starting entry);
* eEventDialogOptionsOpen - run right before the dialog options are shown on screen; arg1 = dialog number
* eEventDialogOptionsClose - run right after the dialog options are removed from the screen; arg1 = dialog number, arg2 = chosen option number
Additionally, added following …
> AGS 4: Script API: add global events for Dialogs, and properties to read current dialog state

- Editor/AGS.Editor/Utils/BitmapExtensions.cs
-It looks like images can have a different _paddedWidth that needs to be taken into account when calculating where in the byte array we are.  The flood fill algorithm was using the normal width instead of the padded width, so it would basically always flood the entire screen since the pixels would be off.
-Also, added a minor optimization.  In our inner loop were were checking image[i] == initial && image[i] != replacement.  The only time you could ever pass the initial check but fail the replacement check is if initial == replacement.  In that case you're just doing if (a == b && a != b), so we can just skip the entire function for cases where the initial and replacement values are the same.
> Editor: Fix room editor flood fill

- Editor/AGS.Editor/Components/FileCommandsComponent.cs
Not sure, but possible fix for https://www.adventuregamestudio.co.uk/forums/ags-engine-editor-releases/ags-4-0-early-alpha-for-public-test/msg636665024/#msg636665024
Edit:
OK, to cause the error it's not that the path tag is empty but that it doesn't exist at all. I had only tested it for it being empty, which instead makes it be an empty string instead of null.
> Editor: fix case recent games menu error on null path

- Common/util/string_utils.cpp
- Common/util/string_utils.h
- Editor/AGS.Editor/Resources/agsdefns.sh
- Engine/ac/string.cpp
- Engine/script/script_api.h
fix #2487
- I don't remember how to deal with the previous script API being only 1 parameter in ags4 branch! (Should I also link to  `String::IndexOf^1` and then have both be able to set through ifdefs in the header? Or is this not needed in ags4 ? the defaults will keep them working but rebuild is still needed.
- I am not convinced that the final code is actually getting proper offset in unicode characters, even as is in the current branch, did we test this at some point?
- I stole bits of the substring function to make the substring that the IndexOf will apply to. I wasn't sure if I should error here too or just throw a warn and return -1.
> Engine: IndexOf add string index, count and case sensitivity params

- Common/ac/gamesetupstruct.h
- Common/game/main_game_file.cpp
- Common/gui/guidefines.h
- Editor/AGS.Editor/DataFileWriter.cs
- Editor/AGS.Editor/GUI/CustomPropertySchemaEditor.Designer.cs
- Editor/AGS.Editor/GUI/CustomPropertySchemaEditor.resx
- Editor/AGS.Editor/GUI/CustomPropertySchemaItemEditor.Designer.cs
- Editor/AGS.Editor/GUI/CustomPropertySchemaItemEditor.cs
- Editor/AGS.Editor/GUI/GUIController.cs
- Editor/AGS.Editor/Resources/agsdefns.sh
- Editor/AGS.Types/CustomPropertySchemaItem.cs
- Editor/AGS.Types/Enums/CustomPropertyAppliesTo.cs
- Editor/AGS.Types/GUIControl.cs
- Engine/ac/gamestate.h
- Engine/ac/guicontrol.cpp
- Engine/game/game_init.cpp
- Engine/game/savegame_components.cpp
A complementary change to #2479.
This adds custom properties functionality to GUI Controls.
In terms of Script API, only parent GUIControl class received new methods, but they may be used by any descendants.
> AGS 4: add custom properties to GUI Controls

- Common/util/wgt2allg.h
- Editor/AGS.Editor/AGSEditor.cs
- Editor/AGS.Editor/ApplicationController.cs
- Editor/AGS.Editor/Panes/PaletteEditor.Designer.cs
- Editor/AGS.Editor/Panes/PaletteEditor.cs
- Editor/AGS.Editor/Panes/PaletteEditor.resx
- Editor/AGS.Editor/Utils/ColorMapper.cs
Fixes #2352
This fix is **purely for user interface** in the editor, they do not change anything in how colors are stored, nor how they are represented in the engine.
1. Fix ColorMapper color defining algorithm to strictly match the internal engine's algorithm. The engine uses Allegro 4 for this, where actual RGB values are found using lookup tables. This seems to result in better distribution, for example it supports pure 255,255,255, while the common conversion algorithm is restricted by 252,252,252 (iirc).
2. On Color Finder pane display actual RGB values that will be used by the engine. This is to honestly notify user that AGS clamps RGBs to less precise 16-bit format.
> Editor: fix Colors pane and ColorMapper to display RGB values matching the engine

- .cirrus.yml
Cirrus CI now only has a single version of macOS available (currently its Sonoma), so the matrix is removed.
Additionally, we occasionally get SIGPIPE failures, so the xcode build variants are removed since we are only using one Xcode version.
Cirrus does have the latest 3 Xcode versions installed so if we want we may do additional builds, but I am keeping it at just one there because they are fairly expensive (in compute credits).
> ci: fixes for macOS in Cirrus CI

- Compiler/script2/cc_compiledscript.cpp
- Compiler/script2/cs_parser.cpp
- Compiler/test2/cc_parser_test_0.cpp
Fixes #2417
Parser code for ternaries could sometimes patch code cells that had once existed but then were ripped out of the codebase.
In 'while(true)' loops with bodies that didn't contain code, the parser tried to look at the first byte beyond the end of the codebase.
> New compiler: Fix bugs uncovered by stricter 'compiledscript' code

- Common/util/string.cpp
- Common/util/string.h
- Common/util/utf8.h
- Solutions/Tools.App/agspak.vcxproj
- Solutions/Tools.App/agspak.vcxproj.filters
- Tools/CMakeLists.txt
- Tools/agspak/Makefile
- Tools/agspak/main.cpp
- Tools/data/include_utils.cpp
- Tools/data/include_utils.h
- Tools/data/mfl_utils.cpp
- Tools/data/mfl_utils.h
partial for #2063 , a later change would be to actually use agspak for building template.
I played a bit with it and it seems it's working.
I noticed I can begin the file with the first line being * and then have the later lines all be prepended by `!` to turn into an include pattern instead. A possbile enhancement for people who prefer the include patter could be to also check for both a `template.include` and `template.ignore` file and adjust the behavior by this.
> Tools: agspak with ignore file support

- Compiler/preproc/preprocessor.cpp
- Compiler/preproc/preprocessor.h
- Compiler/script/cs_parser_common.h
- Compiler/test/preprocessor_test.cpp
This is essentially https://github.com/adventuregamestudio/ags/commit/cc465235b5a20b2a5a377aa4140ee3cbbd6d66d8 (https://github.com/adventuregamestudio/ags/pull/2482) and https://github.com/adventuregamestudio/ags/commit/69704a20c7bb70e34609d6ec78d3549b2a2e8a9f (small part of https://github.com/adventuregamestudio/ags/pull/2180)
- remove undefined behavior from IsScriptWordChar function
- port detection of non-latin characters in the preprocessor
- port escaping of the script name by the preprocessor
- minor readjustment on the error logging to ensure easier error testing this was needed to ease comparison when the error string contained non-latin characters.
**NOTE:** I am modifying the IsScriptWordChar function which is used by the script compiler. It had an undefined behavior - the …
> Compiler: port preprocessor updates from C# to Cpp

- Common/script/cc_common.h
- Compiler/script2/cs_parser.cpp
- Compiler/test2/cc_bytecode_test_0.cpp
- Compiler/test2/cc_bytecode_test_1.cpp
- Compiler/test2/cc_parser_test_0.cpp
In legacy AGS, the engine autogenerates code such as `import Object object[20];` where `object` is meant to be an array of `Object` and not an array of `Object *`. 
I'm told ( **but didn't check this myself** ) that this is no longer true in recent AGS 4.0. This PR makes the compiler cope with this situation. 
Introduce the compiler flag `SCOPT_NOAUTOPTRIMPORT` which is `false` by default. Normally, whenever AGS code declares an object variable then always imply that it is pointered. However, in import declarations of non-autopointered varables only do so when the flag `SCOPT_NOAUTOPTRIMPORT` is `false` (which is the default).
In the legacy AGS situation, the flag  `SCOPT_NOAUTOPTRIMPORT` can be set to `true` so that the compiler generates the correct (legacy) code. This might become …
> New compiler: Only imply `*` in import object declarations when a compiler flag is unset

- Common/script/cc_common.cpp
- Common/script/cc_common.h
- Compiler/test2/cc_bytecode_test_0.cpp
- Compiler/test2/cc_bytecode_test_1.cpp
- Compiler/test2/cc_parser_test_0.cpp
- Compiler/test2/cc_parser_test_1.cpp
Fix #2518
Backwards compatible flags must be reset to defaults whenever a new test runs. This is done in a test initialization method.
Each test that requires a backwards mode should set them explicitly.
> Compiler.Tests: make sure that specific flags are reset to default

- Compiler/script2/cs_parser.cpp
- Compiler/script2/cs_parser.h
- Compiler/test2/cc_parser_test_0.cpp
Fixes #2069
Some ternaries weren't parsed correctly. Root cause was: When processing a ternary, the parser splits it into its components and hands off the components to be parsed in their turn. At this point, the bad code tried to make sure – in an incorrect way – that there weren't any symbols trailing one of the components. But this very check was superfluous in the first place.
Background: When the parser arrives at an expression in the source code, it isolates the whole expression and then processes exactly it, by splitting it apart and processing the respective parts. From that point onwards, it is the responsibility of each function that receives a (sub-) expression as a parameter to check that there aren't any symbols trailing after it, e.g., flag something like  `(5 + 6) %` as an …
> New compiler: Fix bug in ternaries; revamp checks for spurious symbols after expressions

- Solutions/Tools.App/agfexport.vcxproj
- Solutions/Tools.App/agfexport.vcxproj.filters
- Solutions/Tools.sln
- Tools/CMakeLists.txt
- Tools/agfexport/Makefile
- Tools/agfexport/main.cpp
- Tools/data/agfreader.cpp
- Tools/data/agfreader.h
@ivan-mogilko , ages ago you made the pr #1375, with agfexport but then decided to not go forward.
I am making here a tentative idea, I picked your code from that and from the glvar and autoash tools and put together a new tool idea, that makes the three tools into one, using subcommands.
agfexport - parses the game project file (*.agf), and exports various stuff depending on command.
Usage: `agfexport <COMMAND> [<OPTIONS>] <input-game.agf> <out-file>`
Commands:
`autoash <file>`         Generate auto script header
`glvar <header> <body>`  Generate global variables scripts
`script-list`            Exports ordered list of script modules
`room-list`              Exports list of active rooms
`-h, --help`             Show help message
> Tool: agfexport - export miscellaneous data from the game source

- Common/ac/common_defines.h
- Editor/AGS.Editor/Tasks.cs
- Editor/AGS.Types/PropertyGridExtras/FontTypeConverter.cs
- Engine/ac/button.cpp
- Engine/ac/global_game.cpp
- Engine/ac/global_gui.cpp
- Engine/ac/label.cpp
- Engine/ac/listbox.cpp
- Engine/ac/string.cpp
- Engine/ac/string.h
- Engine/ac/textbox.cpp
This is a bit of a exotic feature, it's meant to be used in a situation when you want to have an object with a valid text property, but does not really have that text drawn. One of the use cases is a button which text is used to form a sentence on a action label (MI-style), but you like to have a button image only and not the text.
Maybe there are others, like invisible speech, for instance, or else.
In script this adds `eNullFont` constant, as a part of `eFontType` enum.
Adds "Null Font" in a font selection for properties.
Codewise this is a tiny change, and does not seem to bring much with itself. Our font system already reacts safely on a "invalid" font number, reports 0 width, height, no outline, and not drawing anything with it when requested.
Works for GUI controls, and …
> Script API: support eNullFont, a pseudo font ID which draws nothing

- Common/util/string_utils.h
- Engine/ac/dynobj/scriptgame.cpp
- Engine/ac/gamesetup.h
- Engine/ac/gamestate.cpp
- Engine/ac/gamestate.h
- Engine/ac/global_display.cpp
- Engine/ac/speech.h
- Engine/game/game_init.cpp
- Engine/game/game_init.h
- Engine/game/savegame.cpp
- Engine/main/config.cpp
- Engine/main/engine.cpp
Per a *very old* users request.
This allows players to override game's speech skip style to their preference if the game does not provide such option.
Adds two config options under "[access]" group:
```
[access]
speechskip = <none, input, any, time>
textskip = <none, input, any, time>
```
Both may take following values:
* "none", or empty string (default) - this actually means that the option is not used
* "input", meaning any player input
* "any", meaning any player input, or time
* "time", meaning time only
These options override in-game settings for skipping speech and displayed messages respectively.
The override is done:
- when the game is loaded
- when the save is restored (because these options may be saved)
- when these options are changed by a script, these overriding settings …
> Engine: implement "accessibility" config for speech and text skip

- Common/util/lzw.cpp
Hi!
I'm upstreaming this after ScummVM's [Trac#15179](https://bugs.scummvm.org/ticket/15179) and related scummvm/scummvm#6185 PR of mine.
The following commit fixes Maniac Mansion Deluxe on mips64el (OpenBSD/loongson, more precisely) where a fatal SIGBUS was triggered because of an unaligned load in `lzwexpand()`.
`memcpy()` is guaranteed to be safe, for this.
The unaligned load was also reported by UBSan (see the Trac ticket above for logs, if necessary).
(This may need to be cherry-picked for your ags4 branch as well.)
> Common: Fix lzwexpand on strict-alignment platforms

- Common/font/fonts.h
- Common/game/main_game_file.cpp
- Common/gui/guibutton.cpp
- Common/gui/guibutton.h
- Common/gui/guidefines.h
- Common/gui/guilabel.cpp
- Common/gui/guilabel.h
- Common/gui/guilistbox.cpp
- Common/gui/guimain.cpp
- Common/gui/guimain.h
- Common/gui/guiobject.h
- Common/gui/guitextbox.cpp
- Common/util/geometry.cpp
- Common/util/geometry.h
- Editor/AGS.Editor/AGSEditor.cs
- Editor/AGS.Editor/DataFileWriter.cs
- Editor/AGS.Editor/Resources/agsdefns.sh
- Editor/AGS.Editor/Utils/NativeConstants.cs
- Editor/AGS.Native/NativeMethods.cpp
- Editor/AGS.Native/agsnative.cpp
- Editor/AGS.Types/Enums/FrameAlignment.cs
- Editor/AGS.Types/GUIButton.cs
- Editor/AGS.Types/GUILabel.cs
- Editor/Native/acgui_agsnative.cpp
- Engine/ac/button.cpp
- Engine/ac/drawingsurface.cpp
- Engine/ac/label.cpp
- Engine/game/savegame_components.cpp
- Engine/gui/gui_engine.cpp
Resolves #1876
Resolves #2546
1. Added a GUIControl flag kGUICtrl_WrapText that may be applied to any text-based control, in theory.
GUIButton supports this flag, and in case it is set:
- splits text into lines;
- aligns the text block vertically using vertical part of text alignment;
- aligns each text line horizontally using horizontal part of text alignment;
Wrapping and drawing code is mostly shared with the GUILabel class (picked out as a separate commit).
Added WrapText property to a Button in the Editor.
2. Added TextHorizontalPadding and TextVerticalPadding properties to GUIButton. These specify left-right and top-bottom space between button's frame and aligned text.
Button placeholder text supposedly should not be affected by this.
This has to be tested more.
3. GUILabels support …
> GUI Buttons can wrap & pad text, GUI Labels full alignment

- Editor/AGS.Editor/Resources/agsdefns.sh
- Engine/ac/datetime.cpp
- Engine/ac/datetime.h
- Engine/ac/dynobj/scriptdatetime.cpp
- Engine/ac/dynobj/scriptdatetime.h
- Engine/ac/file.cpp
- Engine/ac/game.cpp
- Engine/ac/global_datetime.cpp
- Engine/platform/base/agsplatformdriver.cpp
- Engine/platform/base/agsplatformdriver.h
- Engine/script/script_api.h
Implements factory methods that create DateTime from full date/time, and from "rawtime".
Creating from normal date/time values may be useful to compare another DateTime object with certain "base point".
All of these may be useful to create DateTime back from previously saved values, either calendar values or rawtime.
```
/// Creates DateTime object from the provided calendar and, optionally, time components
static DateTime* DateTime.CreateFromDate(int year, int month, int day, int hour = 0, int minute = 0, int second = 0); 
/// Creates DateTime object from the provided raw time value (in seconds)
static DateTime* DateTime.CreateFromRawTime(int rawTime);
```
> Script API: more DateTime factory methods

- Compiler/preproc/preprocessor.cpp
- Compiler/preproc/preprocessor.h
- Compiler/test/preprocessor_test.cpp
- Editor/AGS.CScript.Compiler/Preprocessor.cs
I did a stupid mistake in #2178 , missing the nested `#if/#else` possibility. As a result, a nested `#else` inside a disabled parent block enables the following code, even though the parent is still disabled. E.g. code like:
```
#define DEFINEME
#ifdef DEFINEME
import void Func(int a);
#else
#ifdef DEFINEME_NESTED
import void Func(int a, int b);
#else
import void Func(int a, int b, int c);
#endif // DEFINEME_NESTED
#endif // DEFINEME
```
In the above example `import void Func(int a, int b, int c);` will suddenly get enabled.
This PR fixes this problem.
> Fix nested `#else` in a script preprocessor

- Editor/AGS.Editor/Resources/agsdefns.sh
- Engine/ac/dynobj/cc_dynamicarray.h
- Engine/ac/file.cpp
- Engine/script/script_api.h
I wonder if this may be useful?
Adds File.ReadBytes and FileWriteBytes that accept a dynamic `char[]` array and index,count positions:
```
/// Reads up to "count" number of bytes and stores them in a provided dynamic array, starting with index. Returns actual number of read bytes.
int File.ReadBytes(char bytes[], int index, int count);
/// Writes up to "count" number of bytes from the provided dynamic array, starting with index. Returns actual number of written bytes.
int File.WriteBytes(char bytes[], int index, int count);
```
The use case is writing and reading long sequences of byte values, instead of using ReadRawChar/WriteRawChar in a loop.
Simple test example:
```
char bytes[] = new char[100];
for (int i = 0; i < 100; i++)
bytes[i] = i;
int wrote_bytes = f.WriteBytes(bytes, 40, 20); …
```
> Script API: implement File.ReadBytes, WriteBytes

- Editor/AGS.Editor/Resources/agsdefns.sh
- Engine/CMakeLists.txt
- Engine/ac/dynobj/scriptrestoredsaveinfo.h
- Engine/ac/game.cpp
- Engine/ac/game.h
- Engine/ac/global_game.cpp
- Engine/ac/room.cpp
- Engine/game/savegame.cpp
- Engine/game/savegame.h
- Engine/game/savegame_components.cpp
- Engine/game/savegame_internal.h
- Engine/main/game_start.cpp
- Engine/script/exports.cpp
- Solutions/Engine.App/Engine.App.vcxproj
- Solutions/Engine.App/Engine.App.vcxproj.filters
This is a rough draft made as a proof of concept. The purpose of this feature is to let engine load saves from older versions of same game into the newer version, and correctly apply only data that existed in the old version.
It's important to underline that this current feature is intentionally done as a **minimal possible** solution for the problem, which would also be suitable for the backwards compatible branch (ags3). It is meant to work only if user's changes to the game satisfy certain requirements (see below). It's not meant as a "final" or "perfect" solution: that remains a matter for another time (in ags4, I suppose).
Saves are a huge problem, so here's only **for a quick reference**: historically AGS saves do not identify objects by a unique id, but rather by their index in …
> Support reading saves from older game version

- Common/game/main_game_file.cpp
- Common/util/string_compat.c
- Common/util/string_compat.h
- Engine/ac/gamestate.cpp
- Engine/ac/gamestate.h
- Engine/ac/global_parser.cpp
- Engine/ac/parser.cpp
- Engine/ac/sys_events.cpp
- Engine/main/engine.cpp
Fix #2567
This replaces uses of `snprintf` in the code where truncation of the source string is *intended*.
Added a "ags_strncpy_s", using "strncpy_s" from the C11 extension as a reference (see https://en.cppreference.com/w/c/string/byte/strncpy)
> Engine: use safe strcpy function instead of snprintf where truncation expected

- Editor/AGS.Editor/Entities/EditorPreferences.cs
AfterRecentGamesChanged has it's event removed (the update of the Open Recent menu), when the Editor is closed, but later Settings_LimitRecentGames events triggers. This prevents an exception at null in this specific case.
I think this is one of those things I should commit directly on master but I was a bit unsure if it was something wrong on my side since this wasn't reported yet and I thought it would be something common to see.
> Editor: fix exception when saving at close

- Common/script/cc_internal.h
- Compiler/script/cc_compiledscript.cpp
- Compiler/script/cc_compiledscript.h
- Compiler/script/cc_symboltable.cpp
- Compiler/script/cc_symboltable.h
- Compiler/script/cs_compiler.cpp
- Compiler/script/cs_parser.cpp
- Compiler/script2/cs_compiler.cpp
- Compiler/script2/cs_parser.cpp
- Compiler/script2/cs_parser.h
- Compiler/test2/cc_bytecode_test_1.cpp
- Engine/ac/dynobj/cc_dynamicarray.cpp
@fernewelten , I would very much like to know your opinion on this.
I've been revisiting Array.Length pseudo property recently, and it hit me that it's implemented as a static function. Somehow I did not pay attention to this back when it was done (by #1256). I noticed that my proposal in [this comment](https://github.com/adventuregamestudio/ags/issues/637#issuecomment-778922004) mentions "function name accepting 1 argument", so maybe this is what caused it, or maybe there were other considerations too.
But thinking about this now, this does not seem convenient, as such interpretation breaks parsing rules: you have `object.property` syntax, but it's been treated as if it were `function(arg)`. The new compiler has to have a separate case for this, where it has to generate a function call …
> AGS 4: remake DynamicArray.Length pseudo-property getter as a object member function

- Editor/AGS.Editor/GUI/GUIController.cs
- Editor/AGS.Editor/GUI/StartNewGameWizardPage.Designer.cs
- Editor/AGS.Editor/GUI/StartNewGameWizardPage.cs
- Editor/AGS.Editor/GUI/StartNewGameWizardPage.resx
- Editor/AGS.Editor/GUI/WizardDialog.Designer.cs
- Editor/AGS.Editor/GUI/WizardDialog.cs
- Editor/AGS.Editor/GUI/WizardDialog.resx
- Editor/AGS.Native/NativeMethods.cpp
- Editor/AGS.Native/agsnative.cpp
- Editor/AGS.Types/EditorFeatures/BaseTemplate.cs
- Editor/AGS.Types/EditorFeatures/GameTemplate.cs
- Editor/AGS.Types/EditorFeatures/RoomTemplate.cs
This was the PR #1903 , which fixed the issue #564 in AGS 4.
I wanted to backport it to ags3 as I really like it. I also wanted to fix a small annoyance I had with the change of the wizard dialog height, I tried to keep it the same, which is my last commit. I also did some small uses of layout in it using table and some docking.
> Backport Editor Template info preview

- Editor/AGS.Editor/GUI/WelcomeScreen.Designer.cs
- Editor/AGS.Editor/GUI/WelcomeScreen.cs
fix #2576 
adds a subtle version label to the Welcome Screen.
this screen in 3.6.1 for reference
<details>
<summary>I also redid this screen using layouts, in case we ever want to change it's size or for future scaling support.</summary>
</details>
> Editor: adds version in Welcome Screen

- Editor/AGS.Editor/GUI/frmMain.Designer.cs
fix #2566 
From [the MSDN docs on the property](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.form.mainmenustrip?view=netframework-4.6&devlangs=csharp&f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(System.Windows.Forms.Form.MainMenuStrip)%3Bk(TargetFrameworkMoniker-.NETFramework%2CVersion%253Dv4.6)%3Bk(DevLang-csharp)%26rd%3Dtrue), it appears it was just something it was not set by accident.
> Editor: fix pressing alt doesn't select File in menu

- Editor/AGS.Editor/AGSEditor.csproj
- Editor/AGS.Editor/GUI/GUIController.cs
- Editor/AGS.Editor/GUI/MultilineStringEditorDialog.Designer.cs
- Editor/AGS.Editor/GUI/MultilineStringEditorDialog.cs
- Editor/AGS.Editor/GUI/MultilineStringEditorDialog.resx
- Editor/AGS.Editor/Panes/GUIEditor.cs
- Editor/AGS.Types/AGS.Types.csproj
- Editor/AGS.Types/GUIButton.cs
- Editor/AGS.Types/GUILabel.cs
- Editor/AGS.Types/PropertyGridExtras/MultilineStringUIEditor.cs
This is just an idea for a multiline text editor for property grids
https://github.com/user-attachments/assets/abffa5c1-3169-4992-aa7b-9fa8d2202592
When editing properly tagged strings, they will show a three dots and then hitting it they show this custom modal dialog that allow multiline editing.
[I had this idea after this forum post](https://www.adventuregamestudio.co.uk/forums/beginners-technical-questions/how-to-create-a-large-gui-that-would-hold-a-lot-of-text/msg636666904/?boardseen#new)
In a far future of ags perhaps it has an option to have a folder of txt files and you can assign one to a label or whatever, but I don't know the ui for this.
> Editor: multiline text editing in labels and buttons

- Common/gui/guimain.cpp
- Common/gui/guimain.h
- Common/util/directory.h
- Editor/AGS.Editor/Resources/agsdefns.sh
- Engine/ac/event.h
- Engine/ac/game.cpp
- Engine/ac/game.h
- Engine/ac/global_game.cpp
- Engine/ac/global_game.h
- Engine/ac/listbox.cpp
- Engine/ac/listbox.h
- Engine/ac/runtime_defines.h
- Engine/game/savegame.cpp
- Engine/game/savegame.h
- Engine/game/savegame_components.cpp
- Engine/game/savegame_components.h
- Engine/game/savegame_internal.h
- Engine/gui/guidialog.cpp
- Engine/script/executingscript.h
- Engine/script/script.cpp
- Engine/script/script_api.h
This is a logical continuation of #2489
Adds a script function called `Game.ScanSaveSlots()`:
```
static void Game.ScanSaveSlots(int valid_slots_dest[], int min_slot, int max_slot,
SaveGameSortStyle saveSortStyle = eSaveGameSort_None, SortDirection sortDirection = eSortNoDirection, int user_param = 0);
```
Game.ScanSaveSlots() runs a prescan over a range of slots, checks them for validity and compatibility using all available means (including calling "validate_restored_save" callback in script, if one is available), then fills the provided destination array with found valid slot numbers. Array's length is taken into account, limiting number of slots that may be stored there. Any remaining array elements are initialized with -1 - this is to help user to determine that no more slots have …
> Script API: Prescan saves and test for validity

- Editor/AGS.Editor/Resources/agsdefns.sh
- Engine/ac/event.h
- Engine/ac/global_api.cpp
Adds a very simple function:
```
/// Calls the standard "on_event" function, passing EventType and a number of optional parameters
void SendEvent(EventType, int data1=0, int data2=0, int data3=0, int data4=0);
```
This lets to trigger "on_event" callback, passing any arbitrary event type and up to 4 integer parameters (currently).
Declared a `eEventUserEvent` constant inside EventType enum, assigned to a large number. This is meant as a starting index for user scripts to declare their custom events (i.e. eEventUserEvent + 1, eEventUserEvent + 2, and so forth).
As usual, `on_event` is not executed right away, but only after current script finishes running (as a post-script step).
On another hand, since "on_event" is called in every script module, in a regular order (room, then each script …
> Script API: SendEvent() function, calling "on_event"

- Compiler/script2/cc_symboltable.cpp
- Compiler/script2/cc_symboltable.h
- Compiler/script2/cs_parser.cpp
- Compiler/script2/cs_parser.h
- Compiler/test2/cc_bytecode_test_1.cpp
- Compiler/test2/cc_parser_test_1.cpp
CC @fernewelten 
This is a remake of #2529, with proposed changes, based on top of a single original commit.
Managed structs can have an constructor:
* Constructor is defined as a member function of a *managed* struct that has name *identical* to the struct's name.
* The constructor must return `void`. In #2529 I suggested it should be completely typeless, but I did not try that still, as I'm not fully certain whether this is necessary, and and have concerns that implementing it this way may require extra hacks to the parser.
* Can have any parameter list, just like a regular function.
* Cannot be `static`. Having `static` type constructors would technically require to run some sort of a autogenerated script prior to "game_start" callback, but that is far outside current feature.
* Cannot …
> New compiler: support constructors

- Editor/AGS.Editor/Resources/agsdefns.sh
- Engine/ac/character.cpp
In Future Flashback, I use the CustomFollow module I showed in the forums, I also have a similar thing in some other unreleased games. In Don't Give Up the Cat I have this line: https://github.com/ericoporto/dont-give-up-the-cat/blob/fc2810d9d580f6e1b51742489fa388fbd96cdbd0/dont-give-up-the-cat/room1.asc#L164
This PR is to be specific to this need. It's not a major need, I can live without it, as I have a workaround, but it feels useful.
The issue I am not sure though is what happened in #2296 , I don't know how to properly return a Character* here that won't fail equality comparisons, Should I return `&game.chars[charid]` directly or the dynamic memory handle? Is ags4 the only version that has a right answer for this?
> Adds Character.Following readonly property

- Editor/AGS.Editor/AGSEditor.csproj
- Editor/AGS.Editor/Entities/TreeItemDragEventArgs.cs
- Editor/AGS.Editor/Entities/TreeItemTryDragEventArgs.cs
- Editor/AGS.Editor/Enums/TargetDropZone.cs
- Editor/AGS.Editor/GUI/ProjectPanel.Designer.cs
- Editor/AGS.Editor/GUI/ProjectTree.cs
- Editor/AGS.Editor/GUI/TreeViewExtensions.cs
- Editor/AGS.Editor/GUI/TreeViewWithDragDrop.cs
- Editor/AGS.Editor/Panes/SpriteSelector.Designer.cs
- Editor/AGS.Editor/Panes/SpriteSelector.cs
- Editor/AGS.Types/AGS.Types.csproj
Resolve #2595
1. Pick out a drag & drop implementation from ProjectTree into the TreeViewWithDragDrop control class. TreeViewWithDragDrop expands TreeView and provides support for dragging items within itself. It has 3 events: `ItemTryDrag` and `ItemDragOver` and `ItemDragDrop`, which may be used to customize the behavior. They tell whether to start dragging action, if currently dragged item is allowed to be dropped in the current location, and finally handle the drop.
2. Adjust ProjectTree to use TreeViewWithDragDrop type of control. Only 3 drag-related event handlers remain here: `ItemTryDrag`, `ItemDragOver` and `ItemDragDrop`. Everything else was moved to the TreeViewWithDragDrop class.
3. Make SpriteSelector use TreeViewWithDragDrop control for folders, and handle their dragging and …
> Editor: can drag and drop folders in the Sprite Manager

- Engine/script/script_api.cpp
- Engine/script/script_api.h
- Engine/test/scsprintf_test.cpp
Fix #2398
This removes an arbitrary 2k chars limit for result of the script formatting API (such as String.Format).
I think there are still cases in the engine where the formatted string remains to be limited, but in most of them the data is assumed to be short (such as getting "location name). The only other notable case is the core function that creates a textual overlay, still where the final printed text is still limited by 2k chars.
> Script API: remove 2048 length limit for the variadic text functions

- Compiler/script2/cc_internallist.cpp
- Compiler/script2/cc_internallist.h
- Compiler/script2/cc_symboltable.cpp
- Compiler/script2/cc_symboltable.h
- Compiler/script2/cs_parser.cpp
- Compiler/script2/cs_parser.h
- Compiler/test2/cc_bytecode_test_0.cpp
- Compiler/test2/cc_bytecode_test_1.cpp
- Compiler/test2/cc_internallist_test.cpp
- Compiler/test2/cc_parser_test_1.cpp
This PR makes it possible (again) to have classic character arrays as function arguments. 
As far as I can see, the only way that this feature can be used is with _variadic_ arguments in _variadic_ functions such as `Display(const string format, ...)`. When the compiler finds a classic array in a variadic argument, it simply pushes a pointer to the first byte and hopes that the receiving function will find a good use for it. 
As far as I know, the "old" compiler did the same. 
The compiler can't check variadic arguments, anyway, because it doesn't know what types to expect. When I realized that, I gave up all misgivings about implementing "decaying classic arrays" as variadic parameters.
```
char ch[100];
Display("%s", ch);
```
Note that it isn't possible in AGS to define an _explicit_ …
> New compiler: Named function arguments, classic char array arguments

- Editor/AGS.Editor/GUI/ProjectTree.cs
- Editor/AGS.Editor/GUI/TreeViewExtensions.cs
Fix #2473
ProjectTree was using TreeNodeCollection.Find to get a TreeNode with certain Name, but according to MSDN this method does a case-insensitive search for some reason. In AGS Editor currently folder node names (item or folders) are given names that are case-sensitive. Such search could lead to mismatching nodes in case there's e.g. two folders which are only different in name case.
Wrote an extension method FindUnique that filters out precisely matching node name.
NOTE: For the reference TreeNode's Name is not the text that it displays, but its internal "key".
In case user gave two or more folders the same name, that would make their "text" or "title" be the same, but their Names will be made different.
This is achieved with this ugly but working hack: …
> Editor: fix ProjectTree's unreliable search for nodes

- Editor/AGS.Editor/Resources/agsdefns.sh
- Engine/ac/system.cpp
This feels easier to use than remembering to do `Debug(4, 1)`.
This is picked from the discussion in #2436
I use `Debug(4, 1)` when evaluating performance of something I am making, with this I would instead do `System.DisplayFPS = true`, which is more readable, or a simple `on_key_press() { System.DisplayFPS = !System.DisplayFPS }`. This is more for testing quick things than actual final games, where one would probably use GetEngineInteger to retrieve proper fps and do a custom display.
> Engine: Add System.DisplayFPS

- Editor/AGS.Editor.Tests/Editor/AutoComplete/AutoCompleteTests.cs
- Editor/AGS.Editor/AutoComplete.cs
- Editor/AGS.Editor/Panes/ScintillaWrapper.cs
- Editor/AGS.Types/EditorFeatures/AutoComplete/ScriptVariable.cs
fix #2599
This is working, please try.
~~this is the lowest effort for having Length in autocomplete for dynamic arrays. It looks like there are some refactoring opportunities both in the Autocomplete parser and int the typing parser in the Scintilla Wrapper, but they weren't clear for me.~~ I guess we switched for the highest effort.
~~One thing I am not doing here is adding the Length property to the call tip that shows up when the mouse over some property, I looked at the code and couldn't figure some nice way to add it there.~~ this was done
~~This adds a method `GetMembersOfDynamicArray()` that returns a hardcoded Scintilla formatted `Length` as property~~  Edit: switched for fakestruct approach.
> Editor: add Length to Dynamic Array autocomplete

- Editor/AGS.Editor/AGSEditor.csproj
- Editor/AGS.Editor/Components/AudioComponent.cs
- Editor/AGS.Editor/Components/BaseComponent.cs
- Editor/AGS.Editor/Components/CharactersComponent.cs
- Editor/AGS.Editor/Components/CursorsComponent.cs
- Editor/AGS.Editor/Components/DialogsComponent.cs
- Editor/AGS.Editor/Components/FontsComponent.cs
- Editor/AGS.Editor/Components/GuiComponent.cs
- Editor/AGS.Editor/Components/InventoryComponent.cs
- Editor/AGS.Editor/Components/RoomsComponent.cs
- Editor/AGS.Editor/Entities/CompileWarningEx.cs
- Editor/AGS.Editor/GUI/GUIController.cs
- Editor/AGS.Editor/GUI/OutputPanel.cs
- Editor/AGS.Editor/GUI/OutputPanelItem.cs
- Editor/AGS.Editor/Panes/ScriptEditorBase.cs
- Editor/AGS.Editor/Tasks.cs
- Editor/AGS.Types/Exceptions/CompileMessage.cs
As suggested by @messengerbag, as a most primitive solution for #2550.
...and a complementary to #2556
This adds another type of post-compilation warning that reports a script function that *looks like* it's a event handler, but *not linked* to the object events.
The feature uses default function names, as configured in Interaction tables.
For example: `cEgo_Look`, `Room_Load` and so forth.
The reported warning uses following pattern:
```Function "ObjectName_EventName" looks like an event handler, but is not linked on ObjType (ID) ScriptName's Event pane```
Example:
**TODO:**
Option in Editor Preferences that turns this on and off?
Need to decide what happens if user double clicks the warning. Do we want it to go to the script, or to the object's Events Pane?
Or have both options, called …
> Editor: report warnings about possibly unlinked event handlers

- Compiler/script2/cs_parser.cpp
- Compiler/test2/cc_parser_test_1.cpp
Fixes #2617 
The compiler didn't catch functions that are declared `import` and at the same time get a body. This is an error.
Example:
```
import int Func()   // ←'import' keyword
{    // ← function has a body
return 0;
}
```
Add a Googletest that checks that this is now illegal.
> Fix bug: 'import' functions cannot get a body at the same time

- Editor/AGS.Editor/Resources/agsdefns.sh
- Engine/ac/draw.cpp
- Engine/ac/dynamicsprite.cpp
- Engine/ac/game.cpp
- Engine/ac/game.h
- Engine/ac/global_screen.cpp
- Engine/ac/global_screen.h
- Engine/ac/overlay.cpp
- Engine/ac/screenoverlay.cpp
- Engine/ac/screenoverlay.h
By user request, this implements Overlay.Flip property that flips overlay graphic in 3 possible ways.
```
/// Gets/sets the flip direction of this overlay.
attribute eFlipDirection Overlay.Flip;
```
For storage and serialization this uses a new field of type "SpriteTransformationFlags", and a position which was reserved in ags4 save format a while ago. It has flip flags now, but more could be added later as necessary. There's a conversion between script parameter and this new flag set.
NOTE: Software renderer has some bugs in ags4 branch, so switching from some flip to "no flip" does not update the overlay image. I'm planning to address that separately, there's a unfinished code brought by one of the older merges, that was never made to work in completion.
> AGS 4.0: implement Overlay.Flip

- Engine/ac/dynobj/cc_dynamicarray.cpp
- Engine/ac/dynobj/cc_dynamicarray.h
- Engine/plugin/agsplugin.cpp
- Engine/plugin/agsplugin.h
- Engine/script/cc_instance.cpp
Resolve #2313
This adds IAGSEngine::CreateDynamicArray, GetDynamicArrayLength and GetDynamicArraySize:
```
// Create a new dynamic array, allocating space for the given number of elements
// of the given size. Optionally instructs to create an array for managed handles,
// in which case the element size must be sizeof(int32).
// IMPORTANT: you MUST correctly tell if this is going to be an array of handles, because
// otherwise engine won't know to release their references, which may lead to memory leaks.
// IMPORTANT: when writing handles into this array, you MUST inc ref count for each one
// of them (see IncrementManagedObjectRefCount), otherwise these objects may get disposed
// before the array itself, making these handles invalid!
// Dynamic arrays have their meta data allocated …
```
> Engine Plugin API: add CreateDynamicArray()

- Engine/ac/draw.cpp
- Engine/ac/draw.h
- Engine/ac/gamestate.h
- Engine/ac/overlay.cpp
- Engine/ac/screenoverlay.h
Fix #2311
This is a quick solution for resolving objects with identical z-order, in which case we'd like to keep their relative sort persistent, and avoid random sorting "swaps".
This is achieved by a combined comparison in sort's "less" function:
- first compare if (z1 < z2);
- if (z1 == z2), then compare if (drawindex1 < drawindex2)
Global DrawIndex is allocated for each drawable object in game (except for gui controls that are sorted only among each other).
Static objects are reserved draw indexes at the game init.
Dynamic objects (currently only Overlays) have one assigned for them when they are *drawn for the first time*.
DrawIndex is ever incrementing counter. When it reaches max value (of uint32_t), it overflows and gets reset to the "base dynamic index", which is set once to the …
> Make object sorting position on screen deterministic in case of equal z-order

- Editor/AGS.Editor/Resources/agsdefns.sh
- Engine/ac/file.cpp
1. Rename Read/WriteBytes() to Read/WriteRawBytes().
2. Add Read/WriteFloat(), a safeguarded variant complementing Read/WriteRawFloat().
3. Expanded api comments a bit, notifying users about safeguarded functions.
> Script API: fix recently added File API for consistency

- Editor/AGS.Editor/Resources/agsdefns.sh
- Engine/game/savegame.cpp
This is an alternative to #2632, they are mutually exclusive.
When documenting the new ["validate_restored_save" callback](https://github.com/adventuregamestudio/ags-manual/wiki/ValidateRestoredSave) I began to wonder if preseting RestoredSaveInfo.Result property as a set of flags would be convenient to users. Majority of AGS users don't use flag sets very often, and finding out whether a certain flag is set may be confusing to some of them (if not to many of them).
I am wondering now why did I make them set of flags in api at all. Maybe that was complete unnecessary.
Besides, there's not many flags there which may be needed for the end user.
This PR replaces a single RestoredSaveInfo.Result with a set of 3 boolean properties:
```
/// Gets whether this save was only prescanned, and not …
```
> Script API: remake RestoredSaveInfo.Result into multiple bool properties

- Common/ac/game_version.h
- Common/ac/gamesetupstruct.cpp
- Common/ac/gamesetupstruct.h
- Common/game/room_file.cpp
- Common/game/roomstruct.h
- Editor/AGS.Editor/DataFileWriter.cs
- Editor/AGS.Editor/Resources/agsdefns.sh
- Editor/AGS.Native/agsnative.cpp
- Engine/ac/game.cpp
- Engine/ac/global_debug.cpp
- Engine/ac/room.cpp
- Engine/gui/guidialog.cpp
- Engine/gui/guidialog.h
Resolves #1135.
Adds 3 static readonly properties to Game struct:
```
/// Gets the total number of the rooms in game.
static readonly attribute int Game.RoomCount;
/// Gets the existing room numbers by a sequential index (from 0 to RoomCount - 1); returns -1 if index is not valid.
static readonly attribute int RoomNumbers[];
/// Gets the room's name (description) by the room's number; returns null if such room does not exist.
static readonly attribute String Game.RoomNames[];
```
Adds 2 static readonly properties to Room struct:
```
/// Gets the current Room's number
static readonly attribute int Room.Number;
/// Gets the current Room's name (description)
static readonly attribute String Room.Name;
```
The only caveat is that room descriptions were not saved in the room itself, so I had …
> Script API: add Room.Name and Room.Number

- Compiler/script2/cs_parser.cpp
- Compiler/script2/cs_parser.h
- Compiler/test2/cc_bytecode_test_1.cpp
- Compiler/test2/cc_parser_test_1.cpp
Fixes #2067
Currently, whenever the new compiler is compiling the body of a non-static struct function and it encounters an unknown identifier `i` in an expression, it doesn't give up yet. It looks up `this.i` first, and if that subexpression is valid, the compiler uses it.
This PR generalises this concept to static struct functions: When the compiler is compiling the body of a static struct function for the struct `str` and it encounters an unknown identifier `i` in an expression, it doesn't give up yet. It looks up `str.i`, and if that subexpression is valid, then the compiler uses it.
```
float FourCos(static Maths, float rd)
{
return 4.0 * Cos(rd); // ← 'Cos' unknown, but 'Maths.Cos' exists so use that
}
```
This PR also fixes the following bugs:
- When a struct `s` extends another …
> New compiler: When in the body of a static struct function and finding an otherwise unknown symbol, imply static access

- Editor/AGS.Editor/Resources/agsdefns.sh
I have reduced the use of `function` in the Character API in Script Header.
- `SetProperty` and `SetTextProperty` are the only function calls that return something (`bool`s) that aren't a "Get" function.
- The variadic calls (`Say`, `SayAt`, `SayBackground` and `Think`), I actually can't tell if they are meant to always return 0 or be void, so I haven't changed them
- `GetProperty` returns `int`, so I changed from function to int.
- `IsCollidingWithChar` and `IsCollidingWithObject` are meant to be `bool,` so I changed their types to `bool`, but they are using `int` return macros instead of `bool` return macro in `ac/character.cpp`
This is related to #2463
> Editor: Character use less function in Script Header

- Editor/AGS.Editor/Resources/agsdefns.sh
Same as #2641 but for objects. Related  to #2463.
Note that after this there is no more use of `function` in the script header. The remaining use of function is in the templates and handlers created by the Editor.
And it's also used in this file below (I don't know if the editor use this somewhere?)
https://github.com/adventuregamestudio/ags/blob/fd272e21f671c4b17caa8def5460f73b041e727e/Editor/AGS.Editor/Resources/__DialogScripts.asc#L10
> Editor: avoid function on Object in script header

- CMake/FetchSDL_Sound.cmake
- OSX/README.md
- Windows/README.md
- ci/linux/Dockerfile
- ci/windows/Dockerfile
- debian/README.md
- libsrc/download.sh
- libsrc/sha1sums
- version.json
https://github.com/icculus/SDL_sound/commit/16e626561f3b496e4a2da98c95d23359eeee3c01
SDL_sound now has a stable-2.0 branch, but it's still identical to main as SDL3 upgrade PR hasn't been merged yet.
Honestly not much changed there, this is more to guarantee things are kept in sync.
> Update SDL_Sound to latest commit

- Emscripten/install_dependencies.sh
- ci/emscripten/Dockerfile
More chore, upgrades emscripten version. This moves the sdl2 in emscripten to 2.30.9.
My plan is to later this week open a PR upgrading to latest SDL2 for ags itself, but first I need to test it,
> Emscripten: update to 3.1.74

- Common/core/types.h
- Engine/ac/character.cpp
- Engine/ac/display.cpp
- Engine/ac/display.h
- Engine/ac/global_api.cpp
- Engine/ac/global_character.cpp
- Engine/ac/global_overlay.cpp
- Engine/ac/global_overlay.h
- Engine/ac/overlay.cpp
- Engine/ac/overlay.h
* Replaced DISPLAYTEXT_x macros with DisplayTextType enum;
* Got rid of confusing `asspch` parameter which combines text color with the "text style" by applying a sign. Instead have separate `text_color` and a `style` parameter of DisplayTextStyle enum.
* Also added DisplayTextShrink enum for the `allow_shrink` parameter.
* Grouped them into `DisplayTextLooks` struct.
> Engine: refactor passing text_color into display_main()

- CMake/FetchSDL_Sound.cmake
- OSX/README.md
- Windows/README.md
- ci/linux/Dockerfile
- ci/windows/Dockerfile
- debian/README.md
- libsrc/download.sh
- libsrc/sha1sums
- version.json
This is meant to fix #2244 , but the problem is I can't hear the difference between both games that are attached in the bug report
https://github.com/icculus/SDL_sound/commit/474dbf755a1b67ebe7a55467b4f65e033f268aff
possibly fix looping ogg files that have silence appended at the end - the raw file tests using SDL_sound were successful, I just can't hear the issue with the actual ags game that is attached in the issue, so I can't verify the fix actually worked for the actual game.
> SDL_sound: update to latest

- Android/library/runtime/src/main/java/org/libsdl/app/HIDDeviceManager.java
- Android/library/runtime/src/main/java/org/libsdl/app/SDL.java
- Android/library/runtime/src/main/java/org/libsdl/app/SDLActivity.java
- Android/library/runtime/src/main/java/org/libsdl/app/SDLControllerManager.java
- CMake/FetchSDL2.cmake
- ci/linux/Dockerfile
- ci/windows/Dockerfile
- libsrc/download.sh
- libsrc/sha1sums
- version.json
This updates to newer release of SDL2, the 2.30.11 release, from 01/01/2025.
I tested it with my games and it seems that this doesn't break anything.
> SDL upgrade to version 2.30.11

- .cirrus.yml
- Editor/AGS.Native/NativeDLL.vcxproj
- Editor/AGS.Native/NativeDLL.vcxproj.filters
- Solutions/AGS.Editor.Full.sln
- Solutions/Common.Lib/Common.Lib.vcxproj
- Solutions/Compiler.App/Compiler.App.vcxproj
- Solutions/Compiler.Lib.sln
- Solutions/Compiler.Lib/Compiler.Lib.Test.vcxproj
- Solutions/Compiler.Lib/Compiler.Lib.vcxproj
- Solutions/Engine.App/Engine.App.vcxproj
- Solutions/Engine.sln
- Solutions/Tests.App/Common.Lib.Test.vcxproj
- Solutions/Tests.App/Engine.App.Test.vcxproj
- Solutions/Tests.sln
- Solutions/Tools.App/afg2dlgasc.vcxproj
- Solutions/Tools.App/agfexport.vcxproj
- Solutions/Tools.App/agspak.vcxproj
- Solutions/Tools.App/agsunpak.vcxproj
- Solutions/Tools.App/crm2ash.vcxproj
- Solutions/Tools.App/crmpak.vcxproj
- Solutions/Tools.App/trac.vcxproj
- Solutions/Tools.sln
- Solutions/libogg.props
- Solutions/libtheora.props
- Solutions/libvorbis.props
- Solutions/sdl2.props
- Windows/Installer/ags.iss
- Windows/Installer/checksums.sha256
- Windows/README.md
- ci/windows/Dockerfile
fix #1508 
built on top of #2591
---
**Some notes:**
Visual Studio 2022 build tools image did not work with CMake. It seems the big issue is that Visual Studio 2022 Build Tools doesn't correctly installs all VC tools, the 142 (VS 2019, aka VC 14.29) vc tools seems to install most correctly but it doesn't seem to proper have the CLI/C++ tools working, and the VC 143 (VS 2022, aka VC 14.43) doesn't properly create the cl.exe in place.
I used VS 2022 community instead, which worked fine on the Windows container and properly install packages - though this means the image is slightly larger (21.96 GB in the base image). Here is the docker file for the base image
https://raw.githubusercontent.com/ericoporto/min-ags-dev-env/211537671e66f8e6df0c6fcd0826a529b535acd5/Dockerfile
I opted to build …
> adjust CI and docker for VS2019 compatibility using VS2022

- Compiler/script2/cs_parser.cpp
- Compiler/test2/cc_parser_test_0.cpp
Fixes #2647
When AGS code defines a parameter within a function header and a body follows then that parameter can hide or collide with global definitions. Code for these checks is already provided where the compiler processes local variable defns. So no need to duplicate the checks where the compiler processes parameter definitions – delete these checks.
This fixes a bug : These checks were even done when a function body doesn't even follow (i.e., for an import or forward declaration of a function), which is incorrect and makes for strange warnings.
Example code:
```
import void foo();
import void test(int foo); // Should NOT yield any warning or error
``` 
Provide googletests that demonstrate that the bug is fixed.
> Eliminate duplicate tests when function parameters are defined

- Common/gfx/image_file.cpp
- Editor/AGS.Editor/Panes/SpriteImportWindow.cs
- Editor/AGS.Editor/Utils/BitmapExtensions.cs
- Editor/AGS.Editor/Utils/SpriteTools.cs
- Editor/AGS.Native/SpriteFileWriter_NET.cpp
- Editor/AGS.Native/agsnative.cpp
- libsrc/allegro/include/allegro/palette.h
This lets Editor to correctly import 8-bit indexed PNGs that have valid alpha component in its palette.
The previous versions of AGS loaded all PNGs as 32-bit images, which solved this problem, but made it impossible to import 8-bit PNGs as actually 8-bit images.
AGS 3.6.2 imports 8-bit PNGs as 8-bit images, but now has opposite problem: if such image has to be converted to a 32-bit sprite (in 32-bit game), the alpha channel becomes lost. First it does not detect the presence of alpha, secondly the process of converting a 8-bit image to a final sprite does not use alpha component at all.
This PR solves these issues.
EDIT: I am not very good at graphic editors, and could not yet find a way to create or export such images.
So i am attaching a sprite provided by the user who got this …
> Editor: support loading 8-bit images with Alpha in palette

- Engine/ac/character.cpp
- Engine/ac/character.h
- Engine/ac/characterinfo_engine.cpp
- Engine/ac/global_character.cpp
- Engine/ac/global_game.cpp
- Engine/ac/object.cpp
- Engine/ac/object.h
Fixes #1879, along the way.
This is a backport of a code refactor from ags4, that tidies up Character and Object Move and Walk functions, bringing them to consistency of parameter checking and delegating actual work to the internal implementation.
Except here I also did this for deprecated script functions.
The second change is, this optimizes WalkStraight function by not running a pathfinder with "anywhere" parameter. Instead makes it use result of previously called CanSeeFrom method, which is already supposed to tell a walkable path.
As a side effect, this makes WalkStraight also use the position fixup in StopMoving, where engine calls PlaceOnWalkableArea in case character ended up on a non-walkable area by mistake.
NOTE: I was considering writing a different algorithm to use here …
> Refactor Character and Object Move functions, optimize WalkStraight

- Compiler/script2/cs_compile_time.cpp
- Compiler/test2/cc_parser_test_2.cpp
During compile time, attempting to left shift with `int a = 0xFF << 24;` was causing an overflow error where none is expected. 
One test was catching a bogus overflow for `536870912 << 2` but that's just `0x80000000` which is valid, so I amended it to `<< 3` to cause a real overflow.
I also added an extra test to make sure it can shift to the highest bit unimpeded.
Was this "overflow" done on purpose to avoid touching the sign bit? If that's the case I don't agree, as it's a too big departure from runtime, and prevents from filling valid bit positions.
> New compiler: incorrect compile time left bitshift overflow

- Editor/AGS.Editor/Components/GuiComponent.cs
- Editor/AGS.Editor/Components/SettingsComponent.cs
- Editor/AGS.Types/AGS.Types.csproj
- Editor/AGS.Types/Game.cs
- Editor/AGS.Types/PropertyGridExtras/AudioClipTypeConverter.cs
- Editor/AGS.Types/PropertyGridExtras/AudioClipTypeTypeConverter.cs
- Editor/AGS.Types/PropertyGridExtras/FontTypeConverter.cs
- Editor/AGS.Types/PropertyGridExtras/GUIIndexTypeConverter.cs
- Editor/AGS.Types/PropertyGridExtras/RoomListTypeConverter.cs
- Editor/AGS.Types/PropertyGridExtras/ScriptListTypeConverter.cs
- Editor/AGS.Types/PropertyGridExtras/TranslationListTypeConverter.cs
- Editor/AGS.Types/Settings.cs
Fix #2542
1. Properties that let select GUI display a dropdown list of gui script names instead of being raw number fields. The displayed names are mapped to GUI number internally, so no data upgrade is necessary.
2. Whenever a GUI is removed, or has ID changed by command, SettingsComponent class updates all of its properties and fixes GUI selection. If selected GUI got removed, property is changed to 0 ("None").
The feature is purely in UI and does not change data format.
> Editor: update properties referencing GUIs on GUI removal or id change

- Common/gfx/allegrobitmap.h
- Engine/ac/character.cpp
- Engine/ac/character.h
- Engine/ac/route_finder.cpp
- Engine/ac/route_finder.h
Fix #163
This makes Character.PlaceOnWalkableArea use 1-pixel step, in order to not skip thin areas.
Refactored searching algorithm and moved to Pathfinding::FindNearestWalkablePoint(). This function still accepts search "step" parameter, so in theory we could use it if a need arises.
Renamed original function to FindNearestWalkableAreaForCharacter(). Made it clear which restrictions to the scanning area do we make, according to historical AGS rules (don't move character beyond room edges, etc).
Removed the obscure hard-coded restriction which did not let move character to the topmost 14 pixels of the room. I think that may be related to the Sierra-style Statusbar GUI from the default template.
Optimized scanning algorithm for speed (see explanation below).
Would need to make performance …
> Improve PlaceOnWalkableArea

- Engine/ac/draw.cpp
- Engine/ac/game.cpp
- Engine/ac/mouse.cpp
- Engine/ac/mouse.h
- Engine/device/mousew32.cpp
- Engine/device/mousew32.h
- Engine/gfx/ali3dsw.cpp
- Engine/gui/mylistbox.cpp
- Engine/main/engine.cpp
- Engine/main/engine_setup.cpp
- Engine/main/game_run.cpp
- Engine/platform/base/sys_main.cpp
- Engine/platform/base/sys_main.h
> When mouse is locked in window, confine its position to the game viewport

- Editor/AGS.Editor/AGSEditor.csproj
- Editor/AGS.Editor/Components/AudioComponent.cs
- Editor/AGS.Editor/GUI/ReplaceFolderDialog.Designer.cs
- Editor/AGS.Editor/GUI/ReplaceFolderDialog.cs
- Editor/AGS.Editor/GUI/ReplaceFolderDialog.resx
- Editor/AGS.Editor/Panes/SpriteSelector.cs
- Editor/AGS.Editor/Utils/Utilities.cs
Resolve #2520
This implements an operation that replaces parent part of the source file path for sprites and audio clips. In other words, it lets to replace the folder in the source path. This may be useful if a user wants to move game assets elsewhere.
There are two new menu commands.
1. "Replace source paths for sprites..." command in the Sprite Manager's context menu.
2. "Replace source paths for audio clips..." command in the Audio node context menu (in the project explorer).
Both act similarly: open a dialog that lets choose old and new parent folder, then runs all the respective items (sprites or audio clips), and replaces the parent folder in each one of them whose base path matches the "old" path selection.
For example, if you set
old path: "C:/My Documents/Sprites"
new path …
> Editor: implement "Replace source paths" operation for sprites and audio clips

- Editor/AGS.Editor/Resources/agsdefns.sh
- Engine/ac/characterinfo_engine.cpp
- Engine/ac/global_api.cpp
- Engine/ac/math.cpp
- Engine/ac/math.h
- Engine/script/script_api.h
Resolve #1983, #2683
Contents:
1. Expands eRound option with 2 new modes:
* `eRoundTowardsZero` - rounds towards a closest integer *less by magnitude* (absolute value);
* `eRoundAwayFromZero` - rounds towards a closest integer *larger by magnitude* (absolute value);
2. Add `float Maths.Round(float, RoundDirection)` - which rounds a float value to another float value (without making it int).
3. Add `Maths.Random(limit)`, a proper variant of `Random`, which treats limit as an upper exclusive boundary. So `Maths.Random(10)` would choose a number between 0 and 9, but never 10.
4. Add `Maths.RandomFloat()` which produces a float in range [0.0, 1.0) (excluding 1.0).
> AGS 4: Script API: add eRound options and new Maths.Random()

- Common/gfx/blender.cpp
- Common/gfx/gfx_def.h
- Editor/AGS.Editor/Resources/agsdefns.sh
- Editor/AGS.Types/Enums/BlendMode.cs
- Engine/ac/dynobj/scriptdrawingsurface.cpp
- Engine/gfx/ali3dogl.cpp
- Engine/gfx/ali3dogl.h
- Engine/gfx/gfx_util.cpp
- Engine/platform/windows/gfx/ali3dd3d.cpp
- Engine/platform/windows/gfx/ali3dd3d.h
This implements 3 new BlendModes:
* Copy - copies full color from src to dest, fully discards dest;
* CopyRGB - copies rgb color component from src to dest, mixing with dest alpha;
* CopyAlpha - copies src alpha to dest, mixing with dest rgb.
```
/// copy source color to destination
eBlendCopy,
/// copy source rgb to destination (keep destination alpha)
eBlendCopyRGB,
/// copy source alpha to destination (keep destination rgb)
eBlendCopyAlpha
```
Initially my intention was to implement only Copy, meant for drawing transparent primitives on DrawingSurface. This should replace an ability to draw with transparent color, which does not exactly work now after implemented alpha support (#2661).
After adding this mode to object rendering as well, it came to me that having a mode which copies …
> AGS 4: implement CopyX BlendModes

- Engine/main/engine.cpp
An attempt to fix #2700
TBH I don't have a full confidence in that this fixes the problem, but the way the exit after winsetup was coded have always bugged me. Changed the process spawning from OVERLAY to NO_WAIT, which means that the parent process keeps running and shuts down normally and in reliable way.
> Engine: correct game process spawning and winsetup exit

- Engine/gfx/ali3dogl.cpp
- Engine/gfx/ali3dogl.h
Solved the OpenGL renderer not respecting alpha transparency on several blend modes.
It was broken since SDL2 was merged, because the hacks that darken/lighten the textures don't work along the _transparencyShader shader. 
Unlike D3D, there's always a shader enabled for rendering sprites, so I rewrote those texture ops into two new shaders to match D3D output (which is not perfect, but at least it's consistent again).
> OGL: Fixed blendmodes not respecting transparency

- CMake/FetchGoogleTest.cmake
- CMakeLists.txt
It seems GitHub Actions builder had an update in CMake that broke building in PR #2712. Made a quick fix that worked in the pipeline in my fork.
I will need to joing together the fetch content scripts as now it's expected to do a single MakeAvailable call later that contains all libraries in it - so, I can't separately call to build SDL2 and then SDL Sound anymore, I need to tell cmake to build SDL2 and SDL_Sound in sequence, so it figures the link between then, when fetching them. This will take a little more time to figure it out.
> CMake compatibility

- Editor/AGS.Editor/AGSEditor.cs
- Editor/AGS.Editor/AGSEditorController.cs
- Editor/AGS.Editor/GIFLoader/GifDecoder.cs
- Editor/AGS.Editor/ImportExport.cs
- Editor/AGS.Editor/NativeProxy.cs
- Editor/AGS.Editor/Panes/SpriteImportWindow.Designer.cs
- Editor/AGS.Editor/Panes/SpriteImportWindow.cs
- Editor/AGS.Editor/Panes/SpriteSelector.cs
- Editor/AGS.Editor/Utils/SpriteTools.cs
- Editor/AGS.Native/NativeMethods.cpp
- Editor/AGS.Native/NativeMethods.h
- Editor/AGS.Native/SpriteFileWriter_NET.cpp
- Editor/AGS.Native/SpriteFileWriter_NET.h
- Editor/AGS.Native/agsnative.cpp
- Editor/AGS.Types/Enums/SpriteImportTransparency.cs
- Editor/AGS.Types/Sprite.cs
Long overdue, resolves #805
In the sprite import dialog replaces "Palette index 0" with "Palette index" selection and a numeric input field (default to value 0). This allows user to select exact palette index to use as a transparent color, in case the sprite source has it on other index than 0.
"Palette index 0" is still available in the sprite's properties for backwards compatibility.
Images for the test:
8-bit PNG: 
8-bit GIF (multiframe):
> Editor: let select palette index for the sprite's transparent color

- Compiler/script2/cc_compiledscript.cpp
- Compiler/script2/cc_symboltable.cpp
- Compiler/script2/cc_symboltable.h
- Compiler/script2/cs_parser.cpp
- Compiler/script2/cs_parser.h
- Compiler/test2/cc_bytecode_test_0.cpp
- Compiler/test2/cc_bytecode_test_1.cpp
- Compiler/test2/cc_bytecode_test_lib.cpp
- Compiler/test2/cc_bytecode_test_lib.h
- Compiler/test2/cc_parser_test_0.cpp
- Compiler/test2/cc_parser_test_1.cpp
- Compiler/test2/cc_parser_test_2.cpp
- Compiler/test2/cc_symboltable_test.cpp
This is a rebased version of @fernewelten 's #2662 PR, which has a applied change to the initialization syntax, as suggested in the previous PR discussion: when we use "named" initialization for array elements we don't need to use `[N]:` syntax, but `N:` syntax instead.
Example:
```
bool IsPrime[10] = {
2: true,
3: true,
5: true,
7: true,
};
```
Everything else should stay as stated in #2662 description, so please refer to it.
> [Remake] New compiler: Initializers for global classic arrays and structs

- Editor/AGS.Editor/Resources/agsdefns.sh
- Engine/ac/movelist.cpp
- Engine/ac/movelist.h
- Engine/main/update.cpp
This hotfix should resolve the change in behavior after the last refactor that was causing movement skips, because `do_movelist_move()` needs to process the current stage before increasing onpart (as per original behavior).
So I added a new method to avoid interfering with the MotionPath script API.
There were (and still are) some mismatches in the reported MotionPath coordinates when comparing from script the X/Y of player vs motionpath, apparently related to walkable area zoom.
I suspect it's an issue with the old hacks to slow down movement at smaller scalings. If that's the case, the proper fix could be using float coordinates internally, but that's another matter.
> AGS4 Engine: fixing movement issues

- .cirrus.yml
- Changes.txt
- Editor/AGS.CScript.Compiler/AGS.CScript.Compiler.csproj
- Editor/AGS.Controls/AGS.Controls.csproj
- Editor/AGS.Editor.Tests/AGS.Editor.Tests.csproj
- Editor/AGS.Editor/AGSEditor.csproj
- Editor/AGS.Editor/app.config
- Editor/AGS.Editor/app.manifest
- Editor/AGS.Native/NativeDLL.vcxproj
- Editor/AGS.Types/AGS.Types.csproj
- Windows/Installer/ags.iss
- Windows/README.md
- ci/windows/Dockerfile
This updates the .NET framework used for the AGS Editor from 4.6 to [4.7](https://devblogs.microsoft.com/dotnet/announcing-the-net-framework-4-7) for a couple of good reasons:
1. Enable improved support for high DPI scaling. This has been attempted before and had to be rolled back (See #2087), but I'd like to take advantage of the [improved support](https://devblogs.microsoft.com/dotnet/announcing-the-net-framework-4-7/?WT.mc_id=dotnet-35129-website#take-advantage-of-high-dpi) and [new API introduced in 4.7](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.control.logicaltodeviceunits?view=netframework-4.7) onward to make changes to the controls to support it.
2. It's still compatible with Win 7 SP1: https://learn.microsoft.com/en-us/dotnet/framework/get-started/system-req …
> AGS 4 Editor: Update .NET framework from 4.6 to 4.7

- Editor/AGS.Editor/GUI/SpriteExportDialog.Designer.cs
fix #2723 
- remove window "default" icon
- make window non-resizeable
- adjust the buttons on the bottom to not cut on Win11 view
Before:
After:
@edmundito please check
> Editor: sprite export dialog adjustments

- Common/gui/guibutton.cpp
- Common/gui/guibutton.h
- Editor/AGS.Editor/Resources/agsdefns.sh
- Engine/ac/button.cpp
Based on a feature in a "Draconian" engine version, this adds a Button.GraphicFlip property that flips a button image (in all 3 states - normal, over and pressed).
This does not affect animated buttons, as they receive the flip option from the view frames. In fact, Animate() will reset the GraphicFlip property as it resets NormalGraphic.
The property name is "GraphicFlip", and not e.g. "Flip", because this flips only the assigned graphic, not whole control.
> Script API: implement Button.GraphicFlip

- Editor/AGS.Editor/Panes/PaletteEditor.Designer.cs
- Editor/AGS.Editor/Panes/PaletteEditor.cs
- Editor/AGS.Editor/Panes/PaletteEditor.resx
- Editor/AGS.Editor/Utils/ColorMapper.cs
- Editor/AGS.Types/PaletteEntry.cs
- Editor/AGS.Types/PropertyGridExtras/ColorUIEditor.cs
- Editor/AGS.Types/PropertyGridExtras/CustomColorConverter.cs
- Editor/AGS.Types/Utilities.cs
Fix #2743
Redesigns Color Finder:
* Removed RGB sliders, as mostly useless;
* Display 3 text boxes:
* Color in programmer's hex notation `0xAARRGGBB`, useful to copy and insert into the script where you assign this value directly to a color variable;
* Color in HTML notation `#RRGGBBAA` (where AA may be omited), useful to paste from the paint software;
* Color in a comma-separated decimal notation `R, G, B, A` (where AA may be omited), useful to copy into the script where you have a `Game.GetColorFromRGB/A` function call.
Adjust Color properties in Property Grid, allow them accept *any* of the above notation, in addition to the current semicolon-separated notation. This lets copy & paste these values back and forth between Color Finder and properties.
> 4.0: redesign Color Finder, parse colors in various notations

- Compiler/script2/cc_symboltable.cpp
- Compiler/script2/cc_symboltable.h
- Compiler/script2/cs_parser.cpp
- Compiler/script2/cs_parser.h
- Compiler/script2/cs_scanner.cpp
- Compiler/test2/cc_bytecode_test_0.cpp
- Compiler/test2/cc_bytecode_test_1.cpp
- Compiler/test2/cc_parser_test_2.cpp
This partially addresses #2739.
Introduce a new keyword `__format`. 
This can adorn one string parameter of a variadic function. This will declare the function, such as `Character.Say`, as a _format function_ and the adorned parameter as the _format parameter_ of that function.
```
managed struct Character {
import void Say(__format string fmt, ...);
}
```
I'm envisioning that end users don't use the keyword, hence the leading `__`. It's very improbable that there is pre-existing code that has used `__format` in some (incompatible) way.
Whenever the compiler sees a call to a format function where the format parameter is passed a string literal, the compiler will check whether the variadic arguments of that call match the specifications in the format parameter.
```
cEgo.Say("Your backpack …
```
> New compiler: Check arguments of format functions (`String.Format()` …)  at compile time

- Common/util/string.h
- Editor/AGS.Editor.Tests/AGS.Editor.Tests.csproj
- Editor/AGS.Editor.Tests/Editor/Utilities/IncludeUtilsTests.cs
- Editor/AGS.Editor/AGSEditor.cs
- Editor/AGS.Editor/AGSEditor.csproj
- Editor/AGS.Editor/Tasks.cs
- Editor/AGS.Editor/Utils/IncludeUtils.cs
- Tools/data/include_utils.cpp
Resolve #2063
1. Implemented "IncludeUtils" class, porting existing code from agspak (see #2505).
2. Editor looks for the "template.files" file when making a template. If such file is present, then it will read a list of include/exclude patterns and use these to gather a list of files to package. If it's not present, then it will fall back to using standard list.
3. Editor matches the files found in the project folder and all the subfolders (of any nesting), but never any outside files.
NOTE: I only made a quick test with one-level subfolder, need to test that it can pack AND unpack multiple nesting levels properly.
NOTE: there's some strange logic with the standard file list, where Editor will make temporary file copies in order to package a template and later delete them. I can't …
> Editor: support a include/exclude file when making templates

- Solutions/Compiler.Lib/Compiler.Lib.Test.vcxproj
- Solutions/Compiler.Lib/Compiler.Lib.Test.vcxproj.filters
- Solutions/Tests.App/Common.Lib.Test.vcxproj
- Solutions/Tests.App/Common.Lib.Test.vcxproj.filters
- Solutions/Tests.App/Engine.App.Test.vcxproj
- Solutions/Tests.App/Engine.App.Test.vcxproj.filters
- Solutions/Tests.App/Tools.Test.vcxproj
- Solutions/Tests.App/Tools.Test.vcxproj.filters
fix #2762 
The idea here is to upgrade for a less old version, but still keep compatibility with older compilers and without requiring C++17.
This version of Googletest already includes Gmock in the same repository, so the files from Googletest were moved and we have to adjust some paths because of this.
When we merge with ags4, we will need to adjust the Compiler2 test solution too.
> Up googletest submodule to release 1.8.1

- Common/ac/characterinfo.h
- Engine/ac/character.cpp
- Engine/ac/characterextras.h
- Engine/ac/characterinfo_engine.cpp
- Engine/ac/movelist.cpp
- Engine/ac/movelist.h
- Engine/main/update.cpp
Fix #2744
This reimplements a default AGS behavior where character will keep at the previous position for 1 frame more before starting to move along the path.
Previously this worked because MoveList returned a *previous* position when updating. It is now returning a *new* position after a MoveList refactor and a introduction of MotionPath api. Therefore the "animation first" behavior has to be implemented in another way.
IMHO it's reasonable to not have this logic inside MoveList, as that makes MoveList having inconsistent state; instead this logic shall be a part of the Character which decides when to animate and when to move along the path.
Users of the MotionPath api can do according to their desire in script.
@AlanDrake , please try this and tell if this seems working to you. I …
> AGS 4: reimplement Character waiting 1 frame before moving to let animation advance

- Common/core/assetmanager.cpp
The check for asset existence can return too early without checking all libs.
To reproduce, start from BASS template, add a Music file, and check if it's Available. The problem only appears in compiled game, not in editor.
```
function room_FirstLoad()
{
if(aMusic1.IsAvailable)
{
player.Say("It's available.");
}
else
{
player.Say("It's NOT available.");
}
}
```
Looks like this got broken here:
https://github.com/adventuregamestudio/ags/commit/5cb40d3b371ffc31e3ec6eb71656716ff11f63d2
> Engine: fix check for asset existence

- Compiler/script2/cs_parser.cpp
- Compiler/test2/cc_parser_test_2.cpp
Fixes #2781
Fix a bug where the compiler wouldn't accept `null` as an argument for a `string` or `const string` parameter.
Typical code:
```
int func(const string s)
{
func(null); // ← Erroneous error message here
}
```
I'm taking this as an opportunity to also fix a bug where the compiler wouldn't accept `null` as a variadic argument in a format function for a `%s` format.
Typical code:
```
import int func(__format String s, ...);
void game_start()
{
func("%s", null);
}
```
> New compiler: Fix bugs around `null` as an argument for a function parameter

- Editor/AGS.Editor/AGSEditor.cs
- Editor/AGS.Editor/Components/RoomsComponent.cs
- Editor/AGS.Editor/InteractiveTasks.cs
- Editor/AGS.Editor/Tasks.cs
- Editor/AGS.Types/Game.cs
- Editor/AGS.Types/Room.cs
A while ago I've been trying to fix certain historical issue in ags4, but had to revert, as there appeared to be no room upgrade process in AGS 4, similar to the one existing for the game project awhole. This PR resolves that. But it does bit more.
1. Changed the project XML back to using a X.Y.Z.W string version instead of the decimal "index". Apparently CJ thought that index is easier to compare, but it's also more difficult to maintain (even though we switched to XXYYZZWW encoding around 3.6.0). String versions are arguably easier to have, and you may compare them by converting to the System.Version object.
2. I changed Game.SavedXmlVersion property to a Version object. It's a public member, so I wonder if that may have any consequences with editor plugins. But given this is ags4, …
> AGS 4: implement Room upgrading process

- .github/workflows/build.yml
- Engine/platform/windows/setup/advancedpagedialog.cpp
This adds some cool experimental ci runs from the public beta arm64 partner images.
I think these are fun, and also I have a raspiberry pi arriving tomorrow I want to play with. But the real reason I am doing this PR here (and leaving it in draft) is the error that will happen in the Windows Arm64 MinGW build, [on ci here](
const int AccessibilityPageDialog::TextReadSpeedMin;
const int AccessibilityPageDialog::TextReadSpeedMax;), highlighted below:
```
ld.lld: error: undefined symbol: AGS::Engine::AccessibilityPageDialog::TextReadSpeedMin
>>> referenced by C:/a/ags/ags/Engine/platform/windows/setup/advancedpagedialog.cpp
>>>               libengine.a(advancedpagedialog.cpp.obj)
ld.lld: error: undefined symbol: AGS::Engine::AccessibilityPageDialog::TextReadSpeedMax
>>> referenced by …
```
> ci: add Arm64 builds for Linux and Windows MinGW

- Compiler/script/cs_parser.cpp
- Compiler/test/cs_parser_test.cpp
Fixes #2799
Avoid a buffer overflow from a call to `sprintf()` when AGS source contains unicode characters (outside of string literals).
Typical code: 
```
int game_start()
{
¨
}";
```
I'm using this as an opportunity to also convert two other `sprintf()`calls to `snprintf()` calls that were in the same file `cs_parser.cpp`
> Bugfix: Avoid buffer overflow with unicode in source for (old) compiler 

- Editor/AGS.Editor/GUI/PropertiesPanel.cs
- Editor/AGS.Types/AGS.Types.csproj
- Editor/AGS.Types/Attributes/BrowsableMultieditAttribute.cs
- Editor/AGS.Types/AudioClip.cs
- Editor/AGS.Types/AudioClipType.cs
- Editor/AGS.Types/Character.cs
- Editor/AGS.Types/Dialog.cs
- Editor/AGS.Types/Font.cs
- Editor/AGS.Types/GUI.cs
- Editor/AGS.Types/GUIControl.cs
- Editor/AGS.Types/InventoryItem.cs
- Editor/AGS.Types/MouseCursor.cs
- Editor/AGS.Types/PaletteEntry.cs
- Editor/AGS.Types/RoomHotspot.cs
- Editor/AGS.Types/RoomObject.cs
- Editor/AGS.Types/RoomRegion.cs
- Editor/AGS.Types/RoomWalkBehind.cs
- Editor/AGS.Types/RoomWalkableArea.cs
- Editor/AGS.Types/Sprite.cs
- Editor/AGS.Types/View.cs
- Editor/AGS.Types/ViewFrame.cs
- Editor/AGS.Types/ViewLoop.cs
Fix #2802
Implemented BrowsableMultieditAttribute that marks properties that should or should not be displayed whenever multiple objects are selected for edit in PropertyGrid.
When PropertiesPanel.SelectedObjects is set, check whether there are multiple objects, and if yes then assign this custom attribute to the propertiesGrid.BrowsableAttributes collection. If a single object is selected, then reset BrowsableAttributes to defaults.
This allows to hide properties that must have unique values, such as Name, so that user won't try to edit them.
> Editor: hide certain properties when multiple objects are selected for editing.

- .github/workflows/build.yml
- CMakeLists.txt
- Common/util/string_compat.c
This adds Emscripten builds to GitHub Actions. The Emscripten builds don't run either the tests or the auto-tests yet, the regular test require some changes to be js and wasm only that could be run using node, and the `auto-test.ags` game will require a headless browser that can output the `console.log()` to the command line.
The difference between this build and the Cirrus one is mostly that even if not run, the Tools and the Tests are built.
> ci: add Emscripten builds to GitHub Actions

- Common/ac/gamestructdefines.h
- Common/font/agsfontrenderer.h
- Common/font/fonts.cpp
- Common/font/fonts.h
- Common/font/ttffontrenderer.cpp
- Common/font/ttffontrenderer.h
- Common/font/wfnfont.cpp
- Common/font/wfnfont.h
- Common/font/wfnfontrenderer.cpp
- Common/font/wfnfontrenderer.h
- Common/libsrc/alfont-2.0.9/alfont.c
- Common/libsrc/alfont-2.0.9/alfont.h
- Editor/AGS.Editor/AGSEditor.csproj
- Editor/AGS.Editor/Components/FontsComponent.cs
- Editor/AGS.Editor/NativeProxy.cs
- Editor/AGS.Editor/Panes/FontEditor.Designer.cs
- Editor/AGS.Editor/Panes/FontEditor.cs
- Editor/AGS.Editor/Panes/FontEditor.resx
- Editor/AGS.Editor/Panes/FontPreviewGrid.cs
- Editor/AGS.Editor/Utils/MathExtra.cs
- Editor/AGS.Native/NativeMethods.cpp
- Editor/AGS.Native/NativeMethods.h
- Editor/AGS.Native/agsnative.cpp
Resolve #2708
Redesigned Font preview panel, in order to help users see the font when used to draw an actual text, and be able to see all the font's characters when there are more than 256 of them.
1. Font panel is divided (uses splitter) into two parts:
* text preview
* font preview
2. Text preview allows you to type any text and see how it looks like with this font. This allows text wrapping, in order to test line spacing.
3. Font preview displays all the characters available in the font, with a scrollbar if they don't fit into the panel.
4. You can enter either character code or character itself into the input fields, and press "Goto" button to jump to wanted character.
5. You can select a character in the preview and it will be printed in the input fields.
6. Optionally the preview …
> Editor: Font preview redesign

- Common/ac/game_version.h
- Common/ac/gamestructdefines.h
- Common/font/agsfontrenderer.h
- Common/font/fonts.cpp
- Common/font/ttffontrenderer.cpp
- Common/font/ttffontrenderer.h
- Common/font/wfnfontrenderer.cpp
- Common/font/wfnfontrenderer.h
- Common/game/main_game_file.cpp
- Editor/AGS.Editor/AGSEditor.cs
- Editor/AGS.Editor/DataFileWriter.cs
- Editor/AGS.Native/agsnative.cpp
- Editor/AGS.Types/Font.cs
This is a remake of #2767.
@edmundito told me that he's too busy now, so I based on his work with few modifications:
* Added SetCharacterSpacing to the IAGSFontRendererInternal interface, to avoid redundant casts to WFN and TTF renderers.
* Do not scale CharacterSpacing with SizeMultiplier in WFNFontRenderer, for consistency with LineSpacing and VerticalOffset, and to let more precise spacing setting.
* Serialize character spacing property in the existing "v360_fonts" data extension, because it had reserved integers.
Overall the feature is the same:
1. Fonts have CharacterSpacing property.
2. This property defines a global spacing value, in pixels, which is *added* to the default spacing between any pair of characters (kerning).
3. This property is NOT scaled with the font's point size, …
> Support custom Font character spacing

- Common/gui/guidefines.h
- Editor/AGS.Editor/Resources/agsdefns.sh
- Engine/ac/display.cpp
- Engine/ac/display.h
- Engine/ac/gui.cpp
Someone reminded me recently, that there's no direct way to get TextWindow's border sprites.
This PR adds following readonly properties:
```
/// Gets the sprite number used for this TextWindow's left border
readonly attribute int TextWindowGUI.LeftGraphic;
/// Gets the sprite number used for this TextWindow's top-left corner
readonly attribute int TextWindowGUI.TopLeftGraphic;
/// Gets the sprite number used for this TextWindow's top border
readonly attribute int TextWindowGUI.TopGraphic;
/// Gets the sprite number used for this TextWindow's top-right corner
readonly attribute int TextWindowGUI.TopRightGraphic;
/// Gets the sprite number used for this TextWindow's right border
readonly attribute int TextWindowGUI.RightGraphic;
/// Gets the sprite number used for this TextWindow's …
```
> Script API:  add TextWindowGUI properties for getting border graphics

- Common/util/string_utils.cpp
- Common/util/string_utils.h
- Editor/AGS.Editor/Resources/agsdefns.sh
- Engine/game/savegame.cpp
- Engine/game/savegame_components.cpp
- Engine/game/savegame_internal.h
Someone (I think this was @NPatch ?) asked me about this back when I was working on a save upgrade / prescan system, but I postponed this and then forgot, so this piece was not included in 3.6.2.
Earlier we have "game meta information" serialized in game data, and available in script (see #2773).
This PR adds this information into the save. When the save is restored this info does not overwrite the current game's info of course, but is read into RestoredSaveInfo struct, and may be accessed in "validate_restored_save" and used to check the save's compatibility.
Perhaps there may be other uses for this, since this data will be in saves it will be possible to implement more with it in the future.
> Write game version into saves, let read it when scanning/validating a save

- Common/gui/guimain.cpp
- Common/gui/guimain.h
- Engine/ac/draw.cpp
- Engine/ac/gui.cpp
- Engine/gui/gui_engine.cpp
- Engine/main/game_run.cpp
Addresses #2821 (not fixes fully yet)
Fix #2817
This change caches values required by the labels with macros in them, so to prevent these labels from accessing other game data and updating game state right in the middle of their drawing function. The idea is that the timing of macro resolution should be strict and deterministic (and relative order compared with other parts of game update).
Additionally, fixes a potential issue in pre-3.6.0 games, which may appear after #1957, where we changed an order of cursor-related updates. Because of that change some older games may have overhotpost labels displaying text unintended (see #2817 for more details on this issue).
> Move label macro resolving from GUI draw functions + fix unintended overhotspot text in old games

- Editor/AGS.Editor/Resources/agsdefns.sh
- Engine/ac/character.cpp
- Engine/ac/dialog.cpp
- Engine/ac/display.cpp
- Engine/ac/display.h
- Engine/ac/gamestate.cpp
- Engine/ac/gamestate.h
- Engine/ac/overlay.cpp
- Engine/ac/overlay.h
- Engine/ac/screenoverlay.cpp
- Engine/ac/screenoverlay.h
- Engine/game/savegame_components.cpp
Resolve #2859
Reimplement Dialog Options drawing to create a screen overlay instead of a special texture. This makes them a part of the rest of the graphic objects. Add Dialog.OptionsZOrder script property, which lets to change dialog options sorting position among other overlays and GUIs. This allows to have custom effects on top of the dialog options, which is specifically useful for custom drawn cursors.
> Dialog options as screen overlay
