adventuregamestudio/ags

Editor/AGS.Types/SerializeUtils.cs
Timestamps are written to the file Game.agf with the UTC time standard, which adds an 'Z' at the end of the time stamp. However the read from Game.agf did not account for this and was thrown off by the 'Z' character, adding a couple of hours to the time stamp every time the editor was booted up. This should now be fixed.
=> Game.agf: Wrote faulty timestamps to audio files

Editor/AGS.Editor/GUI/GUIController.cs, Editor/AGS.Editor/GUI/TabbedDocumentManager.cs, Editor/AGS.Editor/GUI/frmMain.cs, Editor/AGS.Types/Interfaces/IGUIController.cs
Previously the active pane was the only one which was exposed, but it may be useful for plugin authors to know if a certain pane exists even if it is not currently active. As the active pane was always accessible (regardless of owner), this does not violate the security of the collection, which is now exposed as read-only.
=> Exposed editor panes to plugin API

Editor/AGS.Types/ScriptsAndHeaders.cs
The majority of use cases probably won't need the index when looking up a ScriptAndHeader by filename, so don't require it.
=> Don't require out parameter in ScriptAndHeader look-up

Compiler/script/cs_parser.cpp
This handles *= as a special case inside a parameter declaration. I wasn't aware of this initially, but the inclusion of a *= symbol breaks compatibility with one particular syntax for parameter declarations available in older versions of AGS. The symbol is now broken into two when it occurs directly after a variable type.
=> Scripting: Do not parse *= as one entity in parameter declarations

Editor/AGS.Editor/Components/SpeechComponent.cs, Editor/AGS.Editor/Entities/SpeechLipSyncLine.cs, Engine/ac/character.cpp, Engine/ac/game.cpp, Engine/ac/global_audio.cpp, Engine/ac/lipsync.h, Engine/main/engine.cpp, Engine/main/udpate.cpp
This issue was originally submitted by AGD2. The AGS bug tracker entry can be found here:
http://www.adventuregamestudio.co.uk/forums/index.php?issue=628.0
As stated in the bug tracker entry, Pamela has long been superseded as a method for generating lip sync files. It's buggy and creating the lip sync data is a very manual process. The authors of the software that Pamela was built for have created their own tool called Papagayo. This patch adds support for its .dat file format (which is extremely similar and even a bit simpler than the Pamela format). As AGD2 is the guy who originally suggested Pamela, I think we can trust his research that Papagayo is a worthwhile replacement tool.
AGD2 gave me a test project that can be used to verify support: …
=> Editor: Papagayo .dat File Support for Lip-syncing

Compiler/script/cs_parser.cpp, Compiler/script/cs_parser_common.h
This allows syntax like `for(int i = 0; i < 10; i++)` where `i` is a variable local to the for loop. I started this a long time ago when someone complained about for loops not really being useful in their current state. I thought it would be good for completeness.
=> Scripting: Allow variable declarations in for loop initialisers

Compiler/script/cc_symboltable.cpp, Compiler/script/cc_symboltable.h, Compiler/script/cs_parser_common.h
This replaces all of the fixed-size arrays in the symbol table with vectors. Between 3.3.3 and 3.4.0, some 75 (approximately) new symbols were added to the default environment. This includes new operators, new statements and many new API methods and brings the total to about 2,100 symbols without any user code. It surfaced as a problem recently with one particular game that compiled under 3.3.3 but broke in 3.4.0. The game defined 9980 symbols in a script and the new changes pushed it over the 10,000 symbol limit.
=> Scripting: Remove 10,000 symbol limit

Compiler/script/cc_compiledscript.cpp
This was supposed to be a check for functions with prototypes inside a managed struct that returned a pointer to that struct, e.g.
```
managed struct myStruct
{
import myStruct *getOne();
int x;
};
```
The struct size is unknown at the time of the `getOne()` declaration. At the time of parsing the function body, the check was supposed to grab the real struct size from the return type of the function. Unfortunately, this was occurring with lots of symbols, not just function bodies. Those other symbols don't really have return types (or even an initialised funcparamtypes array for that matter).
This was the cause of cat's bug report in the main 3.4.0.x thread:
http://www.adventuregamestudio.co.uk/forums/index.php?topic=51050.msg636507341#msg636507341
(I sent her a test build and she's …
=> Scripting: Only look up final struct sizes for functions

Compiler/script/cs_parser.cpp
Some of the info written when inserting the loop increment chunk incorrectly referred to `nested_level`, which may or may not have been initialised. The correct location is `loop_level` (as can be seen in the
rest of the function call. This was a typo and/or bad copy+paste on my part. It's possible I originally had `nested_level` and changed some variables but not others on that line.
=> Scripting: Write correct loop increment info

Editor/AGS.Editor/Entities/EditorPreferences.cs, Editor/AGS.Editor/GUI/PreferencesEditor.Designer.cs, Editor/AGS.Editor/GUI/PreferencesEditor.cs, Editor/AGS.Editor/GUI/TabbedDocumentManager.cs
In reference to this http://www.adventuregamestudio.co.uk/forums/index.php?topic=51050.msg636513768#msg636513768 
> Also, regarding removal of the confirmation prompt when closing all other tabs, can I make a request for that to be reimplemented (or at least optional in the settings)? Many's the time I've had numerous important tabs open (sometimes 30+) when I accidentally mis-clicked "close all tabs". That confirmation prompt saved my skin and prevented me from losing my place during complex coding sessions. Since 'closing all other tabs' doesn't seem to be an action the user will be performing very frequently, I think the usefulness of the safeguard outweighs the minor hindrance of having to click an extra dialog button from time to time.
- Added a checkmark in Preferences for if a …
=> Prompt dialog when "closing all tabs" and "closing all other tabs"

Compiler/script/cc_compiledscript.cpp
Fixups were not being adjusted correctly when inserted multiple times in a for loop. Here's a simplified test case (crashes 3.4.0.5):
```
/* Global scope */
int j;
...
/* Somewhere in a function scope */
for(j = 0; j < 5; j++)
continue;
```
=> Scripting: Fixed reuse of fixups in write_chunk

Compiler/script/cs_parser.cpp
The previous validation for expressions within an array was a little too strict. This adds another exception (in addition to commas) for struct types. Also added a break if the struct isn't followed by a dot. As type conversion won't throw an error, this ensures we don't get a static non-property access error.
=> Scripting: Permit static method calls as array indices

Editor/AGS.Editor/GUI/FindReplaceDialog.Designer.cs, Editor/AGS.Editor/GUI/FindReplaceDialog.cs, Editor/AGS.Editor/Panes/ScintillaWrapper.cs, Editor/AGS.Editor/TextProcessing/FindReplace.cs
1. "Case sensitive" check box does not remember its value.
Rewrote the handling for remembering checked value of "Case Sensitive". Mimicking the behaviour of the same feature in Visual Studio it will now remember the value when checked, regardless if a search / replace was made or not.
2. The order of cycling (tabbing) though controls is wrong: "Search for" field is followed by "<< Find" button; must be followed by "Replace with" field instead ("<< Find" button should probably go after all setup fields).
Implemented exactly as described. Setup fields first., then "<<Find/Replace" button, and finally "Find", "Replace" and "Cancel" buttons.
3. Replace / Find All doesn't look at the first line
When attempting a replace / find all, the index position of the search was set to 0, and then …
=> Find / Replace Dialogue Issues

Editor/AGS.Editor/Components/SpeechComponent.cs
Any lip sync data files that contain a non-number where a number would be expected will now be silently ignored. It is assumed that these are files not related to Pamela or Papagayo.
=> Editor: Ignore lip sync files with invalid data

Compiler/script/cc_compiledscript.cpp, Compiler/script/cc_compiledscript.h, Compiler/script/cc_symboldef.h, Compiler/script/cc_symboltable.cpp, Compiler/script/cc_symboltable.h, Compiler/script/cs_compiler.cpp, Compiler/script/cs_parser.cpp, Compiler/test/cc_symboltable_test.cpp, Compiler/test/cs_parser_test.cpp, Solutions/Compiler.Lib/Compiler.Lib.Test.vcproj
* Allow record member qualifiers to be in any order
* friendly names for types in error messages
* fix readonly crashes
=> Compiler symbol fixes

Compiler/script/cc_compiledscript.cpp, Compiler/script/cc_symboldef.h, Compiler/script/cc_symboltable.cpp, Compiler/script/cc_symboltable.h, Compiler/script/cs_parser.cpp, Compiler/script/cs_parser_common.h, Compiler/test/cs_parser_test.cpp
* parse integers with overflow checks
* allow default parameters up to INT_MIN/INT_MAX
* support negative enums
=> Compiler int fixes

Editor/AGS.Editor/ApplicationController.cs, Editor/AGS.Editor/Components/AudioComponent.cs, Editor/AGS.Editor/Components/FontsComponent.cs, Editor/AGS.Editor/EditorEvents.cs, Editor/AGS.Editor/Panes/FontEditor.cs, Editor/AGS.Editor/Panes/SpriteSelector.cs, Editor/AGS.Editor/Tasks.cs, Editor/AGS.Editor/Utils/Utilities.cs, Editor/AGS.Types/Interfaces/ISpriteFolder.cs, Editor/AGS.Types/SpriteFolder.cs
Reference: http://www.adventuregamestudio.co.uk/forums/index.php?issue=520.0
Importing sprites, audio and fonts would always store absolute file path in the property "SourceFileName". It now stores relative path if the file is found inside the Game Project, or absolute path if it is from outside of the game project. This is useful if the the game project is moved to another place on a local computer, or if the game project is shared between multiple collaberators on each their private computer.
Examples:
Relative Path: Resources/Sprites/MySprite.bmp
Absloute Path: D:/MyGameProject/Resources/Sprites/MySprite.bmp
=> Absolute Paths for Resources

PSP/Makefile, Plugins/Makefile.psp, Plugins/ags_parallax/ags_parallax.cpp
Changes to assist in building PSP builds in teamcity.
(against master so it can be merged into develop-* branches)
=> PSP: Fix build scripts for building in linux.

Common/util/ini_util.cpp, Common/util/ini_util.h, Common/util/inifile.cpp, Common/util/inifile.h, Common/util/math.h, Common/util/string.cpp, Common/util/string.h, Common/util/textstreamreader.cpp, Common/util/textstreamwriter.cpp, Engine/ac/gamesetup.h, Engine/main/config.cpp, Engine/main/config.h, Engine/platform/android/acpland.cpp, Engine/platform/ios/acplios.cpp, Engine/platform/psp/acplpsp.cpp, Engine/setup/acwsetup.CPP, Engine/test/test_all.cpp, Engine/test/test_file.h, Engine/test/test_inifile.cpp, Engine/test/test_string.cpp, Solutions/Common.Lib/Common.Lib.vcproj, Solutions/Engine.App/Engine.App.vcproj, iOS/xcode/ags/ags.xcodeproj/project.pbxproj
Few planned future updates requires writing certain options back to config file on exit.
Unfortunately, config write functions provided by Allegro 4 library proved to not be fully reliable: they fail if the config file format is slightly different from their expectations; besides there is a chance we will be moving away from Allegro 4 in the future.
This pull request introduces IniFile class that constructs a description of INI either by parsing a file or by user command, allows to iterate sections and items, and write the contents back into file. IniFile supports merging changes into existing file; this is implemented by remembering precise locations of items in the text. If a single existing item value was changed by user, it is replaced while keeping the rest of the contents unchanged. …
=> IniFile class and reading game config from the generic key-value map

Compiler/script/cs_parser.cpp
This is an improved implementation of switch(). I found multiple issues with my previous implementation. Using non-local variables inside the switch() part caused problems and it was just way more complicated than it needed to be. It also recalculated the switch part for each case statement, which was incorrect. The new implementation stores the result of the switch() statement on the stack and loads it into a register for comparison when necessary.
=> Scripting: Improve switch() statement

Common/util/geometry.h, Editor/AGS.Editor/Resources/agsdefns.sh, Engine/ac/game.cpp, Engine/ac/gamesetup.cpp, Engine/ac/gamesetup.h, Engine/ac/global_screen.cpp, Engine/ac/mouse.cpp, Engine/ac/room.cpp, Engine/device/mousew32.cpp, Engine/device/mousew32.h, Engine/main/config.cpp, Engine/main/config.h, Engine/main/engine.cpp, Engine/main/graphics_mode.cpp, Engine/main/graphics_mode.h, Engine/main/quit.cpp, Engine/resource/resource.h, Engine/resource/version.rc, Engine/script/script_api.h, Engine/setup/acwsetup.CPP, Solutions/Engine.App/Engine.App.vcproj
Implemented mouse speed setting with Script API binding.
* Mouse speed is a multiplier of type 'float'.
* The multiplier is applied only when game is run in Fullscreen mode.
* Initial value is taken from configuration file (section 'mouse', entry 'speed'). There are two modes, defining how the user setting is converted into real multiplier: absolute (1:1) and relative to display mode, which tries to keep speed/resolution relation based on current desktop resolution.
* Added Mouse.Speed property to Script API (allows game developers to implement a mouse speed slider in their game, if they like to).
* On game exit current mouse speed is saved back to the configuration file.
* Related slider control added to Windows setup program.
Notably, this pull request also disables Allegro's mouse …
=> Mouse speed setting

Engine/Makefile-defs.linux, Engine/ac/game.cpp, Engine/ac/game.h, Engine/ac/gamesetup.cpp, Engine/ac/gamesetup.h, Engine/ac/global_game.cpp, Engine/device/mousew32.cpp, Engine/device/mousew32.h, Engine/main/config.cpp, Engine/main/engine.cpp, Engine/main/game_run.cpp, Engine/main/quit.cpp, Engine/platform/base/agsplatformdriver.cpp, Engine/platform/base/agsplatformdriver.h, Engine/platform/linux/acpllnx.cpp, Engine/platform/windows/acplwin.cpp, Engine/resource/resource.h, Engine/resource/version.rc, Engine/setup/acwsetup.CPP
This pull request implements an optional mouse lock (aka mouse grab) in game window.
This option was requested by numerous players, because most of AGS games are mouse controlled, and if the game object is located close to the edge of the screen, it is possible to occasionally click outside of the window and loose control over game.
This is even more essential for games where character, or other entity is controlled by cursor movement in real time.
* Mouse lock only activates in windowed mode (fullscreen mode grabs mouse by definition).
* Manual mouse lock is toggled with Alt + Ctrl key combination anytime game has input focus.
* Automatic lock is enabled in config: section "mouse", entry "auto_lock". Automatic lock is performed whenever game receives input focus or user clicked inside …
=> Mouse lock option

Editor/AGS.Editor/AGSEditor.csproj, Editor/AGS.Editor/Components/HelpCommandsComponent.cs, Editor/AGS.Editor/Utils/AlternateStreams.cs
Add utility class to read and delete NTFS alternate streams. If the help
file exists check it's zone identifier, remove if it's potentially
restrictive.
=> Read and remove Zone Identifier on the help file.

Editor/AGS.Controls/ScintillaNET/ScintillaControl.cs, Editor/AGS.Controls/ScintillaNET/WinAPI.cs
In reference to: http://www.adventuregamestudio.co.uk/forums/index.php?topic=52805.0
The Scintilla Control uses the text edit mouse cursor, but when WM_SETCURSOR was sent back to WinForms it was overriden and set to the default arrow cursor. This commit makes sure that WM_SETCURSOR is not sent back to WinForms.
=> Editor: Mouse flickering in the code editor

Engine/ac/event.cpp, Engine/ac/record.cpp, Engine/debug/debug.cpp, Engine/main/engine.cpp, Engine/media/audio/soundcache.cpp, Engine/platform/android/acpland.cpp, Engine/platform/base/agsplatformdriver.cpp, Engine/platform/base/agsplatformdriver.h, Engine/platform/dos/acpldos.cpp, Engine/platform/ios/acplios.cpp, Engine/platform/linux/acpllnx.cpp, Engine/platform/osx/acplmac.cpp, Engine/platform/psp/acplpsp.cpp, Engine/platform/windows/acplwin.cpp, Engine/platform/windows/gfx/ali3dd3d.cpp
This simplifies printing functions in the platform "driver" classes by removing duplicated code and limiting them to distinct implementations, and also by getting rid of intermediate string buffers where possible.
In short, only Android and Windows now override common "printf" behavior.
Additionally made Windows version write to stdout if not run under debugger (prior it was always writing to the debugger output, even if it was not present).
=> Minor improvements related to logging to standard output

debian/rules
Rebased #300 on master branch, and made debian revision optional instead of removing it. Version info returned by sed will include debian revision, but this does not prevent build scripts from running.
=> Fixed debian rules: make debian revision optional

Common/gui/guimain.h, Editor/Native/acgui_agsnative.cpp, Engine/ac/character.cpp, Engine/ac/character.h, Engine/ac/display.cpp, Engine/ac/display.h, Engine/ac/drawingsurface.cpp, Engine/ac/drawingsurface.h, Engine/ac/global_api.cpp, Engine/ac/global_character.cpp, Engine/ac/global_character.h, Engine/ac/global_display.cpp, Engine/ac/global_display.h, Engine/ac/global_drawingsurface.cpp, Engine/ac/global_drawingsurface.h, Engine/ac/global_game.cpp, Engine/ac/global_game.h, Engine/ac/global_overlay.cpp, Engine/ac/global_overlay.h, Engine/ac/global_string.cpp, Engine/ac/global_string.h, Engine/ac/overlay.cpp, Engine/ac/overlay.h, Engine/ac/string.cpp, Engine/ac/string.h, Engine/script/script_api.cpp, Engine/script/script_api.h, Engine/test/test_sprintf.cpp
This fixes my oversight made long ago when I was rewriting Script interpreter, introducing safer argument list.
A number of engine functions kept redundant variadic parameter list and string printf-to-buffer operations, while they were always called with "%s" format string in every practical case, and required just a constant string.
Additionally, *get_translation()* was being called for the "%s" string in all those functions.
Aside from doing excess work, this caused a bug. A *source_text_length* global variable is set inside *get_translation()* to remember pre-translated text length, which in turn could be used to calculate time required to display the text message on screen. Of course, since get_translation was being called for the second time for "%s" string, this length was always …
=> Fixing the cases of redundant consequent vsprintfs and text translation in the Script API functions

debian/changelog, debian/make_ags+libraries.sh, debian/rules
As noted in #301 the debian/changelog file is actually a *fake* changelog which only exists to allow the debian package tools to function correctly. With this change, the make_ags+libraries script will now read the version info from Common/core/def_version.h, update the changelog file so the debian package tools can run, then reset the changelog file to prevent unnecessary commits.
This also removes the use of dpkg-parsechangelog from debian/rules, because I found that it requires loading several external libraries just to parse the version info. This could be made as a separate commit, if necessary.
It may additionally be worth noting in the debian readme that the changelog is not meant to be changed or updated.
=> Remove changelog dependency from debian/make_ags+libraries script

Compiler/script/cs_parser.cpp
Copies the 'default value exists' flag when structs are forward declared, fixing the incorrect 'Not enough parameters in call to function' error when member functions were invoked without all parameters (required or not).
=> Compiler: Copy default value flag on forward declared structs

Compiler/script/cs_parser.cpp, Compiler/test/cs_parser_test.cpp
This fixes #295 
The tokeniser will now recognise negative numbers as single symbols. `-` continues to be the unary negation operator for situations where the sign and number are separated by a space, e.g. `int x = - 4;`. The specific case of someone negating a negative constant is disallowed.
Some interesting edge cases:
```
int a = 3 - -4; // Legal, previously not allowed
int a = a - -2147483648; // Ditto
int a = a - 2147483648; // Not legal, +2147483648 is out of range
int a = - 2147483648; // Legal (unary negation)
```
Note: This behaviour is in line with C#.
=> Compiler: Better parsing of negative numbers

Editor/AGS.CScript.Compiler/Entities/FastString.cs, Editor/AGS.Editor/AutoComplete.cs
This fixes a bug in auto-complete, the simplest test case for which is a new script file with:
```
{
//
```
Insert a new line *before* the `{` and start typing `int`. The editor will encounter an index out of range exception. The `IncrementIndexToSkipAnyComments` function checked for a multiline comment immediately after a single line comment, but did not ensure that the index was within the bounds of the script. It also only advanced past one comment at a time (or maybe two if you had a multiline following a
single line). I rewrote the function to do what I thought it should do: advance past all comments in succession and return true if the end of the script was reached.
=> Editor: Fixed index out of range exception

Common/ac/common_defines.h, Editor/AGS.Editor/Panes/RoomEditFilters/ObjectsEditorFilter.cs, Editor/AGS.Native/agsnative.cpp, Editor/AGS.Types/RoomObject.cs
Thanks to CalinLeafshade's prior work, AGS allows the user to lock GUI controls. This commit implements locking for room objects with consistent appearance and behaviour to locked GUI controls. Locked objects can't be moved by mouse or keyboard and have an X in the centre. The unused flag, `OBJF_DELETED` has been repurposed as `OBJF_LOCKED`.
=> Editor: Allow room objects to be locked like GUI controls

Engine/platform/linux/acpllnx.cpp
This reverts the commit for fixing X11 mouse lag which seems to cause with input polling (very long delay ~20 seconds) and enables mouse control. It seems that, without mouse control enabled, cursor movement restrictions are not aligned with game display when running fullscreen  - the issue may only show where game display does not fill the screen, i.e. running fullscreen with borders.
Provides opportunity for anyone using the Linux build to build it and report issues.
=> Linux: Revert mouse behaviour for testing

Common/gui/guimain.cpp
The boundaries in the checks used by GUI.GetAtScreenXY() are incorrect. They are inclusive of the bottom/right edges, which means that the row after the bottom of a GUI is considered part of the GUI, and likewise for the column after the right of a GUI.
Here's a screenshot from my test project that hopefully illustrates the problem:
There is one GUI on the screen -- grey with a green border. The mouse is on the very bottom row, shown as a single red dot. The "(190, 199) = 1" indicates that AGS thinks this row is within the GUI. Project files for the curious: http://goo.gl/dlkymd (3.4.0.x)
This is just a simple commit to make GUI.GetAtScreenXY() check the bottom and right edges with `<` rather than `<=`.
Should this be behind a backwards compatibility check? I tend to think it's …
=> Engine: Correct right/bottom boundaries for GUI.GetAtScreenXY()

Common/script/cc_error.cpp, Compiler/script/cs_parser.cpp, Compiler/test/cs_parser_test.cpp, Editor/Native/script_agsnative.cpp, Engine/script/script_engine.cpp
Addresses the issue reported here:
http://www.adventuregamestudio.co.uk/forums/index.php?issue=718.0
AGS will now distinguish between runtime errors and errors where the line number is not known. Additionally, the line number is now reported for "Function still open, missing }" compilation errors.
Note: I understand there is a big merge from 3.3.x -> 3.4.0 happening right now, so I don't expect this to be merged right away.
=> Scripting: Clarify the unclosed brace error message

Engine/Makefile-defs.linux, debian/README.md
This removes redundant linking options from the Linux makefile.
Notably, libice and libsm libraries are no longer required to be linked on Debian and Ubuntu systems.
Additionally, corrected debian package name in the debian/README.
=> Patch Linux makefile

Plugins/AGSflashlight/agsflashlight.cpp, Plugins/ags_parallax/ags_parallax.cpp, Plugins/ags_snowrain/ags_snowrain.cpp
This fixes compilation errors when using gnu gcc-6. The root of the problem is that the standard library headers were included inside plugin namespaces.
=> Fix gcc-6 compilation

Compiler/script/cs_parser.cpp
Continuing the work here:
https://github.com/adventuregamestudio/ags/pull/154
And addressing concerns here:
http://www.adventuregamestudio.co.uk/forums/index.php?issue=361.0
I see two other situations where global names might conflict with struct member names.
1. A struct member has the same name as a global variable, e.g. a GUI
2. A struct member has the same name as a type, e.g. `function MyStruct::Object()`
This is an attempt to tidy up the namespacing of struct members and allow for both of these cases. 
Allowing global variables was easy to achieve. Most namespacing is done at the tokenise step. We just needed to allow tokens of that type to be prefixed with the struct name.
Allowing type names had to happen later in the process (during parsing). It's not known at the point of …
=> Scripting: Struct namespacing

Compiler/script/cc_compiledscript.cpp, Compiler/script/cs_parser.cpp, Compiler/script/cs_parser.h
A couple of things left out of the previous implementation. Continue statements inside switch blocks were being incorrectly rejected as outside a loop. A `case` statement immediately following a `default` label would be evaluated.
Note: I understand there is a big merge from 3.3.x -> 3.4.0 happening right now, so I don't expect this to be merged right away.
=> Scripting: Switch statement improvements

Compiler/script/cs_parser.cpp, Compiler/test/cs_parser_test.cpp
My recent pull request to allow struct members to share names with global types included a Boolean variable to simplify some checks. The check was performed a bit too early and broke function parsing for methods that return dynamic arrays.
- Moved the check to the correct location
- Added a test for parsing structs with methods returning dynamic arrays so it doesn't happen again
=> Scripting: Fix dynamic array parsing in structs

Common/ac/gamestructdefines.h, Editor/AGS.Editor/AGSEditor.cs, Editor/AGS.Editor/DataFileWriter.cs, Editor/AGS.Editor/Panes/ScintillaWrapper.cs, Editor/AGS.Editor/Resources/agsdefns.sh, Editor/AGS.Editor/Tasks.cs, Editor/AGS.Editor/Utils/NativeConstants.cs, Editor/AGS.Native/NativeMethods.cpp, Editor/AGS.Native/agsnative.cpp, Editor/AGS.Types/AGS.Types.csproj, Editor/AGS.Types/Enums/ScriptAPIVersion.cs, Editor/AGS.Types/Game.cs, Editor/AGS.Types/Settings.cs
This implements a switch that determines which variant of Script API will be used when compiling project scripts. This allows to compile old scripts in newer enviroment without changes.
Perhaps not the biggest, but probably most user-irritating problem so far that we had regarding script compatibility was that when we change existing functions or add new names to Script API, that may break old scripts, and require upgrading them.
AGS already has few backward compatibilty settings like this, but they related to very specific cases of API change, and it was not reasonable to extend their use.
With API version switch this problem has a faster solution: if user does not want to fix his/her scripts, he/she may simply set the switch to API version they used before, and continue their work.
This …
=> Script API version switch in the game project settings

Script/build_packages.py, Windows/Installer/ags.iss, Windows/Installer/build.py, version.json
This adds an optional version tag which is appended to the package/installer file names (as well as app name the Editor is registered on Windows with when installed). This tag can be used, for example, to specify beta version, or patch number to make it easier for end users to distinguish updates of same public release.
=> Installer: support for optional extra version tag

Compiler/script/cs_parser.cpp
Added checks for end of file before string comparisons involving symbol names. Standardised end of file check with a common function.
This might require a little work to merge into 3.4.0. There were some changes made to the various EOF checks with the commit to make errors without lines distinct from runtime errors.
=> Scripting: Added / standardised checks for EOF

Compiler/script/cs_parser.cpp, Compiler/script/cs_parser_common.h
Give an error on the declaration of such a variable. This closes a hole in the compiler for now.
=> Scripting: Prevent arrays of structs with dynamic array members

Common/gui/guimain.cpp, Common/util/file.cpp, Common/util/math.h, Common/util/mutifilelib.cpp, Common/util/string.cpp, Common/util/string.h, Engine/ac/file.cpp, Engine/ac/global_gui.cpp, Engine/main/config.cpp, Engine/script/script.cpp, Engine/test/test_string.cpp
Initially I wrote String class using ints for buffer length and indexes for some reasons, now changing to size_t.
This is long overdue, but something distracted me all the time from committing.
NOTE: We currently have string tests in the engine, which are only built in Debug configuration, and run at program startup. I was referencing to them to check that this conversion is correct.
=> Changed String class to use size_t for lengths and indexes instead of int

Common/game/customproperties.h, Common/util/stdtr1compat.h, Common/util/string_types.h, Engine/script/cc_instance.h, Solutions/Common.Lib/Common.Lib.vcproj
Also checks for VS2015, which is the earliest version of Visual Studio which doesn't need the TR1 namespace for these headers (AFAICT).
=> Moved stdtr1compat to a header file

Common/core/types.h
VS2015 is the first Visual Studio which has proper support for `<stdint.h>`, but barfs on these macro replacements. This just excludes the macros for VS2015 and later, and pulls the header instead.
=> Fix for VS2015 standard types

Common/util/c99_snprintf.h, Common/util/string_utils.h, Engine/libsrc/apeg-1.2.1/audio/mpg123.c, Engine/script/script_api.cpp, Solutions/Common.Lib/Common.Lib.vcproj
MSVC's "_snprintf" is **not** C99-compliant as it does not truncate the buffer on overflow (correction: it does limit how much it writes, but does not null-terminate the buffer). As such it is not a safe replacement for snprintf (as is currently implemented). This provides an alternative that is C99-compliant. Additionally, VS2015 implements a C99-compliant snprintf which causes the existing macro to fail with a compile error. This does not supply the macro if not building with MSVC or if using VS2015 or later.
=> C99-compliant snprintf replacement for MSVC

Editor/AGS.Editor/AGSEditor.cs, Editor/AGS.Editor/BuildTargets/BuildTargetDataFile.cs, Editor/AGS.Editor/BuildTargets/BuildTargetDebug.cs, Editor/AGS.Editor/BuildTargets/BuildTargetLinux.cs, Editor/AGS.Editor/BuildTargets/BuildTargetWindows.cs, Editor/AGS.Editor/Components/AudioComponent.cs, Editor/AGS.Editor/Components/SpeechComponent.cs, Editor/AGS.Editor/Components/TranslationsComponent.cs, Editor/AGS.Editor/DataFileWriter.cs, Editor/AGS.Editor/Panes/GeneralSettings.cs
This is equal parts clean-up and a feature-fix for the AndroidBuilder plugin I am working on. Everything appears to build and run properly, including audio and speech VOX files and debug.
Particularly, the `jobb` tool used in Android deployment takes an entire directory (recursively) as input, so the data files need to be in a separate directory.
=> Redirected main output files to Compiled/Data

Engine/ac/global_audio.cpp
Ensure that GetVoiceMode (the Speech.VoiceMode getter) returns the correct value when a vox file isn't available. Operations need to be done in reverse order of those in SetVoiceMode.
=> Engine: Fix return value for GetVoiceMode

Engine/ac/character.cpp
Calling ChangeView during the playback of an idle animation animates the wrong view.
Can be easily tested with something like this:
`	cEgo.SetIdleView(15, 0);
Wait(50);
cEgo.ChangeView(10);`
This is unexpected behaviour, other functions that change the view make sure to check if the idle is playing and if so unlocks the view and resets the "idleleft" timer.
I've also tested against LockedView() and all performs as expected.
=> Engine: fix for idle animation potentially animating the wrong view

Common/game/main_game_file.cpp
gcc 6.2 and clang 4.0 optimize away the previous check because an
unsigned variable (size_t newlen) is compared to an signed
negative constant (0xCAFEBEEF).
Solves part of issue #366.
=> Fix check for CAFEBEEF magic value

Common/ac/characterinfo.h, Common/ac/gamestructdefines.h, Editor/AGS.Editor/Resources/agsdefns.sh, Editor/AGS.Types/Enums/ScriptAPIVersion.cs, Engine/ac/character.cpp, Engine/ac/object.cpp, Engine/ac/roomobject.h
Added **properties for getting Tint component values** from Characters and room Objects.
Added **LightLevel readonly property** (SetLightLevel is still used to explicitly set light level).
Added **HasExplicitLight** to Character to complement **HasExplicitTint**, and add both of same properties to the Object.
This makes Character and Object's tint API compliant to the Region API in ways to read currently applied light & tint parameteres, and complementary to each other.
An explanation is due, why I propose to still have SetLightLevel to set light for characters and objects, as opposed to Region.LightLevel property serving as both setter and getter of a light level.
Unlike Region, which always has **some** light level set (even if default 0, meaning no change in lighting), Character and …
=> ScriptAPI: Character and Object properties for getting tint values

Common/ac/game_version.h, Common/ac/gamestructdefines.h, Common/game/main_game_file.cpp, Common/game/main_game_file.h, Editor/AGS.Editor/DataFileWriter.cs, Engine/game/game_init.cpp, Engine/main/game_file.cpp
There is an issue with alternate versions of AGS Editor that they have no means to tag their games so that original engine could at least detect that the game does not work as expected before trying to load and run it. General data format number is not suitable for this purpose, because there is no guarantee that it won't be duplicated by "official" engine, or another alternate editor.
While there are not so many alternate versions, sometimes users try to run such games with regular engine or its port, and they receive no elaborate message why had this happened.
This change adds simply an *optional* list of strings at the game data header, called "extended capabilities". When the game is opened engine tests the required list of caps with the caps it supports.
It is true that there is no …
=> Provide means for the alternate versions of AGS to indicate their games

Common/ac/game_version.h, Common/ac/gamesetupstruct.cpp, Common/ac/gamesetupstruct.h, Common/font/agsfontrenderer.h, Common/font/fonts.cpp, Common/font/fonts.h, Common/font/ttffontrenderer.cpp, Common/font/ttffontrenderer.h, Common/font/wfnfontrenderer.cpp, Common/font/wfnfontrenderer.h, Common/game/main_game_file.cpp, Editor/AGS.Editor/DataFileWriter.cs, Editor/AGS.Types/Font.cs, Engine/game/game_init.cpp
The ALFont library currently used by AGS to draw TTF is built around very old version of the FreeType font, and also have some additional tweaks done by Chris Jones. It has an issue that it ignores font's descent parameter while keeping its real height, thus aligning font's baseline to the bottom line. This results in some fonts rendered lower than expected.
This pull request adds an optional vertical offset property to fonts, which is applied when a text line is drawn. It works for fine relative positioning of the line of text.
A note should be made that even after we upgrade or fix fonts library, this property may still come handy for dealing with backwards-compatibility cases and imperfectly designed fonts.
=> Font vertical offset property

Engine/main/config.cpp, Engine/main/config.h, Engine/main/engine.cpp, Engine/platform/base/agsplatformdriver.h, Engine/platform/linux/acpllnx.cpp, Engine/platform/windows/acplwin.cpp
As of (rather old) feature request (#287), this adds support for user's global configuration file, that is - a single file that is applied for every game.
The suggested rule is that config files are read in following order, every next one overridding previous ones (only options that are included in the current file are overridden, options that are not included keep their values from previous configs):
* config file inside game installation directory (aka "default game config");
* user's global, all-games config file;
* user's game-specific config file.
The latest is also one that is allowed to be modified by the engine (for example, to write config options that could be changed at runtime, such as game translation).
Actual config location is different for every platform. At the moment …
=> Global (all-games) user configuration

Engine/ac/dialog.cpp, Engine/ac/invwindow.cpp, Engine/ac/record.cpp, Engine/ac/record.h, Engine/ac/room.cpp, Engine/gfx/ali3dogl.cpp, Engine/gfx/ali3dogl.h, Engine/gfx/ali3dsw.cpp, Engine/gfx/ali3dsw.h, Engine/gfx/gfxdriverbase.cpp, Engine/gfx/gfxdriverbase.h, Engine/gfx/gfxfilter_allegro.cpp, Engine/gfx/gfxfilter_allegro.h, Engine/gfx/gfxfilter_hqx.cpp, Engine/gfx/gfxfilter_hqx.h, Engine/gfx/graphicsdriver.h, Engine/main/engine.cpp, Engine/main/engine.h, Engine/main/game_run.cpp, Engine/main/graphics_mode.cpp, Engine/main/graphics_mode.h, Engine/platform/windows/gfx/ali3dd3d.cpp, Engine/platform/windows/gfx/ali3dd3d.h
This implements method for switching between windowed and fullscreen modes at runtime.
Default Alt+Enter key combination is used to trigger the switch.
=> Implement switching graphic modes at runtime

Editor/AGS.Editor/Resources/agsdefns.sh, Engine/ac/button.cpp
These are readonly properties for getting current state of animating button, complying to similar properties of (Room)Object and Character:
* Button.Animating
* Button.View
* Button.Loop
* Button.Frame
Buttons are animated using Button.Animate function, but there were no means to read current state of the animation.
=> ScriptAPI: exposed properties for getting animated button's state

Compiler/script/cs_parser.cpp
If a function contained an instance of a struct with no fields, exiting the function would cause a stack underflow. This bug has been present since at least 3.2.1, possibly earlier.
Note: I am specifically talking about non-managed structs.
It could be argued that the engine's stack pointer handling should know how to properly deal with 0-size structs, but I think not pushing them to the stack is the simplest solution.
Here is a quick example of what I mean:
```
struct MyStruct {};
function OffendingFunction() { MyStruct a; }
```
Also, I am still working on the switch/case string comparison bug. This was in a stash and annoying me, so I thought I'd commit it.
=> Scripting: Do not push 0-size structs onto the stack

Compiler/script/cs_parser.cpp
String comparisons in switch statements haven't been working properly since 3.4.0 final. Instead of comparing the value of strings, the switch statement was comparing the pointers. I have fixed this issue and some incorrect offsets I found when diagnosing the problem.
=> Scripting: Fix the switch statement's handling of strings

Common/ac/game_version.h, Common/ac/gamesetupstruct.cpp, Common/ac/gamesetupstruct.h, Common/font/agsfontrenderer.h, Common/font/fonts.cpp, Common/font/fonts.h, Common/gui/guilabel.cpp, Common/gui/guilistbox.cpp, Editor/AGS.Editor/DataFileWriter.cs, Editor/AGS.Editor/Resources/agsdefns.sh, Editor/AGS.Native/agsnative.cpp, Editor/AGS.Types/Font.cs, Engine/ac/dialog.cpp, Engine/ac/display.cpp, Engine/ac/display.h, Engine/ac/draw.cpp, Engine/ac/drawingsurface.cpp, Engine/ac/gamesetup.h, Engine/ac/global_api.cpp, Engine/ac/global_display.cpp, Engine/ac/global_drawingsurface.cpp, Engine/ac/global_gui.cpp, Engine/ac/global_gui.h, Engine/game/game_init.cpp, Engine/gui/gui_engine.cpp, Engine/main/engine_setup.cpp, Engine/plugin/agsplugin.cpp
This pull request does two things:
1) Introduces new customizable Font property LineSpacing, which defines an automatic height of step between two lines of text. Default value is 0, which actually means "use font's height".
2) Reworks the internal engine's algorithm of text drawing, using line spacing where font height was previously used for calculating steps between lines. Since default value for line spacing is "font height", old games and new games which did not have custom line spacing set should keep identical text looks.
Also added two script functions: GetFontHeight(int font) and GetFontLineSpacing(int font), which are self explanatory.
=> Custom font line spacing

Compiler/script/cs_parser.cpp
Ensure the stack size is the same when parsing a case expression and when it's executed. I'm now including the stack operations in the chunk associated with a case expression.
The imbalance that previously existed was to blame for local variable comparisons not working in switch statements (MAR was wrong).
=> Scripting: Fix switch on local variables

Editor/AGS.Editor/AGSEditor.csproj, Editor/AGS.Editor/app.manifest
Environemnet.OSVersion wouldn't output correct OS version on Windows 8.1 and Windows 10. This is solved by a adding a manifest file with metadata that tells the application at build time that the OS in question are supported.
Microsoft do not actually recommend using Environemnet.OSVersion, but it works just fine  and they haven't provided alternatives that doesn't involve invoking native code or doing registry lookups, which I'm trying to avoid.
=> Environment.OSVersion output correct OS

Editor/AGS.Editor/GUI/AboutDialog.cs
Added support for Windows 8, Windows 8.1 and Windows 10 (and onwards?) detection to the about dialogue box.
I wanted to post about this on #398 , but it got merged before I got a chance to comment. The addition of a manifest file allows us to get the correct values for the about dialogue box. I have updated the code to populate the relevant field according to this table:
https://msdn.microsoft.com/en-us/library/windows/desktop/ms724832%28v=vs.85%29.aspx
=> Editor: Show modern Windows versions in About

Editor/AGS.Native/NativeDLL.vcxproj, Solutions/Common.Lib/Common.Lib.vcxproj, Solutions/Compiler.Lib/Compiler.Lib.vcxproj, Solutions/Engine.App/Engine.App.vcxproj
I just enabled the option for multi process compilation,
It cut down the engine rebuild time from 1m32s to just 40s.
=> Multi process compilation speeds up the build

Editor/AGS.Types/DialogOption.cs, Editor/AGS.Types/PropertyGridExtras/EnumTypeConverter.cs, Editor/AGS.Types/PropertyGridExtras/StringListUIEditor.cs, Editor/AGS.Types/PropertyGridExtras/StringListUIEditorControl.cs
Like the title says, I have more details on the individual commit messages so make sure to read those.
=> Fixed C# project module "AGS.Types" so that it successfully builds in xBuild on *nix systems

Editor/AGS.CScript.Compiler/CodeBlockCompiler.cs, Editor/AGS.CScript.Compiler/Entities/DefaultTokenStore.cs, Editor/AGS.CScript.Compiler/Entities/OperatorToken.cs, Editor/AGS.CScript.Compiler/Entities/ScalarVariableTypeToken.cs, Editor/AGS.Editor/Components/HelpCommandsComponent.cs, Editor/AGS.Editor/Components/ScriptsComponent.cs
Needs #396 to be resolved in order to test properly since AGS.Cscript.Compiler references AGS.Types
=> Fixed C# project module "AGS.CScript.Compiler" so that it successfully builds in xBuild on *nix systems

Compiler/script/cc_symboltable.cpp, Compiler/script/cs_parser.cpp
This relates to the bug reported here:
http://www.adventuregamestudio.co.uk/forums/index.php?issue=825.0
The behaviour of get_friendly_name did not exactly match the get_name it replaced.
There are some areas in the compiler where it assumes the next symbol is valid to print. These are errors in the compiler's logic, but whereas get_name would give the reasonable output "const (null)", get_friendly_name causes a crash.
Note: This was likely because sprintf dealt with a null c-style string pointer and output "(null)".
This new behaviour isn't perfect, but it's better than hard crashes when there are errors in the compiler logic. When there is a problem getting the name of a symbol, it will now be shown as "(invalid symbol)", and we can fix these issues as we find them.
I also added two EOF …
=> Prevent crashes when dealing with unprintable symbols

Engine/platform/linux/acpllnx.cpp
This replaces the sleep function in the Linux platform driver, which is called by platform->YieldCPU() in the main game loop. In testing I'm seeing a CPU usage reduction of between 5% and 10% and no other side effects, having built against the AGS Allegro fork. The kernel has supported this for a long time so I think it's pretty safe to switch.
=> Linux: use nanosleep for CPU yield

Engine/platform/windows/acplwin.cpp
"My Documents" folder was being retrieved on every version of Windows. Now it is only retrieved on XP and earlier, with "Saved Games" retrieved on later versions of Windows. There is also a fallback to store saved games within the data folder in case of failure.
=> Fixed issue #417

Engine/game/savegame.cpp, Engine/game/savegame.h, Engine/game/savegame_components.cpp
Added tags which explicitly mark the beginning and the end of the components data list in the savedgame.
Components are now read until the end of list is found, as opposed to end of file.
This should resolve the error caused by screenshots with the new save format (https://github.com/adventuregamestudio/ags/pull/413#issuecomment-339395427), which are appended to the end of file.
=> Encase whole savedgame's component list in tags

Editor/AGS.CScript.Compiler/AGS.CScript.Compiler.csproj, Editor/AGS.Editor/AGSEditor.csproj, Editor/AGS.Types/AGS.Types.csproj
As discussed in #408. The Werror property seems to have beends randomly set across projects and build configs so it was good we looked into this
=> Disable Werror on C# projects

Editor/AGS.CScript.Compiler/AGS.CScript.Compiler.csproj, Editor/AGS.Controls/AGS.Controls.csproj, Editor/AGS.Editor/AGSEditor.csproj, Editor/AGS.Types/AGS.Types.csproj
Officially minimum supported IDE is Visual Studio is 2015, so we want to avoid that anyone adds any coding of higher language level than VS 2015 supports.
=> Set C# projects language level explicitly to v6.0

Android/buildlibs/armeabi-v7a/ndkenv, Android/buildlibs/armeabi-v7a/ogg.sh, Android/buildlibs/armeabi/ndkenv, Android/buildlibs/armeabi/ogg.sh, Android/buildlibs/buildall.sh, Android/buildlibs/makestandalones.sh, Android/buildlibs/mips/ndkenv, Android/buildlibs/mips/ogg.sh, Android/buildlibs/x86/ndkenv, Android/buildlibs/x86/ogg.sh, Android/library/project.properties, Android/patches/liblua.patch
pull request for building AGS Engine for Android 
Forum Thread here: http://www.adventuregamestudio.co.uk/forums/index.php?topic=44768.msg636581163#msg636581163
My environment is Ubuntu 16.04 and I used the Android Sdk and ndk installed through Android Studio 3.0.1.
uname -a
Linux  4.13.0-32-generic #35~16.04.1-Ubuntu SMP Thu Jan 25 10:13:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
details of my Android Studio : 
Android Studio 3.0.1
Build #AI-171.4443003, built on November 9, 2017
JRE: 1.8.0_152-release-915-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.13.0-32-generic
Commands I used to build:
export PATH=$PATH:~/Android/Sdk/ndk-bundle/
cd git/ags/Android/buildlibs/
./makestandalones.sh 
./buildall.sh 
cd ../library/
ndk-build
=> updates the Android port to use ndk-bundle/platforms/android-14

Android/library/jni/Android.mk, Engine/gfx/ali3dogl.cpp, Engine/gfx/ogl_headers.h
Upgrade OpenGL renderer to use GLES2 on Android, which fixes compilation of the engine v3.4.1.
This should partially solve #420 (still not resolved for iOS).
According to the statistics [posted on Android devs page](https://developer.android.com/about/dashboards/index.html#OpenGL) GLES2 is supposed to be present on more than 99% of devices in use.
=> Android: upgraded OpenGL renderer to GLES2 and fixed compilation

Editor/AGS.Editor/Panes/SpriteSelector.cs
This should restore the SpriteFolder nodes when the data is refreshed, as currently they collapse back down to the root node when the additional sprite selector is closed.
[http://www.adventuregamestudio.co.uk/forums/index.php?topic=55872](http://www.adventuregamestudio.co.uk/forums/index.php?topic=55872)
=> Re-expand SpriteFolder nodes on refresh

Common/ac/game_version.h, Engine/ac/game.cpp, Engine/ac/movelist.cpp, Engine/ac/movelist.h, Engine/ac/route_finder.cpp, Engine/ac/route_finder_jps.inl, Engine/game/savegame_components.cpp
Hi guys, I forked AGS to try my jump point search A* study and it seems to work well so far.
What's the benefit:
+ faster (up to much faster) pathfinding
+ somewhat nicer paths (better refinement especially at path end)
+ when clicking unreachable walls the player moves somewhat closer to destination using the new algorithm
+ amortized heap allocation elimination when pathfinding
+ eliminating old pathfinding code
What's the price to pay:
- 4 times more memory scratch memory required (4xwall bitmap dims), for 3kx1k bitmap, original AGS used 3 megs of extra RAM while my new pathfinder uses 12 megs; probably not a bit deal even on mobiles
- not thoroughly tested (3 games only - King's Quest II, Resonance Demo and Eternally us), may contain bugs
Performance of original AGS (runtime polling …
=> new jump point search routing with path refinement

Editor/AGS.Editor/AGSEditor.cs, Editor/AGS.Editor/Components/BuildCommandsComponent.cs, Editor/AGS.Editor/Entities/EditorPreferences.cs, Editor/AGS.Editor/GUI/GUIController.cs, Editor/AGS.Editor/GUI/OutputPanel.cs, Editor/AGS.Editor/GUI/PreferencesEditor.Designer.cs
Previously the Editor message boxes preference didn't apply to the 'successful compilation' message box.
This makes the following changes:
- adds a default enum 'Always' (previous default 'WarningsAndErrors' was already allowing success messages)
- suppress the 'successful compilation' message box unless using 'Always'
- write the successful compilation message to the output pane
The main benefit being, if you set the option to 'Never', you now get faster testing. As an added bonus, this stops the Windows sound effect that accompany message boxes being played, every time the game is compiled.
Potential problem: With preference set to 'Never' and then reverting to an older AGS version, the index is out of range. I'm not sure if there is any safer way to extend a preference item with a new …
=> Apply Editor message box preferences to 'successful compilation'

Common/ac/gamesetupstruct.cpp, Common/ac/gamesetupstruct.h, Common/game/main_game_file.cpp, Common/game/main_game_file.h, Common/util/error.h, Engine/ac/game.cpp, Engine/ac/global_game.cpp, Engine/ac/movelist.cpp, Engine/ac/movelist.h, Engine/ac/record.cpp, Engine/game/game_init.cpp, Engine/game/game_init.h, Engine/game/savegame.cpp, Engine/game/savegame.h, Engine/game/savegame_components.cpp, Engine/game/savegame_components.h, Engine/main/engine.cpp, Engine/main/game_file.cpp, Engine/main/game_file.h, Solutions/Common.Lib/Common.Lib.vcxproj, Solutions/Common.Lib/Common.Lib.vcxproj.filters
Error class is a basic structure which describes an error, with optional error code, general error message and additional comments. It also supports error nesting, by passing a shared pointer to inner error in constructor.
In theory it could be thrown as an exception type, even inherit std::exception, but I did not do that for now, because AGS lacks proper exception catching at the moment (adding that may require more code cleanup first). This may be still done in future if wanted.
Instead, for now it is supposed to be used with a thin wrapper called ErrorHandle. ErrorHandle only has std::shared_ptr inside, there is no problem in using it as a function return value. Since we expect no errors in majority of cases, this also saves a tiny bit on memory allocation.
The main reason to have a …
=> Error class

Editor/AGS.Editor/Panes/GUIEditor.cs
This should fix #443 by removing the delete option for Text Window GUIs.
=> Check GUI type is NormalGUI when deleting controls

Common/ac/characterinfo.h, Editor/AGS.Editor/Resources/agsdefns.sh, Engine/ac/characterextras.h, Engine/ac/dynobj/cc_character.cpp, Engine/ac/dynobj/cc_character.h, Engine/ac/dynobj/scriptmouse.cpp, Engine/ac/dynobj/scriptmouse.h, Engine/ac/dynobj/scriptsystem.cpp, Engine/ac/dynobj/scriptsystem.h, Engine/ac/game.cpp, Engine/ac/gamestate.h, Engine/ac/statobj/agsstaticobject.cpp, Engine/ac/statobj/agsstaticobject.h, Engine/ac/statobj/staticarray.cpp, Engine/ac/statobj/staticarray.h, Engine/ac/statobj/staticgame.cpp, Engine/ac/statobj/staticgame.h, Engine/game/game_init.cpp, Engine/main/engine.cpp, Solutions/Engine.App/Engine.App.vcxproj, Solutions/Engine.App/Engine.App.vcxproj.filters
Long story short, this properly wraps script variable access in runtime in a way that no longer restricts internal data size or layout.
For more detailed explanation of a problem: [wiki page](https://github.com/adventuregamestudio/ags/wiki/Engine-data-structure-restrictions#engine-memory-exposed-to-scripts)
Pull request affects GameState, CharacterInfo, ScriptMouse and ScriptSystem structs.
Only ones remaining are palette array (which is probably okay as it is), and couple of legacy arrays that probably should be removed for now (I marked them in script header).
After this and #452 it must be absolutely safe to modify game classes in the engine code.
=> Created proper managers for the script structs containing raw variables

Common/ac/characterinfo.h, Common/ac/mousecursor.h, Engine/ac/gamestate.h, Engine/ac/roomobject.h, Engine/plugin/agsplugin.cpp, Engine/plugin/agsplugin.h, Engine/plugin/plugin_builtin.h, Engine/plugin/plugin_engine.h, Plugins/AGSflashlight/agsflashlight.cpp, Plugins/ags_snowrain/ags_snowrain.cpp, Solutions/Engine.App/Engine.App.vcxproj, Solutions/Engine.App/Engine.App.vcxproj.filters
This disables plugin API functions that return addresses to the internal engine's data (characters, room objects, etc).
Their use may be only partially substituted with calls to script API from plugin, but I suppose that in the end plugins will have full and safer access to all script commands.
There are still few things left, like GetPalette and GetSpriteGraphic, but I decided to leave them in for now, because they do not impose much restriction on engine data. Something should be done with these later though.
~Also disabled non-portable API, that returns DirectX interfaces on Windows.~
I say "disabled", because just made them all throw errors, but did not remove function declarations because that would break existing plugins.
NOTE: this is only the first step to make these structs' …
=> Remove internal engine type declarations from the plugin API

Engine/ac/dialog.cpp, Engine/ac/display.cpp, Engine/ac/global_debug.cpp, Engine/gui/cscidialog.cpp, Engine/main/game_run.cpp, Engine/main/game_run.h, Engine/media/video/video.cpp, Engine/platform/windows/media/video/acwavi.cpp, Engine/platform/windows/media/video/acwavi3d.cpp, Engine/plugin/agsplugin.cpp
Picked out a function that polls current key presses and handles service shortcuts (mouse cursor lock, display mode switch). Call this function in all places where game checks for keyboard input to make things consistent.
This fixes windowed/fullscreen switch not working during video playback and dialog options (and couple more places probably).
=> 3.4.1: make sure that service key commands work everywhere in game

Editor/AGS.Editor/Panes/ScintillaWrapper.cs
Resolves #462 .
I honestly do not understand why, but Editor keeps Scintilla component in Read-only state most of the time, manually toggling it when the user types/pastes text.
Scintilla checks for ReadOnly when asked if it can Undo/Redo and may reply negative even when there are entries in the Undo buffer.
This fix is a hack, that similarily turns ReadOnly mode off before asking Scintilla if Undo is allowed.
=> 3.4.1: hotfix script editor to let Undo work after save

Editor/AGS.Editor/NativeProxy.cs, Editor/AGS.Editor/Panes/GUIEditor.Designer.cs, Editor/AGS.Editor/Panes/GUIEditor.cs, Editor/AGS.Native/NativeMethods.cpp, Editor/AGS.Native/NativeMethods.h, Editor/AGS.Native/agsnative.cpp, Editor/AGS.Types/GUI.cs, Editor/AGS.Types/NormalGUI.cs, Editor/AGS.Types/TextWindowGUI.cs
This adds scrollbars and zoom control to the GUI editor (lack of those was causing suffering for high-resolution game developers).
The code ended up tad bloated, perhaps it could be improved in the future by implementing a parent class for the scrollable/zoomable editor pane, and sharing the code with the room editor.
=> 3.4.1: implemented scrollbars and zoom for the GUI editor

Common/ac/gamesetupstruct.cpp, Common/ac/gamesetupstruct.h, Common/ac/gamestructdefines.h, Common/font/fonts.cpp, Common/font/fonts.h, Common/game/main_game_file.cpp, Common/game/main_game_file.h, Editor/AGS.Editor/AGSEditor.cs, Editor/AGS.Editor/Components/FontsComponent.cs, Editor/AGS.Editor/DataFileWriter.cs, Editor/AGS.Editor/Utils/NativeConstants.cs, Editor/AGS.Native/NativeMethods.cpp, Editor/AGS.Native/agsnative.cpp, Editor/AGS.Types/Game.cs, Engine/game/game_init.cpp
This removes the arbitrary font limit (and does tiny bit of refactoring).
NOTE: this is done for the ags3 branch by request from a user. Later this may be merged to ags4 without much problem.
=> AGS 3: remove the fonts limit

Editor/AGS.Native/NativeDLL.vcxproj
If the path to the source code repository contains spaces, then the copy command will parse the parameters wrongly. Adding quotes fixes the problem. For further details, see http://www.adventuregamestudio.co.uk/forums/index.php?topic=56238.msg636590243#msg636590243
=> Add quotes to "copy" command

Editor/AGS.Editor/Utils/Utilities.cs
This should fix #451, as scripts were not recompiled if the last write time for the compiled file was exactly the same as the source file. It should also ensure that files are recompiled if version control or the filesystem has reset the timestamps.
=> Compiled script must be newer than source

Editor/AGS.Editor/AutoComplete.cs
This is already running in a low priority thread, so rather than sleep inside the thread when building the autocomplete cache in the background, just let CPU scheduling handle it.
=> Don't sleep when building autocomplete cache

Editor/AGS.Editor/NativeProxy.cs, Editor/AGS.Editor/Panes/Room/RoomEditFilters/BaseAreasEditorFilter.cs, Editor/AGS.Editor/Panes/Room/RoomEditFilters/CharactersEditorFilter.cs, Editor/AGS.Editor/Panes/Room/RoomEditFilters/EdgesEditorFilter.cs, Editor/AGS.Editor/Panes/Room/RoomEditFilters/EmptyEditorFilter.cs, Editor/AGS.Editor/Panes/Room/RoomEditFilters/HotspotsEditorFilter.cs, Editor/AGS.Editor/Panes/Room/RoomEditFilters/ObjectsEditorFilter.cs, Editor/AGS.Editor/Panes/Room/RoomEditFilters/WalkBehindsEditorFilter.cs, Editor/AGS.Editor/Panes/Room/RoomSettingsEditor.Designer.cs, Editor/AGS.Editor/Panes/Room/RoomSettingsEditor.cs, Editor/AGS.Editor/Panes/Room/RoomSettingsEditor.resx, Editor/AGS.Native/NativeMethods.cpp, Editor/AGS.Native/NativeMethods.h, Editor/AGS.Native/agsnative.cpp
This improves how room's zoom works, making it similar to how I did GUI zoom previously.
Now it may have non-integer multipliers and supports downscale.
Removed unnecessary resizing of a room pane after zoom out (which could hide some of controls).
Notably, fixed a severe case of code duplication: window<->room coordinate conversions were done in-place all around the room code.
**PS.** the branch is named "release-3.4.1--roomzoomfix2", but ignore that, I simply called it wrong.
=> Editor: improved Room pane's zoom

Editor/AGS.Editor/AGSEditor.cs, Editor/AGS.Editor/AGSEditor.csproj, Editor/AGS.Editor/Components/RoomDesignData.cs, Editor/AGS.Editor/Components/RoomsComponent.cs, Editor/AGS.Editor/Panes/Room/RoomEditFilters/BaseAreasEditorFilter.cs, Editor/AGS.Editor/Panes/Room/RoomEditFilters/CharactersEditorFilter.cs, Editor/AGS.Editor/Panes/Room/RoomEditFilters/EdgesEditorFilter.cs, Editor/AGS.Editor/Panes/Room/RoomEditFilters/EmptyEditorFilter.cs, Editor/AGS.Editor/Panes/Room/RoomEditFilters/HotspotsEditorFilter.cs, Editor/AGS.Editor/Panes/Room/RoomEditFilters/IRoomEditorFilter.cs, Editor/AGS.Editor/Panes/Room/RoomEditFilters/ObjectsEditorFilter.cs, Editor/AGS.Editor/Panes/Room/RoomEditFilters/RegionsEditorFilter.cs, Editor/AGS.Editor/Panes/Room/RoomEditFilters/WalkBehindsEditorFilter.cs, Editor/AGS.Editor/Panes/Room/RoomEditFilters/WalkableAreasEditorFilter.cs, Editor/AGS.Editor/Panes/Room/RoomEditNode.cs, Editor/AGS.Editor/Panes/Room/RoomSettingsEditor.cs, Editor/AGS.Types/Interfaces/IRoom.cs, Editor/AGS.Types/SerializeUtils.cs, Editor/AGS.Types/UnloadedRoom.cs
This implements saving and restoring the design-time state of a room editor. At the moment that includes "visible" and "locked" flags for room layers and items, which are set using breadcrumb navigation bar.
Data is saved into XML file called "roomXXX.crm.user", where XXX is a room number (complementing "roomXXX.crm" room data file and "room.asc" script file).
Saving is done whenever room is saved, loading is performed right after main room data was loaded into the editor. I tried to comply to the main project data format.
Since this data is optional, the trivial checks are made that prevent attempts to apply data to non-existant layers and objects. If the file exists but could not be loaded or parsed a mere warning is displayed to user.
---
A few thoughts regarding potential …
=> AGS 3: serialize room's design-time data

Common/ac/common_defines.h, Editor/AGS.Editor/Panes/Room/RoomEditFilters/ObjectsEditorFilter.cs, Editor/AGS.Native/agsnative.cpp, Editor/AGS.Types/RoomObject.cs
Since locking room items in the editor is done using general UI now, removed Locked property from the RoomObject class as unnecessary duplicate.
NOTE: this won't result in data format change, only one flag in the compiled room data will become deprecated.
=> AGS 3: deprecate RoomObject.Locked property and use DesignTimeProperties instead

Common/ac/roomstruct.cpp, Common/ac/roomstruct.h, Common/ac/spritecache.cpp, Common/ac/spritecache.h, Common/core/asset.h, Common/core/assetmanager.cpp, Common/core/assetmanager.h, Common/util/compress.cpp, Common/util/compress.h, Common/util/multifilelib.h, Common/util/mutifilelib.cpp, Editor/AGS.Editor/BuildTargets/BuildTargetWindows.cs, Editor/AGS.Editor/DataFileWriter.cs, Editor/AGS.Editor/Utils/NativeConstants.cs, Editor/AGS.Native/NativeMethods.cpp, Editor/AGS.Native/ScriptCompiler.cpp, Editor/AGS.Native/agsnative.cpp, Editor/AGS.Native/agsnative.h, Engine/game/savegame.cpp, Engine/game/savegame.h, Engine/game/savegame_components.cpp
Formats updated:
1. Assets library (main game data, audio.vox, speech.vox);
2. Sprites file.
3. Room file.
4. Savedgame (just in case).
Also removed encryption from new asset library TOC (it retained very little sense after source code was opened).
=> AGS 3: updated data formats to make use of 64-bit file offsets

Editor/AGS.Editor/GUI/WelcomeScreen.cs
Hides recent game references where the game path doesn't exist.
- When a game folder is removed or renamed, it now won't appear in the recent game list
- The entry remains in the settings file, so that if a game is on a volume which isn't mounted it will be listed again when the game folder returns
=> Hide recent games which are currently missing

OSX/buildlibs/checkenv.sh
- When the pkg check failed the binary name was not printed, because the `which` failure had already aborted the script. This is changed to not exit early (all paths already have an exit code) and just validate the return codes
- I've added a check for 'libtoolize' as well as 'glibtoolize', since installing a packaged build of 'libtool' may give the former rather than the latter. You may encounter this if not using brew as your package manager
- Just a general cleanup. I wasn't sure what the bash + double square brackets were doing, the rest was spacing, or changing quoting/subshell style to remove some escaping requirements. I'll separate these changes out if required though.
=> Fix environment checks for building without brew

Engine/ac/global_object.cpp
fixes "Trilby: Art of Theft" crashing when the level selection is moved
rapidly with the cursor keys.
closes #512
=> make Object.SetPosition on a moving object non-fatal

Editor/AGS.Editor/BuildTargets/BuildTargetLinux.cs, debian/ags+libraries/startgame
- quoted $0 in launch wrapper
This fixes launching the game when there is a space in the path to launch wrapper (the itch.io launch failures are because `readlink -f` could return multiple lines from the sub-shell)
- ~~added exit 1 when printing usage~~
~~For some reason, it was still trying to start the game after printing the instructions~~
- `-h` is not a valid switch
Using this would have printed the usage header but still start the game
- Fix broken if statements and argument checks, when using arguments
e.g. `./MyGame: 4: test: x--help: unexpected operator`
=> Fixes for Linux launch wrapper (fixes issues with itch.io client)

Editor/AGS.Editor/Entities/EditorPreferences.cs
Fixes #521 by comparing recent games using only their path on disk.
=> Ignore game name for recent game comparison

Editor/AGS.Editor/GUI/WelcomeScreen.cs
I'm not sure what I was doing before, but the game path is already in the control. So rather than resolve the index to a game, just return the path from the control selection.
Fixes #537
=> Fix welcome screen returning the wrong game path

Editor/AGS.Editor/Utils/Utilities.cs
This stops spawning a shell when trying to create a hardlink, which seems to help with Windows Explorer locking the files when writing data to the game file (at least, I can't recreate the problem with this change applied). This also removes the potential of cmd.exe hanging the build process, if the command processor has been disabled (it will prompt to press a key, but the window would be hidden).
For Mono, just default to copying the file, for the moment.
=> Use native CreateHardLink

Editor/AGS.Editor/Panes/SpriteImportWindow.cs, Editor/AGS.Editor/Panes/SpriteSelector.cs, Editor/AGS.Editor/Utils/SpriteSheet.cs
- Allows selection to invert when dragging, so you can now make a tile selection with the left mouse button from bottom-right right to top-left, as well as top-left to bottom-right. The inversion is inclusive of the first pixel, which feels correct in practice.
- Clamp selection size to image edges. Previously cursor position was still tracked, even after leaving the control.
- Fix crashes where the selection height or width was set to 0.
- Don't updated selection sizes when switching images. Invalid selection sizes are handled, and it is more likely that someone with a spritesheet will want to work from the top-left corner.
- Fix copy sprite to clipboard (regression)
=> Spritesheet import: inverted mouse selection and fixes

Engine/ac/object.cpp
Reverts the deleted part from commit 15d813ff7 that handled some coords adjustment inside the function is_pos_in_sprite().
=> Engine: restored a piece of code that handled resized cache sprites

Editor/AGS.Editor/Resources/agsdefns.sh, Engine/ac/draw.cpp, Engine/ac/draw.h, Engine/ac/dynobj/scriptcamera.cpp, Engine/ac/dynobj/scriptuserobject.cpp, Engine/ac/dynobj/scriptuserobject.h, Engine/ac/game.cpp, Engine/ac/gamestate.cpp, Engine/ac/gamestate.h, Engine/ac/screen.cpp, Engine/ac/viewport.cpp, Engine/game/viewport.h, Engine/main/engine_setup.cpp, Engine/script/exports.cpp, Engine/script/script_api.h
This adds a bunch of script functions to work with Viewport and Camera.
But first of all, I added Screen struct to place static screen-related properties and functions there. At the moment its declaration looks like this:
<pre>
builtin struct Screen {
/// Gets the width of the game resolution.
import static readonly attribute int Width;
/// Gets the height of the game resolution.
import static readonly attribute int Height;
/// Gets/sets whether the viewport should automatically adjust itself and camera to the new room's background size
import static attribute bool AutoSizeViewportOnRoomLoad;
/// Gets the primary room viewport
import static readonly attribute Viewport *Viewport;
/// Returns the point in room which is displayed at the given screen coordinates
import static Point …
=> Script API: helper functions for Viewport and Camera

Editor/AGS.Editor/Utils/Utilities.cs
Relative sources are stored as URIs, so using Path.Combine ends up with a mix of forward and backward slashes in the combined path (technically this valid, but in practice it isn't treated so). This switches to using a URI to do the join and then returning Uri.LocalPath, which should return the combined path with correct directory separators.
=> Fix path joins with mixed directory seperators

Editor/AGS.Editor/Panes/SpriteSelector.cs
Adds a menu option when right-clicking a sprite, to view the sprite source in Windows Explorer.
This needs #568 and perhaps fixes #563, since this should open Explorer directly at the source location (so you know exactly where the file is) and the menu item will be disabled if the source is missing (so you can tell if the file is missing entirely).
=> Add option to view the source file for a sprite

Editor/AGS.Editor/AGSEditor.csproj, Editor/AGS.Editor/GUI/SpriteExportDialog.Designer.cs, Editor/AGS.Editor/GUI/SpriteExportDialog.cs, Editor/AGS.Editor/GUI/SpriteExportDialog.resx, Editor/AGS.Editor/Panes/SpriteSelector.cs, Editor/AGS.Editor/Utils/SpriteTools.cs
Possible solution to #542, where sprite properties can be used as tokens in the export path. This adds a sprite dialog option, where you can edit the tokens, skip sprites that have an existing source file, and rewrite the source file to use the exported file.
The tokens would probably need to be listed somewhere, but they are just the property names with '%' at either end, case-insensitive. So '%NUMBER%', '%number%', and '%NuMbEr%' would resolve to the sprite number, for example.
=> Tokenised sprite export

Editor/AGS.Editor/Audio/IAudioPreviewer.cs, Editor/AGS.Editor/Audio/IrrklangPlayer.cs, Editor/AGS.Editor/Audio/MidiPlayer.cs, Editor/AGS.Editor/Panes/AudioEditor.Designer.cs, Editor/AGS.Editor/Panes/AudioEditor.cs, Editor/AGS.Editor/Panes/AudioEditor.resx
Fixes #567
- Specifically request the software driver for irrKlang sound engine (on my computer at least, using DirectSound seems to sometimes cause invalid values to come back from Sound data on all but the first play through)
- Show AudioClip length without having to press play (this also splits the position and length text between two labels, and makes them bigger)
- Fix MIDI polling / stop events confusing the stop and pause buttons of the GUI
- Fix MIDI pause and resume resetting all MIDI instruments to channel 0 (if you try this currently, every instrument will become a piano when resuming)
- Throw errors for playback and loading problems
=> Refactor audio player

Editor/AGS.Editor/Panes/SpriteImportWindow.cs, Editor/AGS.Editor/Panes/SpriteSelector.cs, Editor/AGS.Editor/Utils/SpriteTools.cs
- Throws exception for non-GIF images that fail to load (GIF images already did this)
- Catch failed image load and insert a place-holder sprite in its place (the normal in-game blue cup).
The cup is coming from a place-holder generating function which returns an 8-bit bitmap of any size (defaults to just a single cup), but will tile and clip it to fit any resolution.
`SpriteTool.GetPlaceHolder()`
`SpriteTool.GetPlaceHolder(91, 157)`
Long term idea for this was to eventually remove the reliance on having sprite 0 in a new game template (you can call this function to create sprite 0 if it isn't there), and potentially allow people to actively use it for place-holder graphics (probably needs someone to draw a nicer looking and more subtle cup).
=> Fix crash when loading invalid image data

Editor/AGS.Editor/Panes/SpriteImportWindow.cs
Fixes #579
Also draws a dashed  line on the right and bottom edge of the image, since an image with transparent edges wouldn't have a visual boundary as a reference point.
=> Ignore import selections started outside the image boundaries

Common/gfx/allegrobitmap.h, Common/libsrc/aastr-0.1.1/aarot.c, Common/util/wgt2allg.h, Engine/Makefile-defs.linux, Engine/Makefile-defs.osx, Engine/Makefile-objs, Engine/Makefile.psp, Solutions/Common.Lib/Common.Lib.vcxproj, Solutions/Common.Lib/Common.Lib.vcxproj.filters, Solutions/Engine.App/Engine.App.vcxproj
Next release of Allegro 4 is [going to remove fixed-point aliases](https://github.com/liballeg/allegro5/commit/4848f1583c3dbe41f5f056869ff2c796d33d8121) like fadd, fsin, fcos and so forth, because they are conflicting with some of the glibc implementations. Although we base AGS on slightly older version of Allegro, the conflict may still be an issue.
This PR makes sure these aliases are not used anywhere in AGS code, and also moves ALLEGRO_NO_FIX_ALIASES definition to CFLAGS (was previously declared right in code).
Also renamed AAROT.c to aarot.c for consistency.
=> AGS 3: fixed the use of fixed-point Allegro functions

Editor/AGS.Editor/BuildTargets/BuildTargetLinux.cs, debian/ags+libraries/startgame
This is set based on the conversation in #510, to follow the merge of the OpenGL changes. The fork is off the master and has a visible merge commit, so I wasn't sure whether someone was just going to cherry pick the existing commits; I didn't want the script change to be forgotten.
Feel free to close if equivalent changes make into the merging branch.
=> Disable DRI3 in Linux launch wrapper

Android/buildlibs/makestandalones.sh
If you follow instruction from README.md under Android, it tells you to define NDK_HOME
https://github.com/adventuregamestudio/ags/blob/master/Android/README.md#native-3rd-party-libraries
>...
>Set NDK_HOME variable, pointing to the location of Android NDK at your system. Change to the /Android/buildlibs directory and run, e.g. assuming the ndk is installed in '/opt/android-ndk-r16b':
>    `$ export NDK_HOME=/opt/android-ndk-r16b`
>    `$ cd <SOURCE>/Android/buildlibs`
>    `$ ./buildall.sh`
>...
This PR reinforces this by throwing an error message if you don't set NDK_HOME, following #604 .
=> Added an error msg if NDK_HOME is undefined.

Editor/AGS.Editor/Panes/FontEditor.cs, Editor/AGS.Types/Constants.cs
This just copies fonts ending in ".wfn" into place. As I understand it, this is all that is needed to import and use them.
Fixes #598
=> Add WFN font import

.travis.yml
This builds AGS on Linux following the instructions here:
https://github.com/adventuregamestudio/ags/tree/master/debian#building-a-debianubuntu-package-of-ags
Deployed results are upload to Github Releases when a new Release is created.
Requires an user that has TravisCI configured with read and write permissions to this repo and environment variable GITHUB_TOKEN configured for Releases to work.
Build Logs from the PR repo can be seen [on Travis here](https://travis-ci.com/mythsuntold/ags).
It's probably smart to install Allegro [from here](https://github.com/liballeg/allegro5/releases/tag/4.4.3) instead of getting from apt repository - but I didn't do that here.
=> Create .travis.yml for building AGS Engine on Linux

Engine/ac/math.cpp, Engine/ac/math.h, Engine/script/script_api.h
Originally all the script interpreter's Math functions worked with floats packed into int32. That was because interpreter worked only with int32 values internally.
Today RuntimeScriptValues have a union that allows to access same data field both as float32 and int32 directly, so packing floats into int32 manually is not necessary.
This change is *long* overdue (should have done that right after interpreter got rewritten).
=> Simplified script interpreter's Math implementations

Common/util/filestream.h, Engine/ac/game.cpp, Engine/game/savegame_components.cpp, Engine/plugin/agsplugin.cpp, Engine/plugin/plugin_engine.h, Plugins/AGSflashlight/agsflashlight.cpp, Plugins/ags_parallax/ags_parallax.cpp, Plugins/ags_snowrain/ags_snowrain.cpp
Instead of casting a FILE* pointer to an integer, the plugin module will now use an abstract file handle which maps to the currently opened savegame file. 
Plugins are supposed to use the engine->FWrite/FRead functions so this also refactors the inbuilt plugins to use that as well.
Since there's only ever one savegame file open at a time, this reuses the save/restore event code as the file handle.
=> Plugin save/restore uses file handle.

Editor/AGS.Editor/Panes/Room/RoomSettingsEditor.cs
=> Don't select layer objects when the room tab isn't the active tab

Engine/plugin/agsplugin.cpp, Engine/plugin/plugin_builtin.h, Engine/plugin/plugin_engine.h, OSX/xcode/ags/plugin_registration.cpp
The builtin plugin registration is intended to be used by games that wrap the engine as a library.  The api was originally in ags_plugin.h but was moved to plugin_engine.h which meant it wasn't accessible to apps that only had limited access to the ags headers.
Currently the wadjet eye games use it for their ios games to load builtin plugins.
=> AGS3 plugin builtin refactor

Editor/AGS.Editor/Resources/agsdefns.sh, Engine/ac/game.cpp, Engine/ac/global_api.cpp, Engine/ac/global_game.cpp, Engine/ac/global_game.h
Implemented eSkipScriptOnly cutscene mode and SkipCutscene() function to let users little more flexibility in scripting cutscenes.
=> Script API: SkipCutscene and cutscene that cannot be skipped by user input

Common/util/string.h, Common/util/string_utils.cpp, Common/util/string_utils.h, Engine/ac/game.cpp, Engine/ac/gamestate.cpp, Engine/ac/gamestate.h, Engine/main/engine.cpp
The actual problem here was in StrUtil::ReadString. DoOnce tokens would get deserialized occasionally with garbage at the end of the string. 
While debugging this I was annoyed by the old crustiness of "do once tokens". Then I noticed they mixed new[] and malloc, and that was enough to give me the go-ahead to reform them entirely to be more modern.
=> AGS3: Reform do once

Common/ac/game_version.h, Common/ac/gamestructdefines.h, Common/game/main_game_file.cpp, Editor/AGS.Editor/AGSEditor.cs, Editor/AGS.Editor/ApplicationController.cs, Editor/AGS.Editor/DataFileWriter.cs, Editor/AGS.Editor/GUI/GUIController.cs, Editor/AGS.Editor/ImportExport.cs, Editor/AGS.Editor/NativeProxy.cs, Editor/AGS.Editor/Panes/Room/RoomEditFilters/CharactersEditorFilter.cs, Editor/AGS.Editor/Panes/Room/RoomEditFilters/ObjectsEditorFilter.cs, Editor/AGS.Editor/Panes/ViewPreview.cs, Editor/AGS.Editor/Tasks.cs, Editor/AGS.Editor/Utils/NativeConstants.cs, Editor/AGS.Editor/Utils/Utilities.cs, Editor/AGS.Native/NativeMethods.cpp, Editor/AGS.Native/NativeMethods.h, Editor/AGS.Native/agsnative.cpp, Editor/AGS.Types/AGS.Types.csproj, Editor/AGS.Types/Enums/SpriteImportResolution.cs, Editor/AGS.Types/HelperTypes/SpriteInfo.cs, Editor/AGS.Types/Sprite.cs, Engine/ac/sprite.cpp
A brief explanation, in AGS the game may be thought as being "low resolution" and "high resolution".
This exists since the times when it did not support any arbitrary game size, and historically 320x240 was the last "low resolution" and 640x400 was the first "high resolution".
Some assets, like sprites in this case, were letting developer to tag them as either "lowres" or "highres", and if this tag did not match the game's then such sprite would be scaled up or down twice in game respectively. I believe these were mostly meant to reuse same sprites in different games, but now with arbitrary game sizes the border between "lowres" and "highres" games became very vague.
This PR deprecates "Low/high resolution" sprite flags and introduces "Real resolution" type to replace them as the new …
=> AGS 3: deprecate sprite resolution tag

Common/ac/game_version.h, Common/ac/gamesetupstruct.cpp, Common/ac/gamesetupstruct.h, Common/ac/gamestructdefines.h, Common/font/agsfontrenderer.h, Common/font/fonts.cpp, Common/font/fonts.h, Common/font/ttffontrenderer.cpp, Common/font/ttffontrenderer.h, Common/font/wfnfontrenderer.cpp, Common/font/wfnfontrenderer.h, Common/game/main_game_file.cpp, Editor/AGS.Editor/AGSEditor.cs, Editor/AGS.Editor/Components/FontsComponent.cs, Editor/AGS.Editor/DataFileWriter.cs, Editor/AGS.Editor/Panes/FontEditor.cs, Editor/AGS.Editor/Panes/GeneralSettingsPane.cs, Editor/AGS.Editor/Tasks.cs, Editor/AGS.Editor/Utils/NativeConstants.cs, Editor/AGS.Native/NativeMethods.cpp, Editor/AGS.Native/agsnative.cpp, Editor/AGS.Types/Font.cs, Editor/AGS.Types/Settings.cs, Engine/ac/display.cpp, Engine/game/game_init.cpp, Engine/main/engine.cpp, Engine/main/engine_setup.cpp
Similar to sprite resolution tag (#651), global font scale setting made all fonts in game scale up x2 if the game is considered high res. This pr replaces that setting with individual size multiplier for each font which may be set regardless of game resolution.
This setting is primarily meant for bitmap fonts, as it's pretty useless for TTF which have their own scaling. But it is applied to latter as well for consistency (simply multiplying the Size parameter).
When importing older game AGS will apply x2 scaling to each font if game was hires and did not have "Fonts are designed for high resolution" setting enabled.
=> AGS 3: replace global font scale with individual setting

Engine/Makefile-defs.linux
this allows to override them from the make command line like
make FT_CFLAGS=-I ../foo FT_LDFLAGS=/tmp/libfreetype.a
or by defining them in config.mak
=> build system: factor out freetype C/LDFLAGS

Common/ac/gamesetupstructbase.cpp, Common/ac/gamesetupstructbase.h, Common/game/room_file.cpp, Common/game/room_version.h, Common/game/roomstruct.cpp, Common/game/roomstruct.h, Common/gfx/bitmap.cpp, Common/gfx/bitmap.h, Editor/AGS.Editor/AGSEditor.cs, Editor/AGS.Editor/Components/RoomsComponent.cs, Editor/AGS.Editor/NativeProxy.cs, Editor/AGS.Editor/Panes/Room/RoomEditFilters/BaseAreasEditorFilter.cs, Editor/AGS.Editor/Panes/Room/RoomEditFilters/CharactersEditorFilter.cs, Editor/AGS.Editor/Panes/Room/RoomEditFilters/EmptyEditorFilter.cs, Editor/AGS.Editor/Panes/Room/RoomEditFilters/ObjectsEditorFilter.cs, Editor/AGS.Editor/Panes/Room/RoomSettingsEditor.cs, Editor/AGS.Editor/Tasks.cs, Editor/AGS.Native/NativeMethods.cpp, Editor/AGS.Native/NativeMethods.h, Editor/AGS.Native/agsnative.cpp, Editor/AGS.Types/AGS.Types.csproj, Editor/AGS.Types/Enums/RoomResolution.cs, Editor/AGS.Types/Game.cs, Editor/AGS.Types/PropertyGridExtras/RoomMaskResolutionTypeConverter.cs, Editor/AGS.Types/Room.cs, Editor/AGS.Types/Settings.cs, Engine/ac/draw.cpp, Engine/ac/global_debug.cpp, Engine/ac/room.cpp
This change is in line with recent #651 and #654.
1. Deprecated room resolution type (high-res/low-res). All rooms are "real resolution" by default, and when loading old rooms their resolution type is promoted to "real resolution" if it matches game's type.
Also, resolution type will be switched to "real" as soon as the user imports new background.
Old types are kept solely for the purpose of importing old projects, but if user wants to continue working with the new editor they will have to adjust their ways accordingly.
2. Added MaskResolution property for the rooms which affects Hotspots, Regions and Walkable Areas (but not Walk-behinds which are always 1:1). This replaces automatic mask resolution dependent on resolution type, which was 1:1 for low-res and 1:2 for high-res. Now you may …
=> AGS 3: deprecated "room resolution" and added MaskResolution property instead

Engine/libsrc/almp3/almp3.c, Engine/libsrc/alogg/alogg.c
Fixes small bug in mp3/ogg decoder where it assumes creating an audiostream succeeds.
=> AGS3 mp3/ogg decoder: fix small lib bug.

Engine/ac/display.cpp, Engine/ac/draw.cpp, Engine/ac/game.cpp, Engine/ac/game.h, Engine/ac/global_game.cpp, Engine/ac/room.cpp, Engine/game/savegame_components.cpp, Engine/main/game_run.cpp, Engine/main/update.cpp, Engine/media/audio/audio.cpp
Use a finer time source to calculate fps.
I found some parts of the engine were using the requested framerate instead of the actual framerate. This works fine except when in maxed framerate, which never reaches 1000fps :) This PR fixes that too. (only when in maxed framerate mode, in normal gameplay it uses the requested framerate always)
=> AGS3: Make fps display stable and make timing workable when maxed-framerate

Engine/ac/global_audio.cpp, Engine/main/engine.cpp, Engine/media/audio/audio.cpp, Engine/media/audio/audio.h, Engine/media/audio/clip_mydumbmod.cpp, Engine/media/audio/clip_mydumbmod.h, Engine/media/audio/clip_myjgmod.cpp, Engine/media/audio/clip_myjgmod.h, Engine/media/audio/clip_mymidi.cpp, Engine/media/audio/clip_mymidi.h, Engine/media/audio/clip_mymp3.cpp, Engine/media/audio/clip_mymp3.h, Engine/media/audio/clip_myogg.cpp, Engine/media/audio/clip_myogg.h, Engine/media/audio/clip_mystaticmp3.cpp, Engine/media/audio/clip_mystaticmp3.h, Engine/media/audio/clip_mystaticogg.cpp, Engine/media/audio/clip_mystaticogg.h, Engine/media/audio/clip_mywave.cpp, Engine/media/audio/clip_mywave.h, Engine/media/audio/soundclip.h
Since we have the sound cache, we probably don't need this caching method for sounds.
This removes last_sound_played and restart() as restart was only used for this caching behaviour. It means one less thing to reimplement when moving to a different sound system.
It was disabled for multi-threading audio, presumably because we delete soundclips after they have played.
=> AGS3 audio: remove last_sound_played and soundclip->restart()

Engine/ac/audiochannel.cpp, Engine/ac/audioclip.cpp, Engine/ac/game.cpp, Engine/ac/global_audio.cpp, Engine/ac/system.cpp, Engine/ac/viewframe.cpp, Engine/game/savegame.cpp, Engine/game/savegame_components.cpp, Engine/main/update.cpp, Engine/media/audio/ambientsound.cpp, Engine/media/audio/audio.cpp, Engine/media/audio/audio.h, Engine/media/audio/clip_myogg.cpp, Engine/media/audio/clip_mystaticogg.cpp, Engine/media/audio/clip_mywave.cpp, Engine/media/audio/soundclip.cpp, Engine/media/audio/soundclip.h, Engine/plugin/agsplugin.cpp, Solutions/Engine.App/Engine.App.vcxproj, Solutions/Engine.App/Engine.App.vcxproj.filters
This pull request does following:
1. Cherry-picked @mgambrell's commit with channel locks from #659, with following edits:
* fixed few cases of broken logic, incorrect changes to array size etc;
* reduced big changes to indentation;
* reverted move of big chunks of code (not related to the commit's purpose);
the last two edits have a purpose to make merge cleaner.
2. Ammended this with little more refactoring, to comply with recent changes to audio code.
I believe that we need two more things here:
* Fix mutexes to work recursively on Linux too
* There are several places in soundclip implementations (OGG, MP3, MIDI) where AudioChannelsLock has to be placed, see TODO comments.
* anything else?
=> AGS 3: cherry picked and tidied mgambrell's AudioChannelsLocks commit

Editor/AGS.Editor/Resources/agsdefns.sh, Engine/ac/audiochannel.cpp, Engine/ac/character.cpp, Engine/ac/characterinfo_engine.cpp, Engine/ac/display.cpp, Engine/ac/display.h, Engine/ac/game.cpp, Engine/ac/gamestate.cpp, Engine/ac/gamestate.h, Engine/ac/global_api.cpp, Engine/ac/global_audio.cpp, Engine/ac/global_audio.h, Engine/game/savegame_components.cpp, Engine/main/engine.cpp, Engine/main/update.cpp, Engine/media/audio/audio.cpp, Engine/plugin/agsplugin.cpp, Engine/script/script_api.h
**UPDATE**.
This adds a method to play a voice-over clip in a non-blocking manner and without fixed connection to character state or any text displayed on screen. This might come very useful in scripting custom speech, because right now the only way to play a clip from speech.vox in a custom speech style is to call `Character.Say("&NNNN");`, which is a blocking command and makes it harder to handle any background activity.
The new script function is:
<pre>
/// Play speech voice-over in non-blocking mode, optionally apply music and sound volume reduction
import AudioChannel* PlayVoiceClip(Character*, int cue, bool as_speech = true);
</pre>
PlayVoiceClip plays a voice clip in non-blocking manner, clip is chosen by character's ID and cue ID and returns AudioChannel (atm this is always same …
=> Script API: implemented PlayVoiceClip function

Engine/main/engine.cpp
(Instead of guessing the definition or using our own version, myerrno.)
I'm not sure why we needed to do this in the first place. Was it a work around for older systems that didn't have a standard errno?
This fixes an issue where MSVC complains about different signatures for errno
=> AGS3 engine: Use errno.h on all systems

debian/make_ags+libraries.sh, debian/rules
* Switch from cowbuilder to pbuilder
* Fix for Debian mirror changes - these are permanent changes so the existing bootstrap for chroots would always fail
* Remove unneccesary package requirements on the host running the chroots
* Ubuntu doesn't have `dh` after installing the documented packages, so I've also added a note that Ubuntu will need to install 'debhelper'
* Ignore CMake in Debian packaging by explicitly specifying the build system - dh_auto_configure was autodetecting CMake files, and then the package would fail to build
The main change is switching from cowbuilder to pbuilder, which shouldn't be functionally different, but will work in more places. I don't think anything here is relying on using cowbuilder, and cowbuilder is more likely to have problems based on trying to …
=> Fixes for Debian/Ubuntu build script and packaging

Common/core/types.h, Common/util/stdtr1compat.h
As we only support minimum vs2015 and c++11 now.
I wasn't sure if I should remove the TR1INCLUDEs support header entirely.
=> AGS3 Commonlib: remove support for older compilers

CMAKE.md, CMake/FetchAllegro.cmake, CMake/FetchOgg.cmake, CMake/FetchTheora.cmake, CMake/FetchVorbis.cmake, CMake/c_flag_overrides.cmake, CMake/cxx_flag_overrides.cmake, CMakeLists.txt, Common/CMakeLists.txt, Common/libsrc/allegro4/CMakeLists.txt, Engine/CMakeLists.txt, Engine/libsrc/apeg-1.2.1/CMakeLists.txt, Engine/libsrc/ogg/CMakeLists.txt, Engine/libsrc/theora/CMakeLists.txt, Engine/libsrc/vorbis/CMakeLists.txt
Demonstrate automatic download and builds of all dependencies. You only need one Solution to build AGS and all its dependencies!
This will be extremely useful for cross-compilation as you should hopefully only need to supply one toolchain file.
Also includes some fixes for Windows to allow static runtime.
=> AGS3 Further cmake work

Common/debug/debugmanager.h, Common/game/customproperties.h, Common/util/string.h, Common/util/string_types.h, Editor/AGS.Editor/Resources/agsdefns.sh, Engine/ac/dynobj/cc_dynamicarray.cpp, Engine/ac/dynobj/cc_dynamicarray.h, Engine/ac/dynobj/cc_dynamicobject.h, Engine/ac/dynobj/managedobjectpool.h, Engine/ac/dynobj/scriptdict.cpp, Engine/ac/dynobj/scriptdict.h, Engine/ac/dynobj/scriptset.cpp, Engine/ac/dynobj/scriptset.h, Engine/ac/dynobj/scriptstring.cpp, Engine/ac/dynobj/scriptstring.h, Engine/ac/scriptcontainers.cpp, Engine/ac/string.cpp, Engine/ac/string.h, Engine/script/cc_instance.cpp, Engine/script/exports.cpp, Engine/script/script_api.h, Solutions/Engine.App/Engine.App.vcxproj, Solutions/Engine.App/Engine.App.vcxproj.filters
AGS script currently does not support templates, generics, or any good ways to reuse algorithms or user classes with multiple types, which is probably a reason we don't have any containers rather than dynamic arrays there.
In this situation it may be still a good idea to give users at least most commonly used type of key/value container which works with strings, because even if suboptimal but it is possible to store almost anything in a string, even invent a reference to other objects.
Also, I've been thinking that it may be viable to replace some of the existing API with Set or Dictionary, extending their use and reducing duplicate functionality at the same time. For example, this could be Custom Properties and Game.DoOnceOnly (see discussion in #701).
The suggested API for Set and …
=> Script API: string Set and Dictionary types

Editor/AGS.Editor/AGSEditor.cs, Engine/ac/global_debug.cpp, Engine/ac/runtime_defines.h, Engine/main/config.cpp, Engine/main/config.h, Engine/main/engine.cpp, Engine/main/quit.cpp, Engine/media/audio/audio.cpp, Engine/platform/windows/acplwin.cpp, Engine/platform/windows/setup/winsetup.cpp, Engine/plugin/agsplugin.cpp
After #734.
This lets engine use "digiid" and "midiid" config options on all platforms including Windows and deprecates Windows-only "digiwinindx" and "midiwinindx" options.
These two options are now tried as both number and string, letting user to define audio driver ID as a string for convenience, e.g.:
<pre>
[sound]
digiid=ALSA
midiid=AMID
</pre>
of course you have to know driver names from Allegro for this.
Special names: "auto" for getting default driver and "none" to disable sound.
~**NOTE:** I made these names case-sensitive by oversight but they probably should not be, so I'll fix that.~ should be fixed now
Additionally, I adjusted the initialization step; now it does not try to initialize sound blindly by requesting as much voices as engine likes, but instead queries available …
=> Uniform audio config option which supports string driver ID

.travis.yml
This file needs to be present in the branch in order to build it. For release purposes it probably needs to use the chroot build script or also run a build in a 32 bit container, and there is the Allegro version to consider, but for the moment just checking that builds occur is a good start.
Edit: the current build error should be covered by #717
=> Enable Travis-CI builds for the ags3 branch

.circleci/config.yml, docker/debian/Dockerfile
As simple as possible `config.yml` for building AGS Engine, on Debian, using [**circleci**](https://circleci.com/), which uses a [docker image](https://cloud.docker.com/repository/docker/ericoporto/ags-primary). Before accepting, this should be pretty similar to the current lost `.travis.yml` in the repo, but it's a different CI system so people can have options and decide which one to pursue. It also won't magically work without configuring things on Github or clicking Circle-CI in the Github Marketplace.
`Dockerfile` is below
```
FROM debian:stretch
RUN apt-get -y update
RUN apt-get -y --no-install-recommends install ssh tar gzip
RUN apt-get -y --no-install-recommends install curl ca-certificates
RUN apt-get -y --no-install-recommends install git
RUN apt-get -y --no-install-recommends …
```
=> Create config.yml for circleci

Common/game/main_game_file.cpp, Engine/ac/draw.cpp, Engine/ac/game.cpp, Engine/ac/global_game.cpp, Engine/ac/listbox.cpp, Engine/gui/guidialog.cpp, Engine/main/engine.cpp, Engine/script/script.cpp
GCC 8 is much more picky with sprintf and snprintf and fails compilation when the return value remains unchecked.
```c++
script/script.cpp: In function ‘char* make_ts_func_name(const char*, int, int)’:
script/script.cpp:515:40: error: ‘_’ directive output may be truncated writing 1 byte into a region of size between 0 and 60 [-Werror=format-truncation=]
snprintf(bne,MAX_FUNCTION_NAME_LEN,"%s_%c",bname,subd+'a');
^~~~~~~
script/script.cpp:515:13: note: ‘snprintf’ output between 3 and 63 bytes into a destination of size 60
snprintf(bne,MAX_FUNCTION_NAME_LEN,"%s_%c",bname,subd+'a');
~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
This used to be a warning only, but with `-Werror`, it causes failure.
Surprisingly, GCC is able to figure out when a static buffer is passed to …
=> Fixes to increase compatibility with GCC 8

Editor/AGS.Editor/DataFileWriter.cs, Editor/AGS.Editor/Panes/DialogEditor.cs, Editor/AGS.Editor/Panes/DialogOptionEditor.cs, Editor/AGS.Editor/Panes/GeneralSettingsPane.cs, Editor/AGS.Editor/Utils/DialogScriptConverter.cs, Editor/AGS.Types/Settings.cs
This is perhaps the easiest possible solution for using custom speech functions in dialog scripts.
In AGS 3.* dialog scripts are converted to regular ags script by substituting dialog-specific syntax with script commands, for example:
`CHARNAME: Sais something`
gets converted into:
`cCHARNAME.Say("Sais something");`
Obviously this hard-coded behavior was not compatible with custom speech functions many people do, forcing them to use regular functions in dialog scripts as well, which is often inconvenient.
The proposed change introduces two properties in General Settings: DialogScriptSayFunction and DialogScriptNarrateFunction. The values of these properties are simply substituting previously hard-coded "Say" and "Display" commands during dialog script compilation.
Additionally "Say" …
=> Editor: custom replacements for Say and Display in dialog scripts

Common/util/directory.cpp, Common/util/directory.h, Common/util/path.cpp, Common/util/path.h, Common/util/string.cpp, Common/util/string.h, Engine/ac/dynamicsprite.cpp, Engine/ac/file.cpp, Engine/ac/game.cpp, Engine/ac/global_dynamicsprite.cpp, Engine/ac/global_file.cpp, Engine/ac/listbox.cpp, Engine/ac/path_helper.h, Engine/test/test_string.cpp
For #697.
This ensures that when the script commands to open a file for writing in a special game location all subdirectories are created beforehand.
Engine ofcourse must test that these subdirectories are nested inside the allowed location.
Affected API:
* File.Open (write only)
* DynamicSprite.SaveToFile
* Game.SetSaveGameDirectory
=> Create all subdirectories when writing a file by script command

Editor/AGS.Editor/AGSEditor.cs, Editor/AGS.Editor/BuildTargets/BuildTargetBase.cs, Editor/AGS.Editor/BuildTargets/BuildTargetDataFile.cs, Editor/AGS.Editor/BuildTargets/BuildTargetDebug.cs, Editor/AGS.Editor/BuildTargets/BuildTargetLinux.cs, Editor/AGS.Editor/BuildTargets/BuildTargetWindows.cs, Editor/AGS.Editor/Tasks.cs, Editor/AGS.Types/Interfaces/IBuildTarget.cs, Editor/AGS.Types/Settings.cs, Editor/AGS.Types/WorkspaceState.cs
For #629.
This adds Game File Name setting that user may change anytime. It may also be left empty to use current project directory's name, as before.
Additionally Editor will now track last binary name used when building each target separately and store these in workspace file (Game.agf.user). Whenever target is rebuilt, if current game file name is different from its last recorded one, editor will try to delete file of old name if it still exists.
=> Game file name option in General Settings

Compiler/script/cs_parser.cpp, Compiler/test/cs_parser_test.cpp
Fixes #242.
Now, I spent a day poking around the compiler (and fixing few other minor issues in the process) but ended up with 1-line fix... which may be a correct thing, but it bothers me by how simple it is.
May there be other relevant test cases for this in addition to one I added?
**PS.** To elaborate a bit, this function I modified, **extract_variable_name()**, it seems that what it does is gathering a list of symbols accessed in a chain (i.e. "x.y.z.a"). The problem was that when the first member is a type, it set up a flag saying that the next member must be static, but did not reset it when next member was a static member which could have non-static members on its own naturally.
So my fix resets the flag in that case, allowing the function to continue parsing this chain.
**PPS.** …
=> Compiler: fixed accessing non-static members of static members

Android/library/jni/Android.mk, Engine/Makefile-objs, Engine/ac/display.cpp, Engine/ac/global_game.cpp, Engine/main/update.cpp, Engine/media/audio/audio.cpp, Engine/platform/android/acpland.cpp
Fixing Android build. Most things are trivial, but one I'd like to note is that apparently the older NDK version we suggest building against _does not have std::lround implemented_, even though they support C++11 in general.
Could be related: https://github.com/android-ndk/ndk/issues/82
So I went on to replace all the std::lround in our code to lround from C library.
=> 3.5.0 Android fixes

Common/ac/spritecache.cpp, Common/ac/spritecache.h, Common/game/main_game_file.cpp, Editor/AGS.Native/agsnative.cpp, Editor/Native/sprcache_agsnative.cpp, Engine/ac/dynamicsprite.cpp, Engine/ac/game.cpp, Engine/ac/global_dynamicsprite.cpp, Engine/ac/invwindow.cpp, Engine/ac/room.cpp, Engine/ac/sprite.cpp, Engine/ac/spritecache_engine.cpp, Engine/game/savegame_components.cpp, Engine/plugin/agsplugin.cpp
Fixes #773
This is to fix broken SpriteCache logic after commit 238a983 and clarify some things in the class.
This all started when I planned to refactor the class but stopped at some point and decided to push one commit which seemed to be pretty simple, yet broke certain logic inside the cache.
To elaborate a bit, there were certain inconsistencies in how sprites are described internally when dynamic sprites are added to the cache at runtime, but old program logic luckily ignored them. With commit 238a983 I wanted to introduce stricter rules in how sprite state is defined and that revealed this old problem. Also I missed couple of cases when a flag should be (re)set but was not.
In the end dynamic sprites got assigned to the MRU (most-recent-use) list along with the cached data, and then …
=> 3.5.0: fix Sprite Cache after faulty refactor

Editor/AGS.Editor/ApplicationController.cs
This prevents the crash reporter from sending screenshots. I think this commit should also be applied to all previous release branches. I'll look at other problems with the crash reporter separately.
=> Disable crash report screenshots

Editor/AGS.Native/NativeDLL.vcxproj, Solutions/Common.Lib/Common.Lib.vcxproj, Solutions/Engine.App/Engine.App.vcxproj, Solutions/alfont.props, Solutions/allegro.props, Solutions/directx.props, Solutions/libogg.props, Solutions/libtheora.props, Solutions/libvorbis.props
This adds property sheets which should allow for easier building of Engine and Editor, either using pre-built libraries or by building your own. This should also allow for easier to follow build instructions and make automated builds more straight-forward.
Example values:
<pre>set | findstr /b AGS_
AGS_ALFONT_LIB=D:\Build\ags-prebuilt-libs\vs2015\alfont-1.9.1
AGS_ALLEGRO_INCLUDE=D:\Build\lib-allegro\include;D:\Build\lib-allegro\build\VS2015\include
AGS_ALLEGRO_LIB=D:\Build\ags-prebuilt-libs\vs2015\allegro-4.4.2
AGS_DIRECTX_LIB=C:\Program Files (x86)\Microsoft DirectX SDK (August 2007)\Lib\x86\
AGS_LIBOGG_LIB=D:\Build\ags-prebuilt-libs\vs2015\libogg-1.3.2
AGS_LIBTHEORA_LIB=D:\Build\ags-prebuilt-libs\vs2015\libtheora-1.1.1
AGS_LIBVORBIS_LIB=D:\Build\ags-prebuilt-libs\vs2015\libvorbis-1.3.4</ …
=> Add property sheets for build dependencies

Editor/AGS.Editor/AGSEditor.cs
Partially fixes #792.
I believe in later .NET versions this is already forced off and it shouldn't be being used anyway. Ideally this should just mandate TLS 1.2 or higher, but I don't think this currently works with the TLS negotiation settings between .NET and the server where data is being sent - I tried it and got an SSL error.
=> Disable SSL v3

Common/util/mutifilelib.cpp
This fixes issues on systems where it is an error to read at an offset past end. (reading at end should still give you 0 bytes though)
edit: I didn't add a check to Seek itself since it would require grabbing the file size on load. Plus, we can't always rely on that if we're reading sub-resources (in instances where we pass Streams already repositioned to the right resource).
=> multifilelib: don't allow head sig search to extend past tail offset

Engine/ac/dialog.cpp, Engine/ac/display.cpp, Engine/ac/event.cpp, Engine/ac/game.cpp, Engine/ac/invwindow.cpp, Engine/ac/sys_events.cpp, Engine/ac/timer.cpp, Engine/ac/timer.h, Engine/gfx/ali3dogl.cpp, Engine/gfx/ali3dsw.cpp, Engine/gfx/gfxdriverbase.cpp, Engine/gfx/gfxdriverbase.h, Engine/gui/cscidialog.cpp, Engine/gui/mypushbutton.cpp, Engine/main/engine.cpp, Engine/main/game_run.cpp, Engine/main/graphics_mode.cpp, Engine/platform/base/agsplatformdriver.cpp, Engine/platform/windows/gfx/ali3dd3d.cpp, Engine/platform/windows/media/video/acwavi3d.cpp
This introduces the same changes as https://github.com/adventuregamestudio/ags/pull/795 but without the option of switching back to the new implementation (making comparisons harder).
When merging the 3.5.0 release branch into ags3, please be aware to ignore changeset 5424b49
=> Ags3.5  timing use counter only

Solutions/Engine.App/Engine.App.vcxproj
With 'HiDPI' scaling OpenGL and software renderers would only render a corner of the game  and mouse boundaries were mis-calculated. For OpenGL the display resolution was also mistakenly changed. This seems to fix it.
Fixes #736
=> Fix fullscreen modes on Windows system which use display scaling

Engine/ac/dialog.cpp, Engine/ac/display.cpp, Engine/ac/event.cpp, Engine/ac/invwindow.cpp, Engine/ac/timer.cpp, Engine/ac/timer.h, Engine/gui/cscidialog.cpp, Engine/gui/mypushbutton.cpp, Engine/main/game_run.cpp, Engine/main/game_run.h, Engine/platform/windows/media/video/acwavi3d.cpp
Refactor timing so all wait loops are done from the one function.
This reverts an earlier change made in 6db4421 that introduced PollUntilNextFrame that was useful but mixed in the concerns of fast forward and polling. Pulling that out that allowed us to use the one wait loop function.
=> timing: Refactor timing so all wait loops are done from the one function.

Engine/ac/game.cpp, Engine/ac/gamestate.cpp, Engine/ac/gamestate.h, Engine/ac/room.cpp, Engine/game/savegame.cpp, Engine/game/savegame_components.cpp, Engine/game/savegame_internal.h
This should fix #775 and may also fix #779 (not sure if both games mentioned there have same problem).
Changes:
* When loading a save keep viewport & camera data in a temporary struct and only apply in the end: this allows to clamp camera positions to actual room bounds (and not depend on loading order);
* Make sure load_new_room function only adjusts cameras when called *not* during restoring a save.
(This function is super messy and may benefit from splitting into two or more functions with different purposes, but that's not a task for this PR)
=> 3.5.0: fix viewport/camera restoration by reading data into temp structs and applying later

Common/ac/spritecache.cpp, Common/ac/spritecache.h, Editor/AGS.Editor/AGSEditor.cs, Editor/AGS.Editor/InteractiveTasks.cs, Editor/AGS.Editor/NativeProxy.cs, Editor/AGS.Editor/Tasks.cs, Editor/AGS.Native/NativeMethods.cpp, Editor/AGS.Native/NativeMethods.h, Editor/AGS.Native/agsnative.cpp, Engine/ac/global_game.cpp, Engine/main/engine.cpp
This pr attempts to address two potential problems with sprite file after which user may loose an ability to open project and/or loose some data.
1) The current order of actions, and error handling, when saving sprites is such that new data may get lost if there's a trivial file access error, and editor refuses to save it even if it failed to update a backup for example.
2) If the sprite file did not save correctly, next time you load the project it crashes because number of sprites in the sprite file does not match import references in the project itself.
In this pr problem 1) is resolved by saving new sprite file into temporary location provided by system API first, and replacing one in the project folder only after. Even if something fails at the second step, sprite cache *attaches …
=> 3.5.0: safety changes for Editor loading and saving sprite file

Common/core/platform.h, Engine/CMakeLists.txt, Engine/main/engine_setup.cpp
This fixes the colour issues found on macos builds. Also requires the changes made to `allegro-4.4.3.1-agspatch` but cmake should pick that up.
Refer to https://github.com/adventuregamestudio/ags/issues/818 for details
This has been tested in the `ags3` branch but this PR ports those fixes officially to 3.5.0
edit: this also removes a dependency on binreloc that snuck in from the sdl2 branch.  And some small fixes to allow building on a macbook that only has macos 10.10 installed :(
=> AGS 3.5.0 - macOS colour fix

Editor/AGS.Editor/Resources/agsdefns.sh, Engine/ac/scriptcontainers.cpp
By user request, this replaces "sorted" and "caseSensitive" booleans in number of functions to corresponding enum types:
<pre>
enum StringCompareStyle
{
eCaseInsensitive = 0,
eCaseSensitive = 1
};
enum SortStyle
{
eNonSorted = 0,
eSorted = 1
};
</pre>
This applies to some of the String functions as well as newer Dictionary.Create and Set.Create.
The constant values are chosen to match the meaning of boolean parameters, so that the old scripts still compile and work the same way.
---
As a separate commit I also changed two readonly properties in Dicrionary and Set:
* bool CaseSensitive to CompareStyle;
* bool Sorted to SortStyle;
Was not sure about it, so this is done as a separate commit that could be dropped if others think this is not good.
NOTE: Since this is a very new API I believe …
=> Script API: replaced "sorted" and "caseSensitive" boolean params with enums

Editor/AGS.Editor/AGSEditor.cs, Editor/AGS.Editor/Panes/SpriteImportWindow.cs, Editor/AGS.Editor/Panes/SpriteSelector.cs, Editor/AGS.Editor/Tasks.cs, Editor/AGS.Editor/Utils/SpriteTools.cs, Editor/AGS.Types/Sprite.cs
Adds a Sprite property to store the request to use an image's alpha channel. When reloading sprites from source the use of the alpha channel is checked against this property (so if you manually modify the source you can also modify this to suit). When replacing a sprite using the import UI this is used as a the default option for the 'use alpha channel' checkbox.
This should re-add the intended behaviour for bulk sprite reloading that had to be removed in order to fix #772
=> Add alpha channel import preference for Sprites

Editor/AGS.Editor/AGSEditor.cs
Initial changes were to remove freespace checks since:
- if freespace on a volume is actually low then Windows 10 hassles you about it anyway
- they are based on artbitrary values which aren't related to the active game project or correct at actual time of writing (so the result may not be relevant)
- they didn't take into account any form of symlink or redirection done at the filesystem level (so the result may be incorrect if using NTFS junctions)
- potentially masks an actual problem when saving data and the writes fail (see below)
Once the checks were removed and the disk was full, the project file for the game was truncated when writing and there was crash from native Windows components because the StreamWriter wasn't disposed of. The previous backup logic didn't seem correct either, …
=> Remove freespace checks and fix project data saving when writes fail

Engine/script/cc_instance.cpp
the ags script compiler rarely makes use of the registers "cx" and "dx"
if at all. this means they will contain a scriptvalue of type "undefined"
until first usage.
with the check assuming pushing undefined values to the stack is invalid,
it makes it impossible for a bugfix developer to use those registers
freely, as he needs to push them before usage to store their contents,
and pop the original contents after he is done using them.
if they happen to contain undefined values before the push, the engine
will quit, even though everything happening is perfectly safe:
the registers contained undefined before the push, some valid values
while it's used, and undefined again after the pop.
additionally, push is an operation used very often, and the 2 basically
unnecessary check add quite some …
=> PushValueToStack: remove validation code for undefined values

Common/ac/game_version.h, Common/ac/gamesetupstructbase.cpp, Common/ac/gamesetupstructbase.h, Common/ac/gamestructdefines.h, Editor/AGS.Editor/AGSEditor.cs, Editor/AGS.Editor/ApplicationController.cs, Editor/AGS.Native/agsicons.cpp, Editor/AGS.Types/BaseFolderCollection.cs, Editor/scintilla/src/Editor.cxx, Engine/ac/character.cpp, Engine/ac/draw.cpp, Engine/ac/dynamicsprite.cpp, Engine/ac/file.cpp, Engine/ac/global_viewframe.cpp, Engine/ac/invwindow.cpp, Engine/ac/viewframe.cpp, Engine/device/mousew32.cpp, Engine/gfx/blender.h, Engine/gui/gui_engine.cpp, Engine/gui/guidialog.cpp, Engine/libsrc/allegro-4.2.2-agspatch/midi.c, Engine/main/engine.cpp, Engine/main/engine_setup.cpp, Engine/main/graphics_mode.cpp, Engine/media/audio/audio.cpp, Engine/media/audio/soundcache.cpp, Engine/media/video/video.cpp, Engine/platform/windows/gfx/ali3dd3d.cpp, Engine/platform/windows/setup/winsetup.cpp
By [former request](https://github.com/adventuregamestudio/ags/issues/785#issuecomment-495952217) (although delayed more than I planned), this prepares a 3.4.4 update, which only contains critical bugfixes and compatibility fixes to be added on top of 3.4.*.
Notable fixes:
* fixed IsMusicVoxAvailable() in old games that had music.vox;
* fixed Character.GetDestinationY not working if coordinate is >255;
* fixed blinking portrait animations in old 32-bit games;
* fixed some very old games (like Ben Jordan 3) not displaying correct gfx on default inventory screen buttons.
* support loading experimental 3.3.0 CR games ("Skumring").
* allow to link to both Allegro 4.4.2 and 4.4.3.
=> Prepare 3.4.4 release

Engine/ac/dialog.cpp, Engine/ac/display.cpp, Engine/ac/event.cpp, Engine/ac/invwindow.cpp, Engine/ac/timer.cpp, Engine/ac/timer.h, Engine/gfx/ali3dogl.cpp, Engine/gfx/ali3dsw.cpp, Engine/gui/cscidialog.cpp, Engine/gui/mypushbutton.cpp, Engine/main/engine.cpp, Engine/main/game_run.cpp, Engine/main/game_run.h, Engine/platform/base/agsplatformdriver.cpp, Engine/platform/windows/gfx/ali3dd3d.cpp, Engine/platform/windows/media/video/acwavi3d.cpp
The timing api is essentially the same between `ags3` and `release-3.5.0`, just different implementations now.
This is intended for the next version of AGS (which I think `ags` is now), not 3.5
=> ags3/timing: reimplement timing changes similar to c4907f5d but without counter

Common/ac/dynobj/scriptaudioclip.h, Editor/AGS.Editor/AGSEditor.cs, Editor/AGS.Editor/Components/AudioComponent.cs, Editor/AGS.Editor/DataFileWriter.cs, Editor/AGS.Editor/Resources/agsdefns.sh, Editor/AGS.Editor/Tasks.cs, Editor/AGS.Types/AudioClip.cs, Editor/AGS.Types/Game.cs, Editor/AGS.Types/PropertyGridExtras/AudioClipTypeConverter.cs, Editor/AGS.Types/Settings.cs, Engine/ac/audioclip.cpp, Engine/game/game_init.cpp
For #709.
1) Adds ID property to AudioClip, and exports it to script.
2) Clips are saved in game data strictly in the order of their IDs. Note that since it's impossible to change an ID of a game object right now - that means in order of adding them to game.
3) When importing existing project IDs are assigned to clips in the order corresponding to the one they were written to the game data previously. This is to ensure that if script was relying on their order in Game.AudioClips array it still works.
=> Add ID property to AudioClip

Editor/AGS.Editor/AGSEditor.csproj, Editor/AGS.Editor/Components/AudioComponent.cs, Editor/AGS.Editor/Components/CharactersComponent.cs, Editor/AGS.Editor/Components/DialogsComponent.cs, Editor/AGS.Editor/Components/GuiComponent.cs, Editor/AGS.Editor/Components/InventoryComponent.cs, Editor/AGS.Editor/Components/ViewsComponent.cs, Editor/AGS.Editor/GUI/GUIController.cs, Editor/AGS.Editor/GUI/NumberEntryWithInfoDialog.Designer.cs, Editor/AGS.Editor/GUI/NumberEntryWithInfoDialog.cs, Editor/AGS.Editor/GUI/NumberEntryWithInfoDialog.resx, Editor/AGS.Editor/Panes/SpriteSelector.cs, Editor/AGS.Types/Game.cs
This adds context menu command for changing IDs (order in the list) of following game items:
* Audio clips
* Characters
* Dialogs
* GUIs
* Inventory items
* Views
Note that this does not introduce any new data, nor changes file formats, only lets user swap IDs of two game objects. This functionality is purely optional and is mostly meant for advanced users who would like to arrange items in a certain sequence at design time.
The input dialog also displays a warning that explains possible issues following changing order of items.
=> 3.5.0: Allow to change certain game item IDs in Editor

Engine/script/cc_instance.cpp
the special case for a push instruction followed by a pop in the code
here gives a penalty in form of an additional branch which is likely
mispredicted,
and several added instruction to every single push call for a relatively
rare special case.
it's better to improve the codegen not to emit such inefficient
statements.
=> Engine: don't pessimize general execution speed for rare special case

Engine/ac/dynobj/cc_dynamicobject.h, Engine/ac/dynobj/cc_dynamicobject_addr_and_manager.h, Engine/ac/dynobj/managedobjectpool.h, Engine/ac/room.h, Engine/ac/viewframe.h, Engine/plugin/agsplugin.cpp, Engine/script/cc_instance.cpp, Engine/script/runtimescriptvalue.cpp, Engine/script/runtimescriptvalue.h
this should speed up Readvalue() which is one of the most used functions during script executions (taking up as much as 3% cpu in my tests). inlining it *should* speed it up.
"should" because it's hard to measure any improvements to script interpreter code with the --fps method which is only adequate to measure gfx performance.
=> DRAFT: Readvalue() optimization

debian/ags+libraries/hooks/B00_copy_libs.sh
These files shouldn't be needed any longer, since freetype is now built and included with static linking and any licensing info should be originating from the same source.
=> Remove libfreetype from Linux release packaging

Editor/AGS.Native/NativeDLL.vcxproj
This was already changed for the debug build so this puts them back in-sync.
See #477
=> Add quotes to the AGS Native copy command (release build)

Editor/AGS.Editor/Panes/Room/RoomEditFilters/ObjectsEditorFilter.cs
When only the sprite for a room object was changed, and the sprite was chosen by double clicking the room object, room changes were not saved. This marks the room as modified, if a sprite was chosen by double-clicking the object and it wasn't the same sprite that the object was using already.
=> Fix room saving where object sprite was changed by double clicking

Editor/AGS.Types/PropertyGridExtras/AudioClipTypeConverter.cs
This is a workflow improvement, for selecting AudioClips in game settings and the ViewFrame editor. If you have more than a trivial amount of AudioClips to select from, it is easier to find them if they are sorted alphabetically.
User quote:
> Is it possible to organize all my sound files in this window?
I will most likely add sound to most of my animations in the View editor
however, it's kind of hard to find my sounds when they are all thrown into one window here... not even sorted by alphabet:sweat_smile:
if not possible ... adding sounds to the game will become a nightmare lol
- Easiest and clearest way to do this was using Linq
- I don't know why the AudioClip was being referred to as 'type', I think that was probably just a mistake, so I've also changed that for clarity
=> Sort AudioClip select list using the ScriptName property

debian/make_ags+libraries.sh
This was being expanded by the shell (so the value is always blank), and what is passed here will end up appending to the 'real' $ORIGIN, separated with a forward slash.
So currently the Debian build option gets set to `/libxx` which results in an actual rpath value of `$ORIGIN//libxx`
After this change the actual rpath value will be `$ORIGIN/libxx` which I think was the intended result
=> Remove $ORIGIN from build script

debian/copyright
This hadn't been updated since 2012 but is included for distribution. The changes are based on the output from [decopy](https://salsa.debian.org/debian/decopy) when looking at these directories:
* debian
* Common
* Engine
* libsrc
* Plugins
...and then manually cleaned up.
=> Update Debian copyright file

Common/ac/common_defines.h, Common/ac/gamesetupstruct.h, Common/debug/out.h, Common/util/ini_util.cpp, Common/util/ini_util.h, Engine/debug/debug.cpp, Engine/debug/debug_log.h, Engine/main/engine.cpp, Engine/main/engine.h, Engine/main/game_file.cpp, Engine/main/main.cpp, Engine/main/main.h, Engine/platform/android/acpland.cpp, Engine/platform/base/agsplatformdriver.cpp, Engine/platform/base/agsplatformdriver.h, Engine/platform/linux/acpllnx.cpp, Engine/platform/osx/acplmac.cpp, Engine/platform/windows/acplwin.cpp
For #520 (attempt 2)
* Engine detects command line arguments starting with `--tell-`, the suffixes are stored in a set as keys.
* If there was at least one such argument, engine will print out requested info to std out and stop. Because some of this info requires data from the game header, printing is done after game files were found and pre-read.
* Information is printed out in INI format, just like the game config, and may contain multiple sections of key/value pairs.
* This is not very common for INI, but currently the output also has "nested" sections which are indicated by '@' character(s) in their names. This is currently used to group number of sections together and give an extra leeway in avoiding possible naming conflicts in the future. The main reason for this addition was that …
=> Implemented basic functionality for --tell command (take 2, INI version)

Editor/AGS.Editor/Entities/EditorPreferences.cs, Editor/AGS.Editor/GUI/PreferencesEditor.Designer.cs, Editor/AGS.Editor/GUI/PreferencesEditor.cs, Editor/AGS.Editor/Panes/ScriptEditor.cs
This is mostly for #867, but also cleans up the spacing and alignment on the preferences form. If a script is modified externally, one of the following preferences is applied:
- `Always ask what to do`    <-- this is the default
- `Always reload the file`
- `Never reload the file`
So hopefully, if this is set to `Always reload the file` it should fix #867.
=> Add Editor preference for automatic script reload

.travis.yml
Fixes chroot build on Travis CI.
This might just be a temporary issue, but since this environment won't be used for release purposes I think disabling the check isn't an issue.
=> Keep Travis builds on Ubuntu 14.04

Editor/AGS.Editor/AGSEditor.csproj, Editor/AGS.Editor/GUI/GlobalVariableDialog.cs, Editor/AGS.Editor/Panes/GlobalVariablesEditor.cs, Editor/AGS.Editor/Resources/agsdefns.sh, Editor/AGS.Editor/TextProcessing/APITypeDef.cs
For #909.
Removes hard-coded types from the variable dialog (which were not updated in ages anyway) and instead use precreated list of types gathered by parsing script API header with regex.
=> In Global Variables pane gather list of types from script header

Editor/AGS.Editor/Panes/Room/RoomEditFilters/CharactersEditorFilter.cs, Editor/AGS.Editor/Panes/Room/RoomSettingsEditor.cs, Editor/AGS.Types/EditorFeatures/ContentDocument.cs, Editor/AGS.Types/EditorFeatures/EditorContentPanel.cs
For #624.
There's a lot to say about how editor handles property grid, for a quick recap see sequential comments to this thread: https://github.com/adventuregamestudio/ags/pull/619#issuecomment-464797516
In short the editor's event system was built with the assumption that only 1 working pane will be open at same time and that this pane will have exclusive ownership on objects it edits. As development progressed which ceased being true, especially after AGS 3.2.2 where docking UI was added and since when you may have several working panes at the same time. And this conflicts with how property grid gets updated, which presumes that it needs to collect objects and properties from the *active pane*, while some actions may have effect on other panes at the background.
Anyhow, this PR contains …
=> Editor: explicitly update room document's property list on character add/removal

Editor/AGS.Editor/Panes/Room/RoomEditFilters/BaseAreasEditorFilter.cs, Editor/AGS.Editor/Panes/Room/RoomEditFilters/CharactersEditorFilter.cs, Editor/AGS.Editor/Panes/Room/RoomEditFilters/EdgesEditorFilter.cs, Editor/AGS.Editor/Panes/Room/RoomEditFilters/EmptyEditorFilter.cs, Editor/AGS.Editor/Panes/Room/RoomEditFilters/IRoomEditorFilter.cs, Editor/AGS.Editor/Panes/Room/RoomEditFilters/ObjectsEditorFilter.cs, Editor/AGS.Editor/Panes/Room/RoomEditFilters/WalkBehindsEditorFilter.cs, Editor/AGS.Editor/Panes/Room/RoomSettingsEditor.cs
Existing behavior of the room editor, where mouse events may be handled by multiple layers at once until one of them claims it, came along with the new navigation bar code. IMO it is not very well thought through for two reasons:
* this mixes "visible" and "interactable" property in one (Visible), which is not necessarily wanted, and contradicts to how layers usually work in editing programs (e.g. paint software).
* event is handled in the order layers are stored internally in the room editor, and this order is arbitrary and hard-coded.
I suggest to disable this behavior for the time being and instead send events only to layers explicitly activated by user.
=> Editor: send mouse events only to active room layer

Editor/AGS.Editor/Panes/Room/RoomEditFilters/EdgesEditorFilter.cs
- Fixes #914 (positioning when room editor is using fractional scaling)
- Draws room edges with semi-transparent hatchings, the colour is still yellow but you can partially see through it if you want to check exact allignment
- Moves all drawing code to one place and pass the actual edge as a parameter (this also means each edge can have styling applied separately, but I've not done this at the moment)
=> Use FillRectangle and RectangleF to draw room edges

Common/font/fonts.cpp, Common/font/fonts.h, Common/gui/guidefines.h, Common/gui/guilabel.cpp, Common/gui/guilabel.h, Common/gui/guimain.h, Common/util/string.cpp, Common/util/string.h, Common/util/string_utils.cpp, Common/util/string_utils.h, Editor/Native/acgui_agsnative.cpp, Engine/ac/dialog.cpp, Engine/ac/display.cpp, Engine/ac/drawingsurface.cpp, Engine/ac/global_drawingsurface.cpp, Engine/ac/global_gui.cpp, Engine/ac/string.cpp, Engine/ac/string.h, Engine/gui/gui_engine.cpp, Engine/gui/mylabel.cpp, Engine/plugin/agsplugin.cpp
For #707 (although I did not touch splitting code itself much)
Text line wrapping in the engine is performed using split_lines() function, which is used in many locations from GUI elements to DrawStringWrapped script command.
This function was using fixed-sized arrays, which limited both total number of lines and width of such lines.
Current pr removes these limits and makes it use resizing buffers instead.
**Note 1**, I was concerned about this function being called way too often than it's actually may be necessary (which is a separate issue), so, instead of just using plain std::vector<String>, quickly set up a sort of a string pool which prevents from erasing vector elements (dynamic Strings) therefore reducing allocation/deallocation of those strings in game loops. I am not very happy …
=> Removed arbitrary limits in the text wrapping

Editor/AGS.Editor/ApplicationController.cs, Editor/AGS.Editor/GUI/ExceptionDialog.Designer.cs, Editor/AGS.Editor/GUI/ExceptionDialog.resx, Editor/AGS.Editor/GUI/PreferencesEditor.Designer.cs
For #792.
This disables user ability to send crash reports, because it's no longer working and is not particulary useful without proper accessible database (which we don't have anymore).
For now I simply hid the "Send report" button and changed the crash window text, telling user to post on forums instead.
=> Editor: disable sending data to ags server

Editor/AGS.Editor/Panes/SpriteImportWindow.Designer.cs
* 0 is the 'Import' button, so if you just want to import with no changes you can press enter (this was a user request)
* 1 is the 'Import all' button, so pressing tab and then enter is a shortcut to import everything where there are multiple files
* Past 1, the controls are treated as vertical columns, and you are already at the bottom of the first column
I looked at setting keyboard handlers to accept enter on other controls, but I worry this would lead to accidental form submission when people press enter after entering a value, which would then lead to implementing custom keyboard handlers for all controls.
=> Set the tab index on sprite import controls

.cirrus.yml, ci/android/Dockerfile
This adds the missing Android build that I couldn't get to work before.
Container build:
- download NDK version r16b to /opt and build toolchains for Arm, MIPS, and x86
- download SDK tools build to /opt and install required SDK packages using sdkmanager
- merge (no overwrite) SDK tools 25.2.5 over the top to regain Ant support
- download OpenJDK8 (via API query to get the latest LTS release from [AdoptOpenJDK](https://adoptopenjdk.net/)) to /opt
- download Ant to /opt
- build nativelibs and move them to /opt (this is the part that downloads from AWS so this is cached in the container to avoid being repeated, one of the Docker build arguments lets you specify which branch is used for this action)
Note: I still find that merging SDK tools to get Ant support is breaking things like the SDK …
=> Add Android CI build and release

Editor/AGS.Editor/Resources/agsdefns.sh, Engine/ac/character.cpp, Engine/ac/character.h, Engine/ac/global_object.cpp, Engine/ac/global_object.h, Engine/ac/object.cpp
For #560
Added optional "frame" parameter to Character.Animate and Object.Animate functions that tells which frame to begin animating with.
Trying to comply with existing behavior, reverse animations begin with the *previous frame*, so e.g. if you pass frame 0 they will begin with the last frame instead, if you pass frame 1 they will begin with 0th and so on.
Note: I was also thinking about adding same for Button.Animate, but I noticed that its parameter list does not have several other options, such as Direction and BlockingStyle, so maybe later there should be a separate task of adding them all at once. Besides, buttons are much easier to animate in script on your own.
=> Script API: added "frame" parameter to Character.Animate and Object.Animate

Engine/ac/global_game.cpp, Engine/ac/keycode.h, Engine/ac/sys_events.cpp, Engine/device/mousew32.cpp, Engine/main/game_run.cpp
`IsKeyPressed` and `ags_getch` used some complicated arithmetic to map between allegro4 keycodes and ags keycodes (which are mostly based on the older allegro3 keycodes). This led to potentially unreached code, as noted here: https://github.com/adventuregamestudio/ags/issues/237
I ran the functions through some loops, to generate all values, and created these more straightforward switch statements. This is essentially how the SDL2 port maps keys as well.
I also found some issues with macos key maps which should be fixed now. (essentially any alt-key combination did not work, nor did '?')
Note: the switch statements are "squashed" to one line per mapping to make it clearer but this does go against the style guide.
=> AGS3.5 Key mapping refactor and some macos key bugs

.cirrus.yml
The only functional difference is the addition of source archives to the release process, and that the release process is more visible. When releasing, a lot less tasks should run and it should be more apparent where artifacts are coming from.
Adds source releases for #800
Edit: forgot to mention [here](https://github.com/morganwillcock/ags/releases/tag/v3.5.0.17-test-1) is an example release
=> Split and update CI tasks

Editor/AGS.Editor/Panes/SpriteImportWindow.cs
The selected preference was never set in the import window because it mistakenly used its own default value. Also, some typo fixes.
Fixes #925
=> Fix default transparency preference for sprite import

Common/ac/gamestructdefines.h, Editor/AGS.Editor/AGSEditor.cs, Editor/AGS.Editor/DataFileWriter.cs, Editor/AGS.Editor/Tasks.cs, Editor/AGS.Editor/Utils/NativeConstants.cs, Editor/AGS.Native/NativeMethods.cpp, Editor/AGS.Native/agsnative.cpp, Editor/AGS.Types/Settings.cs, Engine/ac/room.cpp, Engine/ac/route_finder.h
For #936.
Originally the speed of character's walking & object's moving in room was scaled by the walkable area resolution. For example, if this resolution was 1:2 of the room's background, these speeds ended up multiplied by 2. This caused hi-res games (640x400 and up) having higher actual speeds than low-res games when using same speed values.
This PR introduces a switch which allows to turn speed scaling on and off, but meant for backward compatibility only and is **off** by default.
=> 3.5.0: have movement speed independent from room mask resolution by default

Editor/AGS.Editor/Components/RoomDesignData.cs, Editor/AGS.Editor/GUI/GUIController.cs, Editor/AGS.Editor/Panes/Room/RoomEditFilters/BaseAreasEditorFilter.cs, Editor/AGS.Editor/Panes/Room/RoomEditFilters/CharactersEditorFilter.cs, Editor/AGS.Editor/Panes/Room/RoomEditFilters/HotspotsEditorFilter.cs, Editor/AGS.Editor/Panes/Room/RoomEditFilters/ObjectsEditorFilter.cs, Editor/AGS.Editor/Panes/Room/RoomEditFilters/RegionsEditorFilter.cs, Editor/AGS.Editor/Panes/Room/RoomEditFilters/WalkBehindsEditorFilter.cs, Editor/AGS.Editor/Panes/Room/RoomEditFilters/WalkableAreasEditorFilter.cs, Editor/AGS.Editor/Panes/Room/RoomSettingsEditor.cs
By user request, this complements room editor saving the "design state" of a room by adding last selected item.
This is a trivial change from data saving perspective, but required additional modifications in the room editor to allow selecting item in "background mode" , that is - while the room pane is not active, because this will be the case when room just getting loaded.
For this I had to write function ~(per each room layer, unfortunately, because of how things are currently abstracted, or rather not abstracted enough)~ that checks whether room editor is an active pane or not. If it is, it then proceeds by a usual route and calls Factory.GUIController.SetPropertyGrid* method which will both update current property list and display one in the grid. If room editor is at the background …
=> Editor: remember last selected item in the room

Engine/platform/windows/gfx/ali3dd3d.cpp, Engine/platform/windows/gfx/ali3dd3d.h
ColorFill is used on pBackBuffer to redraw the black background and ensure that steam overlays and shader wrappers won't cause hall of mirror effects.
Related to issue #971.
=> Engine: clear D3D9 borders

Editor/AGS.Editor/AGSEditor.cs, Editor/AGS.Editor/Panes/SpriteSelector.cs, Editor/AGS.Editor/Tasks.cs, Editor/AGS.Editor/Utils/SpriteTools.cs, Editor/AGS.Types/Sprite.cs
Two new properites specify import width and height, and re-importing a sprite now uses these properties. This fixes the case where a re-import of a sprite from offset 0,0 would reload the frame as the entire image, and also lets the user reconfigure the tile size.
Fixes #973
=> Add editable sprite properties for import width and height

Engine/platform/windows/gfx/ali3dd3d.cpp, Engine/platform/windows/gfx/ali3dd3d.h
This solves the StretchRect distortion in a clean way for pixel perfect mode by using a texture as a render target.
=> Engine: D3D9 render to texture

Editor/AGS.Editor/AutoComplete.cs
This was returning one character too many. For the autocomplete header descriptions it included a carriage return (but not the adjacent line feed) which was then immediately stripped, or where there were no following characters the Editor would crash.
In the absence of tests, probably best if a couple of other people can verify that this looks correct.
Fixes #981
=> Fix autocomplete crash

Editor/AGS.Editor/AGSEditor.cs, Editor/AGS.Editor/Panes/SpriteImportWindow.cs, Editor/AGS.Editor/Panes/SpriteSelector.cs, Editor/AGS.Editor/Tasks.cs, Editor/AGS.Editor/Utils/SpriteTools.cs, Editor/AGS.Types/Sprite.cs
This allows you to re-import a sprite of a different size without needing to adjust the tile size, which fixes the issue of re-importing images which are not from a spritesheet and have been resized. There isn't enough information to automatically set the flag automatic for existing projects where there is already tile size information for the sprite, but I think the upgrade mechansim should cover every case except where the tile selection begins at 0,0 and the size is larger than any other tile from the same source.
Secondary changes were:
- internal import functions are modified to be more consistent in terms of the parameters that are passed
- import size and offset values are hidden from the property grid whilst ImportAsTile is set to false
I'm not entirely sure on the name …
=> Add sprite property 'ImportAsTile'

Editor/AGS.Editor/Components/SpeechComponent.cs
It'll be a lot faster (relatively) to avoid reading the timestamps for all files, when a previous filename or timestamp check has already set the rebuild flag.
=> Editor: Faster check for speech file rebuild

Common/CMakeLists.txt
oldgamestruct.h has been removed from master.
=> Removes oldgamestruct.h from Common/CMakeLists.txt

Engine/CMakeLists.txt
cdaudio has been removed on master, so we need to update CMakeLists.txt
=> Removes cdaudio from Engine/CMakeLists.txt

Engine/ac/sys_events.cpp
To fix script compatibility. Because allegro4's `key` array can hold values other than 0 or 1, this breaks scripts as the values are converted to script bool (which is really just an int define)
Fixes https://github.com/adventuregamestudio/ags/issues/1010
=> Ensure IsKeyPressed only returns 1 or 0

Editor/AGS.Editor/Utils/Utilities.cs
Use 'using' blocks for Bitmap and Graphics resources that should be disposed of. Previously a temporary Bitmap wasn't disposed of.
=> Editor: fix resource leak in sprite preview

Editor/AGS.Editor/AGSEditor.cs, Editor/AGS.Editor/Components/AudioComponent.cs, Editor/AGS.Editor/DataFileWriter.cs, Editor/AGS.Editor/Tasks.cs, Editor/AGS.Types/AudioClip.cs, Editor/AGS.Types/Game.cs, Editor/AGS.Types/PropertyGridExtras/AudioClipTypeConverter.cs, Editor/AGS.Types/Settings.cs, Editor/AGS.Types/ViewFrame.cs
This was a big mistake to switch to using AudioClip.ID as a reference to clips in property fields, because currently ID value is volatile and may change if the list of clips was modified in the middle. This commit partially reverts 72a01d64e31a93be900d6e04bd22e812c64608bc and puts fixed index into use again.
This affects ViewFrame's Sound property and GeneralSettings.PlaySoundOnScore.
=> 3.5.0 Editor: Fix audio clip references in property field, revert to using internal fixed index

Editor/AGS.Editor/Panes/AudioEditor.Designer.cs
Disables the pause and stop buttons by default, otherwise the first time that this pane is used you could attempt to pause or stop audio that isn't currently being played.
Fixes #1016
=> Editor: set default state for audio controls

Editor/AGS.Types/Settings.cs
This stops a previously loaded game's filename being potentially applied to the next game that is loaded.
Fixes #1024
=> Reset game's filename when loading

Engine/ac/draw.cpp, Engine/ac/game.cpp, Engine/ac/game.h, Engine/ac/global_debug.cpp, Engine/ac/global_game.cpp, Engine/ac/timer.cpp, Engine/ac/timer.h, Engine/debug/debug.cpp, Engine/debug/debugger.h, Engine/main/game_run.cpp, Engine/main/game_run.h, Engine/main/main.cpp
Remake of #873.
* No longer store special "maxed" value in "frames_per_second" variable, because it's a game property that may be changed anytime by a script.
* Allow to toggle "maxed fps" mode on and off with the same key combo (Ctrl+E); note: as before, works only if you run game with `--fps`. When turning off should return to the latest fps value set by game script.
* Added enum defining fps display mode (no need to wonder what "display_fps == 2" means).
=> Engine: allow to quit from max framerate mode (2)

Common/ac/game_version.h, Common/ac/gamesetupstruct.cpp, Common/ac/gamestructdefines.h, Common/font/fonts.cpp, Common/font/fonts.h, Common/game/main_game_file.cpp, Common/gfx/allegrobitmap.cpp, Common/gfx/allegrobitmap.h, Editor/AGS.Editor/AGSEditor.cs, Editor/AGS.Editor/DataFileWriter.cs, Editor/AGS.Editor/Tasks.cs, Editor/AGS.Types/AGS.Types.csproj, Editor/AGS.Types/Enums/FontAutoOutlineStyle.cs, Editor/AGS.Types/Font.cs, Engine/ac/display.cpp, Engine/ac/display.h, Engine/gfx/blender.cpp, Engine/gfx/blender.h
This is a remake of @fernewelten's #892 PR. Old one still had several mistakes, but unfortunately I didn't know if and when fernewelten is planning to complete it, so decided to speed things up and fix it on my own.
Following is the original description:
---
_This is proposed code for issue #878 (automatic outlines)._
_Added two additional fields to fonts:_
- _`AutoOutlineStyle` (`Rounded`, `Squared`)._
- _`AutoOutlineThickness` (positive integer, or 0 for default)_ 
_(I couldn't use "1" as the default for `AutoOutlineThickness` because currently, scaled bitmap fonts get an outline that is thicker than 1)._ 
_The fields will only show in the editor if `OutlineStyle==Automatic`._
_The field `OutlineFont` will now only show if `OutlineStyle==UseOutlineFont`._
_The algo for generating the …
=> Automatic font outlines (2)

Common/ac/gamestructdefines.h, Editor/AGS.Editor/Resources/agsdefns.sh, Engine/ac/global_object.cpp, Engine/ac/object.cpp
See #940
This may be somewhat controversial, so I'd like to hear more opinions on this.
The original Object.SetView function had a somewhat unexpected behavior: if no explicit values were provided for loop and frame then it kept the last loop and frame object had from the previously set view.
Although documented, but such behavior seem to cause confusion among users who expect it to reset loop and/or frame instead.
This pr changes default values to 0, which resets loop and frame if they are not provided.
Original behavior is kept for games made with previous script API version.
=> Script API: changed Object.SetView default loop & frame values to 0

Common/game/roomstruct.cpp, Common/game/roomstruct.h, Editor/AGS.Editor/Resources/agsdefns.sh, Editor/AGS.Native/agsnative.cpp, Editor/AGS.Types/Enums/ScriptAPIVersion.cs, Engine/ac/drawingsurface.cpp, Engine/ac/dynobj/scriptdrawingsurface.cpp, Engine/ac/dynobj/scriptdrawingsurface.h, Engine/ac/global_api.cpp, Engine/ac/global_hotspot.cpp, Engine/ac/global_hotspot.h, Engine/ac/global_region.cpp, Engine/ac/global_region.h, Engine/ac/global_walkablearea.cpp, Engine/ac/global_walkablearea.h, Engine/ac/hotspot.cpp, Engine/ac/hotspot.h, Engine/ac/region.cpp, Engine/ac/room.cpp, Engine/ac/room.h
For #480.
This is a minor addition, but may have numerous practical uses.
There's already a DrawingSurface interface, and room areas - walkable areas, hotspots, regions and walk-behinds - are represented as 8-bit bitmap masks, so it's trivial to connect these.
The 4 new script functions allow to get corresponding room mask as a DrawingSurface, and do with it whatever a game developer wants.
Surfaces will be 8-bit, and each color index corresponds to an area ID. Color index = 0 is "no area", or eraser.
There are necessary safety tests in the engine to make sure that indexes beyond supported area limit are simply ignored (treated as "no area").
For example, following script will expand walkable area 1:
<pre>
DrawingSurface* ds = GetDrawingSurfaceForWalkableArea();
ds.DrawingColor = 1; // …
=> Script API: get DrawingSurface for the room masks

Editor/AGS.Editor/Resources/agsdefns.sh, Editor/AGS.Types/Enums/ScriptAPIVersion.cs, Engine/ac/draw.cpp, Engine/ac/object.cpp, Engine/ac/room.cpp, Engine/ac/roomobject.cpp, Engine/ac/roomobject.h
For #954, and for consistency with Character class, this implements Object.ManualScaling and Object.Scaling, and deprecates Object.IgnoreRoomScaling.
No internal data was changed (room object already has got a suitable variable for storing current scale).
Unlike current Character's scaling, Object's don't have an arbitrary limit and instead limits value to 1 -> INT16_MAX percents range ((object's scale variable is int16), or, speaking multipliers, - from x0.01 to x327.67;
For backward compatibility, using old IgnoreRoomScaling property will reset scaling to 100% (also, for consistency with character).
=> Script API: implemented Object.ManualScaling and Object.Scaling

Editor/AGS.Controls/ScintillaNET/ScintillaControl.cs
Turns out that my suggested fix was more legit than I thought.
Newer Scintilla.NET versions leave the `base.WndProc(ref m);`, which is causing the cursor flickering and cpu usage spikes on Windows 10, as the very last case to call.
Therefore this hotfix should be good enough until the day we get to upgrade Scintilla to the latest version.
=> Scintilla: Hotfix for cursor flickering and cpu usage on Windows 10

Editor/AGS.Editor/ColorThemes/Controls/ComboBoxCustom.cs, Editor/AGS.Editor/Panes/ScriptEditor.cs
On windows 10 the performances of switching between script tabs was horrible compared to windows 7 due to the function list updates to the combobox
I've wrapped the functions combobox changes between BeginUpdate-EndUpdate which halved the impact, then I also made so that only the currently focused script pane performs the update, because the update is triggered at any change of focus anyway so there's little point to update every single combobox from every open script.
~~To improve further I'm also updating the DockPanelSuite to the latest 3.0.6 version which brings back the performances I see on a W7 VM.~~
~~There's just one problem, the newer DockPanelSuite versions use a different api for theming so the theme loading is not working correctly and causes a NullPointerException at some …
=> Tab switching performance improvements

.cirrus.yml, Editor/AGS.Editor.Tests/AGS.Editor.Tests.csproj, Editor/AGS.Editor.Tests/ColorThemes/ColorThemesTests.cs, Editor/AGS.Editor.Tests/ColorThemes/Controls/ComboBoxCustomTests.cs, Editor/AGS.Editor.Tests/Properties/AssemblyInfo.cs, Editor/AGS.Editor.Tests/packages.config, Editor/AGS.Editor/AGSEditor.cs, Editor/AGS.Editor/AGSEditor.csproj, Editor/AGS.Editor/ColorThemes/ColorThemeJson.cs, Editor/AGS.Editor/ColorThemes/ColorThemes.cs, Editor/AGS.Editor/ColorThemes/Controls/ComboBoxCustom.cs, Editor/AGS.Editor/ColorThemes/IColorThemes.cs, Editor/AGS.Editor/Entities/EditorPreferences.cs, Editor/AGS.Editor/Entities/IAppSettings.cs, Editor/AGS.Editor/GUI/GUIController.cs, Editor/AGS.Editor/IAGSEditorDirectories.cs, Solutions/AGS.Editor.Full.sln, Solutions/AGS.Editor.NoNative.sln
Reference #1035 
In short I
- Added a project for writing tests to the editor. With NUnit and NSubstitute
- I refactored some code to not make use of Singletons because any impure static call makes testing complicated
- Wrote a few tests
My goal here is to make the testing framework available so people can start using it when they write new code, it's not my plan to start adding coverage to already existing code
What I haven't done is added test execution to the CI system, since I'm not familiar with Cirrus CI and have only tried Dockerfiles a little bit, maybe someone else could do that. The easiest way of running the tests from the command line is by using the dotnet CLI, I used the following command `dotnet test AGS.Editor.NoNative.sln --no-build`. The caveat with using dotnet CLI I …
=> Added testing framework to the AGS Editor

Editor/AGS.Editor/Panes/PaletteEditor.cs, Editor/AGS.Native/agsnative.cpp
This fixes #1030 and another mistake that was found during tests.
1. Internal palette not updated when importing one from the image file. This results in incorrect sprite colours remap made during same editor session ([refer to this comment for details](https://github.com/adventuregamestudio/ags/issues/1030#issuecomment-581580564)).
2. If user sets "Leave as-is" option for transparency at import, then palette remap is skipped. This seem to be simply an oversight in the original code conditions.
Both of these seem to be old issues (also reproducible in AGS 3.2.1), but they are at the same time annoying and easy to fix enough for 3.5.0 patch.
=> 3.5.0 patch: couple of fixes for 8-bit games (editor)

Common/util/string.cpp, Common/util/string.h, Engine/ac/dynobj/scriptdict.h, Engine/ac/dynobj/scriptset.h, Engine/test/test_string.cpp
This pr modifies a String, moving char buffer pointer and length parameter out of the allocated buffer header, and have them as a plain class members. This has two consequences:
* the simple reading operations no longer require extra pointer dereference;
* this allows to reference an external buffer, as an option.
(Note: I used [ScummVM's string as an example too](https://github.com/scummvm/scummvm/blob/master/common/str.h), although it's a bit different)
Latter lets support wrapping an external constant buffer without owning it. Which allows to even wrap string literals. This should be safe, because any writing operation in String class first ensures that owned string buffer exists and has only 1 reference (String::BecomeUnique does that).
Of course, when I say "safe", I assume it is …
=> Supports wrapping a const buffer for the String class

Editor/AGS.Editor/BuildTargets/BuildTargetLinux.cs
`alleg-sdl2digi.so` is currently shipped with the Editor/Linux package but it's not part of the built target of the Editor, so it's missing when building for Linux using the Editor.
=> adds alleg-sdl2digi.so to Linux build target

Compiler/script/cs_parser.cpp, Compiler/test/cs_parser_test.cpp
Allows for float values to be used and shows errors when trying to use non-zero integers for float, String, or pointer types.
Fixes #188
=> Compiler: Default parameters and improvements

Editor/AGS.Editor/GUI/CustomResolutionDialog.Designer.cs, Editor/AGS.Editor/GUI/CustomResolutionDialog.cs, Editor/AGS.Editor/GUI/CustomResolutionDialog.resx, Editor/AGS.Types/Utilities.cs
Adds extra labels to display the aspect ratio of the selected resolution.
Fixes #1057
=> Editor: show aspect ratio on resolution select

Editor/AGS.Editor/BuildTargets/BuildTargetLinux.cs, debian/ags+libraries/startgame
Not all echo implementations or defaults will expand escape sequences
=> Linux: switch to printf in launch wrapper

Editor/AGS.Controls/AdressBarEx/AddressBarExt.cs, Editor/AGS.Editor/Panes/Room/RoomSettingsEditor.Designer.cs, Editor/AGS.Editor/Panes/Room/RoomSettingsEditor.cs
- Fixes that the current address bar node is not always saved into design time data
- Stop the address bar from implementing its own overflow to prefer the built-in ToolStrip overflow. Indirectly fixes #1054 
- Remove unused checkbox for "Display Coordinates as Low Res"
- Rearrange room editing controls to give more space to the address bar
To maintain vertical alignment of the dropdown buttons within the ToolStrip overflow, it seems to be a requirement that text be present in the item. So to fix this, empty dropdown items with an arrow are now replaced by the literal text "···" and no arrow. This has a side-effect of the buttons becoming wider and easier to click, which I think is an improvement over what is there now.
=> Updates for room editor controls

Engine/ac/character.cpp, Engine/ac/characterextras.h, Engine/ac/display.cpp, Engine/ac/gamestate.cpp, Engine/ac/gamestate.h, Engine/ac/overlay.cpp, Engine/ac/room.cpp, Engine/ac/viewport_script.cpp, Engine/game/viewport.cpp, Engine/game/viewport.h
Fixes #1069
1. Fixed crash in case `viewport.Camera = null;` in script. Now actually handle having viewport.Camera unset.
2. Moved coordinate transformation into Viewport class to make code in places simplier, which also fixes couple of bugs:
* RoomToScreen/ScreenToRoom functions that had hardcoded conversion through camera 0, while primary viewport may have different linked camera;
*  GameState::ScreenToRoomImpl() was not properly returning viewport index.
3. Fixed Screen.AutoSizeViewportOnRoomLoad was adjusting camera 0, now adjusts whatever camera is linked to primary viewport instead.
4. (#1069) Fixed character speech displaying in wrong Y position if camera was zoomed in or out. (A character's height was not included when passing room-screen coordinate conversion.)
=> 3.5.0: fix several oversights in new camera system

Common/util/geometry.cpp, Common/util/geometry.h, Engine/ac/character.cpp, Engine/ac/character.h, Engine/ac/characterextras.h, Engine/ac/draw.cpp, Engine/ac/overlay.cpp, Engine/game/viewport.h
This is not exactly a bugfix but rather unfinished business, it had to be in 3.5.0 new cameras but I forgot to add.
Originally, and still even after addition of new camera system, speech coordinates are set based on where character is located relative to **primary viewport**.
This change makes it find either _first viewport_ in the array this _character is seen in_, or one _which camera is nearest to the character_.
**NOTE:** this pr is based on #1076 code so should be merged after that.
A test game that illustrates the problem and allows to test the solution.
[test_camera_speech.zip](https://github.com/adventuregamestudio/ags/files/4674063/test_camera_speech.zip)
Controls:
* space - make character talk
* 1-4 - turn viewports on and off
* click around to make character walk, and see how …
=> 3.5.0: Display character speech relative to nearest viewport

Engine/main/engine.cpp
need to not use `LC_ALL`on MacOS
=> Fixes float locale dependant in #1015

Engine/main/main.cpp, Engine/platform/base/agsplatformdriver.cpp, Engine/platform/base/agsplatformdriver.h, Engine/platform/windows/acplwin.cpp
Add the --no-message-box option in Windows for showing messages on stdout instead of
a message box.
This required changing the SubSystem from Windows to Console, and writing a simple
main() function that calls WinMain(). By making the application a "Console" app,
stdout/stderr handlers properly get initialized now.
This also makes the Windows port behavior more consistent with other platforms:
Startup information now gets shown.
The help menu now appears if there's an error.
The --tell parameter works.
=> Windows: Add option to disable message boxes

Engine/CMakeLists.txt, Engine/platform/osx/alplmac.mm, OSX/README.md
This PR adds MacOS (OSX) build instructions for using CMake with Xcode.
It also renames `ac2game.dat` to `game.ags` in the context of MacOS (OSX) build and the game initialization script.
=> Adds MacOS build instructions for using CMake with Xcode and changes CMakeLists.txt to use game.ags 

Editor/AGS.Editor/Resources/agsdefns.sh, Engine/ac/gamestate.h, Engine/ac/global_api.cpp, Engine/ac/global_game.cpp, Engine/ac/global_game.h, Engine/ac/runtime_defines.h, Engine/main/engine.cpp, Engine/main/game_run.cpp
Resolves #647
* Added WaitMouse(timeout) to complement existing functions (WaitKey, WaitMouseKey).
* All Wait functions return a more precise reason they were skipped:
- `0` = ended by timeout;
- `> 0` = keycode
- `< 0` = negated mouse button code minus one (because of how mouse codes start with 0). In order to get mouse code do this: `MouseButton btn = -(result + 1);`
* All Wait* functions (*including* Wait) may have infinite timeout if negative argument is passed; in all functions except Wait() timeout argument is now optional with default value -1.
* Added SkipWait() function that immediately cancels any active Wait*.
NOTE: SkipWait will be only useful if called from `repeatedly_execute_always` or `late_repeatedly_execute_always`.
=> Script API: expand Wait functions set for more versatility

Editor/AGS.Editor/Components/AudioComponent.cs, Editor/AGS.Editor/Components/BaseComponentWithFolders.cs, Editor/AGS.Editor/Components/CharacterIDChangedEventArgs.cs, Editor/AGS.Editor/Components/CharactersComponent.cs, Editor/AGS.Editor/Components/DialogsComponent.cs, Editor/AGS.Editor/Components/GuiComponent.cs, Editor/AGS.Editor/Components/InventoryComponent.cs, Editor/AGS.Editor/Components/RoomsComponent.cs, Editor/AGS.Editor/Components/ScriptsComponent.cs, Editor/AGS.Editor/Components/ViewsComponent.cs, Editor/AGS.Editor/Panes/CharacterEditor.cs, Editor/AGS.Editor/Panes/Room/RoomEditFilters/CharactersEditorFilter.cs, Editor/AGS.Types/Game.cs, Editor/AGS.Types/HelperTypes/FolderListHybrid.cs, Editor/AGS.Types/Utilities.cs
This fixes underlying character etc arrays not updated properly when user changes game object ID. This mistake caused these objects to remain on previous positions, and, for example, retain previous indexes at runtime (until user reopens project in the editor).
Additional fixes:
* fixed value constraints when changing View's ID;
* update character's preview when View's ID is changed;
* fixed property grid was switching to object whose ID you are changing even if it has different active pane;
* at the same time fixed property grid of inactive panel did not have ID updated in the object title for the second object when two IDs swapped (i.e. if you have Char1 and Char2 panes opened, and swap their IDs, then only one of them got their property grid title updated).
* fixed Character Room …
=> 3.5.0 Patch: fix "Change ID" does not work correctly + related oversights

Common/script/cc_script.cpp
- When engine resolves script imports, empty string imports are expected to be `nullptr`.
[`Engine/script/cc_instance.cpp#L1591`](https://github.com/adventuregamestudio/ags/blob/c52217180969576717173777d8ac195dd4347047/Engine/script/cc_instance.cpp#L1591)
- This works because when reading script objects, empty strings (a single `\0` character) are replaced by a `nullptr`.
[`Common/script/cc_script.cpp#L39`](https://github.com/adventuregamestudio/ags/blob/c52217180969576717173777d8ac195dd4347047/Common/script/cc_script.cpp#L39)
- When writing a script object, we don't treat the `nullptr` case, so if you read a script object, and want to write it back to a file, it breaks on empty strings.
[`Common/script/cc_script.cpp#L211`](https://github.com/adventuregamestudio/ags/blob/c52217180969576717 …
=> Script should serialize back empty imports as empty strings.

Engine/ac/display.cpp, Engine/ac/game.cpp, Engine/ac/overlay.cpp, Engine/ac/screenoverlay.cpp, Engine/ac/screenoverlay.h, Engine/game/savegame_components.cpp
Introduces an internal x,y offset so the original coordinates are not lost due to adjustments for image borders.
Fixes #1098
=> Engine: addresses positioning bug with custom text window GUI

Common/debug/debugmanager.cpp, Common/debug/debugmanager.h, Common/debug/out.h, Common/gui/guimain.cpp, Engine/ac/route_finder.cpp, Engine/debug/debug.cpp, Engine/debug/debug_log.h, Engine/debug/logfile.cpp, Engine/debug/logfile.h, Engine/debug/messagebuffer.cpp, Engine/game/game_init.cpp, Engine/gfx/ali3dogl.cpp, Engine/main/engine.cpp, Engine/main/engine_setup.cpp, Engine/main/game_file.cpp, Engine/main/game_start.cpp, Engine/main/graphics_mode.cpp, Engine/main/main.cpp, Engine/main/quit.cpp, Engine/platform/windows/win_ex_handling.cpp, Engine/plugin/agsplugin.cpp
This is done as a preliminary step for #640.
**As a preface**, engine logging system in a nutshell works like this:
* each message has a "verbosity level" ranging from "debug" to "fatal error".
* there may be a number of message groups, which allow to separate messages related to a component or engine's function (main, script, spritecache, managed pool);
* there may be a number of outputs (stdout, log file, in-game console); each output has its own filter settings, that define which groups & level of messages to let through.
When a message is sent to logging system it tries each registered output implementation, and if its filter allows, message is being printed.
---
**What this PR does**: it actually allows to configure these filters by user (player).
A new section called "[log]" is …
=> 3.5.1: Configurable log options

Engine/CMakeLists.txt
- installs ags on `/usr/local/bin/` on Linux systems by using `sudo make install` on the makefile that was generated by cmake. 
- you can override the directory by passing a different install prefix when generating the makefile, like `-DCMAKE_INSTALL_PREFIX=/home/user/.local/` and the binary `ags` will go inside a directory named `bin/` in that prefix.
Having a install target would greatly simplify building ags snap package.
=> adds install target to cmake for ags on Linux

Common/font/fonts.cpp, Common/game/main_game_file.cpp, Engine/ac/global_debug.h, Engine/ac/global_display.cpp, Engine/ac/gui.cpp, Engine/ac/parser.cpp, Engine/ac/string.cpp, Engine/ac/translation.cpp, Engine/debug/filebasedagsdebugger.cpp, Engine/gui/guidialog.cpp, Engine/script/cc_instance.cpp
Fixes #1080
I'm not 100% sure this is correct, but I've tested it on gcc 10 and it now builds. Hopefully the CI checks confirm that the changes were correct and I haven't broken anything.
=> Engine: Add required '#include <cstdio>' for gcc 10

Editor/AGS.Editor.Tests/AGS.Editor.Tests.csproj, Editor/AGS.Editor.Tests/Panes/FreePanControlTests.cs, Editor/AGS.Editor/AGSEditor.csproj, Editor/AGS.Editor/Panes/FreePanControl.cs, Editor/AGS.Editor/Panes/Room/RoomSettingsEditor.Designer.cs, Editor/AGS.Editor/Panes/Room/RoomSettingsEditor.cs
Creates FreePanControl.cs
- replaces BufferedPanel in Room Editor with FreePanControl
- adds pan with middle mouse click hold to ags editor
- also accepts left click+shift+ctrl 
- adds simple isolated tests for FreePanControl in `AGS.Editor.Tests` to document expected behavior.
**[CirrusCi builds of this PR](https://cirrus-ci.com/github/adventuregamestudio/ags/pull/1089)**
This is a rewrite of #1046
Attempt to solve #613 , [agsforums-57490](https://www.adventuregamestudio.co.uk/forums/index.php?topic=57490.0)
=> adds mouse pan with middle click on Room panel

Engine/main/engine.cpp
This presumably fixes allegro not being able to find its special resources in a game directory if the engine executable is installed somewhere else.
Fixes #896 .
=> 3.5.1: Provide find_resource callback for allegro to search in gamedir

Engine/game/savegame.cpp, Engine/game/savegame.h, Engine/game/savegame_components.cpp, Engine/game/savegame_internal.h
The new audio API was not saving all the necessary properties to restore directional audio (the one from channel.SetRoomLocation)
=> Engine: fixed directional audio data not being saved

Engine/platform/windows/gfx/ali3dd3d.cpp
GetMode() may return the wrong refresh rate in the case the monitor is not at 60hz, moreover the config refresh setting never makes it far enough to be used.
Leaving it as D3DPRESENT_RATE_DEFAULT will ensure switching from windowed to fullscreen is quick and reliable, as long as it's the same resolution.
=> Engine: let D3D9 decide refresh rate on its own

ci/windows/Dockerfile
Triggering a container rebuild will hopefully sort the issue with CI tasks failing on Windows.
Package upgrades:
NuGet command line client 5.7.0
Inno Setup 6.0.5
CMake 3.18.4
=> CI: Bump Windows container for package updates

Editor/AGS.Editor/AGSEditor.csproj, Editor/AGS.Editor/Components/ScriptsComponent.cs, Editor/AGS.Editor/GUI/StartNewGameWizardPage2.cs, Editor/AGS.Editor/Utils/Utilities.cs, Editor/AGS.Editor/Utils/Validation.cs, Editor/AGS.Types/Settings.cs
Fixes #1090 (although since the error handling for the settings panel is in AGS.Types some logic is duplicated)
Adds a struct and support functions for passing error and warning information. Messages are just strings and immutable in transit, the idea being that a single front-end validation may invoke and aggregate messages from delegated validation functions. The resulting message should be suitable to show underneath an input field which incorporates dynamic checks.
For alternative/legacy use of the same validation functions, the same struct can still be used (built in messages don't have to be used).
``` c#
// ValidationResult evalulates as a boolean
if (Project.CanBeProjectDirectory(path))
{
// everything is fine
}
else
{
// handle the problem
}
```
There is a message formatting …
=> Editor: Add some validation tools and validate game filename

Solutions/AGS.Editor.Full.sln
- Mixed Platforms build of AGS.Editor.Full.sln uses Release_MD for
Compiler and Compiler2 projects.
Alternatively it could build Common.lib instead of Common_MD.lib on `Release` directory.
=> Update AGS.Editor.Full.sln to fix Compiler Release build

ci/windows/Dockerfile
- some RUN commands reduced in rearrange to minimize layers (reduce docker size)
- no vcpkg bootstrapping, pulls prebuilt xiph libraries from nuget
(vcpkg was not building with current VS tooling in this image)
- docker image size lowered a bit and is now 11GB
Same as #1150 but applied to master
=> Dockerfile changes to fix Windows CI builds

Engine/main/engine.cpp, Engine/main/main.cpp, Engine/platform/windows/setup/winsetup.cpp
Resolves #1154
Moved "meta" settings from "--tell-config" to "--tell-gameproperties", improved value naming, added couple of more things.
Embedded winsetup receives a merged config map with "--tell-gameproperties" contents.
These were not really a true part of user config, thus supporting old names is not necessary.
All values printed by "--tell-gameproperties" go in "gameproperties" section, and are following:
* title - game title;
* guid - game guid;
* legacy_uniqueid - random generated 32-bit integer, that worked as UID in old games (may be ignored if guid is present);
* legacy_resolution - deprecated resolution type (integer), should be "8" for all new games;
* legacy_letterbox - bool, whether "letterbox by design" setting is on (considered obsolete);
* resolution_width - native …
=> Implement --tell-gameproperties instead of putting game info in --tell-config

Solutions/Compiler2.Lib/Compiler2.Lib.Test.vcxproj
Solution contains Compiler2.Lib.Test; this project wrongly references `Compiler_d.lib` as additional input dependency for the linker. The correct value would be `Compiler2_d.lib`. Otherwise, googletests won't compile.
=> Fix wrong object dependency in solution Compiler2.Lib.sln

Compiler/script2/cs_scanner.cpp, Compiler/test2/cc_parser_test_1.cpp, Solutions/Compiler2.Lib/Compiler2.Lib.Test.vcxproj
This PR depends on the previous one (fix dependency in solution Compiler2.Lib.sln).
The new compiler ran into an endless loop when encountering a last section that is completely empty. This happens in particular when a room file is completely empty. This PR fixes this.
=> Prevent new compiler from going into an endless loop on encountering a last section that is completely empty

Compiler/script2/cc_symboltable.cpp, Compiler/script2/cc_symboltable.h, Compiler/script2/cs_parser.cpp, Compiler/test2/cc_parser_test_1.cpp
Address the following bugs:
- In `import` statements, `autoptr` entities aren't processed correctly, their pointer isn't implied but should be.
- All `autoptr` types are displayed with a spurious trailing `" "` in messages.
In particular, `String` is affected.
Fix the code so that the bugs go away.
=> New compiler import autoptr bugs

Compiler/script2/cs_parser.cpp, Compiler/test2/cc_bytecode_test_1.cpp, Compiler/test2/cc_parser_test_1.cpp
New compiler generated an error when an attribute was incremented or decremented.
Typical code: `oObject.Graphic++;`
This PR fixes the issue.
=> New compiler: Fix: Error on incrementing an attribute

Compiler/script2/cs_parser.cpp, Compiler/test2/cc_parser_test_1.cpp
Typical expression: `player.InventoryQuantity[15] = 0;`
In this expression, player is read-only. But a value may be assigned to the term `player.InventoryQuantity[15]` because the value that `player` points to is _not_ readonly.
The cause of the bug turned out to be in a piece of code that determines whether a sub-expression is the last sub-expression of the expression. This calculation didn't start at the start of the sub-expression, as it should have, but at some random other location. (Also, there was a redundant test on whether the expression is completely empty which I deleted. Also, fixed a typo.)
=> New compiler: Fix bug in determining read-only expressions

Compiler/script2/cs_parser.cpp, Compiler/script2/cs_parser.h, Compiler/test2/cc_bytecode_test_1.cpp, Compiler/test2/cc_parser_test_1.cpp
Typical code: 
```
String s;
if (s != null)
Display("Message: %s", s);
```
Cause of bug: The new compiler generated a String comparison opcode. This should have been a regular (non-String) comparison opcode because a String comparison will yield an error unless _both_ operands are non-null Strings. 
Additionally, in the specific local area that I had to fix there were some unspecific error messages. In particular, they talked about “the” operator, which doesn't really help the coder if a complex expression with _many_ operators is involved. I rewrote those messages to name the specific operator.  This entailed getting this information to the place of the error messages. This also entailed slightly changing some googletests that had expected the unspecific error messages before.
=> New compiler: Comparing String to 'null' yields a runtime error.

Common/ac/gamesetupstruct.cpp
according to analysis of the game data files produced by ags versions
2.6.2, 2.7.0, 2.7.1 and 2.7.2, inventory item names were only added
as of 2.7.0, and dialog script names as of 2.7.2.
the old code used to read past the bounds of the original ac2game.dta
in those versions, effectively reading junk from whatever was stored
behind the data file in the "pack".
closes #1184
=> game data parser: bugfix for versions 2.6-2.7.1

Common/game/main_game_file.cpp, Common/game/main_game_file.h, Common/game/room_file.cpp, Editor/AGS.Editor/DataFileWriter.cs
Resolves #828 (hopefully).
The idea is to enforce the rule that any new change or addition to the main game data should be appended as an extension to the end of the current format. So far we were just adding these changes in the midst of existing format randomly, which complicates format parsing for external tools, and imho just generally a bad thing for long term maintenance.
A support is added for reading and writing a list of "blocks" appended after the "classic" format. _The blocks meta format is shared with the one from room files_, trying to keep things consistent if possible. The only addition is the replacement of 1-byte numeric ID with a 16-chars long string ID. I am thinking of doing same ID change for room format, again for consistency and convenience.
The proposal is to keep …
=> AGS 4: extended meta format for main game data

Engine/main/game_run.cpp
Fixes #1176.
These are key combinations that are not part of the game itself, therefore they should be given a priority and checked regardless of current game state.
=> AGS 3: ensure to check special key combos prior to in-game keys

ci/android/Dockerfile
ant 1.10.7 was removed from apache server.
if this PR results in a successful build, the now used ant version 1.10.9
should be archived ASAP and made available from another URL via a mirror.
addressing #1187
=> android dockerfile: bump ant to oldest version still available

Compiler/script2/cs_parser.cpp, Compiler/script2/cs_parser.h, Compiler/test2/cc_parser_test_1.cpp
This PR fixes the bug reported in issue #1195.
If a forward declaration of a struct has any of the qualifiers 'autoptr', 'builtin', or 'managed' then the actual declaration needs them, too. If OTOH the forward declaration doesn't, then the actual declaration may not have them.
=> New compiler: Forward struct declaration and actual declaration must match with respect to 'autoptr', 'builtin', and 'managed'

Compiler/script2/cs_parser.cpp, Compiler/test2/cc_bytecode_test_0.cpp, Compiler/test2/cc_parser_test_0.cpp
Fix bug: A runtime error occurred whenever a program created a variable of size zero.
Typical code:
```
struct EmptyStruct {
};
{
EmptyStruct s;
}
```
=> Bugfix: Zero-size variables must not get the stack out of sync

Editor/AGS.Editor/GUI/TabbedDocumentManager.cs, Editor/AGS.Editor/Panes/FreePanControl.cs, Editor/AGS.Editor/Panes/Room/RoomSettingsEditor.cs, Editor/AGS.Types/EditorFeatures/EditorContentPanel.cs
For #613, adjust panning & zoom controls as suggested in comments.
* added PanButtons property to FreePanControl and use that instead of hardcoding which buttons to use;
* pass another event (on key up) through from the parent EditorContentPanel class to Room editor pane to be able to react to released keys there;
* changed room panning from Ctrl+Shift+LClick to Space+LClick; Middle mouse button also works.
I did not really know how to better organize this. FreePanControl is not guaranteed to have focus, so it's not possible to catch press and release events there. What I did: made RoomSettingsEditor do that instead, and toggle FreePanControl's PanButtons to allow and disallow Left Click as Space is pressed and released.
If it's bad, I can maybe add methods for passing key pressed/release …
=> Editor: adjustments for room panning controls

Editor/AGS.Editor/AGSEditor.cs, Editor/AGS.Editor/InteractiveTasks.cs, Editor/AGS.Types/WorkspaceState.cs
Long overdue. When upgrading projects, the next run/compile should always do a "rebuild all". This will save us from bogus error reports, and that strange invalid character exception from the new compiler.
Now that I'm writing this I realize  it would be better to serialize this extra value in case the user closed the project without running, although adding parameters to the xml would be annoying if we want to backport this as a simple quality-of-life improvement.
=> Editor: enforce a rebuild-all when running after upgrading the project

Editor/AGS.Editor/GUI/GUIController.cs, Editor/AGS.Types/AGS.Types.csproj, Editor/AGS.Types/Character.cs, Editor/AGS.Types/GUI.cs, Editor/AGS.Types/GUIButton.cs, Editor/AGS.Types/GUILabel.cs, Editor/AGS.Types/GUIListBox.cs, Editor/AGS.Types/GUITextBox.cs, Editor/AGS.Types/NormalGUI.cs, Editor/AGS.Types/PaletteEntry.cs, Editor/AGS.Types/PropertyGridExtras/ColorUIEditor.cs
This is frankly just a quick experiment, and I don't know if it looks good and convenient to use. It seems working though.
Introduced UITypeEditor wrapper over classic ColorDialog. Set it as an editor for each game property of type Color. This replaces default color picker called by property grid, which is not good for AGS Editor at all.
Caveats:
* ColorDialog is from System.Windows.Forms, if that matters. EDIT: made the UITypeEditor class in AGS.Types to use delegate instead of directly referencing Windows.Forms namespace.
* ColorDialog is modal and appears at the center of the screen, as opposed to default non-modal color picker that was displayed right next to the property.
* I made it save "custom colors" array in a static variable, so it will persist during editor session, but it's …
=> (Test) AGS 4: use standard ColorDialog as a color picker for properties

Compiler/script2/cs_parser.cpp, Compiler/test2/cc_parser_test_1.cpp
1.
The Engine doesn't grok allocating dynamic memory of size zero.
Typical code: 
```
managed struct S {}; // doesn't contain any variables (attributes and functions don't count here)
function oCupboard_Anyclick()
{
S *structvar1 = new S;
S *structvar2[] = new S[99];
}
```
2.
Cannot  assign dynamic array to a dynamic pointer or vice versa.
Typical code:
```
managed struct T {
int payload;
};
function oCupboard_Anyclick()
{
S *structvar3 = new S[99]; // dynamic array assigned to pointer variable
S *structvar4[] = new S; // dynamic memory assigned to array variable
}
```
=> New compiler: Fix bug: Prevent assignments pointer ↔ dynamic array or allocation of 0 bytes

Compiler/script2/cs_parser.cpp, Compiler/test2/cc_parser_test_1.cpp
Typical code (should yield an error):
```
void Test1() {
struct MyStruct {
int a;
};
}
```
=> New compiler: Disallow local struct or enum type definitions

Compiler/script2/cs_parser.cpp, Compiler/test2/cc_parser_test_0.cpp
Addresses #1203. The function return type `const string` should be recognized as different from `string`.
Typical code that should be correct:
```
const string GetLiteral() 
{ 
return "string literal"; 
}         
```
Typical code that should be flagged as incorrect:
```
import const string GetConstString();
import void UseString(string s);
int game_start()
{
UseString(GetConstString());
}
```
=> New compiler: Recognize the function return type 'const string'

Editor/AGS.Editor/Resources/agsdefns.sh, Engine/ac/draw.cpp, Engine/ac/overlay.cpp, Engine/ac/screenoverlay.h
Resolves #1202.
This implements Overlay.ZOrder property in compliance with other similar properties from GUI and GUIControl.
Overlays are now z-sorted along with the GUI on screen.
To keep default and backward compatible behavior, newly created overlays have their zorder set:
* For custom overlays and QF4 speech style overlays: to INT_MIN, so that they are beyond any GUI.
* For the text and portraits overlays: to INT_MAX, so that they are above any GUI.
User may adjust Overlay.ZOrder anytime after their creation, so long as there's an access to overlay object in script.
What to note on potential problems?
It must be kept in mind that overlays are not interactable, therefore mouse always "clicks through" them and activates whatever is behind. Just something to remember or maybe write in …
=> Script API: implement Overlay.ZOrder

Editor/AGS.Editor.Tests/Types/RoomTests.cs, Editor/AGS.Editor/AGSEditor.csproj, Editor/AGS.Editor/ApplicationController.cs, Editor/AGS.Editor/Components/RoomsComponent.cs, Editor/AGS.Editor/NativeProxy.cs, Editor/AGS.Editor/Panes/Room/RoomEditFilters/BaseAreasEditorFilter.cs, Editor/AGS.Editor/Panes/Room/RoomEditFilters/CharactersEditorFilter.cs, Editor/AGS.Editor/Panes/Room/RoomEditFilters/EdgesEditorFilter.cs, Editor/AGS.Editor/Panes/Room/RoomEditFilters/EmptyEditorFilter.cs, Editor/AGS.Editor/Panes/Room/RoomEditFilters/HotspotsEditorFilter.cs, Editor/AGS.Editor/Panes/Room/RoomEditFilters/IRoomEditorFilter.cs, Editor/AGS.Editor/Panes/Room/RoomEditFilters/ObjectsEditorFilter.cs, Editor/AGS.Editor/Panes/Room/RoomEditFilters/RegionsEditorFilter.cs, Editor/AGS.Editor/Panes/Room/RoomEditFilters/WalkBehindsEditorFilter.cs, Editor/AGS.Editor/Panes/Room/RoomEditFilters/WalkableAreasEditorFilter.cs, Editor/AGS.Editor/Panes/Room/RoomSettingsEditor.cs, Editor/AGS.Editor/Utils/BitmapExtensions.cs, Editor/AGS.Native/NativeMethods.cpp, Editor/AGS.Native/NativeMethods.h, Editor/AGS.Native/agsnative.cpp, Editor/AGS.Types/Enums/PaletteColourType.cs, Editor/AGS.Types/Interfaces/IRoomController.cs, Editor/AGS.Types/Room.cs
Related to #469 
In short I have
1. Centralized certain room operations used by the room editor to the `IRoomController`, instead of globally used native invocations from `NativeProxy`. This is affects the public API for editor plugin developers.
2. Wrote a small framework as `System.Drawing.Bitmap` extensions for drawing images. I shopped around for potential third party frameworks but drawing on 8-bit indexed images is generally not supported.
3. Replaced a lot of `NativeProxy` invocations related to `IRoomController` with C# code. There's still some room code that uses `NativeProxy`, primarily related to loading/saving data from .crm files. This will be replaced in a future pull request.
4. Deleted dead AGS.Native code related to rooms.
=> Refactored room editor to use graphics from C# instead of AGS.Native

Editor/AGS.Editor.Tests/Types/RoomHotspotTests.cs, Editor/AGS.Editor.Tests/Types/RoomMessageTests.cs, Editor/AGS.Editor.Tests/Types/RoomObjectTests.cs, Editor/AGS.Editor.Tests/Types/RoomRegionTests.cs, Editor/AGS.Editor.Tests/Types/RoomTests.cs, Editor/AGS.Editor.Tests/Types/RoomWalkBehindTests.cs, Editor/AGS.Editor.Tests/Types/RoomWalkableAreaTests.cs, Editor/AGS.Editor.Tests/Types/UnloadedRoomTests.cs, Editor/AGS.Editor/Components/RoomsComponent.cs, Editor/AGS.Native/NativeDLL.vcxproj, Editor/AGS.Types/Room.cs, Editor/AGS.Types/RoomHotspot.cs, Editor/AGS.Types/RoomMessage.cs, Editor/AGS.Types/RoomObject.cs, Editor/AGS.Types/RoomRegion.cs, Editor/AGS.Types/RoomWalkBehind.cs, Editor/AGS.Types/RoomWalkableArea.cs, Editor/AGS.Types/SerializeUtils.cs, Editor/AGS.Types/UnloadedRoom.cs
Related to #469 
Room entities was lacking serialization handling so I added it, with test cases as proof of concept since no actual uses this yet. They will be used in the next PR related to converting the rooms to open format, but this was big enough change I felt it warranted an isolated PR.
The QA I did here was to make sure that the serialization and deserialization handled all the properties that being read/written in `load_crm_file(...)` and `save_crm_file(...)` from `agsnative.cpp`, and I wrote tests that handles these properties from xml. Anything left out can probably be added in the next PR.
I realize there's an ongoing discussion about using yaml instead, but we already have lots of convenient code for handling xml and I feel like adding yaml and handling it for ags should be …
=> Room serialization

Editor/AGS.Editor/Resources/agsdefns.sh, Engine/ac/character.cpp, Engine/ac/display.cpp, Engine/ac/display.h, Engine/ac/draw.cpp, Engine/ac/game.cpp, Engine/ac/gamestate.cpp, Engine/ac/gamestate.h, Engine/ac/global_game.cpp, Engine/ac/gui.cpp, Engine/ac/overlay.cpp, Engine/ac/overlay.h, Engine/ac/runtime_defines.h, Engine/ac/speech.cpp, Engine/ac/speech.h, Engine/game/savegame.cpp, Engine/main/engine.cpp, Engine/main/game_run.cpp, Engine/main/update.cpp
This is a slightly different remake of #1127.
This PR exposes couple of overlays that were already internal objects but could not be accessed from script in any way, plus adds couple of complementary things.
`readonly attribute Overlay *Speech.TextOverlay` returns special overlay created for the blocking speech, or null if no such text is on screen.
`readonly attribute Overlay *Game.PortraitOverlay` returns special overlay created for the speech portrait, or null if no such portrait is on screen.
Because of how blocking speech works, these overlays will be only available in `repeatedly_execute_always` and `late_repeatedly_execute_always` script callbacks.
But these are valid overlays in every other aspect: you can use its properties, read or change position, for example.
Calling Remove() …
=> Script API: add access to blocking speech overlays and latest skip reason

Compiler/script2/cc_compiledscript.cpp, Compiler/script2/cc_compiledscript.h, Compiler/script2/cs_parser.cpp, Compiler/script2/cs_parser.h
This addresses #1219.
In some rare cases, memory allocation for section names went awry. The passage cc_compiledscript.cpp#L236 and following was probably responsible for the bug, it reserves space proportionate to `codesize` (the size of the generated Bytecode) instead of the number of sections. This would fail when very little code is generated for a lot of sections, which possible but rarely the case. So this would explain why the bug only happens rarely. 
I reformulated that passage and the similar passages of that file, introducing some named constants, to make it easy to verify at a glance whether they are set correctly. I rewrote ´ResizeMemory()` to calculate with array elements instead of bytes and renamed some variables to (hopefully) make it clearer what they mean. …
=> New compiler: Memory allocation bug when the section changes

Engine/ac/display.cpp
This was a regression introduced with commit 41d156ef63 (from pull request #1104). Only one of the two calls to draw_text_window_and_bar in _display_main were changed to pass the local adjustedXX and adjustedYY variables. Games using the other unmodified call (when `asspch` is 0) have their text boxes shifted to the bottom and right as a result.
For example in Order of the Thorne: The King's Challenge, we get
And with the fix in this pull request we get
The Blackwell Converge is another game impacted:
Current master:
With the fix in this pull request:
=> Engine: Fix positioning with custom text window GUI

.cirrus.yml, ci/linux/Dockerfile
Adds build of libogg, libtheora, and libvorbis into the Linux build Docker container, with installation into /opt. Installing here means that the existing Debian hook script still gives the same result, but newer versions are available to be copied into the archive which is distributed as the Linux version of the engine.
The CI task which builds intermediate archives for each architecture will now look to replace the named Xiph libraries, if present. i.e. lib64/libvorbis.so.0 will be replaced by dereferencing /opt/lib/libvorbis.so.0 when lib64/libvorbis.so.0 exists
This should be seen as a short term change to work around issues found within older Debian libraries, ideally final archive archive contents need to be verified to be in the correct state but this needs further improvements to …
=> Linux: package newest versions of Xiph libraries

Engine/gfx/ali3dogl.cpp
Resolves #1145.
This supposedly fixes XWindow not updated to the wanted size immediately after GL init. I don't know how often (and to how many users) this happens, it happened to me on Ubuntu virtual machine, and also several users reported this happening with our prebuilt binaries (meaning they also used Ubuntu/Debian).
The window parameters seem to be set correctly, because it would stretch automatically as soon as user drags it around. So probably the problem was that it did not update right after new params are set.
To be honest, I have close to zero knowledge of how XWindows work, and this fix was more a result of experimentation. It would be great if someone can give it a test. I'll try to make users who reported this to test this too.
=> 3.5.0 patch: on Linux: fixed OpenGL window did not set to proper size after GL init

Editor/AGS.Editor/BuildTargets/BuildTargetLinux.cs, debian/ags+libraries/startgame
Given that the primary reason of having the launch wrapper symlinked would be to provide an interface to one or more launch scripts under an alternate name or path, it would seem logical that when the output provides a name it should be what the user specified.
i.e.
```
$ ./linked_launch --help
Usage: linked_launch [<ags options>]
```
=> Linux: display launch wrapper name without dereferencing

Compiler/script2/cc_symboltable.h, Compiler/script2/cs_parser.cpp, Compiler/test2/cc_parser_test_1.cpp
This fix addresses #1237.
Typical code that this fix addresses:
```
{
GetTextHeight
player.Baseline = 1;
}
```
(`GetTextHeight` is a function, so a `(` should follow. It doesn't; the compiler couldn't handle that.)
I'm taking this as an opportunity to add more null pointer guards in the vicinity to make the code more robust.
=> New compiler: Fix bug: Dump when an assignment follows a function symbol

Engine/ac/overlay.cpp
This was a regression from cb7ab658a.
The custom IDs are supposed to be `> OVER_CUSTOM`, but since that commit it can be `OVER_CUSTOM` (for example if the `screenover` vector is empty). We need the loop to have one more iteration than the number of overlays to be sure we find an unused one.
This issue caused some overlays to use `OVER_CUSTOM ` as their ID, which can then result in the "SetTextOverlay internal error: inconsistent type ids" as the ID can gets changed in `add_screen_overlay` when it thinks it need to try to find an unused ID again.
=> Engine: Fix finding unused overlay custom ID

Common/game/main_game_file.cpp
One of the tester for the AGS engine in ScummVM reported a buffer overflow and a crash when trying to save in King of Rock. I checked this and in my case I am getting a buffer overflow when starting the game.
The issue is in `ReadDialogs()`:
```c++
if (script_text_len > 1) {
// Originally in the Editor +20000 bytes more were allocated, with comment:
//   "add a large buffer because it will get added to if another option is added"
// which probably refered to this data used by old editor directly to edit dialogs
char *buffer = new char[script_text_len];
in->Read(buffer, script_text_len);
if (data_ver > kGameVersion_260)
decrypt_text(buffer);
old_dialog_src[i] = buffer;
delete[] buffer;
}
```
For this game `data_ver` is equal to `kGameVersion_260`, so `decrypt_text()` does not get called. …
=> Common: Make sure old dialog script strings are null terminated

Editor/AGS.Editor/AGSEditor.cs, Editor/AGS.Editor/BuildTargets/BuildTargetDebug.cs, Editor/AGS.Editor/BuildTargets/BuildTargetWindows.cs, Editor/AGS.Types/AudioClip.cs, Editor/AGS.Types/AudioClipFolder.cs, Editor/AGS.Types/Enums/AudioFileBundlingType.cs, Editor/AGS.Types/Settings.cs
This implements new option in General Settings called "Attach game data to exe" which currently works only when building Windows version of the game, where traditionally data was appended to engine executable.
It's "true" by default, but may be disabled, in which case GAMENAME.ags file will be copied to Compiled/Windows folder, similar to how Linux build is deployed.
The reasoning behind this is to optionally let users have same sort of distribution for Windows as made for other systems. This might also improve situation with antiviruses which seem to not like ags games reading executable file all the time.
Also changed displayed name of audio bundling properties from "In Game EXE" to "In Main Game Data" (this was not correct since we added build for Linux support).
PS. Maybe it is better …
=> 3.5.1 Editor: implemented Settings.AttachDataToExe

Engine/main/main.cpp
In response to #961 and #975.
Implemented following:
--conf - defines explicit and only config file path;
--user-data-dir - defines user data directory for game files (aka $SAVEGAMEDIR$);
--shared-data-dir - defines shared data directory for game files (aka $APPDATADIR$);
Example of use:
`ags --conf ./my.cfg --user-data-dir ./saves --shared-data-dir ./appdata`
NOTES:
`--conf` forces engine to ignore all other config files.
`--user-data-dir` and `--shared-data-dir` override corresponding options from config file.
---
The biggest issue I have with `--conf` is that so far it does not have a clear rule in regards to *saving config back*. In other words, must it be considered a read-only special config, or actually "user config" with all the rules applying?
A while ago I've disabled saving …
=> Engine: implemented command line options for config and user dir paths

Compiler/script2/cs_parser.cpp, Compiler/script2/cs_parser.h, Compiler/test2/cc_bytecode_test_1.cpp, Compiler/test2/cc_parser_test_1.cpp, Engine/ac/dynobj/cc_dynamicarray.cpp, Engine/script/exports.cpp
This PR adresses #637.
It adds the `Length` attribute for dynamic arrays which will return the length of any dynamic array at runtime. 
Specifically, if `DA` is a dynamic array, then:
- `DA.Length` will return the the total number of all the fields.
- ~~`DA.Length[0]` will return the number of dimensions, which is always `1` because currently our dynamic arrays only have 1 dimension~~
- ~~`DA.Length[i]` for a positive value of `i`  will return the size of the `i`th dimension (where the first dimension is number 1, not number 0).~~ ~~So currently, `DA.Length[1]` will yield the same as `Da.Length`.~~   ~~If there isn't such a dimension, in particular for a negative `i`, you'll get a runtime out-of-bounds error.~~
~~Currently, our dynamic arrays don't support multiple dimensions, but this …
=> New compiler: `.Length` pseudo-attribute for dynamic arrays

Common/util/directory.cpp, Editor/AGS.Editor/Resources/agsdefns.sh, Engine/ac/file.cpp, Engine/ac/global_game.cpp, Engine/ac/system.cpp, Engine/main/config.cpp, Engine/main/quit.cpp
This complements recent changes to config location setting, which let switch user config location to game directory itself, as well as previous change that disabled engine writing config on exit.
Added `System.SaveConfigToFile()` script function that explicitly saves current runtime settings to user config.
This change may suit game developers who simply want to save those options that may be changed at runtime.
Additionally added $CONFIGFILE$ token supported by File.Open that allows to read/write user config regardless of where it is located not relying on assumptions of engine behavior. This is provided for game developers who want to script more accurate user config reading or writing.
=> 3.5.1: Added System.SaveConfigToFile() and support $CONFIGFILE$ scriptpath

Engine/script/cc_instance.cpp, Engine/script/systemimports.cpp, Engine/script/systemimports.h
To help me debug some issues in ScummVM, I made improvements to the DumpInstruction functions.
I am not sure all the changes are a good idea, so I made them incrementally in three separate commits (so that for example you may decide to merge only the first commit).
Feedback and suggestions, if you think I made some mistakes or something could be improved, are welcome.
=> Improve argument print in DumpInstruction

Engine/debug/filebasedagsdebugger.cpp
The PR #1111  was merged on Master but not on `ags3--sdl2` branch or not on all files - not sure.
I did a cherry-pick of it and the line in this PR is the missing change for `ags3--sdl2` branch. Below are the other lines, which are already in.
https://github.com/adventuregamestudio/ags/blob/ags3--sdl2/Common/font/fonts.cpp#L15
https://github.com/adventuregamestudio/ags/blob/ags3--sdl2/Common/game/main_game_file.cpp#L15
https://github.com/adventuregamestudio/ags/blob/ags3--sdl2/Engine/ac/global_debug.h#L21
https://github.com/adventuregamestudio/ags/blob/ags3--sdl2/Engine/ac/global_display.cpp#L15
https://github.com/adventuregamestudio/ags/blob/ags3--sdl2/Engine/ac/gui.cpp#L14
https://github.com/adventuregamestudio/ags/blob/ags3--sdl2/Engine/ac/parser.cpp#L16 …
=> Engine: Add required '#include <cstdio>' for gcc 10 (ags3--sdl2)

Engine/plugin/global_plugin.cpp
this is the agssteam plugin that is shipped with Gemini Rue.
This may be useful when trying to run other games that used this older ags plugin.
=> adds stubs for older agssteam engine plugin

Common/CMakeLists.txt, Common/game/room_file.cpp, Common/game/room_file.h, Common/game/room_file_base.cpp, Solutions/Common.Lib/Common.Lib.vcxproj, Solutions/Common.Lib/Common.Lib.vcxproj.filters, Solutions/Tools.App/crm2ash.vcxproj, Solutions/Tools.App/crm2ash.vcxproj.filters, Solutions/Tools.sln, Tools/crm2ash/Makefile, Tools/crm2ash/main.cpp, Tools/data/room_utils.cpp, Tools/data/room_utils.h
Resolves #1147.
This is a proof-of-concept variant of the tool which parses compiled room files (CRM) and generates script header for them.
As it seemed to be the simpliest to make, I decided to try this tool first.
**crm2ash** stands for - CRM to ASH...
*Input:* compiled ags room (*.crm)
*Output:* generated script header with room declarations.
Usage: `crm2ash room.crm room.ash`
It links several utility cpps from the engine's Common folder. ~I hoped to reuse room file reading code too, but it has unnecessary dependencies and may need splitting before it's possible to do without bringing more stuff. So for now just copied necessary bits.~
Builds on Windows and Linux. For MSVS I added a new "Tools" solution. For Linux there's a Makefile. I am not a big expert in writing these, so copied …
=> Tools: crm2ash - generates room script header

Common/util/memorystream.cpp, Common/util/memorystream.h, Common/util/stream.h, Common/util/string.cpp, Common/util/string.h, Solutions/Common.Lib/Common.Lib.vcxproj, Solutions/Common.Lib/Common.Lib.vcxproj.filters, Solutions/Tools.App/afg2dlgasc.vcxproj, Solutions/Tools.App/afg2dlgasc.vcxproj.filters, Solutions/Tools.App/crm2ash.vcxproj, Solutions/Tools.sln, Tools/agf2dlgasc/Makefile, Tools/agf2dlgasc/main.cpp, Tools/data/agfreader.cpp, Tools/data/agfreader.h, Tools/data/dialogscriptconv.cpp, Tools/data/dialogscriptconv.h, Tools/data/game_utils.h, Tools/data/script_utils.cpp, Tools/data/script_utils.h, Tools/data/scriptgen.cpp
Related to #1008, but does not resolve it (apparently I forgot to create a separate ticket about dialog conversion tool).
agf2dlgasc - stands for "AGF to Dialog ASC" - parses Game.agf (xml) and generates a merged dialog script converting dialog scripts found in the game into standard ags script format.
*Input:* game project (*.agf).
*Output:* generated script body.
Usage: `agf2glvar Game.agf __DialogScripts.asc`
---
For the better context, Dialog Scripts are separate entities in AGS currently, written in their own dialect. Prior to AGS 2.72 they were also processed separately. Today they are converted into regular script and then compiled along with the rest of game scripts.
Here's an article on dialogs: https://github.com/adventuregamestudio/ags-manual/wiki/Settingupthegame#conversations …
=> Tool: agf2dlgasc - generate ags scripts out of Game.agf's dialog scripts

Common/core/assetmanager.cpp
I noticed the priority parameter was never passed. 
`kAssetPriorityLib` is apparently only used when loading a template to fetch an icon and made no difference for me - kept working as it was before.
=> assetmanager SetSearchPriority never set priority fix

Common/font/fonts.cpp
was not really setting outline type but only usage of this function is in the LucasFan-Font fix and it uses the value FONT_OUTLINE_AUTO as parameter so this commit doesn't actually change anything other than correctnes.
=> misleading set outline in fonts.cpp

Engine/gfx/ali3dogl.cpp
OpenGL ES 2.0 doesn't have neither `glColor4f` or [`glTexEnvi`](https://www.khronos.org/registry/OpenGL-Refpages/es1.1/xhtml/glTexEnv.xml) used in the code. 
This PR simply guards these with ifdef until a proper code can be figured out, so that the Android port can be built and the CI doesn't fail at packaging the editor. Note that if using the normal blend mode, things will work alright.
I think overall the blend modes could be reimplemented with shaders but this is not trivial since the color to blend need to be in a texture (see https://stackoverflow.com/a/17666532 and https://www.shadertoy.com/view/XdS3RW). Curiously the [gl blend ](https://docs.gl/es2/glBlendFunc)functions ARE available in Open GL ES 2.0, it's just the mentioned functions above that aren't.
=> workaround invalid OpenGL ES2 functions, need a proper fix

Editor/AGS.Editor/Resources/agsdefns.sh
Adds Ctrl and Shift keys as below in the standard script header:
```
eKeyShiftLeft = 403, 
eKeyShiftRight = 404, 
eKeyCtrlLeft = 405, 
eKeyCtrlRight = 406,
```
---
[keyTest.zip](https://github.com/adventuregamestudio/ags/files/6525167/keyTest.zip) | [keyTest_ags_proj.zip](https://github.com/adventuregamestudio/ags/files/6525169/keyTest_ags_proj.zip)
Above is a game that can be used to test and verify the key presses in AGS and it's project file (I used my own GUI toolkit because I wanted scrollbars).
I used it to verify that the key numbers were correct. Also I chose to go left to right with the less specific to the most specific - so `eKeyCtrlLeft` instead of ~~`eKeyLeftCtrl`~~ because it would feel weird.
Warning: the above game is using 3.5.0.30, so it still has allegro key handling. …
=> adds ctrl and shift keys on agsdefns.sh

Engine/platform/windows/gfx/ali3dd3d.cpp
Probable fix of #1287 
My hypothesis: We are calling Reset on the direct3D device passing the d3dpp structure, and we are setting the Windowed property in it to false, but we are creating our window using `SDL_WINDOW_FULLSCREEN_DESKTOP`, which creates a "fake" fullscreen with a bordless window, so as far as Direct3D is aware, we have a Window, even in FullScreen.
https://docs.microsoft.com/en-us/windows/win32/api/d3d9/nf-d3d9-idirect3ddevice9-reset
=> fixes hang when alt+tab fullscreen direct3d game

Engine/ac/game.cpp, Engine/ac/timer.cpp
The problem is briefly mentioned here: https://github.com/adventuregamestudio/ags/issues/1287#issuecomment-846428137
Previously the engine was using allegro timers that were suspended by default when the player switched away from the game. That stopped game from updating and redrawing itself.
The commits f2ab428a596c67d950f2aed5fbd335f6ccc72e3f and 15489ff2c97762f7c40a8374d5b50241830bcd74 broke that behavior. Here we reintroduce it, now implementing the timer lock mechanic directly in the engine. This is a bit naive implementation but somewhat in line with the older code (e.g. see https://github.com/adventuregamestudio/ags/blob/release-3.5.0/Engine/ac/timer.cpp#L40).
=> 3.5.1: reintroduced a suspend mode in WaitForNextFrame()

Editor/AGS.Types/RuntimeSetup.cs, Engine/main/main.cpp
we have removed the hqx filter but it's still mentioned, this PR removes it from a possible filter when Software driver is selected.
=> removes hqx mention since it's no longer supported

Common/core/assetmanager.cpp, Common/core/assetmanager.h, Common/gfx/allegrobitmap.cpp, Common/gfx/allegrobitmap.h, Common/gfx/bitmap.cpp, Common/gfx/bitmap.h, Common/util/bufferedstream.cpp, Common/util/bufferedstream.h, Common/util/file.cpp, Common/util/file.h, Common/util/string_utils.cpp, Common/util/string_utils.h, Engine/ac/file.cpp, Engine/ac/global_dynamicsprite.cpp, Engine/ac/global_file.cpp, Engine/ac/listbox.cpp, Engine/ac/path_helper.h
For #1227 (does only engine part of the job).
This supports reading resource files ("assets") in script. Resources are retrieved using engine's own AssetManager, thus the script has access to everything that engine has. This method allows to open files only in read mode.
The opened file stream is modified to restrict reading and seeking to the range of offsets: this ensures that the script won't read past the end of resource even if it's retrieved from the larger file (package).
To specify game resource a new path token is introduced: "$DATA$".
Following script functions support this token:
**File.Open** - opens resource file for reading (if script asks to open for writing it will throw an error and return null pointer, as usual).
Example: `File* f = File.Open("$DATA$/myfile.dat");` …
=> AGS 4: Support reading from game assets in script

.cirrus.yml, Solutions/Tests.sln
Added Googletests from #1302 to the CI 
Here's an example of CI test failing: https://cirrus-ci.com/task/5586516735950848 (https://github.com/ericoporto/ags/commit/7b2c8ff0edcc9f8f89393334028f4625d71326c5)
=> Runs Engine Googletest in CI

Engine/platform/windows/setup/winsetup.cpp
- SetClassLongPtr is compatible with 32 and 64 bit
- LoadIcon has been superseded by LoadImage function
=> Winsetup icon to better supported functions

.cirrus.yml
In case we need a new release in this branch, avoiding piping zip files to bsdtar will fix the errors that happen from time to time of missing files in zip files.
=> CI: avoid piping zip to bsdtar (release-3.5.1 branch)

Common/game/tra_file.cpp, Common/game/tra_file.h, Common/util/string_utils.cpp, Common/util/string_utils.h, Solutions/Tools.App/trac.vcxproj, Solutions/Tools.App/trac.vcxproj.filters, Solutions/Tools.sln, Tools/data/tra_utils.cpp, Tools/data/tra_utils.h, Tools/trac/Makefile, Tools/trac/main.cpp
Resolves #1299
This tool compiles TRS (translation source file) into TRA (runtime translation file).
**trac** - stands for "TRAnslation Compiler".
*Input:* translation source (`*.trs`) and game identification parameters (name, uniqueid).
*Output:* runtime translation (`*.tra`).
Usage: `trac name.trs name.tra --gamename MyGame --uniqueid 12345`
---
There's a noteable issue that the TRA needs game title and uniqueid field to be set: engine uses these to match translation with the game. Normally editor would get these from the game data, but here I thought that it may be overkill to parse Game.agf for two values. Also, I thought hypothetically that we may add an option to force translation without game check.
These two arguments may be omited, in which case they will be saved as an empty …
=> Tools: trac - compiles game translation (TRS -> TRA)

Tools/data/dialogscriptconv.cpp
Hey, I tried to use `agf2dlgasc.exe`, but had an issue with `option-on` and `option-off` not being recognized. Additionally, I adjusted one statement that missed a C string conversion - judging from other calls in the same file.
Also I didn't fix here, but I noticed the option `DialogScriptSayFunction` from the `Game.agf` file is not considered - that one that allows using `Character.MySay()` instead of `Character.Say()`.
=> fixes for agf2dlgasc.exe

.cirrus.yml, Solutions/Compiler2.Lib/Compiler2.Lib.Test.vcxproj
fix #1217 
- builds and tests new compiler in CI in ags4 branch
- fix small typo in the test vcxproj for the new compiler
**NOTE: there's a test current failing in `cc_parser_test_1.cpp`, under `TEST_F(Compile1, FloatInt2)`**
I could allow failure tolerance if desired (https://cirrus-ci.org/guide/writing-tasks/#failure-toleration) but it would still break flow on the specific task.
=> CI: add compiler2 tests in ags4 branch

Compiler/script2/cs_parser.cpp, Solutions/Compiler2.Lib/Compiler2.Lib.Test.vcxproj
This addresses a bug that surfaced in #1314. 
The compiler test library throws an SEH exception for the googletest "Compile1/FloatInt2"; but only when compiled in "Release" build, not when compiled in "Debug" build.
Root cause is that the function `Error()`, a `printf()` lookalike, is called in one place with a `std::string` parameter instead of a `C` string parameter. 
Also, the solution `Compiler2.Lib.Test` has an additional dependency on `Compiler.Lib` for the `Release` build. That should read `Compiler2.Lib`.
=> New compiler: Fix bug: Error() called with bad parameter. Also fix dependency in Compiler2.Lib.Test

Compiler/script2/cs_parser.cpp, Compiler/script2/cs_parser.h, Compiler/test2/cc_bytecode_test_1.cpp
This fix addresses #1312.
When a `string` literal is assigned to a `String`, a `string`-to-`String` conversion should be emitted before the assignment is emitted. Wasn't when compiling the following AGS code:
```
struct Stru {
String Txt;
};
void game_start()
{
Stru a;
a.Txt = "Cause bug!";
}
```
Root cause: Parameters for `ConvertAXStringToStringObject()` were named differently in `parser.h` and `parser.cpp`; because of this confusion, this function was called incorrectly in one place.
This PR fixes the bug and adds a googletest.
=> New Compiler: Fix bug when assigning a string literal to a String

Compiler/script2/cs_parser.cpp, Compiler/test2/cc_parser_test_1.cpp
The new compiler let through:
```import static int Foo(this Bar *);```
Judging from the `static` keyword, the function `Foo()` must be static, but in this case it doesn't have any `this` pointer, which collides with `this Bar *` part. So this declaration is nonsensical.  This PR makes the compiler balk if whenever encounters that kind of code.
(The correct way of declaring a static extender function would be `import int Foo(static Bar);`).
=> New compiler: Bug fix: Disallow "this" parameter for static extender function

Common/core/platform.h, Engine/util/library.h, libsrc/allegro/include/allegro/internal/alconfig.h
these are platform specific checks that are used in the Emscripten port, I am adding them here in case they are easier to understand than FreeBSD ones to avoid future conflicts.
=> Platform additions emscripten

Compiler/script2/cs_compiler.cpp, Compiler/script2/cs_compiler.h, Compiler/script2/cs_message_handler.cpp, Compiler/script2/cs_message_handler.h, Compiler/script2/cs_parser_common.h, Editor/AGS.Editor/AGSEditor.cs, Editor/AGS.Editor/Components/RoomsComponent.cs, Editor/AGS.Editor/NativeProxy.cs, Editor/AGS.Native/NativeMethods.h, Editor/AGS.Native/ScriptCompiler.cpp, Solutions/Compiler2.Lib/Compiler2.Lib.vcxproj, Solutions/Compiler2.Lib/Compiler2.Lib.vcxproj.filters
Please test before integrating
I tried hard to keep all the other behaviour as before, but you never know.
-----
The new compiler has generated warnings under certain circumstances that were invisible because they didn't reach the Editor. Typical example: A header file has:
```
import function Foo(float f = 0);
```
The old compiler treats '0' as a special case and lets this through. The new compiler does likewise but warns that this default value is an integer and so putting `0.0` would be preferable.
This PR makes those compiler warnings show up in the Editor. Warnings don't terminate the compilation run (but errors do, of course.)
As a side effect, this PR improves compilation times a bit.
-----
Specific changes:
New compiler:
- `ccCompileText2()`, add parameter for messages
- Move …
=> New compiler: Receive and show compiler warnings in Editor

CMake/FetchSDL_Sound.cmake, ci/linux/Dockerfile, ci/windows/Dockerfile
- SDL_sound is not on icculus mercurial website
icculus switched SDL_sound off from mercurial and is now pushing to his GitHub, so we can't fetch from the old place anymore. Link to new home:
https://github.com/icculus/SDL_sound
PR changes Docker/CMake to fetch from the new place. 
Since previous commit number was now invalid with the system change (hg->git), I took the opportunity to update to the newer version, but there's no significant change/improvements to the formats we use more often.
=> SDL_sound has moved to github (fix CI failing)

CMake/FetchGoogleTest.cmake, CMakeLists.txt, Common/CMakeLists.txt, Compiler/CMakeLists.txt, Compiler/fmem.cpp, Compiler/script/cc_symboltable.h, Compiler/script/cc_treemap.cpp, Engine/CMakeLists.txt
I am adding the option to build existing tests with CMake and run them with CTest.
I am adding tests because I will need them to test my preprocessor in the other PR. :)
I followed google docs on here: https://google.github.io/googletest/quickstart-cmake.html
Tests are off by default, I didn't want to deal with CI just yet. 
Edit: btw we could update the submodule to the current commit (https://github.com/google/googletest/commit/4ec4cd23f486bf70efcc5d2caa40f24368f752e3), I just don't know how exactly to PR this (the submodule change). It needs a small fix to vcxproj files because now googletest has been moved to a directory named googletest. I am skipping the submodule by simply fetching if the test option is on in CMake.
=> adds existing Engine, Common and Compiler tests to CMake

Common/game/main_game_file.cpp, Common/game/main_game_file.h, Engine/ac/room.cpp, Engine/game/game_init.cpp, Engine/game/game_init.h, Engine/main/game_file.cpp
**Summary**
Support loading scripts as separate asset files. Allow to *not* have scripts inside game28.dta and room.crm.
This does not change any data formats, only reinterprets one existing flag in the main game data (as explained below).
The purpose of this is to simplify the data layout in the game package, and the packaging process itself, as this will require at least 1 step less for game and room compilation (compiled script injection into the respective data blob).
**Details**
This allows engine to support game distribs where scripts are not embedded into the game28.dta and roomN.crm blobs, but are present as separate asset files inside the game package.
First of all, the engine will now treat `game.load_compiled_script` flag as an indication whether the scripts are found inside …
=> Engine: support scripts as separate assets

Engine/script/cc_instance.cpp
in games with lots of scripts, this help to narrow down the exact
origin.
=> import error: print original filename if possible

Common/util/misc.cpp
this achieves 2 major improvements:
- if the directory and filename are correct, only a single stat
syscall needs to be done to check whether the file exists.
no need to open the directory (1 syscall) and check whether
each one of the entries matches the filename (1 syscall each).
for perspective, each syscall requires to enter the kernel,
a full contex switch, and therefore at least 1000 cpu cycles.
- if the filename contains a directory separator to dive into
a subdir, the existing method fails.
this allows to use e.g. PlayMP3File("sounds/sound25.ogg")
successfully.
=> ci_find_file/unix: add fast-path for file lookup

Engine/script/cc_instance.cpp
rather than bailing out after the first.
this helps to evaluate missing script functions much quicker, than
with current approach. it's helpful when e.g. trying to implement
stubs for a proprietary binary plugin.
=> import error: print all missing imports for current script module

Common/util/misc.cpp
if lstat() doesn't return success, it's undefined behaviour to access
the uninitialized memory of the stat buffer.
fast path was improved to kick in in almost 100% of cases, namely:
when directory is null and filename starts with a slash (absolute path)
use the absolute path for lookup, when directory is null and filename
doesn't start with a slash (relative path), use current directory.
=> ci_find_file: fix omission to check lstat return value, improve fastpath

Common/core/platform.h, Engine/gfx/ali3dogl.cpp, Engine/gfx/ali3dogl.h
- modify OGL Renderer to fail when shader creation fails so Software renderer is used instead.
- modify shader version to be compatible (https://en.wikipedia.org/wiki/OpenGL_Shading_Language)
- MacOS has at least 2.1 (version 120), but not OpenGL ES2 (version 100)
exactly the same as #1353
=> Allow using OpenGL on MacOS (fail and use Software if it can't)

CMake/FetchSDL2.cmake, Common/CMakeLists.txt, Compiler/script/cs_parser.cpp
Just some small corrections I picked building with CMake on Windows
- link shlwapi when building Common alone 
- hasNegateLiteral is being used without being initialized error pops up when trying to build Compiler Tests with CMake on Windows
Additionally, better always get SDL2 from GitHub on CMake builds, because it has better uptime than the SDL website.
=> Small fixes for building with CMake+MSVC on Windows

.cirrus.yml, Windows/Installer/ags.iss
- Cirrus CI: place SDL2.dll in Installer/Source/Engine
- Editor Installer: add SDL2.dll
If we decide to static link SDL2 on Windows in the future, we can revert this commit. 
This makes both the Editor installer and the archive include the SDL2.dll. 
Edit: there's also the possibility to just squish the SDL2.dll to the exe when making the single exe game, at least I think that works in Windows.
=> Includes SDL2.dll on the editor package

Editor/AGS.Editor/Panes/SpriteSelector.Designer.cs, Editor/AGS.Editor/Panes/SpriteSelector.cs, Editor/AGS.Editor/Panes/SpriteSelector.resx
same as #1344 
- Allows changing preview sizes for 1x, 2x, 3x, and 4x on right click;
- Slider gives 0.5 steps from 0.5x to 4x;
- Ctrl+Mouse Wheel also modifies the slider;
- Default size is 1x;
- Ctrl+0 resets to default size;
- Added a button for importing new sprite files;
- Image File Drop on Sprite Manager is supported, just click hold the desired image files on Windows Explorer and drag them in the Sprite Manager for import.
Droping files from Windows Explorer should not hang anymore. I can rebase and squash commits if needed.
=> sprite browser ease of use improvements

Common/core/assetmanager.cpp, Common/core/assetmanager.h, Common/gfx/allegrobitmap.cpp, Common/gfx/allegrobitmap.h, Common/gfx/bitmap.cpp, Common/gfx/bitmap.h, Editor/AGS.Editor/AGSEditor.cs, Editor/AGS.Editor/BuildTargets/BuildTargetDataFile.cs, Editor/AGS.Editor/Components/SpeechComponent.cs, Editor/AGS.Editor/DataFileWriter.cs, Editor/AGS.Editor/Utils/Utilities.cs, Editor/AGS.Types/Settings.cs, Engine/ac/file.cpp, Engine/ac/global_dynamicsprite.cpp, Engine/ac/global_file.cpp, Engine/ac/listbox.cpp, Engine/ac/path_helper.h
Fully resolves #1227.
This PR does two things:
1. Adds support for reading resource files ("assets") in script. This is a backport of #1294 for ags3. I recommend reading 1294's description to understand how this works.
2. In the Editor adds new property to General Settings called "Package custom data folder". If this property is filled, Editor will gather all files from the corresponding subfolder (recursively, including all files in all nested subfolders), and package these files into the game along with all the standard files.
Regarding p2:
* Resources packaged like this are assigned names containing full relative path. For example: `Data/subdir/myfile.dat`. The topmost dir name is also kept - to easily avoid filename conflicts with the rest of the game files.
* To be precise, the path …
=> 3.6.0: Support reading from game assets in script + Editor supports packing custom files

CMakeLists.txt, Tools/CMakeLists.txt, Tools/crm2ash/main.cpp, Tools/data/scriptgen.cpp, libsrc/tinyxml2/CMakeLists.txt
This add a new toggle to build Tools in CMake - which when on also builds Compiler related stuff.
The toggle is OFF by default, and I am not turning the CI on this yet (we don't have a plan for actually shipping the Tools yet, so no need to turn on now). 
Btw, some Makefiles for tools are broken, `multifilelib.cpp` actually has a typo and is `mutifilelib.cpp` (missing first `l` character), I wasn't sure if I should fix with `git mv` the file name or change the Makefiles to carry the typo.
=> CMake: allow building Tools from CMake

.cirrus.yml
switched the Android task to allow using less CPU, but I am turning greedy on, which means it can use more CPUs if available - but it requires RAM available too, so switching RAM requirement up.
Greedy tasks are explained here:
https://medium.com/cirruslabs/introducing-greedy-container-instances-29aad06dc2b4
This should make the task run and when there are resources on the GKE, running faster. This should unstuck the task - didn't get answers from support yet, but my guess is it's not finding any runner for 6CPU task on GKE.
Note: this task is demmanding because we build ags for 4 architectures, and we do it twice, once for Debug and once for Release. Our other tasks usually do only 1 arch and only 1 build type.
(push forced to fix the commit message.)
This PR asked 4 CPUs but got 13 …
=> CI: adjust to allow running with less resources

Common/util/string_utils.cpp
Fix deletion of a char array (it should use `delete []` instead of `delete`).
=> Common: fix incorrect use of delete

Compiler/script2/cs_scanner.cpp, Compiler/script2/cs_scanner.h, Compiler/test2/cc_scanner_test.cpp
Make the compiler join string _literals_ (!) that are separated by whitespace, if any. This is an operation that happens at compile time, not at runtime.
The same way it is done in `C` or `C++`.
Typical code:
```
player.Say(
"The rain it raineth on the just ""And also on the unjust fella; "
"But chiefly on the just because "     "The unjust hath the just's umbrella.");
```
Generates the same code as
```
player.Say(
"The rain it raineth on the just And also on the unjust fella; But chiefly on the just because The unjust hath the just's umbrella.");
```
=> New compiler: Join juxtaposed string literals

Editor/AGS.Editor/Resources/agsdefns.sh, Engine/ac/audioclip.cpp
This adds AudioClip.PlayOnChannel() function:
`AudioChannel* AudioClip.PlayOnChannel(int chan, AudioPriority=SCR_NO_VALUE, RepeatStyle=SCR_NO_VALUE);`
The purpose of this function is to provide a lower-level control over how the clips are put onto the logical "channel" slots. Normally this distribution is controlled by a number of settings involving audio type reservation and clip priority, but there are circumstances when users want to have their own logic, yet there's no direct way to apply that. With this function it might be possible to script your own audio mixer freely.
The necessary changes for this are minimal, as this script function simply calls an existing internal one that does the necessary thing, circumventing channel calculation.
Notable issues: channel 0 is reserved for …
=> Script API: AudioClip.PlayOnChannel()

Common/game/room_file.h, Common/game/room_file_base.cpp, Common/util/data_ext.h, Solutions/Tools.App/crmpak.vcxproj, Solutions/Tools.App/crmpak.vcxproj.filters, Solutions/Tools.sln, Tools/crmpak/Makefile, Tools/crmpak/main.cpp
After #1330 we may store compiled scripts separate from the room files (*.crm), but then I realized that there will still be rooms with these scripts inside remaining in the ags3 game project. If we, for instance, begin to package scripts separately in the future, there will be redundant script data left inside these rooms.
So here comes the tool that deals with that, but I decided to make it more universal just in case.
(The blocks are searched all the same, so there's no difference)
---
crmpak - imports, exports or deletes chosen blocks from the compiled room file (*.crm).
Usage: `crmpak [OPTIONS] [<in-room.crm> <COMMAND> [<CMD_OPTIONS>]]`
Options:
* `  --tell-blockids` - print a list of the known block ids;
* 
Commands:
* `-d <blockid>` -  delete: remove a block from the compiled room; …
=> Tool: crmpak - compiled room's (re)packer

Compiler/compiler.cpp, Compiler/compiler.h, Compiler/main.cpp
fix the failing builds on the CI, I forgot I let the compiler front end building in it.
=> Compiler: remove deprecated lefttoright flag

Common/util/directory.cpp, Common/util/file.cpp, Common/util/filestream.cpp, Common/util/path.cpp, Common/util/path.h, Common/util/path_ex.cpp, Common/util/stdio_compat.c, Common/util/stdio_compat.h, Engine/ac/global_dynamicsprite.cpp, Engine/ac/runtime_defines.h, Engine/main/engine.cpp, Engine/main/main.cpp, Engine/main/main.h, Engine/platform/base/agsplatformdriver.cpp, Engine/platform/base/agsplatformdriver.h, Engine/platform/windows/acplwin.cpp, Engine/platform/windows/debug/namedpipesagsdebugger.cpp, Engine/platform/windows/debug/namedpipesagsdebugger.h, Engine/platform/windows/setup/winsetup.cpp
After #1321 unix ports should support utf-8 paths naturally, but on Windows standard library functions (as well as WinAPI) accepting `const char*` paths do not handle utf-8, which means we have to use wide-string api for unicode paths.
This pr changes all the file related functions to convert our strings to wide-char paths and use corresponding wide-string api on Windows.
Supposedly, after this change -
* DOS paths (aka "short paths") are no longer used anywhere in the engine;
* Windows engine should correctly interpret unicode paths passed into command line (well, it probably did before, but just to be sure...);
* Hopefully utf-8 paths in config file and winsetup will also work.
=> Windows: support UTF-8 paths in the engine

.cirrus.yml
this PR idea is to package the dependencies necessary for building AGS when using the VS Solutions.
They are already built and available in the AGS Docker used in the CI, so it simply packages it as the zip file below:
[WinDevDependenciesVS.zip](https://github.com/adventuregamestudio/ags/files/6988717/WinDevDependenciesVS.zip)
The idea is that once an AGS release is made, it would upload this package to GH too, and if someone wants to give it a shot with the VS Solutions, they could download this package to get the necessary dependencies. 
After at least one release that includes it, it would be possible to make a script to download and set the necessary environment variables to ease setting up the development environment on Windows - which currently requires the steps mentioned here: …
=> CI: package Windows Dev Dependencies for VS Solutions

Editor/AGS.Types/Font.cs
If you open and upgrade an older project (before 3.6.X) with the current master, it will not set the internal value for thickness of the font (`_autoOutlineThickness`), and then when you try to open the project after saving you will meet this error:
```
An error occurred whilst trying to load your game. The error was:
Exception has been thrown by the target of an invocation
...
---> System.ArgumentException: AutoOutlineThickness must be 1 or greater.
at AGS.Types.Font.set_AutoOutlineThickness(Int32 value) in ags\Editor\AGS.Types\Font.cs:line 132
...
```
<details>
In Game.agf, after upgrade the `AutoOutlineThickness` is 0 as below:
```
<Font>
<AutoOutlineStyle>Squared</AutoOutlineStyle>
<AutoOutlineThickness>0</AutoOutlineThickness>
<ID>0</ID>
<LineSpacing>0</LineSpacing> …
```
=> Editor: fix outline upgrade was set to 0

Compiler/script2/cs_parser.cpp, Compiler/test2/cc_bytecode_test_1.cpp, Compiler/test2/cc_parser_test_1.cpp
This PR addresses #1399.
Assignments to an attribute must be type-checked, but weren't. Typical code:
```
function room_FirstLoad()
{
player.GraphicRotation = 10;
}
```
Should yield an error because the attribute `player.GraphicRotation` is type `float`. Didn't. Does now.
This fix has uncovered and fixes another bug, too: It ensures that `string` values are converted to `String` before they are assigned to an attribute of type `String`.
=> New compiler: Fix bug: Type-check assignments to an attribute

Compiler/script2/cs_scanner.cpp, Compiler/test2/cc_scanner_test.cpp
This PR addresses #1406.
Convert double-backslash within string and character literals to a single backslash, in 'C' style.
Typical code: 
```
String test = "test\\test";
```
=> New Compiler (Scanner): Grok  '\\'

Engine/ac/room.cpp, Engine/script/cc_instance.cpp, Engine/script/cc_instance.h, Engine/script/script.cpp
Rationale:
- It makes life easier for coders, they have less reason to juggle the module sequence. 
- This is a **prerequisite** for implementing any sort of a function pointer or callback mechanism. For callbacks, it's kind of the point that we can call a function without knowing anything about it, in particular without having to guarantee that it has been defined in an earlier module. 
AFAICS existing programs don't need to be changed in any way for this PR; they should continue to work without recompiling.
AFAICS neither the new nor the existing compilers need to be changed for this PR.
The effect is achieved by changing the sequence of the linking steps.
- First, create the instances for the scripts.
- Then, resolve references to imports and the 'IMPORT' fixups.
- Then, create the …
=> Engine: Link in such a way that functions can call all imported (!) functions, no matter the module sequence

Compiler/script2/cs_parser.cpp, Compiler/script2/cs_parser.h, Compiler/test2/cc_parser_test_0.cpp, Compiler/test2/cc_parser_test_1.cpp
Less confusing type descriptions:
– e-g-. "Can't convert **an array** to 'int'", instead of printing a complex type expression.
Better pinpointing:
– In expressions, name the specific operator that has the error and (if applicable) whether the error is the left-hand side or right-hand side 
– In function calls, name the specific function and the number of the parameter that has the error
This should make it easier to find the error location if the AGS code has a complicated expression.
Typical examples:
```
int y[];  
++y;
```
> ` Argument of '++': Can't convert an array to 'int' `
```
import function DoIt(float a, float b);
… DoIt(4, 4.0); …
```
> `Parameter #1 of call to function 'DoIt': Can't convert 'int' to 'float' `
```
int x, y;
float fl[];
int res = (x + y) * (x - fl);  
```
> …
=> New compiler: Better error messages for type mismatches

.cirrus.yml, Editor/AGS.Native/NativeDLL.vcxproj, ci/android/Dockerfile, ci/linux/Dockerfile, ci/windows/Dockerfile
Windows related changes:
- Editor: Native use default Zp alignment (it fails to build the editor in release otherwise)
- CirrusCI: add path to Win SDK or it fails to find `rc.exe` (required to build the Editor)
- Windows Docker: DirectXSDk from MS is not available, use directx sdk from archive.org
- Windows Docker: VS2015 from MS is not availabe, use base image with preinstalled VS2015
If these changes are a problem, we can use the backup Windows Docker image from [here](https://hub.docker.com/repository/docker/ericoporto/ags35x_allegro4) instead.
Additional changes:
- Linux Docker: use XIPH from GitHub for older tls support (Debian Jessie has no newer tls)
- Linux Docker: autoconf necessary for theora build from GitHub sources
- Android Docker: apache ant old version is not available, …
=> Ci release 3.5.1 fixes

Engine/ac/characterinfo_engine.cpp
`update_character_walking()` was applying a new loop without making sure the current frame was still valid, this could trigger an error with scripting because the combination of view-loop-frame could be invalid at that moment.
Closes #802
With this fix I check if the current frame is available, if not it's reset to 0. This way the safe value is correctly available to the scripting system.
An alternative would be resetting if the number of frames is different from old loop to new loop.
=> Engine: Fix potentially invalid frame during Character turning

Engine/ac/draw.cpp, Engine/ac/draw.h, Engine/ac/global_debug.cpp, Engine/ac/walkablearea.cpp
Resolves #724.
1. "Show walkable areas" debug command (`Debug(2, 0)`) is reimplemented from displaying an opaque mask over a freezed game into persistent half-transparent overlay that does not pause the game.
2. `Debug(2, n)` now has a meaningful second parameter which defines a mask type, values are: 0 -none, 1 -hotspot, 2 -walk-behind, 3 -walkable, 4 -regions.
3. `Debug(2, n)` command now works as a on/off toggle, so calling it will same mask type consecutively will turn it on and off.  This also helps with backward compatibility, because old games that have this command in script would not have a way to turn masks off.
4. "Show character walking paths" debug command (`Debug(5, n)`) is similarily reimplemented as a half-transparent overlay, and working in a toggling manner.
**NOTE:** In …
=> Reimplement room mask display as a persistent overlay

Engine/media/audio/audio_core.cpp
Uses OpenAL spatial audio, which only applies to mono-channel clips.
But what I'd rather do, at least for AGS 3.6 given the backward compat, would be getting hang of the two channels of the stereo clip, and manually set the gain in order to reimplement the original behavior.
For this we  supposedly need to call `alGenSources()` with 2 sources, if I understand the documentation correctly.
=> Engine: fixed panning SDL implementation

Common/CMakeLists.txt, Common/util/aasset_stream.cpp, Common/util/aasset_stream.h, Common/util/android_file.cpp, Common/util/android_file.h, Common/util/directory.cpp, Common/util/file.cpp, Engine/platform/android/acpland.cpp
This adds more Android-specific implementations of the file system functions based on Android's AAssetManager; which is a kind of virtual filesystem from the engine's perspective.
This PR covers testing that file (aasset) exists, and searching for files (aassets) inside the pseudo-directory of an android package.
Android port will first search in the real filesystem as usual, then - using AAssetManager.
This hopefully fixes the problem of engine ignoring game data packed as individual AAssets in APK (translation files, etc).
* Better handling of our engine's AAssetManager reference: query it once, keep same ref, then dispose upon engine shutdown.
* AAsset variants of File::IsFile() and File::GetFileSize() functions.
* FindFile class's implementation that also searches through AAssets.
=> Android: expand file-related implementations based on AAssetManager

Compiler/script2/cs_parser.cpp, Compiler/script2/cs_parser.h, Compiler/test2/cc_bytecode_test_0.cpp
Typical code:
```
function game_start() 
{
MKB(0, 7);
MKB(1, 9);
MKB(2, 7);
}
function MKB(int a, int b)
{
return a + b;
}
```
Would only resolve the first call to `MKB()` correctly. The other calls went to the function at location 0.
I hadn't noticed that one because all my Googletests only had __one__ forward call in them.
=> New compiler: Fix bug: Of multiple forward calls to a local function, only the first was resolved correctly

Compiler/script2/cs_parser.cpp, Compiler/test2/cc_bytecode_test_0.cpp, Compiler/test2/cc_parser_test_1.cpp
Typical code:
```
{
int i = 0;
switch (i)
{
case 7:
return -5;
default:
return 555;
} 
}
```
Compiler would warn about the first `return` although there's nothing bad about it since a `default:` label follows. There were similarly bad warnings when a `case` label follows.
This PR suppresses those warnings.
=> New compiler, fix Bug: Mustn't complain about unreachable code at end of switch case

Compiler/script2/cs_parser.cpp, Compiler/script2/cs_parser.h
Fix typos in comments and string literals
Take out two functions that aren't actually called any longer.
Add forgotten `return` statements
Delete a comment in front of a function that should be in front of the declaration (and already is there)
No functional changes.
=> New compiler: Minor code cleanup

Compiler/script2/cc_compiledscript.h, Compiler/script2/cs_parser.cpp, Compiler/script2/cs_parser.h, Compiler/script2/cs_parser_common.h, Compiler/test2/cc_bytecode_test_0.cpp, Compiler/test2/cc_bytecode_test_1.cpp
This addresses #1444.
Turns out that in some circumstances, the compiler did a half-assed job of anticipating whether certain registers get clobbered and got it wrong, so it didn't surround the respective code blocks with `push`/`pop` pairs. I've reworked that part of the code. 
The compiler now generates slightly more efficient code for several Googletest programs, and the error in #1444 has gone away.
Code: 
```
function room_AfterFadeIn()
{
TwoClickHandler.ActionLabel.Visible = true;
}
```
Would set the action label __in__-visible instead of visible, which was wrong. Now leaves the label visible.
=> New compiler: Track when registers are set

Compiler/script2/cc_compiledscript.h, Compiler/script2/cs_parser.cpp, Compiler/script2/cs_parser.h, Compiler/script2/cs_parser_common.h, Compiler/test2/cc_bytecode_test_0.cpp, Compiler/test2/cc_bytecode_test_1.cpp, Compiler/test2/cc_parser_test_0.cpp
This PR adds attributes with extender syntax to the language. So it is possible to add, e.g., a `Weight` attribute to a `Character` even though the struct `Character` has been pre-defined.  This would result in the functions `Character::get_Weight()` and `Character::set_Weight()` to be declared, and the coder must then provide code for these functions, too, probably again using the extender syntax.
Extender attributes can be `readonly`, in this case the setter function isn't declared. 
Declare the attribute, in a header file:
```
attribute int Weight(this Character *);
```
Define the functions, in a code file:
```
#define WEIGHTPROP "Weight"
int get_Weight(this Character *)
{
return this.GetProperty(WEIGHTPROP);
}
void set_Weight(this Character *, int weight)
{ …
```
=> AGS4 / New compiler: Attributes with extender syntax

Common/font/ttffontrenderer.cpp, Common/font/ttffontrenderer.h, Editor/AGS.Editor/AGSEditor.csproj, Editor/AGS.Editor/GUI/ImportTTFDialog.Designer.cs, Editor/AGS.Editor/GUI/ImportTTFDialog.cs, Editor/AGS.Editor/GUI/ImportTTFDialog.resx, Editor/AGS.Editor/NativeProxy.cs, Editor/AGS.Editor/Panes/FontEditor.cs, Editor/AGS.Native/NativeMethods.cpp, Editor/AGS.Native/NativeMethods.h
For #1441.
As per @fernewelten 's suggestion, this gives user a choice when importing a TTF font in the project:
a) provide an explicit point size value;
b) provide a pixel height and ask to find the point size that results in the closest match to that height.
New dialog looks like this:
=> Editor: allow to import TTF by searching for a point size matching pixel height

.cirrus.yml, Editor/AGS.CScript.Compiler/AGS.CScript.Compiler.csproj, Editor/AGS.Controls/AGS.Controls.csproj, Editor/AGS.Editor/AGSEditor.csproj, Editor/AGS.Editor/packages.config, Editor/AGS.Native/NativeDLL.vcxproj, Editor/AGS.Types/AGS.Types.csproj, Windows/Installer/ags.iss, Windows/README.md, ci/windows/Dockerfile
Ref #1446 
We need this for compatibility with Visual Studio 2022 since anything before .NET 4.5.1 is no longer supported
Also need to upgrade the editor test code on the ags4 branch, but I can do that in a separate PR
=> Upgrade to .NET 4.6

Common/script/cc_error.h, Compiler/script2/cs_compile_time.cpp, Compiler/script2/cs_compile_time.h, Compiler/script2/cs_compiler.cpp, Compiler/script2/cs_message_handler.cpp, Compiler/script2/cs_message_handler.h, Compiler/script2/cs_parser.cpp, Compiler/script2/cs_parser.h, Compiler/script2/cs_scanner.cpp, Compiler/script2/cs_scanner.h, Compiler/test2/cc_parser_test_0.cpp, Compiler/test2/cc_scanner_test.cpp, Editor/AGS.Native/ScriptCompiler.cpp
This also addresses concerns that came up in https://github.com/adventuregamestudio/ags/pull/1449#issuecomment-972367384 .
- Add a comment to `Common/script/cc_error.h` for function `cc_error()` that explains that user errors should start with an `!` (which won't be displayed)
The new compiler had it the other way round and started each internal error message with a `!` but not the user messages.
Since I had to touch most all the messages anyway, I took this as an opportunity to convert the error handling from `C` style return code to `C++` style exception. This has cleaned up the code very significantly IMO. For instance, the file `cc_parser.cpp` lost an eighth of its lines. 
- Whenever the compiler detects an error, it calls 'Error()' with a message (that will be passed to `cc_error()` …
=> New compiler: Improve error handling

Common/core/assetmanager.h, Editor/AGS.Editor/Components/SpeechComponent.cs, Editor/AGS.Editor/DataFileWriter.cs, Editor/AGS.Editor/Resources/agsdefns.sh, Engine/ac/display.cpp, Engine/ac/game.cpp, Engine/ac/game.h, Engine/ac/gamestate.cpp, Engine/ac/gamestate.h, Engine/ac/global_audio.cpp, Engine/ac/global_audio.h, Engine/ac/global_debug.cpp, Engine/ac/speech.cpp, Engine/ac/speech.h, Engine/game/savegame.cpp, Engine/game/savegame_internal.h, Engine/main/engine.cpp, Engine/main/engine.h, Engine/script/script_api.h
Resolves #686 (except the part with expanded clip names, which I think may be moved to a separate ticket).
This adds a support for game having multiple voice-over packages, and being able to switch between them at runtime. The primary goal is to let game developers have the game translated with voice-overs in various languages.
Implementation details follow.
---
Engine supports loading a different speech vox at runtime.
By default engine loads a `speech.vox`, if one exists.
When ordered to change to an alternate vox of a name "[name]", engine will look for a vox called `sp_[name].vox`. If this vox is found then it will be loaded. If not, engine falls back to the default `speech.vox`.
The assets in alternate voxes must have names `[name]/filename.ext` where `[name]` is the same "tag name" …
=> Support multiple Speech VOXes for game translations

Common/ac/spritecache.cpp, Common/ac/spritecache.h, Common/ac/spritefile.cpp, Common/ac/spritefile.h, Common/util/compress.cpp, Common/util/compress.h, Editor/AGS.Native/NativeMethods.cpp, Editor/AGS.Native/agsnative.cpp, Editor/AGS.Types/Settings.cs
Resolves #983.
This permits sprite file to store 16 and 32-bit sprites as indexed images (8-bit) with palette *when possible*. This is a form of a lossless compression, and does not change anything in the game looks.
The idea is that the sprite writer will calculate the number of individual colors within the sprite, and if that number is lower than 257, it will create a palette of these colors and convert the sprite to a 8-bit image using palette. The result of this conversion is then saved into the spritefile.
**IMPORTANT:** this *does not affect* how the loaded sprites are stored in the program memory (whether in the Engine or Editor). Only how they are saved in the compiled spritefile.
On success may reduce eligible 32-bit sprites roughly 4 times (not precisely, as palette also takes …
=> Sprite file supports storing 16/32-bit sprites as indexed images with palette

Common/util/directory.cpp, Engine/ac/file.cpp, Engine/ac/game.cpp, Engine/ac/game.h, Engine/ac/path_helper.h, Engine/debug/debug.cpp, Engine/main/engine.cpp, Engine/platform/android/acpland.cpp, Engine/platform/base/agsplatformdriver.h, Engine/platform/ios/acplios.cpp, Engine/platform/linux/acpllnx.cpp, Engine/platform/osx/acplmac.cpp, Engine/platform/windows/acplwin.cpp
Fixes #1459.
Opened the PR mostly to ensure it builds for all platforms and to provide a test build from the build server.
I will be testing this myself too, as there's a number of scenarios to check.
The problem was that platform drivers in AGS were unconditionally creating directories for game saves etc files at the standard paths. This changes them to not precreate any dirs, but only return the paths, letting engine create directories only if necessary. Thus not only standard dirs will not be created if user (player) provided their own in config, but they are not be created unless engine actually writes something. This complements the previous changes to the 3.5.1 engine.
For technical details, the paths are stored as a pair of "base dir"/"full dir", where "base dir" is considered not …
=> 3.5.1 hotfix: don't precreate common engine/game directories

Compiler/script2/cs_parser.cpp, Compiler/script2/cs_parser.h
No functional changes.
– I've refactored the `Expect()` function and its calls. This function makes sure that the next code symbol is in a list of given symbols (or else it yields an error).
– Now that the compiler treats errors by throwing exceptions, we need to take special care that all memory that is allocated is deallocated afterwards – even when an exception is thrown. I've done this "the C++" way and replaced naked pointers `*` by `std::unique_ptr` wherever this could be a problem.
=> New compiler: Refactorings

Engine/main/engine.cpp
when running `audio_core_init()`, it may throw if **no audio device is available**. 
I discovered it today when I had my headphones disconnected from my computer and no speakers since I had just moved the desk. In this case, AGS from our master doesn't start. Verified in Windows 10.
Previous allegro based AGS show a windows message saying it couldn't initialize audio, and then proceed with the game. I thought a debug message is fine - if it isn't, I can add a **`platform->DisplayAlert()`**.
https://github.com/adventuregamestudio/ags/blob/master/Engine/media/audio/audio_core.cpp#L78-L82
This PR simply catches the thrown errors and disables the audio backend.
=> Engine: audio core init may throw

Engine/ac/character.cpp
AnimateCharacter "invalid loop number specified" didn't inform, either loop number, view or character.
Fix #1482
=> Engine: AnimateCharacter with better error message for invalid loop error

CMakeLists.txt, Common/util/aasset_stream.cpp, Common/util/android_file.cpp, Engine/CMakeLists.txt
Crash is caused by unintialized SDL.
fix #1471
=> Android: fix Preferences crashes when no android.cfg

Compiler/script2/cc_symboltable.cpp, Compiler/script2/cc_symboltable.h, Compiler/script2/cs_parser.cpp, Compiler/script2/cs_parser.h, Compiler/test2/cc_bytecode_test_1.cpp, Compiler/test2/cc_parser_test_0.cpp, Compiler/test2/cc_parser_test_1.cpp
No functional changes.
I'm still indulging in yak shaving to make it easier to implement delegates in the compiler.
1. When I started out, I considered attributes to be a special kind of variable - an attribute variable. It's not, it's a different category of type that needs different information in the symbol table and different code to process. In this way, it is similar to functions and the upcoming delegates that need special treatment, too. The implementation has already drifted this way; now I've streamlined it to make it easier to put delegates alongside.
2. Similarly for `const`: Apart from the type `const string`, the compiler uses `const` as a special category; it keeps track of (integer or float) literals using dedicated fields in the symbol table and it has dedicated …
=> New compiler: Further refactorings

Android/agsplayer/app/src/main/java/uk/co/adventuregamestudio/agsplayer/FileUtil.kt, Android/agsplayer/app/src/main/java/uk/co/adventuregamestudio/agsplayer/MainActivity.kt
Possible fix for #597 
Adds a "browse" button when selecting directory which will launch the default file picker to let the use select the directory. I have no idea what happens when there is no file picker, but I think most devices have one.
=> Android Player: let user select dir through file picker

Android/agsplayer/app/src/main/java/uk/co/adventuregamestudio/agsplayer/MainActivity.kt
fixes #77 
Will make Android Player recursively look for games when a directory is set
Based on the original fix from here: https://github.com/sonneveld/ags/commit/a4f3d4af65365c2764f7a3b70bbd415dea02f9f0
=> Android: recursively iterate for games on Android Player

Common/debug/debugmanager.cpp, Common/debug/out.h, Common/util/string_types.h, Common/util/string_utils.h, Engine/debug/debug.cpp, Engine/main/config.cpp, Engine/main/engine.cpp, Engine/main/main.cpp, Engine/platform/base/agsplatformdriver.h, Engine/platform/base/sys_main.cpp, OPTIONS.md
Also fixes #1359.
SDL2 log will be printed using our own log system.
Added new log group called `"sdl"` which may be configured same way as any other log groups.
SDL2 has default message priority "info" (`SDL_LOG_PRIORITY_INFO`).
Added separate config option for SDL's priority:
In config: `[log] sdl=<priority>`
In command line: `--sdl-log=<priority>`
Where "priority" may be: `verbose`, `debug`, `info`, `warn`, `error`, `critical`.
This separate option is necessary, because SDL has a different way of setting message level: it sets priority per group; while we set priority per group _per output_.
Examples of use:
* in command line
`--sdl-log=verbose --log-file=sdl:all`
`--sdl-log=info --log-stdout=all:info`
* or config
```
[log]
file=all:all
sdl=warn
```
=> 3.6.0: print SDL logs through our own log system

Common/ac/gamestructdefines.h, Common/font/wfnfontrenderer.cpp, Common/gui/guibutton.cpp, Common/gui/guidefines.h, Common/gui/guimain.cpp, Common/gui/guimain.h, Common/gui/guiobject.h, Editor/AGS.Editor/DataFileWriter.cs, Editor/AGS.Editor/Panes/GeneralSettingsPane.cs, Editor/AGS.Editor/Tasks.cs, Editor/AGS.Editor/Utils/NativeConstants.cs, Editor/AGS.Native/NativeMethods.cpp, Editor/AGS.Native/agsnative.cpp, Editor/AGS.Types/Settings.cs, Engine/ac/draw.cpp, Engine/ac/global_game.cpp, Engine/ac/global_gui.cpp, Engine/ac/gui.cpp, Engine/ac/gui.h, Engine/ac/guiinv.cpp, Engine/game/savegame.cpp, Engine/gui/gui_engine.cpp, Engine/main/engine.cpp, Engine/main/game_run.cpp
Historically AGS does not clip GUI controls, which may result in texts drawn outside of the control rectangle. While users may get used to this, it's not correct in my opinion. Also in some cases (like with the list boxes) it may be difficult to work around.
This PR introduces a game setting, which tells whether to clip control content or not. It's enabled by default in the new 3.6.0 projects, but disabled for projects upgraded from before 3.6.0.
My thinking is that control clipping their contents (text, images etc) should be a default. I may imagine a couple of use cases when one may want to have text drawn outside of the button, for instance, but it seems these may be resolved by combining a button and a label, or having a custom sprite on a button. But I am ready to hear more opinions …
=> 3.6.0: optionally clip GUI control contents

.cirrus.yml
This is very minor, it won't change performance or anything, on our CI, but currently according to Cirrus docs available MacOS images are Monterrey and Big Sur - they are listed in the docs below. 
https://cirrus-ci.org/guide/macOS/
Our Mojave is being automatically updated to Catalina, but Catalina images are deprecated (according to the docs), this becomes two builds of the same thing (same Catalina image).
This is not related to this weekend MacOS slow builds - I asked Cirrus about it, but haven't been updated on it yet.
=> CI: upgrade MacOS versions from deprecated Mojave

Common/ac/spritecache.cpp, Common/ac/spritefile.cpp, Common/ac/spritefile.h, Editor/AGS.Native/NativeDLL.vcxproj, Editor/AGS.Native/agsnative.cpp
The commit 393ef2c24bbc835d8e7a7229d40f638a6f172304 has introduced a bug, where saving spritefile would unintentionally restore all the sprites that were deleted during the session.
Sprites are not all stored in memory, and when the file is saved, these that were not loaded at the moment would be read from the *previous* version of the file, and copied into new one. Aftter certain changes the code was missing a proper check for non-existing sprites. Because of that all the sprites that were in the previous file but marked for deletion are still carried over.
And because their references are removed from the project, these would be non accessible, and user won't even know about the leftover data, unless they try to import new sprites and notice they cannot assign a presumably "empty" slot …
=> 3.6.0 Editor: fixed sprites never deleted from spritefile

Compiler/script2/cs_parser.cpp, Compiler/test2/cc_bytecode_test_0.cpp, Compiler/test2/cc_parser_test_1.cpp
- `while (true)` should not short-circuit the `while` body
```
{
int i = 5;
while(true)
{
i--;
if (i <= 0) break;
}
if (i ==  5)
AbortGame("'while' was short-circuited");
}
```
- `do … while (false)` should not have a jump back to the start of the `do`
Can't really test that except by examining the generated code: If there __is__ a jump back to the start of the do, it won't ever be executed because the `do while` condition is `false`.
- `if (expr)` should ensure that type of the condition is `int`
```
float TestFunc()
{
if (TestFunc()) // ← Should not compile
return 7.0;
return 0.0;
}
```
=> New compiler: Fix some bugs in constant handling

Tools/crmpak/main.cpp, Tools/data/mfl_utils.cpp
Currently when building agspak with g++ 9 on Ubuntu 20.04 I get the error below, when using `make` at agspak directory. 
```
../../Tools/data/mfl_utils.cpp:66:82: error: format ‘%lld’ expects argument of type ‘long long int’, but argument 3 has type ‘soff_t’ {aka ‘long int’} [-Werror=format=]
66 |                 printf("Error: file was not written correctly: %s\n Expected: %lld, wrote: %lld bytes\n",
|                                                                               ~~~^
|                                                                                  |
|                                                                                  long long int
|                                                                               %ld
67 | …
```
=> Tools: fix error on g++ 9, %lld is long long int, but soff_t is long int

Engine/media/audio/audio_core.cpp, Engine/media/audio/openaldecoder.cpp, Engine/media/audio/openaldecoder.h
Fixes #1503.
It's unclear whether AL_PITCH attribute in OpenAL actually means playback speed or not, the available specification is not clear about this, and in the mojoAL implementation we're using AL_PITCH scales the sample pitch but not the frequency, therefore speed stays the same.
This PR implements playback speed by resampling a portion of sound before we pass it into OpenAL. The result should be equivalent to pre-3.6.0 functionality where the dynamic frequency shift was supported by allegro 4.
So far the only problem I experienced was with calculating playback position, as we no longer may rely only on offset time the OpenAL reports. This is solved by keeping a record of speed and "sped up" time per each queued buffer, and applying these as the buffers are processed.
There's still …
=> 3.6.0: implement audio playback speed using resampling

Common/ac/game_version.h, Common/game/roomstruct.cpp, Editor/AGS.Editor/Resources/agsdefns.sh, Editor/AGS.Types/Room.cs, Engine/ac/character.cpp, Engine/ac/global_game.cpp, Engine/ac/global_hotspot.cpp, Engine/ac/global_object.cpp, Engine/ac/hotspot.cpp, Engine/ac/object.cpp, Engine/ac/room.cpp, Engine/ac/roomobject.cpp, Engine/ac/roomobject.h, Engine/ac/roomstatus.cpp, Engine/ac/roomstatus.h, Engine/game/savegame_components.cpp
Resolves #979.
Hotspot and Object.Name property can now be set from script.
Any internal engine's action retrieving an object or hotspot's name should be using current name from the RoomStatus, rather than the default name from the room file.
These properties are now saved when the game is saved.
=> Script API: settable Hotspot.Name and Object.Name

Common/util/compress.cpp
Some compilers may default char to unsigned char, which makes the RLE decompression fail.
=> RLE decompressing: Redefined char as signed char

Engine/ac/properties.cpp
Name the property. Don't guess and name the command that looks up the property. See #1525 for details.
=> Reword error messages for property lookup

.gitignore
when using the makefile for each tool, it will produce a binary in the directory with the tool itself. It would be better if they were ignored to avoid accidentally commiting one of them.
=> .gitignore: add ags tools binaries

.cirrus.yml, Editor/AGS.Editor/AGSEditor.cs, Editor/AGS.Editor/AGSEditor.csproj, Editor/AGS.Editor/BuildTargets/BuildTargetWeb.cs, Emscripten/build.sh, Emscripten/install_dependencies.sh, ci/emscripten/Dockerfile
This adds support for generating a web build through the Editor.
You will need to extract the contents of the generated artifact and place in the Editor directory in a folder named `Web/` 
I did additional changes to the CI, which are explained in the commit.
I have not wired yet the installer and release to actually use the artifact. I want to let the Emscripten builds happen a bit more on the CI before adding the dependency on the release process.
=> Feature: Web (Emscripten) build through the Editor

Common/ac/characterinfo.cpp, Common/ac/characterinfo.h, Common/ac/game_version.h, Common/ac/mousecursor.cpp, Common/ac/mousecursor.h, Common/game/main_game_file.cpp, Editor/AGS.Editor/AGSEditor.cs, Editor/AGS.Editor/DataFileWriter.cs, Editor/AGS.Editor/Resources/agsdefns.sh, Editor/AGS.Editor/Tasks.cs, Editor/AGS.Types/Character.cs, Editor/AGS.Types/MouseCursor.cs, Engine/ac/character.cpp, Engine/ac/characterinfo_engine.cpp, Engine/ac/draw.cpp, Engine/ac/mouse.cpp, Engine/game/savegame_components.cpp
Resolves #1517.
**1.**
Adds `Character.IdleAnimationDelay` property in the script and editor properties.
The name is complying to previously added SpeechAnimationDelay (also related property is called AnimationDelay internally in the editor, not "speed").
For older games engine assigns this property to (Character.AnimationSpeed + 5) for backward compatibility.
**2.**
Adds `Cursor.AnimationDelay` property in the editor. Added 3rd argument to `Mouse.ChangeModeView` script function, now function is:
`void ChangeModeView(CursorMode, int view, int delay = SCR_NO_VALUE);`
Skipping `delay` argument (or passing SCR_NO_VALUE) will result in keeping previous delay.
For compatibility default delay value in the editor and game data is 5.
=> Script API: added Character.IdleAnimationDelay and Cursor.AnimationDelay

Editor/AGS.Editor/Entities/EditorPreferences.cs, Editor/AGS.Editor/GUI/PreferencesEditor.Designer.cs, Editor/AGS.Editor/GUI/PreferencesEditor.cs
This change modifies the Editor Preferences, it adds a tabbed panel, and allows modifying the settings using a Property Grid. For now all properties available in the Advanced tab are available elsewhere. The idea is that should we need to add a preference, we can add there more easily.
The way it works, is the EditorPreferences has some properties that are hidden using `[Browseable(false)]`, we also copy it when the preferences window is loaded. Any changes modifies this copy. When the user click ok, the values of the properties of this now modified copy is applied to the actual app settings (preferences).
I am not too sure on the names of the tab panels.
Fix #1477
=> Editor: allow using property grid to set Preferences

.cirrus.yml, Windows/Installer/ags.iss
Adds the web build in releases, in the Editor archive under `Web/`, and as the Web component in the installer.
Edit: just squashed the commits with the adjustment to the review.
=> Installer CI: add Web component to releases

Engine/ac/gamesetup.cpp, Engine/ac/gamesetup.h, Engine/ac/room.cpp, Engine/main/config.cpp, Engine/main/main.cpp, OPTIONS.md
**I don't know if we want this or not**
This was a setting that was added to the psp port and to the mobile ports probably due to some memory restriction in these devices back in the day. It's still available in the android.cfg file. If we don't want, then the right PR is the one that removes the psp variable.
We probably need to figure out what goes and what doesn't for #106 and #104
=> Engine: add clear cache on room change from Android port to config

Compiler/script2/cs_scanner.cpp, Compiler/test2/cc_scanner_test.cpp
Previously, when there wasn't any closer for an opened brace, the compiler would move the cursor to the very last line of the input and then complain that the brace higher up at … hasn't been closed. 
That's unnecessarily circuitous. Change things so that the cursor is put on the line where the unopened brace is when the error is reported.
Typical code:
```
function DoubleInt(int x)
{  // ← Complain about the unclosed '{' right here.
return 2 * x;
function TripleInt(int x)
{
return 3 * x;
}
```
=> New compiler: When an opener isn't closed, complain about that on the line of the opener instead of at EOF

Editor/AGS.Editor/Panes/AudioEditor.cs, Editor/AGS.Editor/Panes/CharacterEditor.cs, Editor/AGS.Editor/Panes/GUIEditor.cs, Editor/AGS.Editor/Panes/InventoryEditor.cs, Editor/AGS.Editor/Panes/SpriteManager.cs, Editor/AGS.Editor/Panes/ViewEditor.cs
- Character, GUI, and View editors and the Sprite manager are adjusted.
Part of #1181 
Things not fixed here:
- I noticed the below are missing specific pages in the manual. They are mentioned on Setting up the game:
- CursorEditor
- FontEditor
- GeneralSettings
- RoomSettingsPane -> Help keyword is attached to a layer, but there are no layer specific entries on the manual
=> Editor: adjust help entries for some panes

Editor/AGS.Editor/Panes/ScintillaWrapper.cs
- GetCharAt is clamped to above 0 values, after checkAtPos is negative it will be at char 0 forever in this while loop and hang the editor
This fixes a hang existent in current Script Editor when the first character is a space `' '` character. Regression after the new ScintillaNet.
=> Editor: fix space at first character hangs editor

Editor/AGS.Editor/GUI/PreferencesEditor.cs
I previously made a mistake in the preferences editor, when the DataSource is applied to cmbColorTheme control, the selected index changed event is triggered, but we haven't adjusted the selectedIndex yet to the theme selected, and this changes the theme before the theme can be configured. So whenever you load the Preferences Editor, Default is always the one configured. This fix gets the selected theme into a temporary variable and then readjust it right after. This is the temporary settings property, so any actual settings change is not saved here.
=> Editor: fix preferences menu doesn't select current color theme

Common/game/room_file.cpp, Common/game/roomstruct.h, Editor/AGS.Editor/AGSEditor.cs, Editor/AGS.Editor/ImportExport.cs, Editor/AGS.Editor/NativeProxy.cs, Editor/AGS.Editor/Panes/GeneralSettingsPane.cs, Editor/AGS.Editor/Tasks.cs, Editor/AGS.Native/NativeMethods.cpp, Editor/AGS.Native/NativeMethods.h, Editor/AGS.Native/agsnative.cpp, Editor/AGS.Types/Game.cs, Editor/AGS.Types/Utilities.cs
These are the final changes for #1527 (and maybe #1297 in general).
After #1542 is merged you can have a unicode support in the editor, however if you import an older project, and then switch to UTF-8, the text may become corrupted if it uses any characters but common latin.
This pr adds a conversion process run after changing the encoding setting in the editor. The conversion is done simply as:
* load the data using old encoding;
* save the data using new encoding;
repeated with each file.
Files processed are:
* all script files;
* room files;
* main project file (Game.agf).
Translations (TRS files) *are not affected*, as they each have their individual encoding setting.
No big code changes were necessary, as the Editor already converts texts to C# representation in memory using provided …
=> Editor: convert game files when the text format changes

Compiler/script2/cs_parser.cpp, Compiler/script2/cs_parser.h, Compiler/test2/cc_parser_test_1.cpp
In general, this shouldn't be allowed in any locations where an expression is purely evaluated for its side effects. 
Typical code:
```
function room_AfterFadeIn()
{
player.Say; // ← Compiler should complain about missing '('.
}
```
I'm taking this as an opportunity to fix another, related bug: An expression that contains a bracketed sub-expression has side effects when the sub-expression has side effects. Typical examples `object[++i]` or `arr[calculate_index()]`: these expressions have side effects. The compiler hadn't gotten this correct.
=> New compiler: Disallow function names without following '(' in statements

Tools/crmpak/main.cpp
Fixes the following build issue:
```
g++ -std=c++11 -Werror=delete-non-virtual-dtor  -O2 -g -fsigned-char -fno-strict-aliasing -fwrapv -Wunused-result -Wno-unused-value -Werror=write-strings -Werror=format -Werror=format-security -DNDEBUG -D_FILE_OFFSET_BITS=64 -DRTLD_NEXT  -I../../Common -MD -c -o main.o main.cpp
main.cpp: In function ‘int main(int, char**)’:
main.cpp:137:9: error: ‘errno’ was not declared in this scope
137 |         errno = 0;
|         ^~~~~
main.cpp:9:1: note: ‘errno’ is defined in header ‘<cerrno>’; did you forget to ‘#include <cerrno>’?
8 | #include "util/string_compat.h"
+++ |+#include <cerrno>
9 | 
make: *** [Makefile:71: main.o] Error 1
```
=> Tools: Add missing include for crmpak

Compiler/script/cs_parser.cpp, Compiler/test/cs_parser_test.cpp
Added hexadecimal literals parsing to script compiler.
The code in the old compiler is rather dirty, but hopefully this will be sufficient.
Added compiler tests for hex parsing.
NOTE: I had to use `strtoul` instead of `strtol` to parse hexadecimals, because `strtol` fails to parse large hex numbers (> 0x7fffffff) on 32-bit systems (at least on some of them).
=> Compiler: support hexadecimal literals

Editor/AGS.Editor/Entities/EditorPreferences.cs, Editor/AGS.Editor/GUI/GUIController.cs, Editor/AGS.Editor/GUI/PreferencesEditor.cs, Editor/AGS.Editor/Panes/ScintillaWrapper.cs
Allow selecting which font to use for Script Editor in AGS Editor, and also the font size.
If it's decided we don't want this now, it can be closed. But I thought it was really nice to be able to switch the default font and font size. :)
=> Editor: Script Font and Size selection in Preferences

.cirrus.yml, Tools/data/dialogscriptconv.cpp, Tools/data/mfl_utils.h
- Builds tools binaries on all 3 platforms which are configured to build
- Includes 2 source changes to tools source to account for variations in the compiler being used (as far as I can tell these are errors relating to string data types and the accidental creation of a circular namespace reference)
- Removes some push and pop commands from directory switching because they mislead about how the CI is operating
Note: Tool binaries are not tested and not uploaded as part of a release
=> Build tools on CI

Common/util/string_utils.cpp, Common/util/string_utils.h, Common/util/utf8.h, Engine/ac/sys_events.cpp, Engine/ac/translation.cpp, Solutions/Common.Lib/Common.Lib.vcxproj, Solutions/Common.Lib/Common.Lib.vcxproj.filters
Fixes #1561. (Also may be eventually useful for #1550)
Added some utf-8 utilities (encoding, decoding), based on the code from https://c9x.me/git/irc.git/tree/irc.c with minor adjustments.
Moved previously experimental "convert_utf8_to_ascii" function from translation.cpp to StrUtil module. Don't use allegro4 function uconvert, and use utf-8 utilities instead, to avoid depending on allegro.
Upon SDL_TEXTINPUT convert received text from utf-8 to ascii before assigning to the keycode. This fixes extended ANSI keycodes passed into on_key_press script callback.
NOTE: I had to use custom utf-8 decoding code, because apparently `setlocale` fails at setting "utf-8" on some older Windows systems (prior to Windows 10, judging by documentation, unless some patches are installed). Because of that I …
=> Add basic utf-8 utilities to Common, and fix extended ansi key codes in on_key_press callback

Editor/AGS.Editor/Entities/EditorPreferences.cs, Editor/AGS.Editor/GUI/PreferencesEditor.cs, Editor/AGS.Editor/Panes/ScintillaWrapper.cs
- makes Scintilla use same font style for AutoComplete as the one used for Script
- adds a preference entry for call tip font and font size
---
After #1557 it appears to be a good idea to include a way to modify the tooltip font used in the editor.
Also there's an issue with AutoComplete when font height is changed mentioned here: https://github.com/adventuregamestudio/ags/pull/1557#issuecomment-1061644287
[Scintilla Docs](https://www.scintilla.org/ScintillaDoc.html) also mentions the following
> All lines of text in Scintilla are the same height, and this height is calculated from the largest font in any current style.
=> Editor: Add Call Tip font preferences and additional scintilla modification

.cirrus.yml
- use ninja
- cache ninja and cmake
This at least halved the time it takes for the current MacOS builds in my tests.
=> CI: speedup MacOS builds

Engine/ac/gamesetup.h, Engine/main/config.cpp, Engine/main/engine.cpp, Engine/platform/base/sys_main.cpp, Engine/platform/base/sys_main.h, OPTIONS.md
Resolves #1567.
Implemented config option for SDL2's driver selection, this is currently used only for software renderer.
```
[graphics]
software_driver = name
```
where driver's name could be one of: direct3d, opengl, opengles, opengles2, metal, software.
Not all of the drivers are supported on all systems.
Empty name, or missing option means use defaults.
Note that AGS prints SDL's driver name in the log, when using software renderer. This looks like:
> Created SDL Renderer: opengl
=> Engine: support option for software renderer's output driver

Common/ac/gamestructdefines.h, Common/ac/keycode.h, Editor/AGS.Editor/AGSEditor.cs, Editor/AGS.Editor/DataFileWriter.cs, Editor/AGS.Editor/Panes/ScintillaWrapper.cs, Editor/AGS.Editor/Resources/agsdefns.sh, Editor/AGS.Editor/Tasks.cs, Editor/AGS.Editor/Utils/NativeConstants.cs, Editor/AGS.Native/NativeMethods.cpp, Editor/AGS.Native/agsnative.cpp, Editor/AGS.Types/Settings.cs, Engine/ac/dialog.cpp, Engine/ac/event.cpp, Engine/ac/event.h, Engine/ac/game.cpp, Engine/ac/sys_events.cpp, Engine/ac/sys_events.h, Engine/game/game_init.cpp, Engine/main/game_run.cpp, Engine/main/game_run.h, Engine/script/cc_instance.cpp, Engine/script/nonblockingscriptfunction.h, Engine/script/script.cpp, Engine/script/script.h
Resolves #1563.
Existing `on_key_press` callback is not enough for handling keyboard input in unicode mode, and has other limitations even in ascii mode. The keycodes it receives do not represent the actual character typed, but rather key pressed, where textual representation depends on various factors. While this callback is enough for handling key presses, it may complicate coding of custom input fields in the user script.
This pr proposes a new `on_text_input (int chr)` callback, which receives a text character code in the current game mode (ascii or unicode).
Additionally `dialog_options_text_input(int chr)` callback is meant for doing the same in the "custom dialog options render" state (it may be seen inconvenient that we have such separation between 2 game states, but nothing may …
=> Provide "on_text_input" callback for handling unicode characters

.cirrus.yml
The templates master branch now have 3.6.0 templates, so instead point to release-3.5.1 branch.
=> CI: get templates from release-3.5.1 branch
