adventuregamestudio/ags

- Editor/AGS.Editor/GUI/TabbedDocumentManager.cs
Addressed the following issue in the bug tracker http://www.adventuregamestudio.co.uk/forums/index.php?issue=621.0
While I was in the code area I added an option for closing all tabs as I've been missing this feature myself.
> Editor: Close all other tabs

- Editor/AGS.Editor/Components/HelpCommandsComponent.cs
The HTML Help API's HtmlHelp function forces the help window to stretch across multiple monitors if it opens at a negative location (-x, -y), which can be quite inconvenient.
I added a method that gets the size of the monitor that the help window was created in and resizes the help window to that size, as well as move the window to the top left corner of the monitor.
> Editor: Fixed help window multi-monitor size

- README.md
- Windows/Installer/License.txt
- Windows/Installer/Source/Docs/AGS Forums.url
- Windows/Installer/Source/Docs/AGS Website.url
- Windows/Installer/Source/Docs/license_alfont.txt
- Windows/Installer/Source/Docs/license_almp3.txt
- Windows/Installer/Source/Docs/license_dumb.txt
- Windows/Installer/Source/Docs/license_freetype.txt
- Windows/Installer/Source/Docs/license_gnulgpl.txt
- Windows/Installer/Source/Docs/license_ogg.txt
- Windows/Installer/Source/Docs/license_scintilla.txt
- Windows/Installer/ags.iss
- Windows/Installer/build.py
- Windows/README.md
These are not perfect but hopefully enough to start getting an installer building through teamcity. Comments welcome.
> Windows Installer build scripts.

- Common/util/memory.h
The pull request is created in order to get automatic reports from the build server.
> PSP port compilation fixes

- Editor/AGS.Editor/Panes/DialogEditor.cs
- Editor/AGS.Editor/Panes/ScintillaWrapper.cs
- Editor/AGS.Editor/Panes/ScriptEditor.cs
Was doing some prototyping for a possible future fix and found some code files that needed cleaning up.
- Fixed indenting and general code formatting
- Organized and removed unused usings
> Code cleanup

- Editor/AGS.Editor/GUI/SplashScreen.cs
Remove the "girl next door" tag line from splash screen.
> Make splash screen tag lines gender neutral.

- Common/font/agsfontrenderer.cpp
- Common/font/agsfontrenderer.h
- Common/font/fonts.cpp
- Common/font/fonts.h
- Common/font/ttffontrenderer.cpp
- Common/font/ttffontrenderer.h
- Common/font/wfnfontrenderer.cpp
- Common/font/wfnfontrenderer.h
- Common/gui/guitextbox.cpp
- Engine/ac/display.cpp
- Engine/main/engine.cpp
- Engine/plugin/agsplugin.cpp
Just trying to tidy up some code in the font renderers:
* Eliminate some globals
* Limit some globals to static scope
> Dev 3.4.0  tidy font

- Editor/AGS.Editor/AGSEditor.cs
- Editor/AGS.Editor/BuildTargets/BuildTargetDataFile.cs
- Editor/AGS.Editor/BuildTargets/BuildTargetDebug.cs
- Editor/AGS.Editor/BuildTargets/BuildTargetWindows.cs
- Editor/AGS.Editor/DataFileWriter.cs
- Editor/AGS.Editor/NativeProxy.cs
2f72439 is a major bugfix. The other commits are not essential, but should make the build process more readable/consistent. This does not affect the legacy builder/compiler.
> Refactor new builder

- Copyright.txt
Edit my name (thank you for the credit)
> Edit my name

- Android/library/AndroidManifest.xml
- Editor/AGS.Types/Properties/AssemblyInfo.cs
- Manual/ags.tex
- PSP/README.md
- Script/push_version.py
- Windows/Installer/ags.iss
- Windows/Installer/build.py
- version.json
- Versions are stored in version.json
- Source files can be updated with push_version.py
- Installer uses version.json to set version and appid
- Installer allows selecting engine without mp3 support
- small unicode fix to ags.tex
> Installer changes for release

- Script/build_packages.py
The included script ensures that the Teamcity Release job includes all files needed for release (including installer) with appropriate names and checksums.
> Packaging: script to create release packages with checksums

- Engine/ac/character.cpp
- Engine/ac/viewframe.cpp
- Engine/ac/viewframe.h
- Engine/media/audio/audio.cpp
- Engine/media/audio/audio.h
The adjusted volume was never actually applied to the audio channel
> Engine: fix AdjustVolumeWithScaling

- OSX/buildlibs/Makefile
- OSX/patches/dumb-0.9.3.patch
- OSX/xcode/AGSKit/AGSKit.xcodeproj/project.pbxproj
- OSX/xcode/ags/ags.xcodeproj/project.pbxproj
- OSX/xcode/ags/plugin_registration.cpp
- iOS/xcode/ags/ags.xcodeproj/project.pbxproj
Allows building for ios/osx again.
> Xcode build fixes

- Editor/AGS.Editor/Resources/agsdefns.sh
- Engine/ac/mouse.cpp
- Engine/ac/mouse.h
Includes Mouse.SelectPreviousMode and Mouse.IsModeEnabled. These functions are trivial in the engine source, but less trivial for end-user devs to implement.
> Add mouse utility methods

- Engine/gfx/ali3dogl.cpp
- Engine/main/engine_setup.cpp
- Engine/main/graphics_mode.cpp
- Engine/platform/android/acpland.cpp
- Engine/platform/base/agsplatformdriver.h
- Engine/platform/ios/acplios.cpp
This provides fixes necessary for 3.4.0 branch to be playable on Android device.
The pull request will remain in WIP state until users' tests are complete.
> Fixes for Android port (next 3.4.0 patch)

- Editor/AGS.Editor/AGSEditor.cs
- Editor/AGS.Editor/Audio/MidiPlayer.cs
- Editor/AGS.Editor/Components/StatisticsSenderComponent.cs
- Editor/AGS.Editor/ImportExport.cs
- Editor/AGS.Editor/Panes/DialogOptionEditor.cs
- Editor/AGS.Editor/Panes/GUIEditor.cs
- Editor/AGS.Editor/Panes/ScintillaWrapper.cs
- Editor/AGS.Editor/TextProcessing/SpeechLinesNumbering.cs
Needs #406 to be resolved since "AGS.CScript.Compiler" is a requirement of "AGS.Editor"
> Fixed C# project module "AGS.Editor" so that it successfully builds in xBuild on *nix systems

- Editor/AGS.Editor/NativeProxy.cs
I don't think we need to keep this unused code, we should also discourage or disallow anyone from re-applying any of this code.
> Removed unused code from NativeProxy.cs

- Editor/AGS.Editor/Panes/ViewEditor.cs
- Editor/AGS.Editor/Panes/ViewLoopEditor.cs
This should fix issues with loop positions in the view editor.
[http://www.adventuregamestudio.co.uk/forums/index.php?topic=55992.0](http://www.adventuregamestudio.co.uk/forums/index.php?topic=55992.0)
> Scrollbar fixes for the view editor

- Common/ac/roomstruct.cpp
Previously was only done on ags.native so they would be fixed when the project was loaded and recompiled.
But I understand the need to test existing games, so here it is. 
#457
> Engine: workaround to resize area masks to test 3.4.1 games

- Common/gfx/allegrobitmap.h
- Common/util/wgt2allg.h
- Engine/ac/route_finder.cpp
Fixes problem described in #487.
> Allegro function updates to fix glibc build error.

- Editor/AGS.Editor/Program.cs
This should fix plug-in loading where the plug-in was built referencing an unsigned assembly.
[http://www.adventuregamestudio.co.uk/forums/index.php?topic=56457](http://www.adventuregamestudio.co.uk/forums/index.php?topic=56457.msg636595020#msg636595020)
> Resolve failed assembly loads when public key is null

- Editor/AGS.Editor/Panes/PaletteEditor.Designer.cs
- Editor/AGS.Editor/Panes/PaletteEditor.cs
Presumably this text predated 32 bit colour games?
> Update colour message for palette editor

- .editorconfig
EditorConfig is the new trendy and hip config file that is reusable across various IDEs and text editors (check their homepage for a list)
> EditorConfig is awesome: http://EditorConfig.org

- debian/README.md
Update the docs for compiling on Fedora. This should fix #591
> Update the Fedora compile documentation per Fedora 29 packages

- Common/gui/guimain.cpp
This fixes regression introduced in a2247b8db74b3464718a8a7773d3f76028e0c856 with the removal of GUIMain::ControlCount member variable.
> AGS 3: fix reading GUIs in pre-3.4.0 games

- Android/library/jni/Android.mk
- Android/library/jni/Application.mk
- Engine/Makefile-objs
- Engine/plugin/agsplugin.cpp
- Plugins/agspalrender/Makefile
- Plugins/agspalrender/README.md
- Plugins/agspalrender/ags_palrender.cpp
- Plugins/agspalrender/agspalrender.h
- Plugins/agspalrender/agsplugin.h
- Plugins/agspalrender/palrender.h
- Plugins/agspalrender/raycast.cpp
- Plugins/agspalrender/raycast.h
Good test game: Terror of the Vampire! https://www.adventuregamestudio.co.uk/forums/index.php?topic=54978.0
> SDL2: add agspalrender (or palgorithms) plugin.

- Engine/Makefile
- Engine/Makefile-defs.linux
- Engine/Makefile-defs.osx
- Engine/Makefile-objs
- Engine/platform/osx/acplmac.cpp
- OSX/patches/allegro-4.4.2.patch
Also add 'debug' target for.. debugging.
(note: colours are off because allegro patch assumed a different pixel format, to be fixed in a future patch) (or the SDL port)
> macos: Initial fixes to get macos building with Makefile

- Engine/ac/dynobj/cc_dynamicobject.cpp
- Engine/ac/dynobj/managedobjectpool.cpp
- Engine/ac/dynobj/managedobjectpool.h
- Engine/script/script_runtime.cpp
Uses maps for object handle and address lookups.
> AGS3 refactor ManagedObjectPool to address slow lookups

- Engine/ac/draw.cpp
- Engine/ac/timer.cpp
- Engine/debug/debug.cpp
- Engine/main/game_run.cpp
- Engine/platform/base/agsplatformdriver.cpp
- Engine/platform/base/agsplatformdriver.h
- Engine/platform/linux/acpllnx.cpp
- Engine/platform/osx/acplmac.cpp
- Engine/platform/windows/acplwin.cpp
Small fixes for the recent changes. There should be enough details in the different commits.
Also I added a recursive lock using the std::mutex libraries. Platform developers can still implement their own recursive solutions.
> AGS3 - miscellaneous fixes

- Engine/ac/character.cpp
- Engine/ac/display.cpp
- Engine/ac/global_character.cpp
- Engine/ac/global_game.cpp
- Engine/ac/global_object.cpp
- Engine/ac/object.cpp
- Engine/ac/room.cpp
- Engine/ac/runtime_defines.h
- Engine/main/game_run.cpp
- Engine/main/game_run.h
- Engine/script/script.cpp
Store pointers in void* instead of long (which is 32bit on windows), and introduce some safer methods to call it.
> AGS3: GameLoopUntilEvent is slightly more type safe

- Common/CMakeLists.txt
- Common/api/stream_api.h
- Common/util/alignedstream.cpp
- Common/util/alignedstream.h
- Common/util/bufferedstream.cpp
- Common/util/bufferedstream.h
- Common/util/file.cpp
- Common/util/filestream.cpp
- Common/util/filestream.h
- Common/util/proxystream.cpp
- Common/util/proxystream.h
- Engine/ac/file.cpp
Add a tunable buffered stream to help with systems that have slow seek/low read buffers.
This implementation is based on top of FileStream, so not as reusable. It will also attempt to re-use the buffer after a Seek.
> AGS3 Buffered streams

- Editor/AGS.Editor/Utils/SpriteTools.cs
- Editor/AGS.Types/Sprite.cs
> Revert purpose of AlphaChannel flag

- Engine/CMakeLists.txt
- Engine/ac/game.cpp
- Engine/ac/keycode.cpp
- Engine/ac/keycode.h
- Engine/main/game_run.cpp
- Solutions/Engine.App/Engine.App.vcxproj
- Solutions/Engine.App/Engine.App.vcxproj.filters
This should fix issue https://github.com/adventuregamestudio/ags/issues/848
> SimulateKeyPress: correctly maps from AGS keycodes to allegro4 keycodes.

- Android/library/jni/Android.mk
- Android/library/jni/Application.mk
- Common/util/compress.cpp
- Common/util/filestream.cpp
- Common/util/filestream.h
- Common/util/stream.h
- Engine/Makefile-objs
- Engine/ac/game.cpp
- Engine/ac/global_file.cpp
- Engine/ac/global_translation.cpp
- Engine/plugin/agsplugin.cpp
- Engine/plugin/global_plugin.cpp
- Engine/plugin/plugin_engine.h
- Plugins/AGSflashlight/agsflashlight.cpp
- Plugins/ags_parallax/ags_parallax.cpp
- Plugins/ags_snowrain/ags_snowrain.cpp
- Plugins/agspalrender/Makefile
- Plugins/agspalrender/README.md
- Plugins/agspalrender/ags_palrender.cpp
- Plugins/agspalrender/agspalrender.h
- Plugins/agspalrender/agsplugin.h
- Plugins/agspalrender/palrender.h
- Plugins/agspalrender/raycast.cpp
- Plugins/agspalrender/raycast.h
* Updated 64-bit support for saving/reading files via plugin API
* agspalrender plugin
* agsteam + agsgalaxy stubs
* agsspritefont stubs
* extra agswadjetuils stubs
> 3.4.4: plugins update

- Engine/platform/linux/acpllnx.cpp
RE #799.
Create a "ags-common" directory near "ags" at $XDG_DATA_HOME or ~/local/.share.
When script orders to write a file into $APPDATADIR$ it will be placed in this ags-common/$gamename location.
The reason I decided to make a separate path (as opposed to direct it to existing location where saves are stored) is that in theory game scripts may be checking presence of some files in the $SAVEGAMEDIR$ and may act unexpectedly if there are also files created using $APPDATADIR$ token (or vice-versa). So this is a kind of precaution.
> Proper $APPDATADIR$ location for Linux port

- Editor/scintilla/src/PlatWin.cxx
Fixes #704 by allowing a negative offset for the autocomplete position.
This is patched as a short term solution, in-place of attempting to upgrade Scintilla and ScintillaNet, since ScintillaNet doesn't exist in the same form.
Original commit (fixed for version 2.20):
https://sourceforge.net/p/scintilla/code/ci/e2babe603996587a841069a4cbbca4288eeb9692/tree/win32/PlatWin.cxx?diff=d38bbbcba006504b8ad952500cf40356a2df68b8
Original bug report:
https://sourceforge.net/p/scintilla/bugs/979/
> Apply Scintilla patch for autocomplete position

- .cirrus.yml
- Windows/Installer/ags.iss
- Windows/Installer/build.ps1
Rename changes.txt => Changes.txt
Remove xml files from Editor installer/packaging
See #800
> Closer match for old installer content

- Editor/AGS.Editor/GUI/GUIController.cs
- Editor/AGS.Editor/GUI/StartNewGameWizardPage2.Designer.cs
- Editor/AGS.Editor/GUI/StartNewGameWizardPage2.cs
This just fixes what is already here, by retreiving the specified filename and setting it in the game properties. Plus fixes the label.
For #985
Edit: and separate issue that having no preference for the game directory did not fallback to using the documents folder
> Update new game wizard for new filename

- Common/CMakeLists.txt
- Engine/CMakeLists.txt
These file changes were sufficient for me to have working build of ags using cmake on my system.
> sync CMakeLists.txt for Engine and Common

- Plugins/agspalrender/ags_palrender.cpp
Should fix building palrender plugin on ags4 branch. I have acquired a test game and will test soon and report.
> Modifies palrender plugin for leaner agsplugin.h

- Editor/AGS.Editor/Components/RoomsComponent.cs
> Editor: Refresh room list when changing number

- .cirrus.yml
Adds CI task to run the compiler tests.
> CI: run compiler tests

- Editor/AGS.Editor/NativeProxy.cs
- Editor/AGS.Editor/Panes/CursorEditor.cs
- Editor/AGS.Editor/Panes/InventoryEditor.cs
- Editor/AGS.Editor/Panes/ViewPreview.cs
- Editor/AGS.Editor/Utils/Utilities.cs
- Editor/AGS.Native/NativeMethods.cpp
- Editor/AGS.Native/NativeMethods.h
- Editor/AGS.Native/agsnative.cpp
> Fixed that cursor drawn in editor didn't scale

- Engine/ac/file.cpp
- Engine/media/video/video.cpp
Fixes #1039.
This implements a custom PACKFILE virtual table that wraps calls to our own Stream object for 64-bit file offset support. This is used for each allegro and third-party library calls that require PACKFILE.
Note that the size of asset will be still limited to 32-bit (2 GB) due to PACKFILE format, but this will do for now (until SDL2 version is made).
Also, removed redundant ApegStreamReader which was not really necessary in the first place.
For test game see attachment to #1039.
> Use custom PACKFILE vtable to support 64-bit package offsets

- Engine/Makefile-defs.linux
fix compilation on ubuntu 20.04, some more sensible makefile cleanups
> Ubuntu20fix

- Common/gui/guibutton.cpp
Buttons that don't have any click action are, in effect, just labels. The user can't react to them in the first place. So when the interface becomes disabled, the user should not get the message that they _now_ cannot react to them. 
This PR changes the UI so that GUI buttons whose ClickAction is NoAction are treated as labels.
(Why would an AGS coder use a button without any click action instead of a label in the first place? Because GUI labels can't show sprites. So if you want to denote with a spiffy sprite, e.g., whether Ego can currently fly or not, then a label won't do and you need a button.)
> When user interface is disabled, only grey/black out GUI buttons that have an associated click action.

- Compiler/script/cs_parser.cpp
the following now works:
import const string get_version();
const string baz(const string b) {
return b;
}
const string bar() {
return "bar";
}
this should be sufficient to resolve AGS issue 830
https://github.com/adventuregamestudio/ags/issues/830
using const string variables doesn't work still:
const string muh = "muh";
-> cannot assign value to string, use StrCopy
> script compiler: implement parsing of const function return type

- Solutions/AGS.Editor.Full.sln
- Solutions/AGS.Editor.NoNative.sln
> Changed solutions so AGSEditor is the default startup project

- Editor/AGS.Types/SerializeUtils.cs
Fixes #1282 
Makes the Game.agf more reliable for version control users
> Fixed alphabetical sorting of elements in Game.agf

- Editor/AGS.Editor/Resources/agsdefns.sh
- Engine/platform/base/agsplatformdriver.h
I would like to reserve the eOSWeb enum until I can get the web platform development done.
> reserve eOSWeb enum

- README.md
Did some adjustments in the text of the README, I avoided modifying the content and foccused on making a bit easier to read and adjusted the grammar. Also removed HTML tags.
> adjustments in the README grammar and clarity

- .cirrus.yml
- CMake/FetchGoogleTest.cmake
- CMakeLists.txt
- Common/CMakeLists.txt
- Common/test/stream_test.cpp
- Compiler/CMakeLists.txt
- Compiler/test/cs_parser_test.cpp
- Engine/CMakeLists.txt
I am adding the existing tests to the CI.
I think it's almost done, but I would like to wait the CI to run everything.
> CI add existing tests on Linux and MacOS CMake pipelines

- Tools/CMakeLists.txt
- Tools/crmpak/main.cpp
- also fixes for building with it
> CMake: Add crmpak to CMake build

- Editor/AGS.Editor.Tests/AGS.Editor.Tests.csproj
- Editor/AGS.Editor.Tests/ScriptCompiler/PreprocessorTests.cs
Just adding tests to the preprocessor in the Editor. It's the same tests in the cpp version of the preprocessor.
> Editor Tests: add preprocessor tests (ags4)

- Editor/AGS.Editor.Tests/AGS.Editor.Tests.csproj
- Editor/AGS.Editor.Tests/packages.config
Ref #1446
Upgrade of remaining code for VS2022 compatability
> Dotnet 4.6 upgrade of .NET tests

- Engine/platform/android/acpland.cpp
> Android: fix single game launcher not starting

- Engine/ac/dialog.cpp
- Engine/ac/display.cpp
- Engine/ac/draw.cpp
- Engine/ac/global_audio.cpp
- Engine/ac/global_game.cpp
- Engine/debug/debug.cpp
- Engine/main/game_start.cpp
- Engine/main/quit.cpp
- Engine/media/audio/audio.cpp
- Engine/platform/base/agsplatformdriver.cpp
- Engine/script/script.cpp
> Add stdio.h includes

- Android/agsplayer/build.gradle
- Android/library/runtime/build.gradle
- Android/mygame/build.gradle
- Android/mygame/play_licensing_library/build.gradle
Fix #1496 
Should make Android build work again in the CI.
> Android: fix jcenter has been sunset, use maven instead

- Engine/platform/android/acpland.cpp
Removes some dead code from `acpland.cpp`
> Android: remove unused code from acpland

- Editor/AGS.Editor/AGSEditor.csproj
- Editor/AGS.Editor/Panes/CursorEditor.Designer.cs
- Editor/AGS.Editor/Panes/CursorEditor.cs
- Editor/AGS.Editor/Panes/CursorEditor.resx
- Editor/AGS.Editor/Panes/InventoryEditor.Designer.cs
- Editor/AGS.Editor/Panes/InventoryEditor.cs
- Editor/AGS.Editor/Panes/InventoryEditor.resx
- Editor/AGS.Editor/Panes/ViewEditor.Designer.cs
- Editor/AGS.Editor/Panes/ViewEditor.cs
- Editor/AGS.Editor/Panes/ViewEditor.resx
- Editor/AGS.Editor/Panes/ViewLoopEditor.cs
- Editor/AGS.Editor/Panes/ZoomTrackbar.Designer.cs
- Editor/AGS.Editor/Panes/ZoomTrackbar.cs
- Editor/AGS.Editor/Panes/ZoomTrackbar.resx
- Editor/AGS.Editor/Utils/MathExtra.cs
- Editor/AGS.Native/agsnative.cpp
adds a zoom slider for inventory item images. You can also hold CTRL to scroll with mouse wheel.
A zoom slider is also added to the View Editor!
Edit: and also to the Cursor editor!
fixes #575 (and maybe #710)
> Editor: Zoom Slider in Inventory and View panels

- Compiler/Makefile
> Compiler: add Makefile

- Common/script/cc_options.h
- Compiler/script/cs_parser.cpp
- Editor/AGS.Editor/Resources/agsdefns.sh
- Editor/AGS.Native/ScriptCompiler.cpp
- Engine/ac/string.cpp
- Engine/ac/string.h
- Engine/script/script_api.cpp
- Solutions/Tests.App/Engine.App.Test.vcxproj
- Solutions/Tests.App/Engine.App.Test.vcxproj.filters
Resolves #1550.
1. Adds support for unicode character literals. Technically, script compiler already converts character literals to 32-bit integer, so the only thing remaining was to let it parse utf-8 multibyte sequence properly. For compatibility with ascii/ansi scripts this is done only if the new SCOPT_UTF8 compiler option is set: in ascii mode this will keep extended ansi (>127) codes parsed as single byte chars.
EDIT: i realized that the previous compilers did not support "extended ansi" character literals, as i wrongly assumed, because they resulted in a negative char code. Still this option is necessary to prevent attempts to parse these as utf-8.
2. `String.AppendChar` and `ReplaceChar` now accept "character" parameter as `int`.
3. `String.Chars[]` indexed attribute now works …
> Script API: support working with unicode characters

- Android/and-build.sh
> CI: Android build should fail when there is an error building

- Windows/Installer/ags.iss
> Installer: Editor shortcut in start menu includes version

- Editor/AGS.Editor/Panes/Room/RoomSettingsEditor.cs
> Force refresh of room editor when property panel has changed

- Common/gfx/allegrobitmap.cpp
- Common/gfx/bitmap.cpp
- Common/gui/guibutton.cpp
- Common/gui/guilistbox.cpp
- Common/gui/guimain.cpp
- Common/script/cc_script.cpp
- Common/script/cc_script.h
- Common/util/bufferedstream.cpp
- Common/util/data_ext.cpp
- Common/util/data_ext.h
really tiny code maintenance changes I picked up when I was experimenting with the codebase - nothing that changes how the engine behaves.
> Minor tidy up

- Editor/AGS.Editor/Resources/agsdefns.sh
sorry, I made a small mistake in the header when squashing the commits and did not notice
> fix script header had wrong enum type after 9e3d58a83d

- README.md
did a minor tidy up to reduce the intro text a bit, and placed the bluecup org logo in the README to make it look a bit nicer.
> Shorten README intro text a bit

- CMake/FetchSDL_Sound.cmake
- Windows/README.md
- ci/linux/Dockerfile
- ci/windows/Dockerfile
- debian/README.md
https://github.com/icculus/SDL_sound/commit/495e948b455af48eb45f75cccc060498f1e0e8a2
for #1689
> SDL_Sound: update version, includes mp3 length fix

- Android/library/runtime/src/main/res/layout/credits.xml
- Android/library/runtime/src/main/res/values/strings.xml
> Android: add credits

- Android/README.md
Partially address the items mentioned in #1715 , except controls
> Android: README adjustments

- Editor/AGS.Editor/Panes/ScintillaWrapper.cs
Fixes #1783
There have been a number of inconsistencies in how the dialog scripts are styling comments and strings; or rather in how they detect when to style.
Firstly, there have been this silly mistake in condition here, which made the condition make no sense (it will always be true for letter or digits, as style `!=` are ORed)
https://github.com/adventuregamestudio/ags/blob/084f3f281359560a94ed819ff649edbf8bf9c4a0/Editor/AGS.Editor/Panes/ScintillaWrapper.cs#L2517-L2518
Secondly a number of clauses below never tested for being inside a comment.
~Introduced couple of booleans for more tidy code, and made sure that all necessary cases test for comments.
I guess the code could be reorganized to simplify these checks, but I decided to avoid further refactor at the moment.~
EDIT: Done a …
> Editor: fixed how dialog script is styling the comments and strings

- Engine/device/mousew32.cpp
> Engine: prevent cursor from leaving game area

- Common/util/directory.cpp
minor warnings and clang-tidy notices
> Common: fix warnings in directory.cpp

- Engine/ac/draw_software.cpp
> Engine: avoid dirty rects outside software render surface

- Common/ac/characterinfo.cpp
- Common/font/fonts.cpp
- Common/util/bufferedstream.cpp
- Common/util/ini_util.h
- Common/util/multifilelib.h
- Common/util/stream.cpp
- Common/util/textreader.h
- Common/util/textstreamreader.h
- Engine/ac/sys_events.cpp
- Engine/main/engine.cpp
- Tools/data/agfreader.cpp
very minimal warnings that I picked up when analyzing the code
> Warning cleanup

- Engine/ac/screen.cpp
- Plugins/ags_snowrain/ags_snowrain.cpp
> Fix snowrain plugin

- Common/util/memorystream.cpp
- Compiler/compiler.cpp
- Plugins/agspalrender/ags_palrender.cpp
Picked up some logical mistakes when reading the code and using a static analyzer
- Memory stream doesn't check position (soff_t) after offset being lower than 0 before assigning
- In the compiler frontend, I wrote an error for empty input filename, but it's never checked
- In the palrender, two checks for the stars y position were wrong, and a get method that is used, the function was written as void
> Fix logic mistakes

- Engine/script/cc_instance.cpp
- Plugins/AGSSpriteFont/AGSSpriteFont/SpriteFontRenderer.cpp
- Plugins/AGSSpriteFont/AGSSpriteFont/SpriteFontRendererClifftopGames.cpp
- Plugins/AGSSpriteFont/AGSSpriteFont/VariableWidthSpriteFont.cpp
- Plugins/AGSSpriteFont/AGSSpriteFont/VariableWidthSpriteFontClifftopGames.cpp
- Tools/data/scriptgen.cpp
Just moving strlen out of for loops where it's easy, so it runs only once.
> Move strlen out of loops

- Common/gui/guibutton.cpp
- Common/gui/guibutton.h
- Common/gui/guidefines.h
- Common/gui/guimain.h
- Editor/AGS.Native/agsnative.cpp
- Engine/ac/button.cpp
- Engine/ac/draw.cpp
- Engine/ac/draw.h
- Engine/ac/game.cpp
- Engine/ac/global_button.cpp
- Engine/ac/viewframe.cpp
- Engine/game/savegame_components.cpp
Enables animations with flipped frames to work properly on GUI buttons.
> AGS4 Flipped frames animation for gui buttons

- Common/ac/characterinfo.h
- Editor/AGS.Editor/Resources/agsdefns.sh
- Engine/ac/character.cpp
- Engine/ac/object.cpp
@ericoporto suggested this may be of use.
I did not propose it before because I wasn't sure whether this missing script property should be writable or not.
> Script: Readable UseRegionTint property for Character/Object

- .gitignore
- OSX/xcode/AGSKit/AGSKit.xcodeproj/project.pbxproj
just sync files that should be in the project
> Xcode adjustments

- Solutions/Engine.App/Engine.App.vcxproj
- Windows/README.md
- ci/windows/Dockerfile
Adjust for https://github.com/adventuregamestudio/ags/issues/1442#issuecomment-1575571683
Better wait the CI to build just to make sure
> Windows: remove SDL2_sound-static.lib renaming

- Editor/AGS.Editor/Panes/InventoryEditor.Designer.cs
- Editor/AGS.Editor/Panes/InventoryEditor.cs
- Editor/AGS.Editor/Panes/SpriteSelector.Designer.cs
- Editor/AGS.Editor/Panes/SpriteSelector.cs
This should adjust the layout of the following panes so they work in both 100% and 200% scaling
- SpriteSelector
- InventoryEditor
> Adjust automatic layout of some panes (for 100% and 200% scaling)

- ci/android/Dockerfile
- ci/emscripten/Dockerfile
- ci/linux/Dockerfile
just minor updates to see if they are related to the CI outage. In draft until the support answers on the issues.
> Fixes non-building CI

- ci/android/Dockerfile
- ci/emscripten/Dockerfile
- ci/linux/Dockerfile
This is a cherry pick of #2029.
> CI fixes for release-3.6.0

- ci/android/Dockerfile
- ci/emscripten/Dockerfile
- ci/linux/Dockerfile
> CI fixes for ags4

- Compiler/test2/cc_bytecode_test_0.cpp
- Compiler/test2/cc_bytecode_test_1.cpp
This PR doesn't change code, it only adds/modifies Googletests.
When RTTI is enabled, the compiler needs to generate code that is slightly different from compilations where RTTI is not enabled.
Rewrite the Bytecode tests to check the generated code: 
For each test that has a code snippet that compiles differently depending on whether RTTI is enabled, split the test into two versions where one version has RTTI enabled and the other hasn't.
> New compiler: Bytecode tests for RTTI

- .gitignore
- OSX/xcode/AGSKit/AGSKit.xcodeproj/project.pbxproj
just to sync Xcode project so macOS builds can be created using it too.
> macOS: sync Xcode project

- Common/core/assetmanager.cpp
- Common/gfx/bitmap.cpp
- Common/util/android_file.h
- Common/util/directory.cpp
- Common/util/directory.h
- Common/util/file.cpp
- Common/util/file.h
- Common/util/path.cpp
- Common/util/path.h
- Common/util/path_ex.cpp
- Compiler/CMakeLists.txt
- Compiler/Makefile
- Engine/ac/dynamicsprite.cpp
- Engine/ac/file.cpp
- Engine/ac/game.cpp
- Engine/ac/global_dynamicsprite.cpp
- Engine/ac/global_file.cpp
- Engine/ac/global_game.cpp
- Engine/ac/listbox.cpp
- Engine/ac/path_helper.h
- Engine/platform/windows/setup/winsetup.cpp
- Engine/script/cc_instance.cpp
- Solutions/Compiler.App/Compiler.App.vcxproj
- Solutions/Compiler.App/Compiler.App.vcxproj.filters
- Tools/data/mfl_utils.cpp
Resolves #2026.
Makes all the script file commands simulate case-insensitive filesystem. This fixes compatibility issues in user scripts, and makes game data and file access from script work alike (as engine already uses case-insensitive file search for game assets).
TBH this is a bit annoying, as the problem in question is relatively rare, but I believe it has to be done to make engine consistent.
On another hand, *at least some* of the changes in this PR would be useful on their own.
The changes in this PR:
1. Implemented DirectoryIterator and DirectoryRecursiveIterator classes, extracting code from FindFile and FindFileRecursive. This lets to have an object with bare minimum functionality when you do not need a wildcard pattern match. Also, optimized stats reading on non-Windows …
> Make all script File commands treat paths as case insensitive

- Editor/AGS.Editor/Panes/Room/RoomEditFilters/BaseAreasEditorFilter.cs
- Editor/AGS.Editor/Utils/BitmapExtensions.cs
Fix #1771 
From the discussion in [here](https://github.com/adventuregamestudio/ags/pull/1769#issuecomment-1242970015).
Still need to review the code and test it with more images.
> Editor: allow loading Room Masks with transparent chunks

- Editor/AGS.Editor/Panes/ViewLoopEditor.cs
> Editor: View panel, add replace with sprites from folder

- Editor/AGS.Editor/Components/RoomsComponent.cs
Fixes #2071 (for the most part).
This is an attempt to ensure that the RoomComponent does not unnecessarily resave room images (backgrounds, masks), unless they were actually edited by the user inside the room editor. (For room bgs this is only a case when a new bg was added.)
This is achieved by pairing each cached bitmap (bg and mask) with a Modified flag, and making sure they are set accordingly.
Did a small refactor in RoomComponent to reduce code duplication and make it easier to track actual modifications to masks.
Did few changes to the order of actions when recompiling and saving. Also removed saving script file when recompiling all rooms, as that's likely not necessary anymore since we have a room conversion on import. (According to the comment in code, this was previously done …
> AGS 4: When saving Room only save images that were actually modified

- Common/util/directory.cpp
Trying to fix #2095.
I was not able to find any problems by reading the code, and don't have a proper debugging set up with the real Android device, so will have to abuse our ci and do some practical experiments.
> Fix directory scan on Android

- .cirrus.yml
from
- 4997df895e5add457ce8a3e9fdfb62723184d495
- 0e5f1c055a6bb3fa765c8791eeda0d008086b9eb
- f7dbb60aa0b2936fa57dcd529e43374f0294f261
- additional adjustments for new compiler and editor tests (ags4 exclusives)
> [AGS4] CI: adjustments for lower resource usage

- Editor/AGS.Editor/BuildTargets/BuildTargetLinux.cs
- Editor/AGS.Editor/BuildTargets/BuildTargetWeb.cs
- Editor/AGS.Editor/BuildTargets/BuildTargetWindows.cs
> Fix delete of old files in build when game is renamed

- Editor/AGS.Editor/ComponentController.cs
- Editor/AGS.Editor/Components/AudioComponent.cs
- Editor/AGS.Editor/Components/BaseComponent.cs
- Editor/AGS.Editor/Components/CharactersComponent.cs
- Editor/AGS.Editor/Components/DialogsComponent.cs
- Editor/AGS.Editor/Components/GuiComponent.cs
- Editor/AGS.Editor/Components/InventoryComponent.cs
- Editor/AGS.Editor/Panes/ScriptEditorBase.cs
- Editor/AGS.Types/InventoryItemFolder.cs
Adds support for AudioClip, Characters, Dialogs, GUIs and Inventory Items.
This is part of #1685
> Editor: support go-to for few game instances

- OSX/xcode/AGSKit/AGSKit.xcodeproj/project.pbxproj
just to sync the Xcode project
> macOS: add miniz to Xcode project

- Engine/ac/route_finder_impl.cpp
Per discussion on discord on September 27, I'm finally able to PR the code that uses the intersection between an ellipse and a straight line to normalize move speed.
from the image:
`a` is `speed_x`
`b` is `speed_y`
The red segment is the amount of movement that will be computed for the stage. `q` is used in the drawing instead of the greek letter theta for the angle.
The equation of an ellipse is `(x/a)^2 + (y/b)^2 = 1`. The equation of the straight line from which we drew the red segment is `y = mx`. The slope `m` is found as the ratio `ydist / xdist`.
The proposed method computes the length of the red segment, as the intersection of those two equations.
<details>
<summary>Some computed results follow, to compare the current method from the ags4 branch with the proposed one.</summary> …
> Implemented a different speed normalization technique for diagonals

- Editor/AGS.Editor/Panes/ScintillaWrapper.cs
> Editor: fix char style has wrong back color

- CMake/FetchGoogleTest.cmake
- CMake/FetchOgg.cmake
- CMake/FetchSDL2.cmake
- CMake/FetchSDL_Sound.cmake
- CMake/FetchTheora.cmake
- CMake/FetchVorbis.cmake
- OSX/README.md
- Windows/README.md
- ci/linux/Dockerfile
- ci/windows/Dockerfile
- debian/README.md
- libsrc/download.sh
- libsrc/sha1sums
I wanted to fix a few CMake warnings and turns out I also had to upgrade SDL2_sound!
> Upgrade SDL2 Sound fix a few CMake warnings

- Editor/AGS.Editor/Resources/agsdefns.sh
Noticed this when updating the docs
> Editor: script header Game.ResetDoOnceOnly is void

- Editor/AGS.Editor/ColorThemes/ColorThemeJson.cs
- Editor/AGS.Editor/GUI/LogPanel.Designer.cs
- Editor/AGS.Editor/Panes/WelcomePane.Designer.cs
- Editor/AGS.Editor/Panes/WelcomePane.resx
* start page rewritten for AGS4
* disabled rounded corners in toolbars
* removed border around log panel
I'm also experimenting with dark scrollbars, but I don't know how long that will take to finish and clean up. That will take another PR.
> AGS4: Some UX improvements

- Android/README.md
- Android/and-build.sh
- Android/library/runtime/libs/libs_go_here.txt
- Android/mygame/README.md
- Android/mygame/app/build.gradle
- Android/plugins/plugins_go_here.txt
- Editor/AGS.Editor/BuildTargets/BuildTargetAndroid.cs
- Editor/AGS.Editor/BuildTargets/BuildTargetLinux.cs
- Windows/Installer/ags.iss
Make sure the Android port can package the plugins when building from the editor.
@ivan-mogilko can you test this works with your plugin?
> Android in the Editor support plugins

- Engine/gfx/ali3dogl.cpp
- Engine/gfx/ali3dsw.cpp
- libsrc/allegro/include/allegro/internal/alconfig.h
these are just some picks from the PR #2009 that I think are ok to apply now - until I redo the things there.
> iOS port safe to apply things

- Editor/AGS.Editor/Panes/ScintillaWrapper.cs
fix #2254
(explained in https://github.com/adventuregamestudio/ags/issues/2254#issuecomment-1848819411)
> Editor: fix deleting collapsed text in script editor

- Engine/platform/windows/win_ex_handling.cpp
The error message for Out of Memory would look like this:
Here is a demo game that causes an OoM error: [OoMTest.zip](https://github.com/adventuregamestudio/ags/files/13691155/OoMTest.zip)
- https://learn.microsoft.com/en-us/windows/win32/api/sysinfoapi/ns-sysinfoapi-memorystatusex
- https://learn.microsoft.com/en-us/windows/win32/api/psapi/nf-psapi-getprocessmemoryinfo
> Engine: report extra mem info on OoM failure

- .github/workflows/build.yml
This is does an additional run of the Engine in the GitHub Actions CI running auto-test
The project is here: 
https://github.com/adventuregamestudio/ags-test-games
Example run:
https://github.com/adventuregamestudio/ags/actions/runs/7340091125/job/19985502228?pr=2236#step:7:63
> CI: run auto-test in GitHub Actions pipeline

- Editor/AGS.Editor/Panes/GUIEditor.cs
- Editor/AGS.Editor/Panes/ScintillaWrapper.cs
- Editor/AGS.Editor/Panes/SpriteSelector.cs
- Editor/AGS.Native/NativeMethods.cpp
Hey, was running the Editor codebase through some various tools and found a few things in the reports
> Fix editor minor things

- Editor/AGS.Editor/Panes/Room/RoomEditNode.cs
- Editor/AGS.Native/agsnative.cpp
- Editor/AGS.Types/UnloadedRoom.cs
These are the things that were brought up as very weird when running the Editor codebase through different code analysis.
> Fix Editor analysis warnings

- Common/ac/spritefile.cpp
- Common/game/interactions.cpp
- Common/util/bufferedstream.cpp
- Common/util/geometry.h
- Common/util/scaling.h
- Engine/ac/dialog.cpp
- Engine/ac/display.cpp
- Engine/ac/draw.cpp
- Engine/ac/parser.cpp
- Engine/ac/sys_events.cpp
- Engine/main/engine.cpp
- Engine/media/audio/openalsource.cpp
- Engine/media/audio/openalsource.h
- Tools/data/dialogscriptconv.cpp
This is a bunch of different warnings and analysis picked from different tools, they looked safe enough to apply.
> Fix Common/Engine/Tools analysis warnings

- Compiler/fmem.cpp
- Compiler/fmem.h
- Compiler/script/cc_compiledscript.cpp
- Compiler/script/cc_compiledscript.h
- Compiler/script/cc_internallist.cpp
- Compiler/script/cc_internallist.h
- Compiler/script/cc_symboldef.h
- Compiler/script/cc_symboltable.cpp
- Compiler/script/cc_symboltable.h
- Compiler/script/cc_variablesymlist.h
- Compiler/script/cs_parser.cpp
fix #2274
I tried to keep changes at minimum.
> Remove long usage in Compiler 

- Android/library/runtime/src/main/java/org/libsdl/app/HIDDeviceManager.java
- Android/library/runtime/src/main/java/org/libsdl/app/SDLActivity.java
- CMake/FetchSDL2.cmake
- ci/linux/Dockerfile
- ci/windows/Dockerfile
- libsrc/download.sh
- libsrc/sha1sums
- version.json
Just updating SDL to 2.30.0 so we can keep tracking it closely.
> update SDL to 2.30.0

- ci/windows/Dockerfile
I made a mistake when making the push_dep script and forgot to fix here.
> ci: fix dockerfile sdl_sound arg name

- Editor/AGS.Native/agsnative.cpp
This change should prevent AGS from mangling palette colors when importing 256 color sprites in hi-color/true-color mode.
The problem was using allegro's palette, which restrict the color to 0-63 values, a legacy from the DOS VGA era.
All the palette logic appears to be crippled by Allegro's 0-63 restriction, so it might be worth rewriting at some point to just use 0-255.
Perhaps it could be a good time when we upgrade the inner color format from 16 to 32 bits.
I added checks to ensure this fix only affects hi-color/true-color, because the implications for 256 color games are unclear.
Caveats:
- Magenta will still be altered to not match the magic pink color.
- The original transparent color will appear black, if one of the corners is used instead (already existing issue, specific to …
> fix palettes being altered for 8bit sprites 

- Editor/AGS.Editor/Panes/ViewPreview.cs
fix #2373 
(the GHA failures are actually the new test game running correctly!)
> Editor: fix ViewPreview not using alpha blending

- Editor/AGS.Editor/Resources/agsdefns.sh
- Engine/ac/dynobj/cc_dynamicarray.cpp
- Engine/ac/dynobj/cc_dynamicarray.h
- Engine/ac/string.cpp
- Engine/script/script_api.h
adds String Split - it's working afaict. I am leaving as a draft because I would like to add String Join but I don't know yet how to read a String array.
> [ags4] add string Split and Join

- Engine/CMakeLists.txt
- Engine/platform/osx/acplmac.cpp
- Engine/platform/osx/alplmac.mm
- OSX/Resources/PrivacyInfo.xcprivacy
- OSX/xcode/AGSKit/AGSKit.xcodeproj/project.pbxproj
- OSX/xcode/ags/ags.xcodeproj/project.pbxproj
@edmundito can you check if this is correct for macOS ?
In my tests this worked alright. I made a separate repo to test the command here: https://github.com/ericoporto/size 
But please check this specifically in ags.
> Engine: add macOS free space check

- Editor/AGS.Editor/Resources/agsdefns.sh
- Engine/ac/string.cpp
- Engine/script/script_api.h
fix #2458
This is an autotest game (fixed again!) 
[ags4-auto-test-string-split.zip](https://github.com/user-attachments/files/16069724/ags4-auto-test-string-split.zip)
<details>
<summary>It adds the following ported from the C# example in the issue (redone!)</summary>
```
// String.Split
// String.Split
{
{
String s = ",ONE,, TWO,, , THREE,,";
String result[] = s.Split(",", eStrSplit_None);
tap.is_int(result.Length, 9, "String.Split: (1,length) by character delimiter without options");
tap.is(result[0], "",       "String.Split: (1,element check 0) by character delimiter without options");
tap.is(result[1], "ONE",    "String.Split: (1,element check 1) by character delimiter without options");
tap.is(result[2], "",       "String.Split: (1,element check 2) by character delimiter without …
```
> [ags4] add to String Split the trim and empty removal options

- Editor/AGS.Editor/GUI/GUIController.cs
- Editor/AGS.Editor/Utils/CommandLineOptions.cs
I am trying to figure a command line option to build a template in the editor from the command line, so it can be ran in a CI environment.
The idea would it be using it for automation purposes, like https://github.com/adventuregamestudio/ags-template-source/issues/27 .
> Editor: add a template save command line option

- libsrc/allegro/include/allegro/internal/aintern.h
- libsrc/allegro/include/allegro/unicode.h
- libsrc/allegro/src/file.c
- libsrc/allegro/src/unicode.c
- libsrc/allegro/src/win/wfile.c
> Hotfix utf8_getx argument type and other errors in mingw build

- Editor/AGS.CScript.Compiler/Entities/ErrorCode.cs
- Editor/AGS.CScript.Compiler/Preprocessor.cs
- Editor/AGS.Editor.Tests/ScriptCompiler/PreprocessorTests.cs
possible fix #2480 
It would certainly be nice to have more tests to add here.
> Editor: error preprocessor in invalid script characters

- Common/gfx/bitmap.cpp
- Common/gfx/bitmap.h
- Editor/AGS.Editor/Tasks.cs
- Editor/AGS.Native/agsnative.cpp
- Engine/ac/draw.cpp
- Engine/ac/draw.h
- Engine/ac/drawingsurface.cpp
- Engine/ac/game.cpp
- Engine/ac/global_dynamicsprite.cpp
- Engine/ac/global_palette.cpp
- Engine/ac/room.cpp
- Engine/ac/sprite.cpp
- Engine/ac/sprite.h
- Engine/gfx/ali3dogl.cpp
- Engine/gfx/gfx_util.cpp
- Engine/gfx/gfx_util.h
- libsrc/allegro/include/allegro/gfx.h
- libsrc/allegro/src/graphics.c
This is based on a work done in #2496 and ported to 3.6.* code base.
> Minor refactor and fixes related to the sprites color depth

- Editor/AGS.Editor/Tasks.cs
- Editor/AGS.Editor/Utils/Utilities.cs
Fix #2242
Seems like a very trivial fix, but please check out in case I missed anything.
> Editor: update ConstructBasicFileListForTemplate() for AGS 4

- libsrc/mojoAL/.icculus.mojoAL.txt
- libsrc/mojoAL/mojoal.c
mojoAL is updated, but we keep the hotfix from 2a7884d27d3f47d0fc5df786e79f83761187e0c7
Previous update was https://github.com/adventuregamestudio/ags/commit/3bcd8c160ba587ffe9df190fb002bcbe7d89efdb, which was synced to https://github.com/icculus/mojoAL/commit/bfaf2f24034c5776c930a5575e115ee561f372b7, there were very few changes since then, the spatialization math was reworked and some warnings were dealt with.
> libsrc: update mojoAL

- Common/util/geometry.cpp
- Common/util/math.h
> Fix sprite rotation

- Common/ac/game_version.h
- Common/game/main_game_file.cpp
- Common/gui/guidefines.h
- Common/gui/guimain.cpp
- Common/gui/guiobject.cpp
- Common/gui/guiobject.h
- Editor/AGS.Editor/AGSEditor.cs
- Editor/AGS.Editor/DataFileWriter.cs
- Editor/AGS.Editor/Resources/agsdefns.sh
- Editor/AGS.Types/GUIControl.cs
- Engine/ac/character.cpp
- Engine/ac/draw.cpp
- Engine/ac/gui.cpp
- Engine/ac/guicontrol.cpp
- Engine/ac/object.cpp
- Engine/ac/object.h
- Engine/ac/overlay.cpp
- Engine/game/savegame_components.cpp
This adds BlendMode property to gui controls, both in script and the editor.
Also added Transparency property in the Editor.
> AGS 4: Added GUIControls.BlendMode (and Transparency in the Editor)

- Editor/AGS.Editor/Resources/agsdefns.sh
- Engine/ac/draw.cpp
- Engine/ac/draw.h
- Engine/ac/dynobj/scriptshader.cpp
- Engine/ac/dynobj/scriptshader.h
- Engine/ac/shader_script.cpp
- Engine/gfx/ali3dogl.cpp
- Engine/gfx/ali3dogl.h
- Engine/gfx/graphicsdriver.h
- Engine/platform/windows/gfx/ali3dd3d.cpp
- Engine/platform/windows/gfx/ali3dd3d.h
This adds a support of having up to 3 secondary textures (samplers) to work with in shaders (so a total of 4 samplers, including primary input texture).
In script, added a new function to the ShaderInstance struct:
```
/// Sets a secondary shader's input texture, using a sprite number. Only indexes 1-3 are supported.
void ShaderInstance.SetTexture(int index, int sprite);
```
Note that you can only use indexes 1..3. Index 0 means primary texture, so it's not allowed here.
The `sprite` can be any sprite number, either regular or dynamicsprite, there's no difference.
Use in shaders:
1. In GLSL you must use hardcoded `sampler2D` uniforms `iTexture2`, `iTexture3` and `iTexture4`.
2. In HLSL names are not hardcoded per se (although you may use the same), but the registers matter: the …
> AGS 4: Support multiple textures in shaders (samplers)
